const config=window.TASK_PANEL_CONFIG||{};
const apiBase=(config.API_BASE_URL||"").replace(/\/$/,"");
const state={token:sessionStorage.getItem("task_token"),user:null,tasks:[],users:[]};
const $=id=>document.getElementById(id);
const statuses=["pending","in_progress","completed"];
const labels={pending:"Bekliyor",in_progress:"Devam ediyor",completed:"Tamamlandı",low:"Düşük",normal:"Normal",high:"Yüksek"};
const initials=name=>(name||"K").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();

async function request(path,options={}){
  const response=await fetch(apiBase+path,{...options,headers:{"Content-Type":"application/json",...(state.token?{Authorization:`Bearer ${state.token}`}:{}) ,...(options.headers||{})}});
  if(response.status===401){logout();throw new Error("Oturumun sona erdi.")}
  if(!response.ok){const text=await response.text();throw new Error(text||"İşlem başarısız.")}
  return response.status===204?null:response.json();
}
function toast(message){$("toast").textContent="✓ "+message;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2300)}
function setRoleUi(){document.querySelectorAll(".admin-only").forEach(x=>x.classList.toggle("hidden",state.user.role!=="admin"));$("profileName").textContent=state.user.fullName||state.user.email;$("profileRole").textContent=state.user.role==="admin"?"Yönetici":"Çalışan";$("avatar").textContent=initials(state.user.fullName||state.user.email)}
async function boot(){if(!state.token)return showLogin();try{state.user=await request("/api/users/me");setRoleUi();$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");await refresh()}catch(e){showLogin(e.message)}}
function showLogin(error=""){$("appView").classList.add("hidden");$("loginView").classList.remove("hidden");$("loginError").textContent=error}
function logout(){sessionStorage.removeItem("task_token");state.token=null;state.user=null;showLogin()}
async function refresh(){$("loading").classList.remove("hidden");try{state.tasks=await request("/api/tasks");if(state.user.role==="admin")state.users=await request("/api/users");renderTasks();renderUsers();$("tasksView").classList.remove("hidden")}catch(e){toast(e.message)}finally{$("loading").classList.add("hidden")}}
function renderTasks(){$("stats").innerHTML=statuses.map(s=>`<article><strong>${state.tasks.filter(t=>t.status===s).length}</strong><small>${labels[s]}</small></article>`).join("");$("board").innerHTML=statuses.map(s=>`<section class="column"><h2>${labels[s]} <small>${state.tasks.filter(t=>t.status===s).length}</small></h2>${state.tasks.filter(t=>t.status===s).map(task=>`<article class="task-card"><span class="priority ${task.priority}">${labels[task.priority]}</span><h3>${escapeHtml(task.title)}</h3><p>${escapeHtml(task.description)}</p><small>${task.assigneeName?"Atanan: "+escapeHtml(task.assigneeName):""}</small><select data-task-id="${task.id}">${statuses.map(x=>`<option value="${x}" ${x===task.status?"selected":""}>${labels[x]}</option>`).join("")}</select></article>`).join("")||'<div class="empty">Burada görev yok.</div>'}</section>`).join("");document.querySelectorAll("[data-task-id]").forEach(select=>select.addEventListener("change",async e=>{try{await request(`/api/tasks/${e.target.dataset.taskId}/status`,{method:"PATCH",body:JSON.stringify({status:e.target.value})});toast("Görev güncellendi");await refresh()}catch(err){toast(err.message)}}))}
function renderUsers(){if(state.user?.role!=="admin")return;$("teamCount").textContent=`${state.users.length} kullanıcı kayıtlı.`;$("userList").innerHTML=state.users.map(u=>`<article><i>${initials(u.fullName)}</i><span><strong>${escapeHtml(u.fullName)}</strong><small>${escapeHtml(u.email)}</small></span><b>${u.role==="admin"?"Yönetici":"Çalışan"}</b></article>`).join("")}
function switchView(view){document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("tasksView").classList.toggle("hidden",view!=="tasks");$("teamView").classList.toggle("hidden",view!=="team");$("pageTitle").textContent=view==="tasks"?(state.user.role==="admin"?"Görev merkezi":"Görevlerim"):"Ekip yönetimi"}
function openTaskModal(){$("modalTitle").textContent="Yeni görev ata";$("modalForm").innerHTML=`<label>Görev başlığı<input name="title" required></label><label>Açıklama<textarea name="description" required></textarea></label><label>Atanan kişi<select name="assigneeId">${state.users.filter(u=>u.role==="employee").map(u=>`<option value="${u.id}">${escapeHtml(u.fullName)}</option>`).join("")}</select></label><label>Öncelik<select name="priority"><option value="normal">Normal</option><option value="high">Yüksek</option><option value="low">Düşük</option></select></label><label>Bitiş tarihi<input type="date" name="dueDate"></label><button class="primary">Görevi ata</button>`;$("modalForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.dueDate)delete d.dueDate;await request("/api/tasks",{method:"POST",body:JSON.stringify(d)});closeModal();toast("Görev atandı");await refresh()};$("modalBackdrop").classList.remove("hidden")}
function openUserModal(){$("modalTitle").textContent="Yeni kullanıcı oluştur";$("modalForm").innerHTML=`<label>Ad soyad<input name="fullName" required></label><label>E-posta<input type="email" name="email" required></label><label>Geçici şifre<input type="password" name="password" required minlength="6"></label><label>Rol<select name="role"><option value="employee">Çalışan</option><option value="admin">Yönetici</option></select></label><button class="primary">Kullanıcıyı oluştur</button>`;$("modalForm").onsubmit=async e=>{e.preventDefault();await request("/api/users",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});closeModal();toast("Kullanıcı oluşturuldu");await refresh()};$("modalBackdrop").classList.remove("hidden")}
function closeModal(){$("modalBackdrop").classList.add("hidden")}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}

$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";try{const result=await request("/api/auth/login",{method:"POST",body:JSON.stringify({email:$("loginEmail").value,password:$("loginPassword").value})});state.token=result.access_token;sessionStorage.setItem("task_token",state.token);await boot()}catch(err){$("loginError").textContent=err.message}});
$("logoutButton").onclick=logout;document.querySelectorAll("nav button").forEach(x=>x.onclick=()=>switchView(x.dataset.view));$("newTaskButton").onclick=openTaskModal;$("newUserButton").onclick=openUserModal;$("newUserButton2").onclick=openUserModal;$("closeModal").onclick=closeModal;$("modalBackdrop").addEventListener("mousedown",e=>{if(e.target===$("modalBackdrop"))closeModal()});boot();
