using System.Net.Http.Headers;using System.Net.Http.Json;using System.Text;using System.Text.Json;using TaskPanel.Api.Models;
namespace TaskPanel.Api.Services;
public class UserService(SupabaseRestClient supabase,IHttpClientFactory clients,IConfiguration config){
  static readonly HashSet<string> ValidRoles=["admin","manager","reception","procurement","kitchen","housekeeping","maintenance"];
  static bool CanManage(CurrentUser user)=>user.Role is "admin" or "manager";
  string Secret=>config["Supabase:SecretKey"]??"";
  public async Task<JsonElement> GetAllAsync(CurrentUser user){if(!CanManage(user))throw new UnauthorizedAccessException();var response=await supabase.SendAsync(user,HttpMethod.Get,"profiles?select=id,email,full_name,role,created_at&order=full_name.asc");await Ensure(response);return JsonDocument.Parse(await response.Content.ReadAsStringAsync()).RootElement.Clone();}
  public async Task CreateAsync(CreateUserRequest request,CurrentUser user){if(user.Role!="admin")throw new UnauthorizedAccessException();ValidateRole(request.Role);RequireSecret();var client=clients.CreateClient();using var message=new HttpRequestMessage(HttpMethod.Post,$"{config["Supabase:Url"]!.TrimEnd('/')}/auth/v1/admin/users");message.Headers.Add("apikey",Secret);message.Headers.Authorization=new AuthenticationHeaderValue("Bearer",Secret);message.Content=JsonContent.Create(new{email=request.Email,password=request.Password,email_confirm=true,user_metadata=new{full_name=request.FullName},app_metadata=new{app_role=request.Role}});var response=await client.SendAsync(message);await Ensure(response);}
  public async Task UpdateRoleAsync(Guid id,string role,CurrentUser user){if(user.Role!="admin")throw new UnauthorizedAccessException();ValidateRole(role);RequireSecret();var client=clients.CreateClient();using(var message=new HttpRequestMessage(HttpMethod.Put,$"{config["Supabase:Url"]!.TrimEnd('/')}/auth/v1/admin/users/{id}")){message.Headers.Add("apikey",Secret);message.Headers.Authorization=new AuthenticationHeaderValue("Bearer",Secret);message.Content=JsonContent.Create(new{app_metadata=new{app_role=role}});await Ensure(await client.SendAsync(message));}var profileResponse=await supabase.SendAsSecretAsync(HttpMethod.Patch,$"profiles?id=eq.{id}",Secret,new{role});await Ensure(profileResponse);}
  static void ValidateRole(string role){if(!ValidRoles.Contains(role))throw new ArgumentException("Geçersiz personel rolü.");}
  void RequireSecret(){if(string.IsNullOrWhiteSpace(Secret))throw new InvalidOperationException("Supabase SecretKey ayarlanmamış.");}
  static async Task Ensure(HttpResponseMessage response){if(response.IsSuccessStatusCode)return;throw new HttpRequestException(await response.Content.ReadAsStringAsync(),null,response.StatusCode);}
}
