const EX_SHOPS={healer:'Şifacı',blacksmith:'Demirci',armorer:'Zırhçı',fletcher:'Okçu',general:'Genel Eşya',tavern:'Han / Bar',restaurant:'Restoran',mystic:'Gizemli Dükkân',cursed:'Lanetli Dükkân'};
const EX_CATALOG=[
 ['healing-potion','İyileştirme İksiri','healer',1,500,12,'2d4+2 HP yeniler.','Tüketilebilir'],['antitoxin','Antitoksin','healer',1,500,8,'1 saat zehire karşı avantaj sağlar.','Tüketilebilir'],['healers-kit','Şifacı Çantası','healer',1,500,5,'10 kullanım; ölmekte olan hedefi stabilize eder.','Ekipman'],['greater-healing','Büyük İyileştirme İksiri','healer',2,15000,5,'4d4+4 HP yeniler.','Tüketilebilir'],['restoration-salve','Arındırıcı Merhem','healer',2,9000,4,'DM onayıyla bir hastalık veya hafif durumu temizler.','Tüketilebilir'],['superior-healing','Üstün İyileştirme İksiri','healer',3,45000,2,'8d4+8 HP yeniler.','Tüketilebilir'],
 ['dagger','Hançer','blacksmith',1,200,10,'1d4 delici; finesse, hafif, fırlatma.','Silah'],['shortsword','Kısa Kılıç','blacksmith',1,1000,8,'1d6 delici; finesse, hafif.','Silah'],['longsword','Uzun Kılıç','blacksmith',1,1500,6,'1d8 kesici; versatile 1d10.','Silah'],['battleaxe','Savaş Baltası','blacksmith',1,1000,6,'1d8 kesici; versatile 1d10.','Silah'],['warhammer','Savaş Çekici','blacksmith',2,1500,5,'1d8 ezici; versatile 1d10.','Silah'],['greatsword','Büyük Kılıç','blacksmith',2,5000,3,'2d6 kesici; ağır, iki elli.','Silah'],['halberd','Teber','blacksmith',2,2000,3,'1d10 kesici; ağır, reach, iki elli.','Silah'],['silvered-blade','Gümüş Kaplı Kılıç','blacksmith',3,12000,2,'Gümüşe hassas yaratıkların direncini aşabilir.','Silah'],
 ['shield','Kalkan','armorer',1,1000,8,'Kullanırken AC +2.','Kalkan'],['leather','Deri Zırh','armorer',1,1000,6,'AC 11 + DEX.','Hafif Zırh'],['studded','Çivili Deri','armorer',1,4500,5,'AC 12 + DEX.','Hafif Zırh'],['chain-shirt','Zincir Gömlek','armorer',2,5000,4,'AC 13 + DEX (en fazla +2).','Orta Zırh'],['breastplate','Göğüs Zırhı','armorer',2,40000,2,'AC 14 + DEX (en fazla +2); stealth dezavantajı yok.','Orta Zırh'],['chain-mail','Zincir Zırh','armorer',2,7500,3,'AC 16; STR 13; stealth dezavantajı.','Ağır Zırh'],['plate','Plaka Zırh','armorer',3,150000,1,'AC 18; STR 15; stealth dezavantajı.','Ağır Zırh'],['tower-shield','Kule Kalkanı','armorer',3,35000,2,'Özel: DM kuralıyla güçlü siper; hareketi kısıtlayabilir.','Kalkan'],
 ['shortbow','Kısa Yay','fletcher',1,2500,6,'1d6 delici; menzil 80/320, iki elli.','Silah'],['light-crossbow','Hafif Arbalet','fletcher',1,2500,5,'1d8 delici; menzil 80/320, loading.','Silah'],['arrows20','20 Ok','fletcher',1,100,20,'Yaylar için 20 adet mühimmat.','Mühimmat'],['longbow','Uzun Yay','fletcher',2,5000,4,'1d8 delici; menzil 150/600, ağır.','Silah'],['heavy-crossbow','Ağır Arbalet','fletcher',2,5000,3,'1d10 delici; menzil 100/400, ağır, loading.','Silah'],['silver-arrows','10 Gümüş Ok','fletcher',3,10000,2,'Gümüşe hassas yaratıklara karşı 10 ok.','Mühimmat'],
 ['rope','15 m Halat','general',1,100,15,'Tırmanma, bağlama ve yaratıcı planlar için.','Ekipman'],['torch','Meşale','general',1,10,30,'1 saat parlak/loş ışık sağlar.','Ekipman'],['rations','1 Günlük Erzak','general',1,50,30,'Bir günlük yolculuk erzağı.','Erzak'],['bedroll','Uyku Tulumu','general',1,100,10,'Kamp sırasında konfor sağlar.','Ekipman'],['thieves-tools','Hırsız Aletleri','general',2,2500,4,'Kilit ve tuzak işlerinde yeterlilikle kullanılır.','Alet'],['climbers-kit','Tırmanış Seti','general',2,2500,4,'Düşme riskini azaltan piton ve kemerler.','Ekipman'],['bag-holding','Taşıma Çantası','general',3,40000,1,'İç hacmi dışından çok daha büyüktür.','Nadir Eşya'],
 ['ale','Bir Kupa Bira','tavern',1,4,99,'Keyif verir; aşırısı CON save isteyebilir.','İçecek'],['wine','Şişe Şarap','tavern',1,200,20,'Kaliteli sofra şarabı.','İçecek'],['room','Han Odası','tavern',1,500,20,'Bir gecelik güvenli konaklama.','Hizmet'],['rumor','Yerel Söylenti','tavern',2,300,10,'DM bir söylenti, ipucu veya görev kancası verir.','Bilgi'],['private-room','Özel Salon','tavern',3,5000,1,'Toplantı için gizli, korunaklı oda.','Hizmet'],
 ['stew','Sıcak Güveç','restaurant',1,30,30,'Doyurucu sıcak yemek.','Yemek'],['feast','Maceracı Sofrası','restaurant',1,100,20,'İyi bir dinlenmeye lezzet katar.','Yemek'],['heroes-feast-lite','Şefin Özel Menüsü','restaurant',2,1500,6,'DM onayıyla sonraki CON save’e ilham/avantaj verebilir.','Yemek'],['royal-banquet','Kraliyet Ziyafeti','restaurant',3,10000,1,'Gruba sosyal sahnelerde prestij sağlar.','Hizmet'],
 ['identify-pearl','Tanımlama İncisi','mystic',1,10000,3,'Identify büyüsünün maddi bileşeni.','Büyü Bileşeni'],['spell-scroll-1','1. Seviye Büyü Parşömeni','mystic',1,7500,5,'İçindeki 1. seviye büyüyü tek kullanımlık taşır.','Parşömen'],['sending-stones','Mesaj Taşları','mystic',2,35000,1,'Eş taşla günde bir kez kısa mesajlaşma sağlar.','Nadir Eşya'],['cloak-protection','Koruma Pelerini','mystic',3,60000,1,'Attunement: AC ve saving throw +1.','Nadir Eşya'],['pearl-power','Güç İncisi','mystic',3,65000,1,'Attunement: günde bir kez 3. seviyeye kadar spell slot yeniler.','Nadir Eşya'],
 ['whisper-ring','Fısıldayan Yüzük','cursed',1,500,1,'Avantaj: gizli sesler duyarsın. Bedel: DM zaman zaman yanlış fısıltı verir.','Lanetli'],['blood-blade','Kan İçen Bıçak','cursed',2,12000,1,'Kritikte ek 1d6 hasar; her uzun dinlenmede sahibinden 1d6 HP isteyebilir.','Lanetli'],['coin-greed','Açgözlülük Sikkesi','cursed',2,6660,1,'Pazarlıkta çekicilik sağlar; paylaşmayı reddetme dürtüsü doğurur.','Lanetli'],['mask-nameless','İsimsizin Maskesi','cursed',3,45000,1,'Kısa süreli görünüş değişimi; her kullanım bir anıyı bulanıklaştırabilir.','Lanetli'],['deck-minor-fates','Küçük Kader Destesi','cursed',3,77700,1,'DM destesinden faydalı veya korkunç tek sonuç çektirir.','Lanetli']
].map(x=>({id:'ex-'+x[0],name:x[1],shop:x[2],tier:x[3],priceCopper:x[4],stock:x[5],note:x[6],effect:x[7],active:true,ready:true}));

// Geniş katalog: eski kampanyalara seedVersion yükseltilerek, özel ürünlere dokunmadan eklenir.
const EX_EXTRA_CATALOG=[
 ['herbal-poultice','Şifalı Bitki Lapası','healer',1,150,15,'Kısa dinlenmede harcanan bir Hit Die sonucuna DM onayıyla +2 ekler.','Tüketilebilir'],['burn-salve','Yanık Merhemi','healer',1,350,10,'Yanıkları yatıştırır; sıradaki hafif ateş hasarına karşı hazırlık sağlar.','Tüketilebilir'],['smelling-salts','Ayıltma Tuzu','healer',1,250,8,'Baygın fakat ölmemiş bir hedefi ayıltmak için kullanılır.','Tüketilebilir'],['lesser-restoration','Küçük Arındırma İksiri','healer',2,12500,4,'DM onayıyla blinded, deafened, paralyzed veya poisoned durumlarından birini kaldırır.','Tüketilebilir'],['vitality-tonic','Canlılık Toniği','healer',2,18000,4,'1 saat boyunca maksimum HP’ye geçici +5 verir; birikmez.','Tüketilebilir'],['heroism-draught','Kahramanlık Şurubu','healer',2,22000,3,'10 dakika frightened durumuna karşı avantaj ve 5 geçici HP sağlar.','Tüketilebilir'],['supreme-healing','Yüce İyileştirme İksiri','healer',3,135000,1,'10d4+20 HP yeniler.','Tüketilebilir'],['elixir-health','Sağlık İksiri','healer',3,70000,2,'Blindness, deafness, paralysis ve poison etkilerini temizler.','Nadir Tüketilebilir'],['phoenix-tear','Anka Gözyaşı','healer',3,180000,1,'Ölümden hemen sonra kullanılırsa DM onayıyla hedefi 1 HP ile döndürebilir.','Çok Nadir Tüketilebilir'],
 ['club','Budaklı Sopa','blacksmith',1,10,15,'1d4 ezici; hafif.','Silah'],['spear','Mızrak','blacksmith',1,100,10,'1d6 delici; versatile 1d8, fırlatma 20/60.','Silah'],['mace','Topuz','blacksmith',1,500,8,'1d6 ezici.','Silah'],['rapier','İnce Kılıç','blacksmith',1,2500,6,'1d8 delici; finesse.','Silah'],['scimitar','Palâ','blacksmith',1,2500,6,'1d6 kesici; finesse, hafif.','Silah'],['maul','Ağır Balyoz','blacksmith',2,1000,5,'2d6 ezici; ağır, iki elli.','Silah'],['pike','Uzun Kargı','blacksmith',2,500,5,'1d10 delici; ağır, reach, iki elli.','Silah'],['flame-tongue','Alevdil Uzun Kılıç','blacksmith',3,85000,1,'Attunement: isabette ek 2d6 ateş hasarı verir.','Nadir Büyülü Silah'],['frost-brand','Ayazdamga Büyük Kılıç','blacksmith',3,140000,1,'Attunement: ek 1d6 soğuk hasarı ve ateş direnci.','Çok Nadir Büyülü Silah'],['dragon-slayer','Ejderkatleden Kılıç','blacksmith',3,95000,1,'Ejder türü hedefe isabette ek 3d6 hasar verir.','Nadir Büyülü Silah'],['sun-blade','Güneş Kılıcı','blacksmith',3,110000,1,'Attunement: +2 finesse longsword; radiant hasar verir ve ışık saçar.','Nadir Büyülü Silah'],['executioner-plus2','Keskin Cellât Kılıcı +2','blacksmith',3,175000,1,'Saldırı ve hasar zarlarına +2; kritiklerde DM özel keskinlik kuralı uygulayabilir.','Çok Nadir Silah'],
 ['padded','Yastıklı Zırh','armorer',1,500,8,'AC 11 + DEX; stealth dezavantajı.','Hafif Zırh'],['hide','Post Zırh','armorer',1,1000,8,'AC 12 + DEX (en fazla +2).','Orta Zırh'],['scale-mail','Pullu Zırh','armorer',1,5000,5,'AC 14 + DEX (en fazla +2); stealth dezavantajı.','Orta Zırh'],['splint','Şeritli Zırh','armorer',2,20000,3,'AC 17; STR 15; stealth dezavantajı.','Ağır Zırh'],['mithral-shirt','Mithral Zincir Gömlek','armorer',2,45000,2,'Stealth dezavantajı ve Strength şartı olmayan mithral işçiliği.','Nadir Zırh'],['sentinel-shield','Nöbetçi Kalkanı','armorer',2,30000,2,'Kuşanırken initiative ve Perception kontrollerinde avantaj.','Nadir Kalkan'],['adamantine-plate','Adamantin Plaka Zırh','armorer',3,165000,1,'Kuşanana gelen kritik vuruşları normal vuruşa çevirir.','Nadir Ağır Zırh'],['armor-resistance','Direnç Zırhı +1','armorer',3,190000,1,'AC’ye +1; DM’in seçtiği bir hasar türüne direnç.','Çok Nadir Zırh'],['spellguard-shield','Büyüsavar Kalkan','armorer',3,155000,1,'Attunement: büyülere karşı save avantajı; büyü saldırıları sana karşı dezavantajlı.','Çok Nadir Kalkan'],['animated-shield','Canlı Kalkan','armorer',3,125000,1,'Attunement: bonus action ile havada korur ve elleri serbest bırakır.','Çok Nadir Kalkan'],
 ['sling','Sapan','fletcher',1,10,15,'1d4 ezici; menzil 30/120.','Silah'],['hand-crossbow','El Arbaleti','fletcher',1,7500,4,'1d6 delici; hafif, loading, menzil 30/120.','Silah'],['bolts20','20 Arbalet Oku','fletcher',1,100,20,'Arbaletler için 20 adet mühimmat.','Mühimmat'],['poison-arrows','10 Zehirli Ok','fletcher',2,7500,3,'İsabette düşük DC Constitution save; başarısızsa zehir etkisi.','Özel Mühimmat'],['grappling-bolt','Kancalı Arbalet Oku','fletcher',2,4000,5,'Sağlam yüzeye halat sabitlemek veya yaratıcı manevra yapmak için.','Özel Mühimmat'],['walloping-ammo','Sarsıcı Ok Paketi','fletcher',2,12000,3,'10 ok; isabette Strength save başarısızsa hedef prone olabilir.','Büyülü Mühimmat'],['bow-warning','Uyarı Yayı','fletcher',2,28000,2,'Attunement: initiative avantajı verir ve uyurken tehlikeyi sezdirir.','Nadir Silah'],['oathbow','Yemin Yayı','fletcher',3,150000,1,'Attunement: seçilmiş düşmana karşı avantaj ve ek 3d6 hasar; yemin kısıtı taşır.','Çok Nadir Silah'],['lightning-bow','Fırtına Yayı +2','fletcher',3,120000,1,'Saldırı ve hasara +2; günde bir kez yıldırım çizgisi oluşturur.','Çok Nadir Silah'],['arrow-slaying','Yaratık Avcısı Oku','fletcher',3,25000,3,'DM’in seçtiği yaratık türüne karşı ağır ek hasar verir.','Çok Nadir Mühimmat'],
 ['lantern','Kapaklı Fener','general',1,500,8,'Yağla 6 saat yanar; ışık huzmesi ayarlanabilir.','Ekipman'],['crowbar','Levye','general',1,200,8,'Uygun Strength kontrollerinde avantaj sağlayabilir.','Ekipman'],['grappling-hook','Kanca','general',1,200,10,'Halatla birlikte tırmanış ve geçiş planlarında kullanılır.','Ekipman'],['tent','İki Kişilik Çadır','general',1,200,6,'İki kişiyi kötü hava koşullarından korur.','Kamp Ekipmanı'],['spyglass','Dürbün','general',2,100000,1,'Uzaktaki nesneleri iki kat büyük gösterir.','Keşif Ekipmanı'],['portable-ram','Taşınabilir Koçbaşı','general',2,400,3,'Kapı kırma Strength kontrollerinde güçlü destek verir.','Ekipman'],['immovable-rod','Sabitlenmez Çubuk','general',2,50000,2,'Düğmeyle uzayda sabitlenir; 8.000 libreye kadar tutabilir.','Nadir Eşya'],['boots-elvenkind','Elf Çizmeleri','general',2,45000,2,'Sessiz hareket sağlar ve Stealth avantajı verir.','Nadir Eşya'],['rope-climbing','Tırmanan Halat','general',2,30000,2,'Komutla kendi kendine yükselir, düğümlenir ve sabitlenir.','Nadir Eşya'],['portable-hole','Taşınabilir Delik','general',3,145000,1,'Katlanabilir boyutlar arası depolama alanı; taşıma çantasıyla tehlikeli etkileşir.','Çok Nadir Eşya'],['boots-speed','Sürat Çizmeleri','general',3,130000,1,'Attunement: hızı ikiye katlar ve fırsat saldırılarını zorlaştırır.','Çok Nadir Eşya'],['carpet-flying','Uçan Halı','general',3,240000,1,'Komutla uçan taşıt; kapasite ve hızı boyutuna bağlıdır.','Çok Nadir Eşya'],
 ['cheap-lodging','Ortak Yatakhane','tavern',1,50,30,'Kalabalık fakat ucuz bir gecelik konaklama.','Hizmet'],['stable','Binek Ahırı','tavern',1,50,20,'Bir bineğin bir gecelik yem ve barınması.','Hizmet'],['bard-song','Ozanın Özel Şarkısı','tavern',1,250,8,'Yerel efsane, isim veya söylenti hakkında ipucu sağlayabilir.','Eğlence'],['gambling-table','Bahis Masası Girişi','tavern',2,500,12,'DM’in yönettiği beceri mücadeleli şans oyunu oturumu.','Eğlence'],['underworld-contact','Yeraltı Teması','tavern',2,3500,3,'Kaçakçılar veya hırsızlar loncasıyla tek kullanımlık bağlantı.','Bilgi'],['safehouse-night','Gizli Güvenli Ev','tavern',3,12500,2,'Takipten saklanan grup için kimliği gizli bir gecelik mekân.','Hizmet'],['royal-audience','Saray Davetiyesi','tavern',3,40000,1,'Soylu bir çevreye veya özel toplantıya giriş sağlar.','Nadir Hizmet'],
 ['trail-bread','Yolcu Ekmeği','restaurant',1,20,40,'Ucuz ve dayanıklı tek öğünlük yiyecek.','Yemek'],['dwarven-breakfast','Cüce Kahvaltısı','restaurant',1,75,20,'Ağır ve doyurucu; soğuk yolculuk öncesi iyi bir öğün.','Yemek'],['elven-tea','Elf Ay Çayı','restaurant',1,125,15,'Sakinleştirici aromalı sıcak içecek.','İçecek'],['spiced-drake','Baharatlı Drake Eti','restaurant',2,750,8,'Sonraki ateş veya korku save’ine DM onayıyla +1 verebilir.','Yemek'],['travelers-platter','Gezgin Tabağı','restaurant',2,500,12,'Uzun yol öncesi bir günlük kaliteli erzak içerir.','Yemek'],['giant-feast','Dev Sofrası','restaurant',2,2500,4,'Grup boyu servis; kısa dinlenmede moral avantajı sağlayabilir.','Ziyafet'],['moonlit-course','Ayışığı Menüsü','restaurant',3,7500,3,'Bir sonraki Charisma beceri kontrolüne ilham sağlayabilir.','Büyülü Yemek'],['dragons-banquet','Ejder Ziyafeti','restaurant',3,30000,1,'DM’in seçtiği hasar türüne 1 saatlik direnç sağlayabilir.','Nadir Ziyafet'],
 ['moon-touched-sword','Ay Dokunuşlu Kılıç','mystic',1,12000,3,'Çekildiğinde ay ışığı yayar; büyülü silah sayılır.','Yaygın Büyülü Silah'],['wand-magic-detection','Büyü Sezme Asası','mystic',1,18000,2,'Günde 3 kez Detect Magic etkisi oluşturur.','Yaygın Asa'],['alchemy-jug','Simya Sürahisi','mystic',2,35000,2,'Her gün seçilen sıradan veya tuhaf bir sıvı üretir.','Nadir Eşya'],['brooch-shielding','Koruyucu Broş','mystic',2,40000,2,'Attunement: force direnci ve Magic Missile bağışıklığı.','Nadir Eşya'],['eyes-minute-seeing','Keskin Görüş Mercekleri','mystic',2,32000,2,'Attunement: yakındaki ayrıntıları inceleyen Investigation kontrollerinde avantaj.','Nadir Eşya'],['wand-web','Ağ Asası','mystic',2,50000,1,'Attunement: şarj harcayarak Web büyüsü kullanır.','Nadir Asa'],['ring-spell-storing','Büyü Saklama Yüzüğü','mystic',3,145000,1,'Attunement: toplam 5 seviye büyüyü saklar ve sonradan kullanır.','Nadir Yüzük'],['staff-power','Kudret Asası','mystic',3,260000,1,'Attunement: büyü saldırısı ve save DC’ye +2; güçlü şarjlı büyüler içerir.','Çok Nadir Asa'],['robe-stars','Yıldızlar Cübbesi','mystic',3,210000,1,'Attunement: save +1, yıldız saldırıları ve Astral Plane yolculuğu.','Çok Nadir Cübbe'],['tome-intellect','Berrak Düşünce Kitabı','mystic',3,300000,1,'Uzun eğitim sonunda Intelligence değerini ve üst sınırını 2 artırabilir.','Çok Nadir Kitap'],
 ['hungry-amulet','Aç Tılsım','cursed',1,900,2,'Günde bir kez 3 geçici HP verir; sahibinin iştahını kontrol edilemez artırır.','Lanetli'],['liars-dice','Yalancının Zarları','cursed',1,1300,2,'Bir blöf kontrolünde avantaj; başarısızlıkta sahibini doğruyu söylemeye zorlar.','Lanetli'],['mirror-envy','Haset Aynası','cursed',2,15000,1,'Bir hedefin görünüşünü taklit eder; kullanıcının kendi yüzünü unutmasına yol açabilir.','Lanetli'],['armor-martyr','Şehit Zırhı','cursed',2,28000,1,'AC +1; yakındaki müttefik hasar aldığında sahibine de psişik hasar verebilir.','Lanetli Zırh'],['bell-last-breath','Son Nefes Çanı','cursed',2,22000,1,'Düşen müttefiki stabilize edebilir; kullanan bir Hit Die kaybeder.','Lanetli'],['crown-dominion','Tahakküm Tacı','cursed',3,90000,1,'Charisma kontrollerine +2; emir reddedilince kullanıcı öfke save’i yapar.','Lanetli Nadir Eşya'],['blade-soul-debt','Ruh Borçlusu +2','cursed',3,135000,1,'Saldırı ve hasara +2, öldürücü darbede geçici HP; her ruh gelecekte bir bedel doğurur.','Lanetli Silah'],['hourglass-undoing','Geri Alım Kum Saati','cursed',3,160000,1,'Bir zarı yeniden attırır; DM daha sonra başka bir başarılı zarı yeniden attırır.','Lanetli Çok Nadir'],['eye-abyss','Uçurum Gözü','cursed',3,185000,1,'Karanlıkta ve görünmezleri görmeye yardım eder; delilik veya korku riski taşır.','Lanetli Çok Nadir']
].map(x=>({id:'ex-'+x[0],name:x[1],shop:x[2],tier:x[3],priceCopper:x[4],stock:x[5],note:x[6],effect:x[7],active:true,ready:true}));
const EX_ALL_CATALOG=[...EX_CATALOG,...EX_EXTRA_CATALOG];

const EX_DEFAULT_SETTINGS=()=>({buyingEnabled:false,discount:0,shops:Object.fromEntries(Object.keys(EX_SHOPS).map(k=>[k,{enabled:false,tier:1}]))});
let exWalletRows=[],exGuildWallet=null,exWalletCampaign=null,exWalletLoading=false,exShopFilter='all';
function exCoinTotal(w={}){return (+w.platinum||0)*1000+(+w.gold||0)*100+(+w.silver||0)*10+(+w.copper||0)}
function exMoney(total){total=Math.max(0,+total||0);let pp=Math.floor(total/1000);total%=1000;let gp=Math.floor(total/100);total%=100;let sp=Math.floor(total/10),cp=total%10;return `<span class="coin pp">${pp} PP</span><span class="coin gp">${gp} GP</span><span class="coin sp">${sp} SP</span><span class="coin cp">${cp} CP</span>`}
function exEnsureState(){if(!state.shopSettings)state.shopSettings=EX_DEFAULT_SETTINGS();for(let k of Object.keys(EX_SHOPS)){state.shopSettings.shops[k]??={enabled:false,tier:1}}let changed=false;state.market=(state.market||[]).map(x=>{if(x.priceCopper!=null)return x;let m=String(x.price||'0').match(/([\d.]+)\s*(pp|gp|sp|cp)/i),mult={pp:1000,gp:100,sp:10,cp:1};changed=true;return {...x,shop:'general',tier:1,priceCopper:Math.round(+(m?.[1]||0)*(mult[(m?.[2]||'cp').toLowerCase()]||1)),note:x.note||'DM tarafından eklenen ürün.',effect:x.effect||'Özel',active:true,custom:true}});if(current?.role==='dm'&&(+state.shopSeedVersion||0)<3){for(let item of EX_ALL_CATALOG)if(!state.market.some(x=>x.id===item.id||x.name===item.name))state.market.push({...item});state.shopSeedVersion=3;changed=true}if(changed&&current?.role==='dm')setTimeout(save,0)}
function exWalletCard(title,w,target,scope='player'){return `<article class="wallet-card"><h3>${esc(title)}</h3><div class="wallet-total">${exMoney(exCoinTotal(w))}</div>${current.role==='dm'?`<div class="coin-actions">${[['platinum','PP'],['gold','GP'],['silver','SP'],['copper','CP']].map(c=>`<div class="coin-editor"><b>${c[1]}</b><span>Mevcut: ${w?.[c[0]]||0}</span><label><small>Miktar</small><input class="coin-amount" type="number" min="1" step="1" value="1" inputmode="numeric"></label><button data-coin-adjust="${scope}|${target||''}|${c[0]}|1" class="coin-add">Ekle</button><button data-coin-adjust="${scope}|${target||''}|${c[0]}|-1" class="coin-remove">Çıkar</button></div>`).join('')}</div><small class="wallet-help">Girilen miktar seçilen para türünde eklenir veya çıkarılır. Sistem gerekirse parayı otomatik bozar.</small>`:'<p class="muted">Bu bakiye yalnızca sana ve DM’e görünür.</p>'}</article>`}
async function exLoadWallets(force=false){if(!auth||!current||exWalletLoading||(!force&&exWalletCampaign===current.id))return;exWalletLoading=true;let cid=current.id,[a,b]=await Promise.all([db.rpc('wallet_list',{p_user:auth.id,p_campaign:cid}),db.rpc('guild_wallet_get',{p_user:auth.id,p_campaign:cid})]);exWalletLoading=false;if(current?.id!==cid)return;if(a.error||b.error){exWalletRows=[];exGuildWallet=null;exWalletCampaign=cid;if(page==='treasury'||page==='market')render();return}exWalletRows=a.data||[];exGuildWallet=b.data?.[0]||{platinum:0,gold:0,silver:0,copper:0};exWalletCampaign=cid;if(page==='treasury'||page==='market')render()}
function exTransferCard(){let players=members.filter(x=>x.role==='player'&&x.userId!==auth.id);return `<section class="card money-transfer"><div><small>OYUNCUDAN OYUNCUYA</small><h3>Para Gönder</h3><p>Gönderilen para anında diğer oyuncunun kesesine geçer. Gerekirse sistem büyük parayı otomatik bozar.</p></div>${players.length?`<div class="transfer-form"><label>Alıcı<select id="exTransferTarget">${players.map(x=>`<option value="${x.userId}">${esc(x.name)}</option>`).join('')}</select></label><label>Para<select id="exTransferCoin"><option value="platinum">Platin (PP)</option><option value="gold" selected>Altın (GP)</option><option value="silver">Gümüş (SP)</option><option value="copper">Bakır (CP)</option></select></label><label>Miktar<input id="exTransferAmount" type="number" min="1" step="1" value="1"></label><button id="exTransferMoney" class="primary">Parayı Gönder</button></div>`:'<p class="muted">Gönderilebilecek başka bir oyuncu henüz odada değil.</p>'}</section>`}
function exDiscardCard(){return `<section class="card money-transfer money-discard"><div><small>KESENDEN SİL</small><h3>Parayı Kalıcı Sil</h3><p>Seçtiğin para kesenden kalıcı olarak çıkar. Yerde alınabilir eşya oluşmaz ve işlem geri alınamaz.</p></div><div class="transfer-form discard-form"><label>Para<select id="exDiscardCoin"><option value="platinum">Platin (PP)</option><option value="gold" selected>Altın (GP)</option><option value="silver">Gümüş (SP)</option><option value="copper">Bakır (CP)</option></select></label><label>Miktar<input id="exDiscardAmount" type="number" min="1" step="1" value="1" inputmode="numeric"></label><button id="exDiscardMoney" class="danger">Kalıcı Olarak Sil</button></div></section>`}
function exMoneyActions(){let npc=typeof window.v66NpcCoinCard==='function'?window.v66NpcCoinCard():'';return `<section class="v68-money-hub"><div class="v68-money-head"><div><small>TEK PARA MERKEZİ</small><h2>Para İşlemleri</h2></div><p>Oyuncuya gönderme, NPC’ye gönderme ve keseden kalıcı silme burada.</p></div><div class="v68-money-grid">${exTransferCard()}${npc}${exDiscardCard()}</div></section>`}
function exTreasury(){queueMicrotask(()=>exLoadWallets());let mine=exWalletRows.find(x=>x.user_id===auth.id);return `<div class="economy-head"><div><p>${current.role==='dm'?'HAZİNE YÖNETİMİ':'KESEN'}</p><h2>Platin, Altın, Gümüş, Bakır</h2></div><small>1 PP = 10 GP = 100 SP = 1000 CP</small></div>${exWalletCampaign!==current.id?'<div class="card empty">Kasalar sayılıyor…</div>':!exGuildWallet?'<div class="card pact-error">Güncel economy-update.sql dosyasını Supabase’te çalıştır.</div>':`<div class="wallet-grid">${exWalletCard('Lonca Kasası',exGuildWallet,'','guild')}${current.role==='dm'?exWalletRows.map(w=>exWalletCard(w.player_name,w,w.user_id)).join(''):exWalletCard('Kişisel Kesen',mine||{},auth.id)}</div>${current.role==='player'?exMoneyActions():''}`}`}
function exPrice(item){let d=Math.max(0,Math.min(100,+state.shopSettings.discount||0));return Math.max(0,Math.round(item.priceCopper*(100-d)/100))}
function exVisibleItems(){let s=state.shopSettings;return state.market.filter(i=>{let shop=s.shops[i.shop]||{enabled:false,tier:1};return current.role==='dm'||(s.buyingEnabled&&shop.enabled&&i.active!==false&&i.tier<=shop.tier)}).filter(i=>exShopFilter==='all'||i.shop===exShopFilter)}
function exItemCard(i){let price=exPrice(i),canBuy=current.role==='player'&&state.shopSettings.buyingEnabled&&i.stock>0;return `<article class="shop-item ${i.active===false?'disabled':''}"><div class="between row"><b>${esc(i.name)}</b><span class="tier">T${i.tier}</span></div><small>${esc(EX_SHOPS[i.shop]||i.shop)} • ${esc(i.effect||'Eşya')}</small><p>${esc(i.note||'Açıklama yok.')}</p><div class="between row"><div>${exMoney(price)}</div><b>Stok ${i.stock}</b></div>${current.role==='dm'?`<div class="shop-admin"><button data-item-toggle="${i.id}" class="ghost">${i.active===false?'Göster':'Gizle'}</button><button data-item-price="${i.id}" class="ghost">Fiyat</button><button data-item-stock="${i.id}" class="ghost">Stok</button>${i.custom?`<button data-item-delete="${i.id}" class="danger">Sil</button>`:''}</div>`:`<button data-buy-item="${i.id}" class="primary buy-button" ${canBuy?'':'disabled'}>${i.stock>0?'Satın Al':'Tükendi'}</button>`}</article>`}
function exShopControls(){let s=state.shopSettings;return `<section class="shop-control card"><div class="between row"><div><small>OYUNCU SATIN ALIMI</small><h3>${s.buyingEnabled?'Açık':'Kapalı'}</h3></div><button id="exToggleBuying" class="${s.buyingEnabled?'danger':'primary'}">${s.buyingEnabled?'Satın Almayı Kapat':'Satın Almayı Aç'}</button></div><label>Genel indirim: <b>%${s.discount}</b><input id="exDiscount" type="range" min="0" max="90" step="5" value="${s.discount}"></label><div class="shop-switches">${Object.entries(EX_SHOPS).map(([k,n])=>{let x=s.shops[k];return `<article class="${x.enabled?'open':''}"><button data-shop-toggle="${k}">${x.enabled?'● AÇIK':'○ KAPALI'} — ${n}</button><label>Tier<select data-shop-tier="${k}">${[1,2,3].map(t=>`<option value="${t}" ${x.tier===t?'selected':''}>${t}</option>`).join('')}</select></label></article>`}).join('')}</div><button id="exAddItem" class="primary">+ Özel ürün ekle</button></section>`}
function exMarket(){exEnsureState();queueMicrotask(()=>exLoadWallets());let shops=current.role==='dm'?Object.keys(EX_SHOPS):Object.keys(EX_SHOPS).filter(k=>state.shopSettings.shops[k].enabled);return `${current.role==='dm'?exShopControls():`<div class="shop-player-head card"><div><small>KİŞİSEL BAKİYE</small>${exMoney(exCoinTotal(exWalletRows.find(x=>x.user_id===auth.id)||{}))}</div><p>${state.shopSettings.buyingEnabled?'Dükkânlar alışverişe açık.':'DM henüz satın almayı açmadı.'}</p></div>`}<div class="shop-tabs"><button data-shop-filter="all" class="${exShopFilter==='all'?'active':''}">Tümü</button>${shops.map(k=>`<button data-shop-filter="${k}" class="${exShopFilter===k?'active':''}">${EX_SHOPS[k]}</button>`).join('')}</div><div class="shop-grid">${exVisibleItems().map(exItemCard).join('')||'<div class="card empty">Bu dükkân şu anda kapalı veya rafları boş.</div>'}</div>`}
function exEffects(x){return (x.effects||[]).map(e=>{let name=typeof e==='string'?e:e.name,dur=typeof e==='string'?'':e.duration;return `<span class="effect">${esc(name)}${dur?` (${esc(dur)})`:''}</span>`}).join('')||'<small>Efekt yok</small>'}
function exFightPlayer(){return `<div class="grid">${card('Aktif Encounter',state.encounter.length?`<div class="fight-board">${state.encounter.map((x,i)=>`<article class="fighter ${x.turn?'active-turn':''}"><div class="fighter-order">${i+1}</div><div><h3>${esc(x.name)}</h3><p>${x.hp}/${x.maxHp||x.hp} HP • AC ${x.ac} • Initiative ${x.init||0}</p>${exEffects(x)}</div>${x.turn?'<b class="turn-badge">SIRASI</b>':''}</article>`).join('')}</div>`:'<div class="empty">Şu anda aktif savaş yok.</div>',8)}${card('Parti Durumu',state.characters.map(c=>`<div class="party-combat"><b>${esc(c.name)}</b>${hpbar(c)}<div>${exEffects(c)}</div></div>`).join('')||'<div class="empty">Parti hazırlanıyor.</div>',4)}</div>`}
const exOldEncounter=dmPages.encounter;
function exFightDM(){let base=exOldEncounter().replace('<button id="addEncounter" class="primary">+ Savaşçı</button>','<button id="addEncounterPlayer" class="primary">+ Oyuncu</button><button id="addEncounter" class="ghost">+ Özel Savaşçı</button>').replace(/<button data-hitenc="([^"]+)" class="ghost">HP<\/button>/g,'<button data-hitenc="$1" class="ghost">HP</button><button data-enc-effect="$1" class="ghost">Efekt</button>');let effects=state.encounter.map((x,i)=>({x,i})).filter(r=>(r.x.effects||[]).length).map(r=>`<article class="effect-ledger"><b>${esc(r.x.name)}</b><div>${(r.x.effects||[]).map((e,j)=>{let n=typeof e==='string'?e:e.name,d=typeof e==='string'?'':e.duration;return `<span class="effect">${esc(n)}${d?` (${esc(d)})`:''} <button data-enc-remove-effect="${r.i}|${j}">×</button></span>`}).join('')}</div></article>`).join('');return base+`<section class="card encounter-effects"><h3>Encounter Efektleri</h3>${effects||'<p class="muted">Aktif efekt yok. Savaşçı kartındaki Efekt düğmesini kullan.</p>'}</section>`}

if(!dmNav.some(x=>x[0]==='treasury'))dmNav.splice(dmNav.findIndex(x=>x[0]==='market'),0,['treasury','◈','Kasa']);
if(!playerNav.some(x=>x[0]==='treasury'))playerNav.splice(playerNav.findIndex(x=>x[0]==='market'),0,['treasury','◈','Kesem']);
if(!playerNav.some(x=>x[0]==='encounterview'))playerNav.splice(playerNav.findIndex(x=>x[0]==='market'),0,['encounterview','⚔','Savaş']);
dmPages.treasury=exTreasury;playerPages.treasury=exTreasury;dmPages.market=exMarket;playerPages.market=exMarket;dmPages.encounter=exFightDM;playerPages.encounterview=exFightPlayer;
const exOriginalRender=render;render=function(){if(current)exEnsureState();return exOriginalRender()};

document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b||!current)return;
 if(b.dataset.coinAdjust){let [scope,target,coin,sign]=b.dataset.coinAdjust.split('|'),input=b.closest('.coin-editor')?.querySelector('.coin-amount'),amount=Math.floor(+(input?.value||0));if(!Number.isFinite(amount)||amount<1){alert('Miktar en az 1 olmalı.');input?.focus();return}let fn=scope==='guild'?'guild_wallet_adjust':'wallet_adjust',args=scope==='guild'?{p_user:auth.id,p_campaign:current.id,p_coin:coin,p_delta:amount*(+sign)}:{p_user:auth.id,p_campaign:current.id,p_target:target,p_coin:coin,p_delta:amount*(+sign)};b.disabled=true;let old=b.textContent;b.textContent='…';let {error}=await db.rpc(fn,args);if(error){b.disabled=false;b.textContent=old;return alert('Para güncellenemedi: '+error.message)}exWalletCampaign=null;await exLoadWallets(true);toast(`${amount} ${coin==='platinum'?'PP':coin==='gold'?'GP':coin==='silver'?'SP':'CP'} ${+sign>0?'eklendi':'çıkarıldı'}`)}
 if(b.id==='exTransferMoney'){let target=$('#exTransferTarget')?.value,coin=$('#exTransferCoin')?.value,amount=Math.floor(+($('#exTransferAmount')?.value||0));if(!target||!coin||amount<1)return alert('Alıcı ve geçerli bir miktar seç.');if(!confirm(`${amount} ${coin==='platinum'?'PP':coin==='gold'?'GP':coin==='silver'?'SP':'CP'} gönderilsin mi?`))return;b.disabled=true;let {error}=await db.rpc('wallet_transfer',{p_user:auth.id,p_campaign:current.id,p_target:target,p_coin:coin,p_amount:amount});if(error){b.disabled=false;return alert('Para gönderilemedi: '+error.message)}exWalletCampaign=null;await exLoadWallets(true);toast('Para gönderildi')}
 if(b.id==='exDiscardMoney'){let coin=$('#exDiscardCoin')?.value,amount=Math.floor(+($('#exDiscardAmount')?.value||0)),label=coin==='platinum'?'PP':coin==='gold'?'GP':coin==='silver'?'SP':'CP';if(!coin||amount<1)return alert('Para türü ve geçerli bir miktar seç.');if(!auth?.sessionToken)return alert('Güvenli işlem için çıkış yapıp yeniden giriş yap.');if(!confirm(`${amount} ${label} kalıcı olarak yok edilsin mi? Bu işlem geri alınamaz.`))return;b.disabled=true;let old=b.textContent;b.textContent='Yok ediliyor…';let {error}=await db.rpc('wallet_discard_v61',{p_session_token:auth.sessionToken,p_campaign:current.id,p_coin:coin,p_amount:amount});if(error){b.disabled=false;b.textContent=old;return alert('Para yok edilemedi: '+error.message)}exWalletCampaign=null;await exLoadWallets(true);toast(`${amount} ${label} kesenden çıkarıldı`)}
 if(b.id==='addEncounterPlayer'){if(!state.characters.length)return alert('Önce Karakterler menüsünden en az bir oyuncu karakteri oluştur.');modal('Oyuncuyu savaşa ekle',`<label>Karakter<select id="encPlayerSelect">${state.characters.map((c,i)=>`<option value="${i}">${esc(c.name)} — HP ${c.hp}/${c.maxHp||c.hp} • AC ${c.ac||10}</option>`).join('')}</select></label>${field('encPlayerInit','Initiative','number',0)}<button class="primary" id="saveEncounterPlayer">Savaşa Ekle</button>`)}
 if(b.id==='exToggleBuying'){state.shopSettings.buyingEnabled=!state.shopSettings.buyingEnabled;save();render()}
 if(b.dataset.shopToggle){let x=state.shopSettings.shops[b.dataset.shopToggle];x.enabled=!x.enabled;save();render()}
 if(b.dataset.shopFilter){exShopFilter=b.dataset.shopFilter;render()}
 if(b.id==='exAddItem')modal('Özel market ürünü',field('exItemName','Ürün adı')+`<label>Dükkân<select id="exItemShop">${Object.entries(EX_SHOPS).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label><label>Tier<select id="exItemTier"><option>1</option><option>2</option><option>3</option></select></label>`+field('exItemPrice','Fiyat (CP cinsinden)','number',100)+field('exItemStock','Stok','number',1)+field('exItemEffect','Tür / etkisi')+`<label>Açıklama<textarea id="exItemNote"></textarea></label><button id="exSaveItem" class="primary">Ürünü ekle</button>`)
 if(b.id==='exSaveItem'){state.market.push({id:uid(),name:$('#exItemName').value,shop:$('#exItemShop').value,tier:+$('#exItemTier').value,priceCopper:+$('#exItemPrice').value||0,stock:+$('#exItemStock').value||0,effect:$('#exItemEffect').value,note:$('#exItemNote').value,active:true,custom:true});save();$('#modal').close();render()}
 if(b.dataset.itemToggle){let x=state.market.find(i=>i.id===b.dataset.itemToggle);x.active=x.active===false;save();render()}
 if(b.dataset.itemPrice){let x=state.market.find(i=>i.id===b.dataset.itemPrice),v=+prompt('Yeni fiyat (CP)',x.priceCopper);if(Number.isFinite(v)&&v>=0){x.priceCopper=Math.floor(v);save();render()}}
 if(b.dataset.itemStock){let x=state.market.find(i=>i.id===b.dataset.itemStock),v=+prompt('Yeni stok',x.stock);if(Number.isFinite(v)&&v>=0){x.stock=Math.floor(v);save();render()}}
 if(b.dataset.itemDelete){state.market=state.market.filter(i=>i.id!==b.dataset.itemDelete);save();render()}
 if(b.dataset.buyItem){b.disabled=true;b.textContent='Alınıyor…';let {data,error}=await db.rpc('shop_buy',{p_user:auth.id,p_campaign:current.id,p_item_id:b.dataset.buyItem});if(error){b.disabled=false;b.textContent='Satın Al';return alert(error.message)}exWalletCampaign=null;await Promise.all([syncFromServer(false),exLoadWallets(true)]);if(realtimeChannel)realtimeChannel.send({type:'broadcast',event:'campaign-changed',payload:{campaignId:current.id,at:Date.now()}});toast((data?.[0]?.item_name||'Eşya')+' satın alındı')}
 if(b.dataset.encEffect){let x=state.encounter[+b.dataset.encEffect],name=prompt('Efekt adı (örn. Zehirli)');if(!name)return;let duration=prompt('Süre (örn. 3 tur / savaş sonuna kadar)','3 tur');x.effects??=[];x.effects.push({name,duration});window.v31SyncCharacterFromEncounter?.(x,{effects:true});save();render()}
 if(b.dataset.encRemoveEffect){let [i,j]=b.dataset.encRemoveEffect.split('|'),x=state.encounter[+i];x?.effects?.splice(+j,1);window.v31SyncCharacterFromEncounter?.(x,{effects:true});save();render()}
 if(b.id==='saveEncounterPlayer'){let c=state.characters[+$('#encPlayerSelect').value];if(!c)return;let existing=state.encounter.find(x=>x.characterId===c.id);if(existing){$('#modal').close();return alert(c.name+' zaten savaş alanında.')}state.encounter.push({id:uid(),characterId:c.id,userId:c.userId||'',name:c.name,init:+$('#encPlayerInit').value||0,hp:+c.hp||0,maxHp:+c.maxHp||+c.hp||0,ac:+c.ac||10,effects:Array.isArray(c.effects)?c.effects.map(x=>typeof x==='string'?x:{...x}):[],turn:!state.encounter.length,kind:'player'});save();$('#modal').close();render();toast(c.name+' savaşa eklendi')}
});
document.addEventListener('change',e=>{if(e.target.id==='exDiscount'){state.shopSettings.discount=+e.target.value;save();render()}if(e.target.dataset.shopTier){state.shopSettings.shops[e.target.dataset.shopTier].tier=+e.target.value;save();render()}});
setInterval(()=>{if(page==='treasury'||page==='market')exLoadWallets(true)},7000);
if(auth&&current)render();
