-- Kadim Masa Defteri v21: kalıcı kampanya mesajları ve bildirimler.

create table if not exists public.campaign_messages(
 id bigint generated by default as identity primary key,
 campaign_id uuid not null references public.campaigns(id) on delete cascade,
 sender_id uuid not null references public.accounts(id) on delete cascade,
 recipient_id uuid references public.accounts(id) on delete cascade,
 body text not null check(length(body) between 1 and 1200),
 created_at timestamptz not null default now()
);
create index if not exists campaign_messages_room_time_idx on public.campaign_messages(campaign_id,created_at desc);
alter table public.campaign_messages enable row level security;

create table if not exists public.campaign_notifications(
 id bigint generated by default as identity primary key,
 campaign_id uuid not null references public.campaigns(id) on delete cascade,
 user_id uuid not null references public.accounts(id) on delete cascade,
 title text not null,body text not null default '',is_read boolean not null default false,
 created_at timestamptz not null default now()
);
create index if not exists campaign_notifications_user_idx on public.campaign_notifications(user_id,campaign_id,is_read,created_at desc);
alter table public.campaign_notifications enable row level security;

create or replace function public.campaign_message_send(p_user uuid,p_campaign uuid,p_recipient uuid,p_body text)
returns bigint language plpgsql security definer set search_path=public as $$
declare mid bigint; sender_name text;
begin
 if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user) then raise exception 'Bu kampanyaya üye değilsin'; end if;
 if p_recipient is not null and not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_recipient) then raise exception 'Alıcı bu kampanyada değil'; end if;
 if length(trim(coalesce(p_body,'')))<1 then raise exception 'Mesaj boş olamaz'; end if;
 select display_name into sender_name from accounts where id=p_user;
 insert into campaign_messages(campaign_id,sender_id,recipient_id,body) values(p_campaign,p_user,p_recipient,left(trim(p_body),1200)) returning id into mid;
 if p_recipient is null then
  insert into campaign_notifications(campaign_id,user_id,title,body)
  select p_campaign,m.user_id,'Yeni genel mesaj',sender_name||': '||left(trim(p_body),120) from campaign_members m where m.campaign_id=p_campaign and m.user_id<>p_user;
 elsif p_recipient<>p_user then
  insert into campaign_notifications(campaign_id,user_id,title,body) values(p_campaign,p_recipient,'Yeni özel mesaj',sender_name||': '||left(trim(p_body),120));
 end if;
 return mid;
end $$;

create or replace function public.campaign_message_list(p_user uuid,p_campaign uuid,p_limit integer default 150)
returns table(id bigint,sender_id uuid,sender_name text,recipient_id uuid,recipient_name text,body text,created_at timestamptz)
language sql security definer set search_path=public as $$
 select q.id,q.sender_id,q.sender_name,q.recipient_id,q.recipient_name,q.body,q.created_at from (
  select m.id,m.sender_id,s.display_name as sender_name,m.recipient_id,r.display_name as recipient_name,m.body,m.created_at
  from campaign_messages m join accounts s on s.id=m.sender_id left join accounts r on r.id=m.recipient_id
  where m.campaign_id=p_campaign and exists(select 1 from campaign_members cm where cm.campaign_id=p_campaign and cm.user_id=p_user)
  and (m.recipient_id is null or m.sender_id=p_user or m.recipient_id=p_user)
  order by m.created_at desc limit greatest(1,least(coalesce(p_limit,150),300))
 ) q order by q.created_at asc
$$;

create or replace function public.campaign_notification_emit(p_user uuid,p_campaign uuid,p_target uuid,p_title text,p_body text)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user and role='dm') then raise exception 'Yalnızca DM bildirim gönderebilir'; end if;
 if p_target is null then
  insert into campaign_notifications(campaign_id,user_id,title,body) select p_campaign,m.user_id,left(p_title,100),left(coalesce(p_body,''),500) from campaign_members m where m.campaign_id=p_campaign and m.user_id<>p_user;
 else insert into campaign_notifications(campaign_id,user_id,title,body) values(p_campaign,p_target,left(p_title,100),left(coalesce(p_body,''),500)); end if;
 return true;
end $$;

create or replace function public.campaign_notification_list(p_user uuid,p_campaign uuid)
returns table(id bigint,title text,body text,is_read boolean,created_at timestamptz)
language sql security definer set search_path=public as $$
 select n.id,n.title,n.body,n.is_read,n.created_at from campaign_notifications n
 where n.user_id=p_user and n.campaign_id=p_campaign
 and exists(select 1 from campaign_members m where m.campaign_id=p_campaign and m.user_id=p_user)
 order by n.created_at desc limit 150
$$;

create or replace function public.campaign_notification_read(p_user uuid,p_campaign uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin update campaign_notifications set is_read=true where user_id=p_user and campaign_id=p_campaign and not is_read;return true;end $$;

revoke all on function public.campaign_message_send(uuid,uuid,uuid,text),public.campaign_message_list(uuid,uuid,integer),public.campaign_notification_emit(uuid,uuid,uuid,text,text),public.campaign_notification_list(uuid,uuid),public.campaign_notification_read(uuid,uuid) from public;
grant execute on function public.campaign_message_send(uuid,uuid,uuid,text),public.campaign_message_list(uuid,uuid,integer),public.campaign_notification_emit(uuid,uuid,uuid,text,text),public.campaign_notification_list(uuid,uuid),public.campaign_notification_read(uuid,uuid) to anon,authenticated;
