let sessionMessages=[],sessionNotifications=[],sessionLoadedRoom=null,sessionNotificationRoom=null,sessionLoading=false,sessionNotificationLoading=false,sessionUnread=0;
const SESSION_TRANSIENT_EFFECTS=new Set(['Blinded','Deafened','Frightened','Grappled','Incapacitated','Paralyzed','Poisoned','Prone','Restrained','Stunned','Unconscious','Concentration','Burning','Bleeding','Hasted','Slowed']);
function sessionEnsure(){state.worldDate??=new Date().toISOString().slice(0,10);state.encounterRound??=1;state.encounterActive??=false}
function sessionDateText(){sessionEnsure();return new Date(state.worldDate+'T12:00:00').toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'})}
function sessionPending(){let c=myChar();return c?.approvalStatus==='pending'}
function sessionPendingPage(){let c=myChar();return `<section class="card approval-wait"><small>DM ONAYI BEKLENİYOR</small><h2>${esc(c?.name||'Karakterin')} masanın kapısında</h2><p>${esc(c?.species||'')} ${c?.subspecies?'• '+esc(c.subspecies):''} • ${esc(c?.className||'')}</p><p>DM karakterini onayladığında bütün oyuncu menüleri açılacak. Bu sırada seçimin kampanyaya kaydedildi.</p></section>`}

const sessionBasePlayerDash=playerPages.dashboard;
playerPages.dashboard=()=>sessionPending()?sessionPendingPage():`<div class="session-strip"><span>📅 ${sessionDateText()}</span><span>Oturum #${state.session||1}</span></div>${sessionBasePlayerDash()}`;
const sessionBaseDmDash=dmPages.dashboard;
dmPages.dashboard=()=>{sessionEnsure();return `<section class="card session-control"><div><small>KAMPANYA ZAMANI</small><h2>${sessionDateText()}</h2></div><div class="toolbar"><input id="sessionWorldDate" type="date" value="${state.worldDate}"><button id="sessionSetDate" class="ghost">Tarihi Ayarla</button><button data-day="1" class="ghost">+1 Gün</button><button data-day="7" class="ghost">+7 Gün</button><button id="sessionLongRest" class="primary">☾ Long Rest</button></div></section>${sessionBaseDmDash()}`};

function sessionEncounterPlayer(){sessionEnsure();let active=state.encounter.find(x=>x.turn);return `<section class="card encounter-board"><div class="between row"><div><small>${state.encounterActive?'AKTİF ÇATIŞMA':'BEKLEMEDE'}</small><h2>Tur ${state.encounterRound}</h2></div><b>${active?'Sıra: '+esc(active.name):'Savaş başlamadı'}</b></div><div class="encounter-view">${state.encounter.map(x=>`<article class="${x.turn?'active-turn':''}"><b>${esc(x.name)}</b><span>Initiative ${x.init}</span><span>HP ${x.hp} • AC ${x.ac}</span>${(x.effects||[]).map(e=>{let name=typeof e==='string'?e:e?.name,duration=typeof e==='string'?'':e?.duration;return name?`<small>${esc(name)}${duration?` • ${esc(duration)}`:''}</small>`:''}).join('')}</article>`).join('')||'<div class="empty">Savaş alanı boş.</div>'}</div></section>`}
const sessionBaseEncounter=dmPages.encounter;
dmPages.encounter=()=>{sessionEnsure();let active=state.encounter.find(x=>x.turn);return `<section class="card combat-console"><div><small>${state.encounterActive?'ÇATIŞMA DEVAM EDİYOR':'ENCOUNTER HAZIRLIĞI'}</small><h2>Tur ${state.encounterRound}${active?' • '+esc(active.name):''}</h2></div><div class="toolbar"><button id="sessionStartCombat" class="primary">⚔ Savaşı Başlat</button><button id="sessionNextCombat" class="ghost">Sonraki Tur</button><button id="sessionEndCombat" class="danger">Savaşı Bitir</button></div></section>${sessionBaseEncounter()}`};
playerPages.encounter=sessionEncounterPlayer;

function sessionDice(){queueMicrotask(()=>prLoadDice());return `<div class="session-dice"><section class="card dice-forge"><div class="dice-hero"><div class="pr-d20">20</div><div><small>KEMİKLER KONUŞSUN</small><h2>Gelişmiş Zar Ocağı</h2><p>Standart, avantaj/dezavantaj, özel formül ve Fate zarları.</p></div></div><div class="dice-type-grid">${[['2','Yazı/Tura'],['3','Üçlü'],['4','d4'],['6','d6'],['8','d8'],['10','d10'],['12','d12'],['20','d20'],['100','d%'],['F','Fate']].map(x=>`<button data-session-die="${x[0]}"><b>${x[1]}</b><small>${x[0]==='F'?'- / 0 / +':'1–'+x[0]}</small></button>`).join('')}</div><div class="dice-action-row"><label>Adet<input id="sessionDiceCount" type="number" min="1" max="20" value="1"></label><label>Bonus<input id="sessionDiceBonus" type="number" value="0"></label><button data-session-roll="normal" class="primary">Zarı At</button><button data-session-roll="adv" class="ghost">Avantaj d20</button><button data-session-roll="dis" class="ghost">Dezavantaj d20</button></div><div class="formula-row"><input id="sessionFormula" class="input" placeholder="Özel formül: 4d6+3"><button id="sessionFormulaRoll" class="ghost">Formülü At</button></div><div id="sessionRollout" class="session-rollout"><b>—</b><small>Zar türünü seç</small></div></section><section class="card pr-log-card"><div><small>ORTAK MASA KAYDI</small><h2>Zar Günlüğü</h2></div><div class="pr-dicelog">${prDiceRows.map(r=>`<article><div><b>${esc(r.roller_name)}</b><small>${new Date(r.created_at).toLocaleString('tr-TR')}</small></div><span>${esc(r.formula)}</span><strong>${r.total}</strong><small>[${(r.rolls||[]).join(', ')}]</small></article>`).join('')||'<p class="empty">Henüz zar atılmadı.</p>'}</div></section></div>`}
dmPages.dice=sessionDice;playerPages.dice=sessionDice;
let sessionSelectedDie='20';
async function sessionRecordRoll(formula,values,bonus,total){let name=myChar()?.name||auth?.name||'Bilinmeyen',out=$('#sessionRollout');if(out)out.innerHTML=`<b>${total}</b><small>${formula} → [${values.join(', ')}]</small>`;let {error}=await db.rpc('dice_roll_add',{p_user:auth.id,p_campaign:current.id,p_roller_name:name,p_formula:formula,p_rolls:values,p_bonus:bonus,p_total:total});if(error)return alert(error.message);prDiceCampaign=null;await prLoadDice(true)}
function sessionRoll(mode='normal',count=null,sides=null,bonus=null){count=Math.max(1,Math.min(20,count??+($('#sessionDiceCount')?.value||1)));bonus=bonus??+($('#sessionDiceBonus')?.value||0);sides=sides??sessionSelectedDie;if(mode==='adv'||mode==='dis'){let v=[1+Math.floor(Math.random()*20),1+Math.floor(Math.random()*20)],picked=mode==='adv'?Math.max(...v):Math.min(...v);return sessionRecordRoll(`${mode==='adv'?'Avantaj':'Dezavantaj'} 2d20${bonus?prSigned(bonus):''}`,v,bonus,picked+bonus)}let vals=Array.from({length:count},()=>sides==='F'?Math.floor(Math.random()*3)-1:1+Math.floor(Math.random()*(+sides))),total=vals.reduce((a,b)=>a+b,0)+bonus;return sessionRecordRoll(`${count}d${sides}${bonus?prSigned(bonus):''}`,vals,bonus,total)}

async function sessionLoadMessages(force=false){if(!current||sessionLoading||(!force&&sessionLoadedRoom===current.id))return;sessionLoading=true;let cid=current.id,{data,error}=await db.rpc('campaign_message_list',{p_user:auth.id,p_campaign:cid,p_limit:200});sessionLoading=false;if(current?.id!==cid)return;if(error){sessionMessages=[];sessionLoadedRoom=cid;if(page==='chat')render();return}let changed=JSON.stringify(data||[])!==JSON.stringify(sessionMessages);sessionMessages=data||[];sessionLoadedRoom=cid;if(changed&&page==='chat')render()}
function sessionChat(){queueMicrotask(()=>sessionLoadMessages());let recipients=members.filter(x=>x.userId!==auth.id);return `<section class="card chat-shell"><div class="between row"><div><small>KAMPANYA HABERCİSİ</small><h2>Masa Yazışmaları</h2></div><label>Alıcı<select id="sessionRecipient"><option value="">Herkes • Genel</option>${recipients.map(x=>`<option value="${x.userId}">${esc(x.name)} • ${x.role==='dm'?'DM':'Oyuncu'}</option>`).join('')}</select></label></div><div class="chat-feed">${sessionMessages.map(m=>`<article class="${m.sender_id===auth.id?'mine':''} ${m.recipient_id?'private':''}"><small>${esc(m.sender_name)}${m.recipient_id?' → '+esc(m.recipient_name):' → Herkes'} • ${new Date(m.created_at).toLocaleString('tr-TR')}</small><p>${esc(m.body)}</p></article>`).join('')||'<div class="empty">Henüz mesaj yok.</div>'}</div><div class="chat-compose"><textarea id="sessionMessage" maxlength="1200" placeholder="Masaya mesaj bırak…"></textarea><button id="sessionSendMessage" class="primary">Gönder</button></div></section>`}
function sessionUpdateNoticeBadge(){let b=document.querySelector('[data-page="notifications"]');if(!b)return;let mark=b.querySelector('.nav-unread');if(sessionUnread&&!mark)b.insertAdjacentHTML('beforeend',` <i class="nav-unread">${sessionUnread}</i>`);else if(mark){mark.textContent=sessionUnread;mark.hidden=!sessionUnread}}
async function sessionLoadNotifications(force=false){if(!current||sessionNotificationLoading||(!force&&sessionNotificationRoom===current.id))return;sessionNotificationLoading=true;let cid=current.id,{data,error}=await db.rpc('campaign_notification_list',{p_user:auth.id,p_campaign:cid});sessionNotificationLoading=false;if(error||current?.id!==cid)return;let changed=sessionNotificationRoom!==cid||JSON.stringify(data||[])!==JSON.stringify(sessionNotifications);sessionNotifications=data||[];sessionNotificationRoom=cid;sessionUnread=sessionNotifications.filter(x=>!x.is_read).length;sessionUpdateNoticeBadge();if(changed&&page==='notifications')render()}
function sessionNotificationPage(){queueMicrotask(()=>sessionLoadNotifications());return `<section class="card notification-shell"><div class="between row"><div><small>HABERCİ KUZGUNLAR</small><h2>Bildirimler ${sessionUnread?`<span class="notice-count">${sessionUnread}</span>`:''}</h2></div><button id="sessionReadNotifications" class="ghost">Tümünü Okundu Yap</button></div><div class="notification-list">${sessionNotifications.map(n=>`<article class="${n.is_read?'':'unread'}"><b>${esc(n.title)}</b><p>${esc(n.body)}</p><small>${new Date(n.created_at).toLocaleString('tr-TR')}</small></article>`).join('')||'<div class="empty">Yeni bildirim yok.</div>'}</div></section>`}
dmPages.chat=sessionChat;playerPages.chat=sessionChat;dmPages.notifications=sessionNotificationPage;playerPages.notifications=sessionNotificationPage;
if(!dmNav.some(x=>x[0]==='chat'))dmNav.splice(-2,0,['chat','✉','Yazışmalar'],['notifications','♢','Bildirimler']);
if(!playerNav.some(x=>x[0]==='encounter'))playerNav.splice(5,0,['encounter','⚔','Aktif Savaş']);
if(!playerNav.some(x=>x[0]==='chat'))playerNav.splice(-2,0,['chat','✉','Yazışmalar'],['notifications','♢','Bildirimler']);
for(let key of Object.keys(playerPages)){if(key==='dashboard')continue;let original=playerPages[key];playerPages[key]=()=>sessionPending()?sessionPendingPage():original()}

document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b||!current)return;
 if(b.dataset.approveChar){let c=state.characters.find(x=>x.id===b.dataset.approveChar);c.approvalStatus='approved';save();await db.rpc('campaign_notification_emit',{p_user:auth.id,p_campaign:current.id,p_target:c.userId,p_title:'Karakter onaylandı',p_body:`${c.name} artık maceraya hazır.`});render()}
 if(b.dataset.rejectChar){let c=state.characters.find(x=>x.id===b.dataset.rejectChar);if(!confirm(`${c.name} reddedilsin mi? Oyuncu yeniden karakter oluşturabilecek.`))return;state.characters=state.characters.filter(x=>x.id!==c.id);save();await db.rpc('campaign_notification_emit',{p_user:auth.id,p_campaign:current.id,p_target:c.userId,p_title:'Karakter yeniden düzenlenmeli',p_body:'DM karakter başvurunu reddetti. Yeni bir karakter oluşturabilirsin.'});render()}
 if(b.dataset.day){sessionEnsure();let d=new Date(state.worldDate+'T12:00:00');d.setDate(d.getDate()+(+b.dataset.day));state.worldDate=d.toISOString().slice(0,10);save();render()}
 if(b.id==='sessionSetDate'){state.worldDate=$('#sessionWorldDate').value||state.worldDate;save();render()}
 if(b.id==='sessionLongRest'){if(!confirm('Tüm onaylı karakterlere Long Rest uygulansın mı?'))return;for(let c of state.characters.filter(x=>x.approvalStatus!=='pending')){c.hp=c.maxHp;c.tempHp=0;c.effects=(c.effects||[]).filter(x=>!SESSION_TRANSIENT_EFFECTS.has(typeof x==='string'?x:x?.name));c.spellSlotsUsed={};c.hitDiceSpent=0;c.resources={};window.v31SyncEncounterFromCharacter?.(c,{hp:true,effects:true})}save();await db.rpc('campaign_notification_emit',{p_user:auth.id,p_campaign:current.id,p_target:null,p_title:'Long Rest tamamlandı',p_body:'HP ve dinlenme kaynakları yenilendi; geçici savaş efektleri temizlendi.'});render()}
 if(b.id==='sessionStartCombat'){if(!state.encounter.length)return alert('Önce savaş alanına karakter veya yaratık ekle.');state.encounter.forEach(x=>{if(!+x.init)x.init=1+Math.floor(Math.random()*20);x.turn=false});state.encounter.sort((a,z)=>z.init-a.init);state.encounter[0].turn=true;state.encounterRound=1;state.encounterActive=true;save();render()}
 if(b.id==='clearEncounter'){state.encounterActive=false;state.encounterRound=1}
 if(b.id==='sessionNextCombat'){if(!state.encounter.length)return;let i=state.encounter.findIndex(x=>x.turn);state.encounter.forEach(x=>x.turn=false);let next=(i+1+state.encounter.length)%state.encounter.length;if(i>=0&&next===0)state.encounterRound=(state.encounterRound||1)+1;state.encounter[next].turn=true;state.encounterActive=true;save();render()}
 if(b.id==='sessionEndCombat'){if(!confirm('Aktif savaş sona ersin mi? Savaşçılar listede kalır.'))return;state.encounter.forEach(x=>x.turn=false);state.encounterActive=false;state.encounterRound=1;save();render()}
 if(b.dataset.sessionDie){sessionSelectedDie=b.dataset.sessionDie;document.querySelectorAll('[data-session-die]').forEach(x=>x.classList.toggle('selected',x===b))}
 if(b.dataset.sessionRoll)sessionRoll(b.dataset.sessionRoll);
 if(b.id==='sessionFormulaRoll'){let raw=$('#sessionFormula').value.trim(),m=raw.match(/^(\d{1,2})d(\d{1,3})(?:\s*([+-])\s*(\d+))?$/i);if(!m)return alert('Formül örneği: 4d6+3');let count=Math.min(20,+m[1]),sides=Math.min(1000,+m[2]),bonus=m[3]?(m[3]==='-'?-1:1)*(+m[4]):0;sessionRoll('normal',count,String(sides),bonus)}
 if(b.id==='sessionSendMessage'){let body=$('#sessionMessage').value.trim();if(!body)return;let recipient=$('#sessionRecipient').value||null;b.disabled=true;let {error}=await db.rpc('campaign_message_send',{p_user:auth.id,p_campaign:current.id,p_recipient:recipient,p_body:body});if(error){b.disabled=false;return alert(error.message)}sessionLoadedRoom=null;await sessionLoadMessages(true)}
 if(b.id==='sessionReadNotifications'){await db.rpc('campaign_notification_read',{p_user:auth.id,p_campaign:current.id});await sessionLoadNotifications(true)}
},true);
setInterval(()=>{if(page==='chat')sessionLoadMessages(true);if(current)sessionLoadNotifications(true)},5000);
