create extension if not exists pgcrypto with schema extensions;
create table if not exists public.accounts(id uuid primary key default gen_random_uuid(),username text unique not null,display_name text not null,password_hash text not null,created_at timestamptz default now());
create table if not exists public.campaigns(id uuid primary key default gen_random_uuid(),code text unique not null,name text not null,dm_password_hash text not null default '',state jsonb not null default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.campaign_members(campaign_id uuid references public.campaigns(id) on delete cascade,user_id uuid references public.accounts(id) on delete cascade,role text not null check(role in ('dm','player')),joined_at timestamptz default now(),primary key(campaign_id,user_id)); alter table public.campaigns alter column dm_password_hash set default '';
alter table public.accounts enable row level security; alter table public.campaigns enable row level security; alter table public.campaign_members enable row level security;
create or replace function public.account_register(p_username text,p_password text,p_display text) returns table(user_id uuid,display_name text) language plpgsql security definer set search_path=public,extensions as $$declare uid uuid;begin if length(trim(p_username))<3 or length(p_password)<3 then raise exception 'Kullanıcı adı ve şifre en az 3 karakter olmalı';end if;insert into accounts(username,display_name,password_hash) values(lower(trim(p_username)),coalesce(nullif(trim(p_display),''),trim(p_username)),crypt(p_password,gen_salt('bf'))) returning id into uid;return query select uid,a.display_name from accounts a where a.id=uid;exception when unique_violation then raise exception 'Bu kullanıcı adı alınmış';end$$;
create or replace function public.account_login(p_username text,p_password text) returns table(user_id uuid,display_name text) language sql security definer set search_path=public,extensions as $$select a.id,a.display_name from accounts a where a.username=lower(trim(p_username)) and a.password_hash=crypt(p_password,a.password_hash)$$;
create or replace function public.campaign_create_v2(p_user uuid,p_name text) returns table(campaign_id uuid,code text) language plpgsql security definer set search_path=public,extensions as $$declare cid uuid;c text;begin loop c:=upper(substr(md5(random()::text),1,6));begin insert into campaigns(code,name,state) values(c,p_name,'{}') returning id into cid;insert into campaign_members(campaign_id,user_id,role) values(cid,p_user,'dm');return query select cid,c;return;exception when unique_violation then null;end;end loop;end$$;
create or replace function public.campaign_join_v2(p_user uuid,p_code text) returns boolean language plpgsql security definer set search_path=public as $$declare cid uuid;begin select id into cid from campaigns where code=upper(trim(p_code));if cid is null then return false;end if;insert into campaign_members(campaign_id,user_id,role) values(cid,p_user,'player') on conflict do nothing;return true;end$$;
create or replace function public.campaign_list_v2(p_user uuid) returns table(id uuid,code text,name text,role text) language sql security definer set search_path=public as $$select c.id,c.code,c.name,m.role from campaign_members m join campaigns c on c.id=m.campaign_id where m.user_id=p_user order by c.updated_at desc$$;
create or replace function public.campaign_load_v2(p_user uuid,p_campaign uuid) returns table(id uuid,code text,name text,role text,state jsonb,members jsonb) language sql security definer set search_path=public as $$select c.id,c.code,c.name,me.role,c.state,coalesce((select jsonb_agg(jsonb_build_object('userId',a.id,'name',a.display_name,'role',cm.role)) from campaign_members cm join accounts a on a.id=cm.user_id where cm.campaign_id=c.id),'[]'::jsonb) from campaigns c join campaign_members me on me.campaign_id=c.id and me.user_id=p_user where c.id=p_campaign$$;
create or replace function public.campaign_save_v2(p_user uuid,p_campaign uuid,p_state jsonb) returns boolean language plpgsql security definer set search_path=public as $$begin update campaigns c set state=p_state,updated_at=now() where c.id=p_campaign and exists(select 1 from campaign_members m where m.campaign_id=c.id and m.user_id=p_user and m.role='dm');return found;end$$;
grant execute on function public.account_register(text,text,text),public.account_login(text,text),public.campaign_create_v2(uuid,text),public.campaign_join_v2(uuid,text),public.campaign_list_v2(uuid),public.campaign_load_v2(uuid,uuid),public.campaign_save_v2(uuid,uuid,jsonb) to anon,authenticated;

-- Gizli oyuncu <-> DM anlaşmaları
create table if not exists public.pact_messages(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references public.campaigns(id) on delete cascade,player_id uuid not null references public.accounts(id) on delete cascade,sender_role text not null check(sender_role in ('dm','player')),body text not null check(char_length(body) between 1 and 1000),created_at timestamptz not null default now());
create index if not exists pact_messages_campaign_player_created_idx on public.pact_messages(campaign_id,player_id,created_at);
alter table public.pact_messages enable row level security;
create or replace function public.pact_send(p_user uuid,p_campaign uuid,p_body text) returns uuid language plpgsql security definer set search_path=public as $$declare new_id uuid;begin if char_length(trim(coalesce(p_body,''))) not between 1 and 1000 then raise exception 'Mesaj 1-1000 karakter olmalı';end if;if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user and role='player') then raise exception 'Bu kampanyada oyuncu değilsin';end if;insert into pact_messages(campaign_id,player_id,sender_role,body) values(p_campaign,p_user,'player',trim(p_body)) returning id into new_id;return new_id;end$$;
create or replace function public.pact_reply(p_user uuid,p_campaign uuid,p_player uuid,p_body text) returns uuid language plpgsql security definer set search_path=public as $$declare new_id uuid;begin if char_length(trim(coalesce(p_body,''))) not between 1 and 1000 then raise exception 'Mesaj 1-1000 karakter olmalı';end if;if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user and role='dm') then raise exception 'Yalnızca DM cevap verebilir';end if;if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_player and role='player') then raise exception 'Oyuncu bu kampanyada değil';end if;insert into pact_messages(campaign_id,player_id,sender_role,body) values(p_campaign,p_player,'dm',trim(p_body)) returning id into new_id;return new_id;end$$;
create or replace function public.pact_list(p_user uuid,p_campaign uuid) returns table(id uuid,player_id uuid,player_name text,sender_role text,body text,created_at timestamptz) language plpgsql security definer set search_path=public as $$declare caller_role text;begin select cm.role into caller_role from campaign_members cm where cm.campaign_id=p_campaign and cm.user_id=p_user;if caller_role is null then return;end if;return query select q.id,q.player_id,q.player_name,q.sender_role,q.body,q.created_at from(select pm.id,pm.player_id,a.display_name as player_name,pm.sender_role,pm.body,pm.created_at from pact_messages pm join accounts a on a.id=pm.player_id where pm.campaign_id=p_campaign and(caller_role='dm' or pm.player_id=p_user) order by pm.created_at desc limit 300)q order by q.created_at;end$$;
revoke all on function public.pact_send(uuid,uuid,text),public.pact_reply(uuid,uuid,uuid,text),public.pact_list(uuid,uuid) from public;
grant execute on function public.pact_send(uuid,uuid,text),public.pact_reply(uuid,uuid,uuid,text),public.pact_list(uuid,uuid) to anon,authenticated;
