const V50_LEVEL_PROFILES=[
  {levels:'1–2',epithet:'İlk İz',difficulty:'Kolay–Orta',duration:'2–4 saat',dc:'10–12',coin:'8–30 GP',threat:'haydut gözcüler, aç kurtlar veya tek bir düşük CR yaratık',scale:'3–4 kişilik parti için 1 ana tehdit ve en fazla 3 minion; ölümcül alan etkisi kullanma.'},
  {levels:'3–4',epithet:'Sınır Alarmı',difficulty:'Orta',duration:'1 oturum',dc:'12–14',coin:'40–120 GP',threat:'örgütlü kaçakçılar, ghoul sürüsü veya CR 2–4 seçkin yaratık',scale:'3–5 kişilik parti için iki aşama; ikinci dalgayı yalnız ilk sahne kolay geçtiyse getir.'},
  {levels:'5–7',epithet:'Kırılan Yemin',difficulty:'Orta–Zor',duration:'1–2 oturum',dc:'14–16',coin:'180–450 GP',threat:'wyvern, troll, wight birliği veya büyü kullanan kıdemli düşman',scale:'partinin kaynaklarını tüketen bir çevre tehlikesi ve bir ana çatışma kullan; kısa dinlenme noktası bırak.'},
  {levels:'8–10',epithet:'Bölgesel Kriz',difficulty:'Zor',duration:'2–3 oturum',dc:'16–18',coin:'650–1.200 GP',threat:'genç ejderha, planar birlik, savaş büyücüsü veya çok aşamalı boss',scale:'boss’a legendary olmayan iki özel tepki ya da ikinci faz ver; tek başarısız zar görevi bitirmesin.'},
  {levels:'11–14',epithet:'Krallık Meselesi',difficulty:'Çok Zor',duration:'3–5 oturum',dc:'18–20',coin:'2.500–5.000 GP',threat:'kadim muhafız, büyük iblis, krallık ordusu veya bölgeyi değiştiren afet',scale:'çatışmayı hedef, tahliye ve ritüel gibi üç eşzamanlı sorunla kur; başarı derecelerini bölgesel sonuçlara bağla.'},
  {levels:'15–20',epithet:'Efsanevi Sonuç',difficulty:'Efsanevi',duration:'kampanya yayı',dc:'20–24',coin:'10.000+ GP veya artifact',threat:'avatar, elder varlık, planar ordu veya dünya düzenini değiştiren düşman',scale:'yalnız HP yarışı kurma; üç mühür/hedef, lair etkileri ve oyuncu seçimlerine bağlı en az iki final sonucu kullan.'}
];

const V50_REGIONS=[
  {id:'karacam',name:'Karaçam',feature:'sık, kadim orman ve sisli av patikaları',faction:'Karaçam ormancıları'},
  {id:'tacova',name:'Taçova',feature:'verimli ovalar, sur dışı köyler ve saray yolları',faction:'Taçova muhafızları'},
  {id:'kultac',name:'Kültaç',feature:'lav yarıkları, kül tarlaları ve ateş kültü kalıntıları',faction:'Kor Ocağı ustaları'},
  {id:'buzdis',name:'Buzdiş',feature:'donmuş geçitler, derin madenler ve çığ koridorları',faction:'Buzdiş madencileri'},
  {id:'tuzhisar',name:'Tuzhisar',feature:'gelgit tünelleri, tuz depoları ve kaçakçı koyları',faction:'Tuzhisar liman nöbetçileri'},
  {id:'gumusgol',name:'Gümüşgöl',feature:'ay ışıklı göl, yansıma büyüsü ve batık mahzenler',faction:'Gümüşgöl kâtipleri'},
  {id:'uckopru',name:'Üçköprü',feature:'nehir kavşağı, gümrük kapıları ve yoğun kervan trafiği',faction:'Üçköprü tüccar loncası'},
  {id:'sazlik',name:'Sazlık Nöbeti',feature:'bataklık adaları, karantina kuleleri ve zehirli sis',faction:'Sazlık şifacıları'},
  {id:'kizilkapi',name:'Kızılkapı',feature:'camlaşmış çöl, kuruyan kuyular ve gömülü mezarlar',faction:'Kızılkapı su meclisi'},
  {id:'firtinaburnu',name:'Fırtınaburnu',feature:'uçurum fenerleri, sert deniz ve batık filolar',faction:'Fırtınaburnu denizcileri'},
  {id:'aykuyu',name:'Aykuyu',feature:'ay tapınakları, yeraltı kuyuları ve unutulmuş katakomblar',faction:'Aykuyu gece rahipleri'},
  {id:'kirikadalar',name:'Kırıkadalar',feature:'parçalı adalar, mercan geçitleri ve eski leviathan zincirleri',faction:'Kırıkadalar kaptanları'}
];

const V50_QUEST_BLUEPRINTS=[
  {id:'border-patrol',title:'Sınırda Sönen Fenerler',type:'Devriye / Keşif',tags:['devriye','iz sürme','sınır'],brief:'$region çevresindeki üç nöbet feneri aynı gece söndü. $faction, rota kapanmadan fenerleri kontrol edip kayıp nöbetçileri bulmanızı istiyor.',objectives:['Üç feneri belirlenen sırayla kontrol et.','Kayıp nöbetçilerin izini hava değişmeden takip et.','Sınır ihlalinin kaynağını bul ve yolu yeniden güvenli ilan et.'],clues:['İlk fenerde kan değil, ters çevrilmiş bir bölge mührü var.','Ayak izleri $feature içinden kasıtlı olarak ikiye ayrılıyor.'],checks:['Survival DC $dc: gerçek izi sahte olandan ayır.','Perception DC $dc: uzaktaki duman işaretini fark et.','Investigation DC $dc: fener mekanizmasının içeriden bozulduğunu kanıtla.'],encounter:'$threat; kaçan nöbetçiyi korumak çatışmanın ikincil hedefidir.',twist:'Fenerleri düşman değil, yaklaşan saldırıyı kimse fark etmesin diye rüşvet alan bir yüzbaşı söndürdü.',secret:'Kayıp nöbetçilerden biri yüzbaşının suçunu gösteren mühürlü emir kâğıdını saklıyor.',reward:'$coin, $faction itibarı ve bir sonraki yolculukta güvenli kamp noktası.',failure:'Sınır yolu üç gün kapanır; sonraki yolculuk +1 gün sürer ve yüzbaşı kanıtları temizler.',scaling:'$scale'},
  {id:'caravan-audit',title:'Mühürsüz Kervan',type:'Kervan / İnceleme',tags:['kervan','kaçakçılık','sosyal'],brief:'$region kapısına gelen değerli bir kervanın yük listesi eksik. Yolcular içeride beklerken yükü denetleyin ve sahte mührün sahibini bulun.',objectives:['Yük listesiyle sandıkları eşleştir.','Kervan halkını birbirinden ayırarak sorgula.','Tehlikeli yükü şehre girmeden güvene al.'],clues:['Bir sandığın ağırlığı listedeki malzemeyle uyuşmuyor.','Arabacı, yol üzerindeki ikinci mola yerini özellikle saklıyor.'],checks:['Investigation DC $dc: sahte tabanı bul.','Insight DC $dc: ezberlenmiş ifadeyi yakala.','Persuasion veya Intimidation DC $dc: muhbirin konuşmasını sağla.'],encounter:'Sandık açılırsa $threat ortaya çıkar; kalabalığı tahliye etmek ayrı bir hedeftir.',twist:'Kaçak mal kâr amacıyla değil, şehirdeki bir hastayı kurtarmak için taşınıyor; asıl suçlu mühür memurudur.',secret:'Mühür memuru aynı yöntemi kullanan üç kervanın tarihini kişisel defterinde tutuyor.',reward:'$coin ve tüccar loncasında fiyat/erişim kolaylığı.',failure:'Kervan tutulur, temel mallar pahalanır ve suçlu başka bir masumu hedef gösterir.',scaling:'$scale'},
  {id:'missing-resident',title:'Dönmeyen Yolcu',type:'Kurtarma / Arama',tags:['kayıp kişi','kurtarma','zaman'],brief:'$region halkından sevilen bir yolcu iki gündür dönmedi. Son görüldüğü patikayı tarayın; hava kararmadan canlı iz bulun.',objectives:['Son görülen yeri yeniden kur.','Kişiye ait üç izi doğrula.','Yolcuyu ve varsa yanında kalanları güvenle çıkar.'],clues:['Kırık dal izleri kaçış değil, birine yol göstermek için bırakılmış.','Kişisel eşya özellikle görünür bir taşın altına konmuş.'],checks:['Survival DC $dc: yağmurdan önce rotayı çıkar.','Medicine DC $dc: bulunan kanın yaşını ve miktarını anla.','Athletics DC $dc: çöken geçidi güvenli biçimde aş.'],encounter:'$threat bölgeyi tutuyor; kayıp kişinin her tur artan çevre tehlikesi vardır.',twist:'Kayıp kişi kaçırılmadı; yaralı bir “düşmanı” koruduğu için kendi isteğiyle saklandı.',secret:'Kurtarılan yabancı bölgedeki yaklaşan daha büyük tehlikenin tek tanığıdır.',reward:'$coin, minnettar aile ve güvenilir bir yerel rehber.',failure:'Kişi hayatta kalır ama tanık kaybolur; tehlike bir sonraki görevde hazırlıklı gelir.',scaling:'$scale'},
  {id:'workshop-sabotage',title:'Ustanın Kırılan Ocağı',type:'Sabotaj / Zanaat',tags:['zanaat','sabotaj','demirci'],brief:'$region ustalarının ana atölyesinde üretim her gece bozuluyor. Ocağı kapatmadan sabotajı ve yöntemi bulun.',objectives:['Bozulan üç üretim aşamasını incele.','Atölyeye erişimi olanları sorgula.','Bir sonraki vardiyada sabotajı güvenle durdur.'],clues:['Metal kusurları ateşten değil, suya karışan ince bir tozdan kaynaklanıyor.','Nöbet defterinde aynı el yazısıyla düzeltilmiş iki saat var.'],checks:['Arcana veya Smith’s Tools DC $dc: kusurun kaynağını belirle.','Investigation DC $dc: gizli besleme hattını bul.','Insight DC $dc: rekabet yalanını ortaya çıkar.'],encounter:'Sabotaj yakalanınca $threat atölyeyi ateşe verir; ocakları korumak gerekir.',twist:'Rakip lonca suçsuzdur; yaşlı usta savaş siparişlerini durdurmak için kendi ocağını sabote ediyor.',secret:'Siparişlerin gerçek alıcısı kalenin resmî kayıtlarında görünmeyen bir paralı asker ordusudur.',reward:'$coin ve bir adet ustalık işi ekipman veya ücretsiz onarım.',failure:'Atölye haftalarca kapanır; bölgedeki silah/zırh stoku düşer ve savaş hazırlığı sürer.',scaling:'$scale'},
  {id:'cursed-heirloom',title:'Mirasın Fısıltısı',type:'Lanet / Ahlaki',tags:['lanet','aile','rol yapma'],brief:'$region soylularından biri, aile yadigârı takıldıktan sonra uykusunda yabancı emirler vermeye başladı. Eşyayı kırmadan lanetin kaynağını bulun.',objectives:['Eşyanın geçmişindeki üç sahibi araştır.','Lanetin tetikleyicisini güvenli ortamda doğrula.','Taşıyıcıyı kurtaracak ritüel veya uzlaşmayı tamamla.'],clues:['Fısıltılar taşıyıcının bilmediği eski bir lehçede ama aynı üç adı tekrarlıyor.','Aile portresinde eşyanın bugünkünden farklı bir parçası var.'],checks:['History DC $dc: adları eski kayıtlarla eşleştir.','Religion veya Arcana DC $dc: lanet türünü belirle.','Charisma save DC $dc: eşyayla temas sırasında emre diren.'],encounter:'Ritüel bozulursa $threat hatıraların biçiminde ortaya çıkar.',twist:'Eşya kötü değildir; ailenin örtbas ettiği cinayetin gerçeğini zorla söyletmeye çalışır.',secret:'Lanet kaldırılırsa soylunun meşruiyetini yok edecek bir tanıklık da serbest kalır.',reward:'$coin, aile arşivine erişim ve DM onaylı tek kullanımlık koruma tılsımı.',failure:'Taşıyıcı bir gece kaybolur ve sırrın kanıtını yok etmeye yönelir.',scaling:'$scale'},
  {id:'mine-rescue',title:'Derindeki Son Vardiya',type:'Maden / Kurtarma',tags:['maden','çöküş','kurtarma'],brief:'$region madeninde asansör hattı koptu; aşağıdan hâlâ vardiya zili geliyor. Hava tükenmeden mahsur kalanları çıkarın.',objectives:['Alternatif iniş rotası kur.','Mahsur kalan grupları ve hava durumunu belirle.','Ana desteği çökertmeden tahliyeyi tamamla.'],clues:['Zil düzenli yardım kodu değil, eski bir maden şarkısının ritminde.','Çöküş yüzeyden aşağı değil, içeriden dışarı doğru olmuş.'],checks:['Athletics DC $dc: güvenli halat hattı kur.','Investigation DC $dc: çöküş yönünü çöz.','Survival DC $dc: hava ve gaz cebini ölç.'],encounter:'$threat dar galeride belirir; yüksek hasar veren saldırılar yeni çöküş riski yaratır.',twist:'Madenciler yaratıkla savaşmıyor; daha derindeki ortak tehdide karşı geçici ateşkes kurdu.',secret:'Maden sahibinin yasak galeriyi açma emri, kazanın gerçek nedenidir.',reward:'$coin, değerli cevher ve bölge ustalarından özel işçilik.',failure:'Herkes ölmez; fakat bir galeri kapanır, cevher kıtlığı ve siyasi suçlama başlar.',scaling:'$scale'},
  {id:'smuggler-tide',title:'Gelgit Kaçakçıları',type:'Kaçakçılık / Takip',tags:['kaçakçı','su','takip'],brief:'$region kıyısında yalnız geceleri görünen işaretler, yasak bir sevkiyata bağlanıyor. Bir sonraki gelgitte hattı izleyin.',objectives:['İşaret sisteminin anlamını çöz.','Alıcı ve taşıyıcıyı aynı anda tespit et.','Tehlikeli sevkiyatı siviller zarar görmeden ele geçir.'],clues:['Fener renkleri gemilere değil, kıyıdaki mağaralara bakıyor.','Yakalanan küçük paketlerin hepsi kasıtlı olarak değersiz.'],checks:['Perception DC $dc: sis içindeki karşı işareti gör.','Stealth DC $dc: teslim noktasına fark edilmeden yaklaş.','Water Vehicles veya Survival DC $dc: gelgit penceresini hesapla.'],encounter:'$threat dar kıyıda sevkiyatı korur; yükselen su tur sayısını sınırlar.',twist:'Kaçakçılar silah değil, resmî şifacıların el koyduğu ilaçları hastalara taşıyor.',secret:'İlaç kıtlığını yaratan kişi, kaçak hattından da pay alan liman sorumlusudur.',reward:'$coin, gizli deniz rotası ve kaçakçı ya da liman ittifakı.',failure:'Sevkiyat kaybolur; hastalık artar ve iki taraf da partiyi suçlar.',scaling:'$scale'},
  {id:'festival-watch',title:'Şenlikteki Dördüncü Maske',type:'Festival / Güvenlik',tags:['festival','kalabalık','sosyal'],brief:'$region şenliğinde üç resmî maskeli ekip var; tanıklar dördüncü bir grubun kasayı izlediğini söylüyor. Töreni durdurmadan güvenliği sağlayın.',objectives:['Kalabalık içinde sahte maskeleri ayır.','Kasa, konuk ve tören alanı için savunma planı kur.','Sabotajı panik çıkmadan engelle.'],clues:['Sahte maskelerde yerel ustaların kullanmadığı bir dikiş var.','Bir yarışmanın başlama saati iki farklı ilanda farklı yazılmış.'],checks:['Perception DC $dc: kalabalık düzenindeki boşluğu fark et.','Performance veya Persuasion DC $dc: paniği bastır.','Insight DC $dc: sahte görevliyi yakala.'],encounter:'$threat kalabalığın içine karışır; sivilleri çıkarmak saldırmaktan daha önemlidir.',twist:'Hedef para değil, tören sırasında ortaya çıkan kadim bir simgedir.',secret:'Şenlik yöneticisi simgenin ne yaptığını biliyor ve saldırıyı yem olarak kullandı.',reward:'$coin, bölgesel ün ve bir festival bağlantısının kalıcı yardımı.',failure:'Şenlik dağılır; can kaybı yerine itibar ve önemli kanıt kaybedilir.',scaling:'$scale'},
  {id:'envoy-road',title:'Elçinin Sessiz Rotası',type:'Diplomasi / Koruma',tags:['elçi','diplomasi','koruma'],brief:'$region üzerinden geçen elçi, görüşme yerine kimseye görünmeden ulaşmak istiyor. Yol, siyasi rakipler ve doğal tehlikelerle dolu.',objectives:['Açık yol ile gizli rota arasında seçim yap.','Elçinin gerçek taleplerini ve kırmızı çizgilerini öğren.','Görüşme yerine kimliği açığa çıkmadan ulaş.'],clues:['Elçinin mührü gerçek ama taşıdığı mektubun kâğıdı başka saraydan.','Yol üzerindeki pusu noktaları saldırıdan çok gözetleme için hazırlanmış.'],checks:['Insight DC $dc: elçinin sakladığı hedefi anla.','Survival DC $dc: iz bırakmayan rota bul.','Deception veya Persuasion DC $dc: kontrol noktasını aş.'],encounter:'$threat elçiyi öldürmek değil canlı ele geçirmek ister.',twist:'Elçi barış için değil, savaşı başlatacak sahte bir teslim anlaşması için gönderildi.',secret:'Elçinin yardımcısı gerçek barış metnini taşıyor ve doğru anda partiye açacak.',reward:'$coin, diplomatik geçiş belgesi ve bir sarayda açık kapı.',failure:'Elçi ölmek yerine ele geçirilir; sonraki görev bir kurtarma ve propaganda yarışı olur.',scaling:'$scale'},
  {id:'monster-contract',title:'Yanlış Canavar Ödülü',type:'Canavar Avı / İnceleme',tags:['av','yaratık','iz'],brief:'$region yerleşimlerinde aynı yaratığa bağlanan saldırılar arttı. Ödülü alın; fakat önce hedefin gerçekten suçlu olduğunu kanıtlayın.',objectives:['En az iki saldırı yerini karşılaştır.','Yaratığın yuvasını sivillerden önce bul.','Öldürme, uzaklaştırma veya uzlaşma kararını kanıta göre ver.'],clues:['Isırık izleri ilan edilen yaratığın çene yapısıyla uyuşmuyor.','Çalınan malların yalnız belirli türleri kayıp.'],checks:['Nature DC $dc: iz ve yara uyumunu kontrol et.','Investigation DC $dc: saldırılardaki ortak kişiyi bul.','Animal Handling veya Survival DC $dc: yaratığa yaklaş.'],encounter:'İlan edilen hedefe ek olarak $threat olay yerini kullanır.',twist:'Yaratık saldırgan değil, gerçek failin bıraktığı tehlikeyi uzak tutmaya çalışıyor.',secret:'Ödülü koyan kişi değerli araziyi boşaltmak için korkuyu büyüttü.',reward:'$coin, yaratık rehberliği veya bölge avcılarıyla itibar.',failure:'Yanlış hedef öldürülürse gerçek fail güçlenir ve halk başlangıçta partiyi kahraman sanır.',scaling:'$scale'},
  {id:'haunted-records',title:'Arşivde Kalan Sesler',type:'Hayalet / Gizem',tags:['hayalet','arşiv','gizem'],brief:'$region arşivindeki kâtipler, geceleri kendi el yazılarıyla yazılmış itiraflar buluyor. Bina mühürlenmeden kaynağı bulun.',objectives:['Üç itirafı olay kayıtlarıyla karşılaştır.','Gece tezahürünü gözlemle ve tetikleyiciyi belirle.','Ruhu, laneti veya taklitçiyi kalıcı biçimde sustur.'],clues:['İtiraflarda yalnız ölü bir kâtibin bildiği kayıt numaraları var.','Mürekkep yeni, fakat kâğıt arşivde yüz yıldır kayıp.'],checks:['History DC $dc: olaylar arasındaki bağı kur.','Religion veya Arcana DC $dc: tezahürün doğasını belirle.','Wisdom save DC $dc: kendi itirafını yazma dürtüsüne diren.'],encounter:'$threat rafları ve kanıtları yok etmeye başlar; savaş alanı her tur daralır.',twist:'Ruh suçlu aramıyor; arşivin resmî tarihindeki yalanları düzeltmeye çalışıyor.',secret:'Son itiraf yaşayan ve güçlü bir yöneticinin suçunu doğrudan kanıtlar.',reward:'$coin, arşiv erişimi ve tek bir tarih/lore sorusuna doğru cevap.',failure:'Arşiv yanmaz ama resmî olarak kapatılır; kanıta ulaşmak siyasi suç hâline gelir.',scaling:'$scale'},
  {id:'bridge-crisis',title:'Köprünün Üçüncü Ayağı',type:'Savunma / Mühendislik',tags:['köprü','savunma','zanaat'],brief:'$region geçidindeki ana köprü titriyor; aynı gece düşman hareketi bildirildi. Geçişi açık tutun veya kontrollü tahliye planı kurun.',objectives:['Hasarın doğal mı sabotaj mı olduğunu belirle.','Onarım, tahliye ve savunma görevlerini paylaştır.','Son konvoy geçene kadar köprüyü tut.'],clues:['Çatlaklar akıntı yönüne ters ilerliyor.','Eksik taşlar düşmemiş; kesilerek alınmış.'],checks:['Investigation DC $dc: zayıf noktaları belirle.','Mason’s Tools veya Athletics DC $dc: geçici destek kur.','Perception DC $dc: su altındaki saldırganı gör.'],encounter:'$threat köprünün taşıyıcı noktalarını hedefler; her yıkım hareket alanını azaltır.',twist:'Sabotajcı düşman ordu değil, köprünün altındaki mühür kırılmasın diye çalışan eski bir bekçidir.',secret:'Köprü onarılırsa mühürlü oda açılacak; yıkılırsa bölge aylarca ikiye ayrılacak.',reward:'$coin, ücretsiz geçiş ve mühendislik/ulaşım desteği.',failure:'Köprü tamamen yok olmaz; bir şerit kapanır, seyahat +2 gün ve fiyatlar artar.',scaling:'$scale'},
  {id:'plague-sample',title:'Karantina Mührü',type:'Hastalık / Teslimat',tags:['karantina','tıbbî','teslimat'],brief:'$region bölgesinden alınan mühürlü örnek, bozulmadan uzmandan uzmana taşınmalı. Paket açılmamalı ve taşıyıcılar gözlenmeli.',objectives:['Güvenli taşıyıcı ve rota seç.','Üç kontrol noktasında mührü doğrula.','Örneği süre dolmadan laboratuvara ulaştır.'],clues:['Kutudan gelen ses taşıyıcının adını doğru söylüyor.','Mühür üzerindeki tarih örneğin alındığı günden daha eski.'],checks:['Medicine DC $dc: bulaş belirtisini ayır.','Arcana DC $dc: mührün ikinci işlevini çöz.','Constitution save DC $dc: sızıntının etkisine diren.'],encounter:'$threat örneği çalmaya veya yok etmeye çalışır; kutuya alan hasarı zarar verir.',twist:'Örnek hastalık değil, hastalığı taklit eden ve yardım isteyen bilinçli bir kolonidir.',secret:'Laboratuvarın gerçek amacı tedavi değil, etkiyi silaha çevirmektir.',reward:'$coin, iki tedavi/antitoksin ve şifacı ağına erişim.',failure:'Örnek hemen salgın yaratmaz; yanlış kişinin eline geçerek sonraki krizi hazırlar.',scaling:'$scale'},
  {id:'temple-relic',title:'Kayıp Ayin Emaneti',type:'Tapınak / Takip',tags:['tapınak','emanet','takip'],brief:'$region tapınağının ana emaneti törenden önce kayboldu. Halk duymadan eşyayı ve onu alan kişiyi bulun.',objectives:['Kilitli odanın nasıl açıldığını çöz.','Emanetin rotasını pazar ve arka sokaklarda takip et.','Tören başlamadan eşyayı güvenle geri getir veya gerçeği açıkla.'],clues:['Kapıda zorlama yok ama dua sırasındaki bir kelime yanlış yazılmış.','Emanetin kabından kutsal yağ değil, sıradan lamba yağı damlıyor.'],checks:['Religion DC $dc: ayindeki hatayı fark et.','Investigation DC $dc: sahte emaneti ayır.','Persuasion DC $dc: paniğe kapılan tanığı koruyarak konuştur.'],encounter:'$threat gerçek emanete çekilir; eşya savaş sırasında korunmalıdır.',twist:'Emaneti alan eski rahip, içindeki sahte mucize düzeneğini halka göstermek istiyor.',secret:'Tapınak yöneticisi yıllardır gerçek emaneti saklıyor ve taklit üzerinden nüfuz kazanıyor.',reward:'$coin, tapınak hizmeti ve kutsal arşive sınırlı erişim.',failure:'Tören sahte eşyayla yapılır; kısa vadede düzen korunur ama yalan büyür.',scaling:'$scale'},
  {id:'river-rescue',title:'Akıntıdaki Sessiz Tekne',type:'Su / Kurtarma',tags:['nehir','deniz','kurtarma'],brief:'$region sularında mürettebatsız bir tekne dönüp duruyor; kargo sağlam, yolcular kayıp. Akıntı tekneyi tehlikeli bölgeye sürüklüyor.',objectives:['Tekneye güvenle yanaş.','Mürettebatın son hareketlerini belirle.','Kayıpları ve kargoyu akıntı değişmeden kurtar.'],clues:['Yemek hâlâ sıcak ama güverte günlerdir temizlenmemiş gibi.','Halatlar dışarıdan değil içeriden tek hamlede kesilmiş.'],checks:['Water Vehicles DC $dc: tekneyi sabitle.','Investigation DC $dc: zaman çelişkisini çöz.','Athletics DC $dc: akıntıdaki kişiyi çek.'],encounter:'$threat teknenin altında dolaşır; batma sayacı sahneye süre koyar.',twist:'Mürettebat gemiyi terk etmedi; küçük bir cep boyuta çekildi ve yalnız sesleri duyuluyor.',secret:'Kargo cep boyutun anahtarıdır ve teslim edilirse aynı olay tekrar yaşanacaktır.',reward:'$coin, tekne/ulaşım hakkı ve kurtarılan kaptanın haritası.',failure:'Tekne batar ama yolcuların konumu anlaşılır; görev daha zor bir dalışa dönüşür.',scaling:'$scale'},
  {id:'counterfeit-ring',title:'Bakırdan Basılan Taç',type:'Casusluk / Sahtecilik',tags:['casus','para','inceleme'],brief:'$region pazarında kusursuz görünen sahte paralar dolaşıyor. Ekonomiyi çökertmeden basım yerini ve dağıtıcıyı bulun.',objectives:['Sahteyi gerçek paradan ayıran işareti belirle.','Dağıtım zincirini küçük esnaftan yukarı izle.','Kalıpları ve kayıtları aynı operasyonda ele geçir.'],clues:['Paraların ağırlığı doğru ama çıkardığı ses yarım ton kalın.','Aynı seri yalnız gece vardiyası sonrası görülüyor.'],checks:['Investigation DC $dc: metal ve kalıp izini incele.','Sleight of Hand veya Deception DC $dc: kontrollü sahte ödeme yap.','Insight DC $dc: zorlanan esnafı örgüt üyesinden ayır.'],encounter:'$threat basımevini temizlemeye gelir; kanıtların yanma süresi vardır.',twist:'Sahte para kâr için değil, ağır vergiler altında kalan mahalleyi ayakta tutmak için basılıyor.',secret:'Kalıpları sağlayan vergi görevlisi hem isyanı hem baskıyı finanse ediyor.',reward:'$coin, suç ağı bilgisi ve pazarda geçici indirim.',failure:'Kalıplar kaçar; sahtecilik sürer ve masum esnaf tutuklanır.',scaling:'$scale'},
  {id:'arcane-weather',title:'Ters Yağan Yağmur',type:'Büyüsel Anomali',tags:['büyü','anomali','çevre'],brief:'$region üzerinde yağmur göğe doğru yükseliyor ve büyüler yanlış hedefe sapıyor. Kaynağı bulun, bölge kalıcı değişmeden dengeleyin.',objectives:['Anomalinin sınırını ve döngüsünü haritala.','Üç odak noktasını doğru sırada sabitle.','Ana kaynağı kapat veya güvenli işleve dönüştür.'],clues:['Su damlaları aynı unutulmuş sembolün çevresinde yön değiştiriyor.','Cantripler bozuluyor ama ritüeller normal çalışıyor.'],checks:['Arcana DC $dc: büyü döngüsünü çöz.','Nature DC $dc: doğal hava ile anomaliyi ayır.','Spellcasting ability check DC $dc: odağı sabitle.'],encounter:'$threat değişken gravity ve görüş altında ortaya çıkar; her tur farklı alan etkisi olur.',twist:'Anomali bir kaza değil, gelecekteki kuraklıktan bölgeye su gönderen başarısız bir düzenektir.',secret:'Düzenek kapatılırsa bugün kurtulur, açık bırakılırsa gelecekte başka bir yer kurur.',reward:'$coin, tek kullanımlık büyü odağı ve anomali araştırması.',failure:'Anomali yayılmaz ama bölgede yolculuk ve büyü kullanımı bir hafta zorlaşır.',scaling:'$scale'},
  {id:'sealed-dungeon',title:'Mührün Altındaki Kapı',type:'Dungeon / Mühür',tags:['dungeon','mühür','keşif'],brief:'$region altında yeni bir kapı açıldı; içeriden düzenli vuruşlar geliyor. Mühür tamamen kırılmadan içeri girip kaynağı değerlendirin.',objectives:['Kapıyı hasar vermeden açacak sırayı çöz.','İçerideki güvenli ve tehlikeli katları işaretle.','Mührü onar, değiştir veya bilinçli olarak kaldır.'],clues:['Vuruşlar yardım kodu gibi başlıyor ama her gece bir vuruş eksiliyor.','Mühürdeki bazı çizikler dışarıdan yapılmış.'],checks:['Arcana veya Religion DC $dc: mühür işlevini belirle.','Investigation DC $dc: kapı sırasını çöz.','Thieves’ Tools DC $dc: tuzağı mekanizmadan ayır.'],encounter:'$threat dar odalar ve çalışan tuzaklar arasında nöbet tutar.',twist:'Mühür içerideki şeyi hapsetmiyor; dış dünyanın sesini ondan saklıyor.',secret:'İçerideki muhafız, bölge hanedanının resmî tarihini çürüten yaşayan bir tanıktır.',reward:'$coin, bir büyü sayfası/harita ve güvenli dungeon girişi.',failure:'Mühür çatlar; tehdit hemen çıkmaz ama geri sayım başlar.',scaling:'$scale'},
  {id:'rebel-parley',title:'Silahsız Masanın Bedeli',type:'İsyan / Müzakere',tags:['isyan','diplomasi','ahlaki'],brief:'$region yöneticisi ile isyancı temsilciler yalnız tarafsız bir partinin huzurunda görüşecek. Silahları dışarıda bırakın ve ateşkesi koruyun.',objectives:['Her tarafın gerçek vazgeçilmez talebini öğren.','Görüşme alanında gizli silah ve ajan kontrolü yap.','En az bir uygulanabilir ateşkes maddesi çıkar.'],clues:['İki tarafın da listesinde aynı kayıp kişinin adı var.','Masanın oturma düzeni özellikle bir pencereye bakacak şekilde değiştirilmiş.'],checks:['Insight DC $dc: sahte talepleri ayır.','Persuasion DC $dc: ortak madde oluştur.','Perception DC $dc: dışarıdaki işaretçiyi fark et.'],encounter:'$threat görüşmeyi bozmak için iki tarafın üniformasını birlikte kullanır.',twist:'İsyanı başlatan olay iki tarafın da bilmediği üçüncü bir grubun sahte emridir.',secret:'Kayıp kişi hayatta ve üçüncü grubun elinde; ateşkes onun kurtarılmasına bağlı.',reward:'$coin, iki grupla itibar ve bölgesel karar üzerinde söz hakkı.',failure:'Görüşme tam savaşa dönüşmez; 48 saatlik son süre ve zor bir kurtarma fırsatı kalır.',scaling:'$scale'},
  {id:'ancient-engine',title:'Uyuyan Taş Makine',type:'Kadim Makine / Bulmaca',tags:['makine','bulmaca','kadim'],brief:'$region yakınında yer altından yükselen taş çarklar yolları değiştiriyor. Makinenin amacını öğrenin ve kontrolünü ele alın.',objectives:['Üç kontrol düğümünün işlevini keşfet.','Makinenin eski komut dilini çöz.','Güvenli mod, kapatma veya yeni hedef arasında seçim yap.'],clues:['Çarklar güneşe değil haritadaki kalelere göre dönüyor.','Kırık bir düğümün içinde güncel tarih kazılı.'],checks:['History DC $dc: üretici uygarlığı tanı.','Arcana veya Tinker’s Tools DC $dc: düğümü onar.','Investigation DC $dc: komut sırasını çıkar.'],encounter:'$threat makinenin savunma protokolüyle güçlenir; düğümleri kapatmak boss’u zayıflatır.',twist:'Makine saldırı aracı değil, yaklaşan coğrafi felakette kaleleri yer değiştirmek için yapılmış.',secret:'Güncel tarih, makinenin daha önce bir zaman döngüsünde çalıştırıldığını gösterir.',reward:'$coin, kadim bileşen ve bir bölge yolunu kalıcı kısaltma seçeneği.',failure:'Makine tamamen durmaz; bir yol kapanır, başka gizli rota açılır.',scaling:'$scale'},
  {id:'dragon-tribute',title:'Ejderhanın İstemediği Vergi',type:'Ejderha / Diplomasi',tags:['ejderha','haraç','siyaset'],brief:'$region hazinesi yıllık ejderha vergisini taşıyacak koruma arıyor. Ödeme noktasında önceki kervandan hiç iz yok.',objectives:['Hazinenin tam ve gerçek olduğunu doğrula.','Teslim noktasındaki kayboluşu araştır.','Ejderha, kale ve hazine hakkında bağlayıcı karar ver.'],clues:['Önceki arabanın izleri teslim noktasından geri dönüyor.','Ejderha işareti yeni ve insan yapımı bir kalıpla basılmış.'],checks:['Investigation DC $dc: sahte saldırı izlerini çöz.','Persuasion DC $dc: ejderhayla protokol kur.','History DC $dc: verginin ilk kaydını bul.'],encounter:'$threat hazineyi sessizce almak ister; ejderhanın gelişi çatışmayı değiştirebilir.',twist:'Ejderha hiçbir zaman vergi istemedi; bir hanedan korkuyu kullanarak servet topluyor.',secret:'Ejderha bu yalanı biliyor ama kalelerin birbirini tüketmesini izlemek için sustu.',reward:'$coin veya ejderha lütfu, siyasi kanıt ve verginin kaderi.',failure:'Hazine kaybolur; kale ejderhayı suçlar ve diplomasi penceresi daralır.',scaling:'$scale'},
  {id:'planar-breach',title:'Gökteki İnce Yarık',type:'Planar / Ritüel',tags:['planar','ritüel','felaket'],brief:'$region göğünde ince bir yarık açıldı; geceleri başka bir yerin gölgeleri düşüyor. Üç odak kurulmadan yarık genişleyecek.',objectives:['Yarığın üç çapa noktasını bul.','Her çapada gerekli ritüeli tamamla.','Geçidin öte tarafıyla iletişim veya kapatma kararı ver.'],clues:['Gölgeler saldırmıyor; sürekli aynı yönde kaçıyor.','Yarıktan düşen toz burada olmayan çiçekler açtırıyor.'],checks:['Arcana DC $dc: çapa dizisini belirle.','Religion DC $dc: varlığın ilahi olmadığını doğrula.','Concentration check DC $dc: ritüeli saldırı altında sürdür.'],encounter:'$threat yarıktan değil, bu tarafta geçidi ele geçirmek isteyenlerden gelir.',twist:'Öte taraf işgalci değil, kendi dünyasındaki felaketten kaçan sivillerdir.',secret:'Yarığı kapatmak güvenli; açık tutmak güçlü müttefik ve bilinmeyen göç dalgası getirir.',reward:'$coin, planar bileşen ve tek kullanımlık geçit hakkı.',failure:'Yarık patlamaz; bir çapa kalıcılaşır ve çevresinde yeni macera bölgesi doğar.',scaling:'$scale'},
  {id:'siege-supplies',title:'Kuşatmadan Önce Üç Gece',type:'Kuşatma / Hazırlık',tags:['kuşatma','savunma','kaynak'],brief:'$region üç gün içinde kuşatma bekliyor. Erzak, savunma ve tahliye için yalnız bir öncelik planı var; hepsine yetişmek mümkün değil.',objectives:['Üç kritik kaynağın gerçek durumunu ölç.','Savunma, sabotaj ve tahliye ekiplerini görevlendir.','Düşmanın ilk hamlesini boşa çıkaracak hazırlığı tamamla.'],clues:['Erzak sayımı kâğıt üzerinde fazla, depoda eksik.','Düşman kamp ateşleri gerçek asker sayısını olduğundan çok gösteriyor.'],checks:['Investigation DC $dc: stok yolsuzluğunu bul.','Persuasion DC $dc: halkı tahliye planına ikna et.','Survival veya Warfare yorumu DC $dc: gerçek saldırı hattını seç.'],encounter:'$threat hazırlık noktalarından birine baskın yapar; seçilmeyen öncelik sonuç doğurur.',twist:'Kuşatma ordusunun hedefi kale değil, kalenin altından geçen kadim taşıyıcı hattıdır.',secret:'Kale komutanı hattı biliyor ve halkı bilerek yem olarak tutuyor.',reward:'$coin, komuta itibarı ve savaş sonrası toprak/ünvan ihtimali.',failure:'Kale tek zarla düşmez; kaybedilen her hedef final savaşına somut dezavantaj ekler.',scaling:'$scale'},
  {id:'artifact-race',title:'Parçalanmış Haritanın Sonu',type:'Artifact / Yarış',tags:['artifact','yarış','keşif'],brief:'$region içinde kadim bir eşyanın son parçası bulundu. En az iki rakip ekip aynı hedefe gidiyor; parçayı alıp ne yapılacağına karar verin.',objectives:['Rakiplerin rotasını ve niyetini öğren.','Haritanın üç yanlış işaretini çöz.','Parçayı ele geçir ve birleştirme/yok etme kararını ver.'],clues:['Haritadaki kuzey işareti her ay farklı yönü gösteriyor.','Rakiplerden biri sürekli geride kalıyor ama hiçbir tuzağa basmıyor.'],checks:['History DC $dc: haritanın dönemini belirle.','Survival DC $dc: değişen kuzeyi çöz.','Sleight of Hand veya Athletics DC $dc: parçayı tehlikeden çıkar.'],encounter:'$threat hedef odasında uyanır; rakiplerle savaşmak yerine geçici işbirliği mümkündür.',twist:'Artifact bir silah değil, onu arayanların niyetini kaydeden bir yargıçtır.',secret:'Birleştiren kişi gücü değil, önceki sahiplerin suçlarını ve düşmanlarını miras alır.',reward:'$coin ve DM onaylı artifact izi/parçası; gerçek güç sonraki görevle açılır.',failure:'Rakip parça ile kaçar ama haritanın kalanını parti alır; takip görevi başlar.',scaling:'$scale'},
  {id:'moral-evacuation',title:'Son Sandal Kimin?',type:'Tahliye / Ahlaki',tags:['tahliye','ahlaki','zaman'],brief:'$region felaketinde güvenli çıkış kapasitesi herkese yetmiyor. Yeni rota bulana kadar halkı sıraya koyun ve paniği yönetin.',objectives:['Tehlike bölgelerini ve zaman penceresini belirle.','Öncelik kuralını halka açıkça ilan et.','Ek çıkış aç veya son grubun güvenliğini sağla.'],clues:['Resmî yol en kısa ama ilk çökecek olan.','Terk edilmiş işçi tünelinin anahtarı tahliye listesinde olmayan birinde.'],checks:['Investigation DC $dc: güvenli rota hesabını doğrula.','Persuasion veya Intimidation DC $dc: paniği kontrol et.','Athletics veya Tools DC $dc: ek çıkışı aç.'],encounter:'$threat kaçış yolunu tutar; saldırı ve sivilleri taşıma eylemleri arasında seçim gerekir.',twist:'Kapasite hesabı bilerek düşük gösterildi; yönetici yalnız seçkinleri kurtarmak istiyor.',secret:'Gizli tünel herkesi kurtarabilir fakat bölgenin mühürlü tehlikesini de açar.',reward:'$coin, halk desteği ve gelecekte toplu yardım çağırma hakkı.',failure:'Başarısızlık herkesi öldürmez; seçilen öncelikler hangi NPC/faksiyonun kayıp verdiğini belirler.',scaling:'$scale'},
  {id:'memory-theft',title:'Çalınan Bir Gün',type:'Hafıza / Gizem',tags:['hafıza','gizem','şehir'],brief:'$region halkı aynı günü hatırlamıyor; yalnız parti ve birkaç çocuk etkilenmemiş. Kayıp yirmi dört saatte ne olduğunu bulun.',objectives:['Etkilenmeyen tanıkları koru ve ifadeleri karşılaştır.','Kayıp günün üç önemli olayını yeniden kur.','Hafızaları geri ver veya gerçeği saklama kararı ver.'],clues:['Herkesin ayakkabısında aynı yerden gelen toz var.','Boş bir meydanda kutlama sonrası izler bulunuyor.'],checks:['Investigation DC $dc: kayıp günün rotasını çıkar.','Arcana DC $dc: hafıza büyüsünün sınırını bul.','Wisdom save DC $dc: ikinci silinmeye diren.'],encounter:'$threat anı parçalarıyla beslenir; doğru anı söylenince savunması düşer.',twist:'Hafıza saldırıyla değil, halkın topluca istediği bir ritüelle silindi.',secret:'Silinen gün halkın sevdiği yöneticinin gönüllü bir kurban seçtiğini gösteriyor.',reward:'$coin, bir gerçek anı şişesi ve yerel tanık ağı.',failure:'Anılar eksik döner; her önemli NPC gerçeğin farklı bir sürümüne inanır.',scaling:'$scale'},
  {id:'living-map',title:'Yer Değiştiren Patika',type:'Harita / Keşif',tags:['harita','yol','keşif'],brief:'$region yolları her şafakta başka yere çıkıyor. Kervanlar kaybolmadan değişimin kuralını bulun ve kalıcı bir rota işaretleyin.',objectives:['Üç günün yol değişimini kaydet.','Sabit kalan coğrafi çapayı bul.','Yeni güvenli yol veya kontrol yöntemi oluştur.'],clues:['Kaybolanlar farklı yerler tarif ediyor ama hepsi aynı kuş sesini duymuş.','Eski yol taşlarının gölgeleri gerçek kuzeyi gösteriyor.'],checks:['Survival DC $dc: döngüyü haritala.','Nature DC $dc: sabit canlı işareti bul.','Cartographer’s Tools DC $dc: kullanılabilir rota üret.'],encounter:'$threat kaybolan yolcuları avlar; savaş alanının kenarları her tur başka çıkışa bağlanır.',twist:'Yollar bozulmadı; bölgenin yaşayan haritası yaklaşan ordudan sivilleri saklıyor.',secret:'Harita kontrol edilirse kaleler arası süre kısalır ama saklanan eski bir ordu da yolu bulur.',reward:'$coin, kalıcı kestirme ve yaşayan haritanın bir işareti.',failure:'Kervanlar tamamen kaybolmaz; yolculuk süreleri artar ve harita başka bölgeye taşınır.',scaling:'$scale'},
  {id:'oath-trial',title:'Bozulan Üç Yemin',type:'Mahkeme / Rol Yapma',tags:['mahkeme','yemin','sosyal'],brief:'$region mahkemesi aynı olay için üç farklı yeminli ifade aldı. Açık çatışma başlamadan hangi yeminin bozulduğunu kanıtlayın.',objectives:['Üç ifadeyi zaman ve mekâna göre karşılaştır.','Tanıkları baskıdan koru.','Mahkemeye kanıt, itiraf veya uzlaşma sun.'],clues:['Üç kişi de aynı önemsiz ayrıntıyı aynı kelimelerle anlatıyor.','Mahkeme kâtibinin tuttuğu saat bir çeyrek geri.'],checks:['Insight DC $dc: hazırlanmış ifadeyi fark et.','Investigation DC $dc: zaman çelişkisini kanıtla.','Persuasion DC $dc: koruma karşılığında tanık kazan.'],encounter:'$threat tanıkları susturmak için duruşma sırasında saldırır; mahkeme kayıtları da hedeftir.',twist:'Üç tanık da yalan söylüyor fakat aynı suç için değil; birbirlerini başka sırlardan koruyorlar.',secret:'Hakim gerçeği biliyor ve siyasi denge için partinin eksik kanıt sunmasını tercih ediyor.',reward:'$coin, yasal yetki ve bir tutuklu/borcun affı.',failure:'Yanlış hüküm kesin son değildir; suçlanan kişi kaçar ve gerçeği bulmak için tehlikeli müttefik olur.',scaling:'$scale'},
  {id:'dream-beacon',title:'Aynı Rüyadaki Kule',type:'Rüya / Psionik',tags:['rüya','psionik','gizem'],brief:'$region sakinleri her gece aynı kuleyi görüyor ve uyanınca ona doğru yürüyor. Uyurgezerler sınıra varmadan rüyanın kaynağını bulun.',objectives:['Rüyaya birlikte ve hazırlıklı gir.','Kulenin üç katındaki sembolleri çöz.','Kaynağı uyandır, iyileştir veya bağını kes.'],clues:['Çocuklar kuleyi yetişkinlerden bir kat daha yüksek çiziyor.','Uyananların avuçlarında aynı ince toz var.'],checks:['Arcana DC $dc: ortak rüya bağını belirle.','Insight DC $dc: rüya NPC’sinin gerçek niyetini çöz.','Wisdom save DC $dc: sahte uyanıştan çık.'],encounter:'$threat rüyada biçim değiştirir; fiziksel hasar yerine hedef tamamlamak savunmasını kırar.',twist:'Kule çağrı değil, bölgenin bastırdığı toplu bir hatıranın güvenli arşividir.',secret:'Hatıra açılırsa halkın kurucu efsanesi yıkılır ama yaklaşan tehdidin çözümü öğrenilir.',reward:'$coin, bir kez avantaj veren rüya tılsımı ve kehanet ipucu.',failure:'Parti uyanır ama rüya bir NPC’yi içeride tutar; kurtarma için ikinci giriş mümkündür.',scaling:'$scale'}
];

function v50QuestFill(text,region,profile){
  return String(text||'')
    .replaceAll('$region',region.name).replaceAll('$feature',region.feature).replaceAll('$faction',region.faction)
    .replaceAll('$threat',profile.threat).replaceAll('$dc',profile.dc).replaceAll('$coin',profile.coin)
    .replaceAll('$tier',profile.epithet).replaceAll('$duration',profile.duration).replaceAll('$scale',profile.scale);
}

function v50ProfileFor(levels){return V50_LEVEL_PROFILES.find(row=>row.levels===levels)||V50_LEVEL_PROFILES[0]}

function v50LegacyQuest(quest,index){
  let profile=v50ProfileFor(quest.levels),region=V50_REGIONS[index%V50_REGIONS.length];
  return {
    id:`v50-legacy-${String(index+1).padStart(3,'0')}`,sourceId:quest.id,title:quest.title,levels:quest.levels,type:quest.type,
    region:region.name,difficulty:profile.difficulty,duration:profile.duration,
    publicBrief:quest.hook,
    objectives:[`Görev verenden ${quest.title} için hedef ve sınırları doğrula.`,`${region.name} bölgesinde en az iki bağımsız iz veya tanık bul.`,`Ana sorunu çöz ve sonucu görev verene güvenle bildir.`],
    clues:[`${region.feature} içindeki ilk iz, olayın görünen nedeninden daha karmaşık olduğunu gösterir.`,`Yerel bağlantı: ${region.faction}; iyi yaklaşım ek bilgi sağlayabilir.`],
    checks:[`Perception veya Investigation DC ${profile.dc}: ilk somut kanıt.`,`Insight veya Survival DC ${profile.dc}: yanlış yönlendirmeyi ayır.`,`Uygun alet/skill DC ${profile.dc}: çözümü güvenli tamamla.`],
    encounter:`Görevin türüne uygun olarak ${profile.threat}. Çatışma zorunlu değildir; amaç tamamlanınca düşman geri çekilebilir.`,
    twist:quest.twist,secret:`DM notu: ${quest.twist} bilgisini en az iki ipucuyla aç; tek başarısız zarın görevi kilitlemesine izin verme.`,
    hiddenReward:quest.reward,failure:`Başarısızlık görevi silmez: ${region.name} içinde yeni bir bedel, zaman kaybı veya rakip avantajı doğar.`,
    scaling:profile.scale,tags:[quest.type,region.name,'v34-klasik'],origin:'v34'
  };
}

function v50GeneratedQuest(blueprint,blueprintIndex,profile,profileIndex){
  let region=V50_REGIONS[(blueprintIndex*5+profileIndex*2)%V50_REGIONS.length],fill=value=>v50QuestFill(value,region,profile);
  return {
    id:`v50-${blueprint.id}-${String(profileIndex+1).padStart(2,'0')}`,
    title:`${blueprint.title} — ${region.name}: ${profile.epithet}`,
    levels:profile.levels,type:blueprint.type,region:region.name,difficulty:profile.difficulty,duration:profile.duration,
    publicBrief:fill(blueprint.brief),objectives:blueprint.objectives.map(fill),clues:blueprint.clues.map(fill),checks:blueprint.checks.map(fill),
    encounter:fill(blueprint.encounter),twist:fill(blueprint.twist),secret:fill(blueprint.secret),hiddenReward:fill(blueprint.reward),
    failure:fill(blueprint.failure),scaling:fill(blueprint.scaling),tags:[...blueprint.tags,region.name,profile.levels],origin:'v50'
  };
}

const V50_QUESTS=[
  ...V34_QUESTS.map(v50LegacyQuest),
  ...V50_QUEST_BLUEPRINTS.flatMap((blueprint,blueprintIndex)=>V50_LEVEL_PROFILES.filter((profile,profileIndex)=>blueprintIndex<5||profileIndex!==blueprintIndex%V50_LEVEL_PROFILES.length).map((profile,profileIndex)=>v50GeneratedQuest(blueprint,blueprintIndex,profile,V50_LEVEL_PROFILES.indexOf(profile))))
];
V50_QUESTS.forEach(quest=>{Object.freeze(quest.objectives);Object.freeze(quest.clues);Object.freeze(quest.checks);Object.freeze(quest.tags);Object.freeze(quest)});
Object.freeze(V50_QUESTS);
