/* v59: guild NPCs, spell-slot tracker, loot money delivery and battle expansion. */
(function(){
  Object.assign(V38_PROP_DEFS,window.V59_PROP_DEFS||{});
  Object.assign(V38_BATTLE_PRESETS,window.V59_BATTLE_PRESETS||{});
  const v59OldAllMonsters=allMonsters;
  function v59MonsterDetail(m){return {...m,stats:Array.isArray(m.stats)&&m.stats.length===6?m.stats:[10,10,10,10,10,10],attacks:m.attacks||m.note||'Stat bloğu DM tarafından tamamlanmalı.',traits:m.traits||m.note||'Özel özellik yok.',resist:m.resist||'Yok',immune:m.immune||'Yok',weak:m.weak||'Belirgin zayıflık yok.'}}
  allMonsters=()=>[...v59OldAllMonsters(),...(window.V59_MONSTERS||[]).map(v59MonsterDetail)];

  const FULL_SLOTS=[[],[2],[3],[4,2],[4,3],[4,3,2],[4,3,3],[4,3,3,1],[4,3,3,2],[4,3,3,3,1],[4,3,3,3,2],[4,3,3,3,2,1],[4,3,3,3,2,1],[4,3,3,3,2,1,1],[4,3,3,3,2,1,1],[4,3,3,3,2,1,1,1],[4,3,3,3,2,1,1,1],[4,3,3,3,2,1,1,1,1],[4,3,3,3,3,1,1,1,1],[4,3,3,3,3,2,1,1,1],[4,3,3,3,3,2,2,1,1]];
  const HALF_SLOTS=[[],[],[2],[3],[3],[4,2],[4,2],[4,3],[4,3],[4,3,2],[4,3,2],[4,3,3],[4,3,3],[4,3,3,1],[4,3,3,1],[4,3,3,2],[4,3,3,2],[4,3,3,3,1],[4,3,3,3,1],[4,3,3,3,2],[4,3,3,3,2]];
  const THIRD_SLOTS=[[],[],[],[2],[3],[3],[3],[4,2],[4,2],[4,2],[4,3],[4,3],[4,3],[4,3,2],[4,3,2],[4,3,2],[4,3,3],[4,3,3],[4,3,3],[4,3,3,1],[4,3,3,1]];
  const PACT_SLOTS=[[0,0],[1,1],[2,1],[2,2],[2,2],[2,3],[2,3],[2,4],[2,4],[2,5],[2,5],[3,5],[3,5],[3,5],[3,5],[3,5],[3,5],[4,5],[4,5],[4,5],[4,5]];
  function v59Slots(c){let l=Math.max(1,Math.min(20,+c.level||1)),cl=c.className;if(cl==='Warlock'){let [count,level]=PACT_SLOTS[l];return Array.from({length:level},(_,i)=>i===level-1?count:0)}if(['Cleric','Druid','Wizard','Bard','Sorcerer'].includes(cl))return FULL_SLOTS[l]||[];if(['Paladin','Ranger','Artificer'].includes(cl))return HALF_SLOTS[l]||[];if(cl==='Fighter'&&c.subclass==='Eldritch Knight'||cl==='Rogue'&&c.subclass==='Arcane Trickster')return THIRD_SLOTS[l]||[];return []}
  function v59SlotCard(c,dm){let totals=v59Slots(c);if(!totals.some(Boolean))return '';c.spellSlotsUsed??={};return `<article class="v59-slot-card"><header><div><small>${esc(c.className)} • LV ${c.level}</small><h3>${esc(c.name)}</h3></div>${dm?`<button class="ghost" data-v59-slot-rest="${esc(c.id)}">Slotları Yenile</button>`:''}</header><div class="v59-slot-grid">${totals.map((total,i)=>{if(!total)return '';let used=Math.min(total,Math.max(0,+c.spellSlotsUsed[i+1]||0)),left=total-used;return `<div><b>${i+1}. seviye</b><span>${left}/${total} hazır</span><div class="v59-pips">${Array.from({length:total},(_,p)=>`<i class="${p<used?'used':''}"></i>`).join('')}</div>${dm?`<footer><button data-v59-slot="${esc(c.id)}|${i+1}|-1" ${used<=0?'disabled':''}>Geri</button><button data-v59-slot="${esc(c.id)}|${i+1}|1" ${used>=total?'disabled':''}>Harca</button></footer>`:''}</div>`}).join('')}</div></article>`}
  function v59SpellTracker(dm){let chars=(state.characters||[]).filter(c=>v59Slots(c).some(Boolean));return `<section class="card v59-slots"><div class="between row"><div><span class="v26-kicker">BÜYÜ KAYNAKLARI</span><h2>Spell Slot Tablosu</h2></div><small>${dm?'DM kullandıkça Harca der; Long Rest hepsini yeniler.':'Dolu noktalar harcanmış slotları gösterir.'}</small></div><div class="v59-slot-list">${chars.map(c=>v59SlotCard(c,dm)).join('')||'<div class="empty">Spell slot kullanan karakter yok.</div>'}</div></section>`}

  const oldParty=dmPages.party;dmPages.party=()=>oldParty()+v59SpellTracker(true);
  const oldSkills=playerPages.skills;playerPages.skills=()=>oldSkills()+v59SpellTracker(false);
  const oldGuildDm=dmPages.guilddm;dmPages.guilddm=()=>{let rows=(state.npcs||[]).filter(n=>n.guildMember);return oldGuildDm()+`<section class="card v59-guild-npcs"><div class="between row"><div><span class="v26-kicker">LONCA KADROSU</span><h2>NPC Üyeler</h2></div><small>${rows.length} NPC</small></div><div class="chargrid">${rows.map(n=>`<article class="sheet"><h3>${esc(n.name)}</h3><p>${esc(n.role||'NPC')} • ${esc(n.faction||'Lonca')}</p><div class="v59-coins"><span>${+n.coins?.pp||0} PP</span><span>${+n.coins?.gp||0} GP</span><span>${+n.coins?.sp||0} SP</span><span>${+n.coins?.cp||0} CP</span></div><button class="ghost" data-v59-npc-money="${esc(n.id)}">Para Bırak</button><button class="danger" data-v59-guild-remove="${esc(n.id)}">Lonca Kadrosundan Çıkar</button></article>`).join('')||'<div class="empty">NPC Defteri’nden loncaya bir NPC ekleyebilirsin.</div>'}</div></section>`};
  const oldGuildPlayer=playerPages.guild;playerPages.guild=()=>{let rows=(state.npcs||[]).filter(n=>n.guildMember);return oldGuildPlayer()+`<section class="card v59-guild-npcs"><h2>Lonca NPC’leri</h2>${rows.map(n=>`<div class="itemrow row between"><span><b>${esc(n.name)}</b><small>${esc(n.role||'NPC')}</small></span><span>${esc(n.faction||'Lonca')}</span></div>`).join('')||'<div class="empty">NPC üye yok.</div>'}</section>`};
  const oldNpcs=dmPages.npcs;dmPages.npcs=()=>oldNpcs().replace(/<div class="toolbar">/,'<div class="toolbar"><span class="muted">NPC kartından lonca üyeliğini ve parasını yönet.</span>');

  const oldNpcPageRender=dmPages.npcs;dmPages.npcs=()=>{let html=oldNpcPageRender();return html.replace(/(<button data-npchp="([^"]+)"[^>]*>HP<\/button>)/g,(all,hp,id)=>`${hp}<button class="ghost" data-v59-guild-toggle="${id}">${state.npcs.find(n=>n.id===id)?.guildMember?'Lonca Üyesi ✓':'Loncaya Ekle'}</button><button class="ghost" data-v59-npc-money="${id}">Para Bırak</button>`) };

  if(dmPages.lootgen){const oldLoot=dmPages.lootgen;dmPages.lootgen=()=>oldLoot().replace('</div>\n      <div class="v44-result-list">',`<button class="primary v59-send-loot-money" data-v59-loot-money>Parayı Karaktere Gönder</button></div><div class="v44-result-list">`)}
  const oldGuide=dmPages.guide;const slotGuide=`<section class="card v59-slot-guide"><span class="v26-kicker">HIZLI REFERANS</span><h2>Spell Slot Kullanımı</h2><div class="v59-guide-grid"><article><b>Cantrip</b><p>Slot harcamaz; istediğin kadar kullanılabilir.</p></article><article><b>1–9. seviye büyü</b><p>Büyünün seviyesine eşit veya daha yüksek bir slot harcar. Attack roll kaçsa da slot gider.</p></article><article><b>Long Rest</b><p>Normal caster slotlarını tamamen yeniler. Warlock Pact Magic slotları kısa dinlenmede de yenilenir.</p></article><article><b>Upcast</b><p>Daha yüksek slot harcarsan yalnız büyü metni söylüyorsa etkisi güçlenir.</p></article></div><p class="notice">DM tablosunda “Harca” kullanılan slotu işaretler; “Geri” yanlış tıklamayı düzeltir.</p></section>`;dmPages.guide=()=>oldGuide()+slotGuide;const oldPlayerGuide=playerPages.guide;playerPages.guide=()=>oldPlayerGuide()+slotGuide;

  function v59MoneyModal(npcId=''){let npc=state.npcs.find(n=>n.id===npcId);modal(npc?'NPC’ye Para Bırak':'Ganimet Parasını Gönder',`<label>Hedef<select id="v59MoneyTarget">${npc?`<option value="npc:${esc(npc.id)}">${esc(npc.name)}</option>`:(state.characters||[]).map(c=>`<option value="character:${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><div class="v59-money-fields">${['pp','gp','sp','cp'].map(k=>`<label>${k.toUpperCase()}<input id="v59Money${k}" type="number" min="0" value="${npc?0:+state.v44LootHistory?.[0]?.coins?.[k]||0}"></label>`).join('')}</div><button id="v59ConfirmMoney" class="primary">Parayı Bırak</button>`)}
  document.addEventListener('click',async event=>{let b=event.target.closest('button');if(!b)return;
    if(b.dataset.v59Slot){let [id,level,delta]=b.dataset.v59Slot.split('|'),c=state.characters.find(x=>x.id===id),total=v59Slots(c)[+level-1]||0;if(!c||!total)return;c.spellSlotsUsed??={};c.spellSlotsUsed[level]=Math.max(0,Math.min(total,(+c.spellSlotsUsed[level]||0)+ +delta));save();render();return}
    if(b.dataset.v59SlotRest){let c=state.characters.find(x=>x.id===b.dataset.v59SlotRest);if(c){c.spellSlotsUsed={};save();render()}return}
    if(b.dataset.v59GuildToggle){let n=state.npcs.find(x=>x.id===b.dataset.v59GuildToggle);if(n){n.guildMember=!n.guildMember;n.coins??={pp:0,gp:0,sp:0,cp:0};save();render()}return}
    if(b.dataset.v59GuildRemove){let n=state.npcs.find(x=>x.id===b.dataset.v59GuildRemove);if(n){n.guildMember=false;save();render()}return}
    if(b.dataset.v59NpcMoney){v59MoneyModal(b.dataset.v59NpcMoney);return}
    if(b.hasAttribute('data-v59-loot-money')){v59MoneyModal();return}
    if(b.id==='v59ConfirmMoney'){let target=$('#v59MoneyTarget').value,coins=Object.fromEntries(['pp','gp','sp','cp'].map(k=>[k,Math.max(0,Math.trunc(+$('#v59Money'+k).value||0))]));if(target.startsWith('npc:')){let n=state.npcs.find(x=>x.id===target.slice(4));if(!n)return;n.coins??={pp:0,gp:0,sp:0,cp:0};for(let k in coins)n.coins[k]=(+n.coins[k]||0)+coins[k];save()}else{let c=state.characters.find(x=>x.id===target.slice(10));if(!c)return;let map={pp:'platinum',gp:'gold',sp:'silver',cp:'copper'};for(let [k,amount] of Object.entries(coins))if(amount){let {error}=await db.rpc('wallet_adjust',{p_user:auth.id,p_campaign:current.id,p_target:c.userId,p_coin:map[k],p_delta:amount});if(error)return alert(error.message)}}$('#modal').close();await syncFromServer(true);render();toast('Para hedefe gönderildi');return}
  });
  if(current)render();
})();
