/* v65: one-of-a-kind named caster relics sold as single-stock market records. */
((root)=>{
  'use strict';
  const rows=[
    {name:'Kırık Merhamet',className:'Cleric',shop:'temple',slot:'focus',category:'focus',price:180000,magicBonus:1,effect:'Spell Attack ve Spell Save DC +1. Bir iyileştirme büyüsünde attığın tek bir 1 sonucunu yeniden atabilirsin (1/long rest).',note:'İkiye ayrılmış porselen bir kutsal sembol; iki parça birbirine değmeden aynı duayı fısıldar.'},
    {name:'Sessiz Çan',className:'Cleric',shop:'temple',slot:'neck',category:'accessory',price:240000,saveBonus:1,effect:'Saving throw +1. 30 ft içindeki dying müttefik death save attığında reaction ile +1d4 verirsin (1/long rest).',note:'Sallandığında ses çıkarmaz; yalnız ölmek üzere olanlar uzaktan çaldığını duyar.'},
    {name:'Yedinci Yara',className:'Cleric',shop:'temple',slot:'back',category:'accessory',price:420000,acBonus:1,effect:'AC +1. Bir müttefikin aldığı hasarın proficiency bonusun kadarını reaction ile kendine aktarabilirsin (1/short rest).',note:'Beyaz pelerindeki yedinci kızıl dikiş, taşıyıcının üstünde hiç kurumaz.'},

    {name:'Geceyi İkiye Bölen Asa',className:'Wizard',shop:'arcane',slot:'focus',category:'focus',price:520000,magicBonus:2,effect:'Spell Attack ve Spell Save DC +2. Counterspell check’inde bir kez avantaj alırsın (1/long rest).',note:'Siyah ve gümüş damarları olan asa, gölgesini iki farklı yöne düşürür.'},
    {name:'Mavi Hiçlik',className:'Wizard',shop:'arcane',slot:'ring',category:'accessory',price:260000,statBonuses:{INT:1},effect:'INT +1. Arcana check’inde proficiency sahibiysen bir check’e expertise uygularsın (1/long rest).',note:'İçine bakıldığında taş değil, yıldızsız ve dipsiz bir gökyüzü görülür.'},
    {name:'Tersine Akan Kum',className:'Wizard',shop:'arcane',slot:'neck',category:'accessory',price:380000,saveBonus:1,effect:'Saving throw +1. Initiative attıktan sonra zarını yeniden atabilirsin; yeni sonuç kullanılır (1/long rest).',note:'Kum saati hangi yana çevrilirse çevrilsin taneler yukarı doğru akar.'},

    {name:'Borçsuz Gölge',className:'Warlock',shop:'arcane',slot:'back',category:'accessory',price:310000,saveBonus:1,effect:'Saving throw +1. Pact slot harcadıktan sonra loş ışıkta 15 ft teleport olabilirsin (1/long rest).',note:'Pelerin ışığı kesmez; taşıyıcının gölgesini kendine sarar.'},
    {name:'Son Kapının Anahtarı',className:'Warlock',shop:'arcane',slot:'focus',category:'focus',price:450000,magicBonus:2,effect:'Spell Attack ve Spell Save DC +2. Bir curse hedefi 0 HP’ye düşünce proficiency bonusu kadar geçici HP kazanırsın.',note:'Hiçbir kilide uymayan anahtar, rüyalardaki son kapının önünde ısınır.'},
    {name:'Fısıltıyutan',className:'Warlock',shop:'arcane',slot:'head',category:'accessory',price:220000,statBonuses:{CHA:1},effect:'CHA +1. Telepatik, charm veya fear etkisine karşı bir save’i +1d4 ile güçlendirebilirsin (1/long rest).',note:'Kulakları örten taç konuşmaları susturmaz; yalnız patronların sesini aç bırakır.'},

    {name:'Köklerin Hafızası',className:'Druid',shop:'arcane',slot:'focus',category:'focus',price:360000,magicBonus:1,effect:'Spell Attack ve Spell Save DC +1. Wild Shape açtığında proficiency bonusu kadar geçici HP kazanırsın (1/long rest).',note:'Canlı meşe dalı, dokunduğu her toprağın kokusunu halkalarına işler.'},
    {name:'Ayaltı Postu',className:'Druid',shop:'arcane',slot:'back',category:'accessory',price:280000,saveBonus:1,effect:'Saving throw +1. Doğal difficult terrain’i yok sayarsın; ay ışığında Stealth +2.',note:'Hiçbir hayvandan yüzülmemiş gümüş post, dolunayda sessizce nefes alır.'},
    {name:'İlk Yağmur',className:'Druid',shop:'arcane',slot:'neck',category:'accessory',price:230000,statBonuses:{WIS:1},effect:'WIS +1. Bir creature’ı büyüyle iyileştirdiğinde hedef bir tur opportunity attack çekmeden 5 ft hareket edebilir (1/long rest).',note:'Kuraklıkta bile üzerinde tek bir serin damla taşıyan yeşil taş.'},

    {name:'İçindeki Fırtına',className:'Sorcerer',shop:'arcane',slot:'focus',category:'focus',price:480000,magicBonus:2,effect:'Spell Attack ve Spell Save DC +2. Metamagic kullandığın büyünün bir hasar zarını yeniden atabilirsin (1/long rest).',note:'Şeffaf kürenin içindeki yıldırım, sahibinin kalp atışıyla aynı ritimde çakar.'},
    {name:'Kan Yıldızı',className:'Sorcerer',shop:'arcane',slot:'neck',category:'accessory',price:250000,statBonuses:{CHA:1},effect:'CHA +1. Sorcery point harcadığında bir tur concentration save’lerine +2 alırsın.',note:'Beş köşeli kızıl kristal yalnız doğuştan büyü taşıyanların teninde ısınır.'},
    {name:'Kırılmayan Kıvılcım',className:'Sorcerer',shop:'arcane',slot:'ring',category:'accessory',price:300000,saveBonus:1,effect:'Saving throw +1. 0 HP’ye düşecekken 1 HP’de kalırsın; eşya sonra long rest bitene kadar kararır (1/long rest).',note:'Çatlamış yüzüğün arasında söndürülemeyen küçücük bir ışık yanar.'},

    {name:'Unutulan Nakarat',className:'Bard',shop:'arcane',slot:'focus',category:'focus',price:330000,magicBonus:1,effect:'Spell Attack ve Spell Save DC +1. Bardic Inspiration alan hedef ayrıca 5 ft fırsat saldırısız hareket edebilir (1/long rest).',note:'Gümüş akort çatalının sesi herkese tanıdık gelir fakat melodiyi kimse hatırlayamaz.'},
    {name:'Alkışsız Sahne',className:'Bard',shop:'arcane',slot:'back',category:'accessory',price:210000,saveBonus:1,effect:'Saving throw +1. Performance veya Persuasion check’inde attığın 1 sonucunu 10 kabul edebilirsin (1/long rest).',note:'Kadife pelerin açıldığında çevredeki bütün yankıları bir anlığına yutar.'},
    {name:'Dokuzuncu Tel',className:'Bard',shop:'arcane',slot:'hands',category:'accessory',price:270000,statBonuses:{CHA:1},effect:'CHA +1. Charm büyüne karşı ilk başarılı save’i yeniden attırabilirsin (1/long rest).',note:'Hiçbir çalgıya takılı olmayan tel, doğru söz söylendiğinde kendi kendine titreşir.'},

    {name:'Eğilmeyen Şafak',className:'Paladin',shop:'temple',slot:'weapon',category:'weapon',price:460000,attackBonus:1,damageBonus:1,effect:'Silah saldırısı ve hasarı +1. Divine Smite kullandığında hedef bir tur 5 ft ışık saçar.',note:'Güneş doğmadan hemen önce dövülmüş uzun kılıç, teslimiyet yemini eden elde ağırlaşır.'},
    {name:'Son Nöbet',className:'Paladin',shop:'temple',slot:'back',category:'accessory',price:350000,saveBonus:1,effect:'Saving throw +1. Aura içindeki müttefik 0 HP’ye düşecekken reaction ile 1 HP’de kalmasını sağlarsın (1/long rest).',note:'Koyu lacivert pelerinin kenarında sabaha ulaşamayan muhafızların isimleri belirir.'},
    {name:'Yemin Külü',className:'Paladin',shop:'temple',slot:'focus',category:'focus',price:290000,magicBonus:1,effect:'Spell Attack ve Spell Save DC +1. Channel Divinity kullandığında proficiency bonusu kadar geçici HP kazanırsın.',note:'Avuç içinde dağılmayan sıcak kül, bozulan bir yemin yakınındaysa kıpkırmızı olur.'},

    {name:'Ufkun Öteki Ucu',className:'Ranger',shop:'arcane',slot:'weapon',category:'weapon',price:410000,attackBonus:1,damageBonus:1,effect:'Ranged weapon attack ve hasarı +1. İşaretli hedefe long range saldırıda disadvantage’ı bir kez yok sayarsın (1/long rest).',note:'Yayın kirişi çekildiğinde hedefin arkasındaki ufuk bir anlığına yakınlaşır.'},
    {name:'İzsiz Adım',className:'Ranger',shop:'arcane',slot:'feet',category:'accessory',price:240000,saveBonus:1,effect:'Saving throw +1. Doğal difficult terrain’in ilk 15 ft’sini yok sayar ve iz bırakmazsın.',note:'Çizmeler çamura basar ama ne çukur ne de su izi bırakır.'},
    {name:'Son Ok',className:'Ranger',shop:'arcane',slot:'back',category:'accessory',price:320000,statBonuses:{WIS:1},effect:'WIS +1. Bir ranged saldırıyı kaçırdığında aynı hedefe bonus action ile tekrar saldırabilirsin (1/long rest).',note:'Boş sadakta her şafak tek bir siyah ok belirir; atılmadan ikinci ok oluşmaz.'},

    {name:'Mükemmel Hata',className:'Artificer',shop:'arcane',slot:'focus',category:'focus',price:440000,magicBonus:2,effect:'Spell Attack ve Spell Save DC +2. Tool check’inde natural 1 attığında sonucu 10 kabul edersin (1/long rest).',note:'Yanlış yerleştirilmiş tek dişi sayesinde kusursuz çalışan pirinç mekanizma.'},
    {name:'Yürüyen Atölye',className:'Artificer',shop:'arcane',slot:'back',category:'accessory',price:370000,acBonus:1,effect:'AC +1. Bir action ile smith, tinkering veya alchemist tools setine dönüşür.',note:'Küçük metal sırt çantası açıldığında yüzlerce ayak üzerinde kullanıcısının çevresine kurulur.'},
    {name:'Sıfırıncı Dişli',className:'Artificer',shop:'arcane',slot:'ring',category:'accessory',price:260000,statBonuses:{INT:1},effect:'INT +1. Infused bir eşyanın kullanıcısına reaction ile 1d8 hasar azaltma verirsin (1/long rest).',note:'Her mekanizmadan önce var olmuş gibi görünen, hiçbir ölçü sistemine uymayan dişli.'}
  ];
  const rarityMeta={rarity:'veryRare',minLevel:7,size:'small',qtyMax:1,lootKind:'uniqueRelic',release:'v65',attunement:true,unique:true,stock:1,tier:3,active:true,ready:true};
  const loot=rows.map((row,index)=>Object.freeze({...rarityMeta,id:`v65-unique-${String(index+1).padStart(2,'0')}`,name:row.name,category:row.category,slot:row.slot,classRestriction:[row.className],themes:['mixed',row.shop==='temple'?'sacred':'arcane'],valueCopper:row.price,effect:row.effect,note:`${row.className} için tekil emanet • ${row.note}`,...Object.fromEntries(['magicBonus','saveBonus','acBonus','attackBonus','damageBonus','statBonuses'].filter(key=>row[key]!=null).map(key=>[key,row[key]]))}));
  root.V65_UNIQUE_RELICS=Object.freeze(loot);
  root.V48_LOOT_KIND_LABELS=Object.freeze({...root.V48_LOOT_KIND_LABELS,uniqueRelic:'Tekil isimli emanetler'});
  const baseBuild=root.V48_BUILD_LOOT;
  root.V48_BUILD_LOOT=function(add,context={}){baseBuild(add,context);const names=new Set((context.catalogue||[]).map(x=>String(x.name).toLocaleLowerCase('tr-TR')));for(const item of loot)if(!names.has(item.name.toLocaleLowerCase('tr-TR'))){add({...item});names.add(item.name.toLocaleLowerCase('tr-TR'))}};
  root.V65_UNIQUE_MARKET=Object.freeze(rows.map((row,index)=>Object.freeze({...loot[index],id:`ex-v65-unique-${String(index+1).padStart(2,'0')}`,shop:row.shop,priceCopper:row.price,stock:1})));
  EX_ALL_CATALOG.push(...root.V65_UNIQUE_MARKET);
})(typeof window!=='undefined'?window:globalThis);
