/* Build 74: player combat desk, effect timers and requested dice. */
(()=>{
 'use strict';
 const A=window.v74,R=window.v74Rules,{h,btn,field,select,check,textarea,dm,own,get,q,checks,empty,modalForm}=A;
 const local=(key,fallback)=>window.kadimUiState?.get('v74-'+key,fallback)??fallback;
 const set=(key,value)=>window.kadimUiState?.set('v74-'+key,value);
 const character=()=>own().find(c=>c.id===local('character',''))||own()[0];
 const signed=n=>n>=0?'+'+n:String(n);
 const targetOptions=()=>{
  const chars=(state.characters||[]).filter(c=>(c.approvalStatus||'approved')==='approved').map(c=>['c:'+c.id,c.name]),ids=new Set(chars.map(x=>x[0]));
  const b=state.battleMap;
  for(const f of state.encounter||[]){
   if(f.characterId&&ids.has('c:'+f.characterId))continue;
   const token=b?.tokens?.find(t=>t.id===f.id||t.combatantId===f.id);
   if(!dm()&&(!b?.published||!token||token.hidden||typeof v38CellIsHidden==='function'&&v38CellIsHidden(b,token.x,token.y,true)))continue;
   chars.push(['e:'+f.id,f.name]);
  }
  return chars;
 };
 const targetLabel=id=>targetOptions().find(x=>x[0]===id)?.[1]||'Hedef';
 const featureRows=c=>{
  const base=window.V53_CLASSES?.[c.className]?.features||[],sub=window.V53_SUBCLASS_FEATURES?.[c.className]?.[c.subclass]||[],domain=c.className==='Cleric'?Object.values(window.V52_CLERIC_DOMAINS||{}).find(d=>d.id===c.subclass)?.features||[]:[];
  return [...base,...sub,...domain].filter(f=>f.level<=R.level(c)).filter((f,i,rows)=>rows.findIndex(x=>x.name===f.name)===i);
 };
 function spellsFor(c){const selected=R.spells(c);if(local('spellMode','selected')!=='catalog')return selected;const ids=new Set((typeof v53SpellRows==='function'?v53SpellRows(c):[]).map(x=>x.sourceId));return [...selected,...(window.V47_SPELLS||[]).filter(s=>ids.has(s.id)&&!selected.some(x=>x.id===s.id))];}
 function spellCards(c){
  const query=R.key(local('spellQuery','')),level=local('spellLevel','all'),selected=new Set(R.spells(c).map(x=>x.id));
  const rows=spellsFor(c).filter(s=>(level==='all'||String(s.level)===level)&&(!query||R.key(s.name+' '+s.nameTr+' '+s.schoolTr).includes(query))).sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name,'en'));
  return `<div class="v74-spell-grid">${rows.map(s=>`<article class="v74-spell" data-entity-id="${h(s.id)}"><div class="v74-spell-top"><small>${s.level===0?'CANTRIP':'SEVİYE '+s.level}${s.concentration?' · KONSANTRASYON':''}</small>${s.automatic?'<span class="v74-badge">Otomatik</span>':''}</div><h4>${h(s.name)}</h4><small>${h(s.nameTr||s.schoolTr)}</small><p>${h(s.castingTime)} · ${h(s.range)}</p><div class="v74-actions">${btn('spell_open',selected.has(s.id)?'Seç / kullan':'İncele',s.id,selected.has(s.id)?'primary':'ghost')}</div></article>`).join('')||empty(query?'Aramada büyü bulunamadı.':R.casting(c)?'Henüz büyü seçilmemiş. Beceriler sayfasında büyülerini hazırla; domain büyüleri burada otomatik görünür.':'Bu sınıfın bu seviyede büyü kullanımı yok. Sınıf özelliklerini aşağıdan kullanabilirsin.')}</div>`;
 }
 function resourceCards(c){return `<div class="v74-resources">${R.resources(c).map(r=>`<div class="v74-resource" data-entity-id="${h(r.id)}"><div><b>${h(r.name)}</b><small>${r.rest==='short'?'Kısa veya uzun':'Uzun'} dinlenme</small></div><strong>${r.max===999?'∞':r.remaining+' / '+r.max}</strong>${btn('resource_open',r.remaining?'Harca':'Tükendi',r.id,'ghost',!r.remaining)}</div>`).join('')}</div>`;}
 function desk(){
  const c=character();if(!c)return empty('Savaş araçları için onaylanmış bir karakter gerekli.');
  const cfg=R.casting(c),stats=typeof prStats==='function'?prStats(c):c.stats||{},prof=2+Math.floor((R.level(c)-1)/4),magic=typeof v63SpellBonus==='function'?v63SpellBonus(c):0,castingMod=R.mod(stats[cfg?.ability]);
  const turn=(state.encounter||[]).find(f=>f.turn),ownTurn=turn?.characterId===c.id;
  const slots=R.slots(c).map((n,i)=>n?`<span>Seviye ${i+1}<b>${Math.max(0,n-(+c.spellSlotsUsed?.[i+1]||0))} / ${n}</b></span>`:'').join('');
  return A.errorHtml()+`<div class="v74-combat-title"><div><small>${h(c.className)} · ${h(c.subclass||'')} · Sv ${R.level(c)}</small><h3>${h(c.name)}</h3></div><span class="v74-turn ${ownTurn?'is-turn':''}">${!state.encounterActive?'Savaş hazırlığı':ownTurn?'Sıra sende':'Sıranı bekliyorsun'}</span></div><div class="v74-facts"><span>Can <b>${c.hp} / ${c.maxHp}</b></span><span>AC <b>${c.ac}</b></span>${cfg?`<span>Büyü DC <b>${8+prof+castingMod+magic}</b></span><span>Büyü saldırısı <b>${signed(prof+castingMod+magic)}</b></span>`:''}</div>${slots?`<div class="v74-slot-strip" aria-label="Kalan büyü slotları">${slots}</div>`:''}<details open data-ui-key="v74-spells"><summary>Büyüler & Cantripler</summary>${spellCards(c)}</details><details data-ui-key="v74-features" ${cfg?'':'open'}><summary>Sınıf özellikleri & Kaynaklar</summary>${resourceCards(c)}<div class="v74-feature-list">${featureRows(c).map(f=>`<details data-ui-key="feature-${h(f.name)}"><summary>${h(f.name)} <small>Sv ${f.level}</small></summary><p class="v74-prose">${h(f.summary||f.description||'Özelliğin sınıf kurallarını Rehber’den inceleyebilirsin.')}</p>${btn('ability_open','Kullanımı kaydet',f.name)}</details>`).join('')}</div></details>${dm()?`<div class="v74-actions">${btn('rest_short','Kısa dinlenme: kaynakları yenile',c.id)}${btn('rest_long','Uzun dinlenme: kaynakları yenile',c.id)}</div>`:''}<p class="v74-note">Büyü kullanınca slot ve süre takibi işlenir. İsabet, hasar/şifa, aksiyon ekonomisi ve pahalı bileşen tüketimini DM çözümler.</p>`;
 }
 function rollCard(r,compact=false){
  const status=r.status==='pending'?'Bekliyor':r.status==='cancelled'?'İptal':r.private&&!dm()?'Sonuç DM’ye iletildi':`${(r.dice||[]).join(' / ')} ${signed(r.bonus)} = ${r.total}${r.success==null?'':r.success?' · Başarılı':' · Başarısız'}`;
  return `<article class="v74-roll" data-entity-id="${h(r.id)}"><div><b>${h(r.title)}</b><small>${h(r.characterName)} · ${r.mode==='advantage'?'Avantajlı':r.mode==='disadvantage'?'Dezavantajlı':'Normal'} d20 ${signed(r.bonus)}${r.dc!=null?' · DC '+r.dc:''}${r.private?' · Sonuç yalnız DM’ye':''}</small><span aria-live="polite">${h(status)}</span></div><div class="v74-actions">${r.status==='pending'&&(r.userId===auth.id||dm())?btn('roll','Zarı at',r.id,'primary'):''}${r.status==='pending'&&dm()&&!compact?btn('roll_cancel','İptal',r.id):''}</div></article>`;
 }
 function rollBanner(){if(page==='encounter'&&(dm()||local('combatView','map')==='tools'))return '';const rows=(A.data.rolls||[]).filter(r=>r.status==='pending'&&r.userId===auth.id);return rows.length?`<section class="v74 v74-roll-banner" aria-label="Bekleyen atışlar"><details open data-ui-key="pending-rolls"><summary>🎲 ${rows.length} atışın bekliyor</summary>${rows.map(r=>rollCard(r,true)).join('')}</details></section>`:'';}
 function rolls(){const all=A.data.rolls||[],pending=all.filter(r=>r.status==='pending'),past=all.filter(r=>r.status!=='pending');return `<section class="v74-card"><div class="v74-section-head"><h3>Atış istekleri</h3>${dm()?btn('roll_new','+ Atış iste','','primary'):''}</div>${pending.map(r=>rollCard(r)).join('')||empty('Bekleyen atış yok.')}<details data-ui-key="roll-history"><summary>Son atışlar (${past.length})</summary>${past.slice(0,40).map(r=>rollCard(r)).join('')||empty('Henüz atış yok.')}</details></section>`;}
 function effects(){return `<section class="v74-card"><div class="v74-section-head"><h3>Etkin büyüler & Durumlar</h3>${dm()?btn('effect_new','+ Etki ekle'):''}</div><div class="v74-effect-list">${(A.data.effects||[]).map(e=>`<article class="v74-effect" data-entity-id="${h(e.id)}"><div><b>${h(e.name)}</b><small>${e.concentration?'Konsantrasyon · ':''}${e.remaining==null?'Elle bitirilir':e.remaining+' tur'}${!e.visible?' · Yalnız DM':''}</small><p>${(e.targets||[]).map(targetLabel).map(h).join(', ')||'Hedef belirtilmedi'}</p></div><div class="v74-actions">${dm()&&e.remaining!=null?btn('effect_tick','−1 tur',e.id):''}${dm()||e.concentration&&e.userId===auth.id?btn('effect_end','Bitir',e.id):''}</div></article>`).join('')||empty('Etkin süreli büyü veya durum yok.')}</div><small>Süre, kaynağın yeni sırası başladığında azalır. Kaynaksız etkiler yeni raundda azalır. Savaş dışında DM süreyi ilerletir.</small></section>`;}
 function log(){return `<details class="v74-card" data-ui-key="combat-log"><summary>Son kullanımlar</summary>${(A.data.log||[]).slice(0,30).map(r=>`<p>${h(r.text)} <small>${h(A.date(r.createdAt))}</small></p>`).join('')||empty('Henüz kullanım yok.')}</details>`;}
 Object.assign(A.renderers,{desk,rolls,effects,combatLog:log,rollBanner});
 function combatPanel(){
  queueMicrotask(()=>A.load());if(!own().length)return `<section class="v74 v74-combat">${empty('Büyü ve sınıf araçları için onaylanmış bir karakter gerekli.')}${dm()?`<div data-v74-live="effects">${effects()}</div><div data-v74-live="rolls">${rolls()}</div>`:''}</section>`;
  return `<section class="v74 v74-combat"><section class="v74-card v74-desk"><div class="v74-section-head"><h2>Savaş araçlarım</h2>${own().length>1?select('v74Character','Karakter',own().map(c=>[c.id,c.name]),character()?.id):''}</div><div class="v74-filters">${field('v74SpellQuery','Büyü ara',local('spellQuery',''),'search','placeholder="Ad, okul…"')}${select('v74SpellMode','Liste',[['selected','Seçili + otomatik büyüler'],['catalog','Sınıfın büyü kataloğu']],local('spellMode','selected'))}${select('v74SpellLevel','Seviye',[['all','Tüm seviyeler'],['0','Cantrip'],...Array.from({length:9},(_,i)=>[String(i+1),String(i+1)])],local('spellLevel','all'))}</div><div data-v74-live="desk">${desk()}</div></section><div class="v74-combat-support"><div data-v74-live="effects">${effects()}</div><div data-v74-live="rolls">${rolls()}</div></div><div data-v74-live="combatLog">${log()}</div></section>`;
 }
 for(const registry of [dmPages,playerPages]){const old=registry.encounter;registry.encounter=()=>{A.ensureScope();const base=old();if(dm())return base+combatPanel();const view=local('combatView','map');return `<div class="v74"><div class="v74-actions v74-battle-tabs" aria-label="Savaş görünümü">${btn('combat_map','Harita & hareket','',view==='map'?'primary':'ghost')}${btn('combat_tools','Büyüler & sınıf','',view==='tools'?'primary':'ghost')}</div></div>`+(view==='map'?base:combatPanel());};}
 A.clicks.combat_map=()=>{set('combatView','map');render();};A.clicks.combat_tools=()=>{set('combatView','tools');render();};
 const baseRender=render;render=function(){A.ensureScope();const result=baseRender.apply(this,arguments);if(current){const view=document.querySelector('#view');if(view&&!view.querySelector('[data-v74-live="rollBanner"]')){const el=document.createElement('div');el.dataset.v74Live='rollBanner';el.innerHTML=rollBanner();view.prepend(el);}queueMicrotask(()=>A.load());}return result;};
 A.clicks.spell_open=b=>{
  const c=character(),s=(window.V47_SPELLS||[]).find(s=>s.id===b.dataset.id);if(!c||!s)return;
  const usable=R.spells(c).some(x=>x.id===s.id),options=R.castOptions(c,s),concentration=(A.data.effects||[]).find(e=>e.sourceId===c.id&&e.concentration);
  const body=`<input type="hidden" name="characterId" value="${h(c.id)}"><p><b>${h(s.name)}</b> · ${s.level===0?'Cantrip':'Seviye '+s.level} · ${h(s.schoolTr||s.school)}</p><div class="v74-facts"><span>Kullanım <b>${h(s.castingTime)}</b></span><span>Menzil <b>${h(s.range)}</b></span><span>Süre <b>${h(s.duration)}</b></span><span>Bileşen <b>${h((s.components||[]).join(', '))}</b></span></div><p class="v74-prose">${h(s.description)}</p>${s.materialTr?`<p class="v74-note">Malzeme: ${h(s.materialTr)}</p>`:''}${s.higher?`<details><summary>Yüksek slotla kullanım</summary><p class="v74-prose">${h(s.higher)}</p></details>`:''}${usable?select('slot','Harcanacak kaynak',options.map(o=>[o.level,o.label]),options.find(o=>o.remaining>0)?.level??options[0]?.level)+`<fieldset><legend>Hedefler (isteğe bağlı)</legend><div class="v74-checklist">${targetOptions().map(([id,name])=>check('targets',name,false,id)).join('')}</div></fieldset>${s.concentration&&concentration?`<p class="v74-note">Bu büyü mevcut ${h(concentration.name)} konsantrasyonunu bitirir.</p>`:''}<p class="v74-note">Kullanım kaydedilir; slot harcanır. Zar, hasar/şifa ve malzeme tüketimi DM ile çözülür.</p>`:'<p class="v74-note">Bu büyü seçili değil. Beceriler sayfasından hazırla veya öğren.</p>'}`;
  if(usable&&options.some(o=>o.remaining>0))modalForm(s.nameTr||s.name,body,'cast',s.id);else modal(s.nameTr||s.name,`<div class="v74 v74-form">${body}${usable?empty('Kullanılabilir büyü kaynağın kalmadı.'):''}</div>`);
 };
 A.clicks.cast=(b,f)=>{const c=own().find(c=>c.id===get('characterId',f)),s=(window.V47_SPELLS||[]).find(s=>s.id===b.dataset.id);if(s.concentration&&(A.data.effects||[]).some(e=>e.sourceId===c.id&&e.concentration)&&!confirm('Mevcut konsantrasyonu bitirip bu büyüyü kullan?'))return;return A.act('cast',{characterId:c.id,spellId:s.id,slot:Number(get('slot',f)),targets:checks('targets',f)},f);};
 A.clicks.resource_open=b=>{const c=character(),r=R.resources(c).find(r=>r.id===b.dataset.id);modalForm(r.name,`<input type="hidden" name="characterId" value="${h(c.id)}"><p>Kalan: ${r.remaining} / ${r.max===999?'Sınırsız':r.max}. Kaynak azalır; özelliğin sonucunu DM çözümler.</p>`+field('amount','Harcanacak miktar',1,'number',`required min="1" max="${r.remaining}" step="1"`),'resource',r.id);};
 A.clicks.resource=(b,f)=>A.act('resource',{characterId:get('characterId',f),resourceId:b.dataset.id,amount:Number(get('amount',f))},f);
 A.clicks.ability_open=b=>{const c=character(),f=featureRows(c).find(f=>f.name===b.dataset.id);modalForm(f.name,`<input type="hidden" name="characterId" value="${h(c.id)}"><p class="v74-prose">${h(f.summary||f.description||'Ayrıntılar sınıf rehberinde.')}</p><p>Bu düğme özelliği kullandığını masaya kaydeder. Ki, Channel Divinity gibi sınırlı kaynakları “Harca” ile azalt.</p>`,'ability',f.name);};
 A.clicks.ability=(b,f)=>A.act('ability',{characterId:get('characterId',f),name:b.dataset.id},f);
 for(const kind of ['short','long'])A.clicks['rest_'+kind]=b=>{if(confirm('Seçilen karakterin uygun slotları ve sınıf kaynakları yenilensin mi? Can ve hit dice değişmez.'))return A.act('rest',{characterId:b.dataset.id,kind});};
 for(const action of ['roll','roll_cancel','effect_tick'])A.clicks[action]=b=>A.act(action,{id:b.dataset.id});
 A.clicks.effect_end=b=>{if(confirm('Etki sona ersin mi?'))return A.act('effect_end',{id:b.dataset.id});};
 A.clicks.effect_new=()=>modalForm('Süreli etki / durum',field('name','Etki adı','','text','required maxlength="100" placeholder="Örn. Poisoned, Haste"')+select('sourceId','Kaynak karakter',[['','Kaynaksız: raund başında azalır'],...(state.characters||[]).map(c=>[c.id,c.name])])+field('remaining','Kalan tur (süresizse boş)',1,'number','min="1" max="14400" step="1"')+check('concentration','Konsantrasyon gerektirir')+check('visible','Oyuncular görebilsin',true)+`<fieldset><legend>Hedefler</legend><div class="v74-checklist">${targetOptions().map(([id,name])=>check('targets',name,false,id)).join('')}</div></fieldset>`,'effect_add');
 A.clicks.effect_add=(b,f)=>A.act('effect_add',{name:get('name',f),sourceId:get('sourceId',f),remaining:get('remaining',f)===''?null:Number(get('remaining',f)),concentration:q('concentration',f).checked,visible:q('visible',f).checked,targets:checks('targets',f)},f);
 const abilities=['STR','DEX','CON','INT','WIS','CHA'];
 const rollTypes=()=>[['flat','Düz d20'],...abilities.map(x=>['save:'+x,x+' kurtarma']),...abilities.map(x=>['ability:'+x,x+' yetenek']),...Object.keys(typeof V30_SKILLS==='undefined'?{}:V30_SKILLS).map(k=>['skill:'+k,(typeof V30_TR!=='undefined'&&V30_TR[k]||k)+' kontrolü'])];
 function bonus(c,type){
  const [kind,key]=type.split(':'),stats=prStats(c),prof=2+Math.floor((R.level(c)-1)/4);
  if(kind==='save')return R.mod(stats[key])+(typeof v53SaveProficient==='function'&&v53SaveProficient(c,key)?prof:0)+(typeof v31EquipmentSaveBonus==='function'?v31EquipmentSaveBonus(c):0)+(c.className==='Paladin'&&c.level>=6?Math.max(1,R.mod(stats.CHA)):0);
  if(kind==='skill')return v53SkillCheckBonus(c,key,V30_SKILLS[key]);
  return kind==='ability'?R.mod(stats[key]):0;
 }
 function rollPreview(f){const type=get('rollType',f),extra=Number(get('extra',f)),ids=checks('rollTargets',f);const node=f.querySelector('[data-v74-roll-preview]');if(node)node.textContent=(state.characters||[]).filter(c=>ids.includes(c.id)).map(c=>`${c.name}: ${signed(bonus(c,type)+extra)}`).join(' · ')||'Atış yapacak karakterleri seç.';}
 A.clicks.roll_new=()=>{modalForm('Oyunculardan atış iste',field('title','Atış başlığı','','text','required maxlength="120" placeholder="Örn. Kapının ardındaki sesi fark et"')+select('rollType','Atış türü',rollTypes(),'skill:Perception')+`<div class="v74-two">${field('extra','Ek bonus / ceza',0,'number','min="-30" max="30" step="1"')}${field('dc','Hedef DC (isteğe bağlı)','','number','min="1" max="100" step="1"')}</div>`+select('mode','Atış biçimi',[['normal','Normal'],['advantage','Avantajlı'],['disadvantage','Dezavantajlı']])+check('private','Sonucu yalnız DM görsün')+`<fieldset><legend>Karakterler</legend><div class="v74-checklist">${(state.characters||[]).filter(c=>members.some(m=>m.userId===c.userId)).map(c=>check('rollTargets',c.name,false,c.id)).join('')}</div></fieldset><p class="v74-note" data-v74-roll-preview>Atış yapacak karakterleri seç.</p>`,'roll_request');};
 A.clicks.roll_request=(b,f)=>{const type=get('rollType',f),ids=checks('rollTargets',f),extra=Number(get('extra',f));return A.act('roll_request',{title:get('title',f),dc:get('dc',f)===''?null:Number(get('dc',f)),mode:get('mode',f),private:q('private',f).checked,targets:(state.characters||[]).filter(c=>ids.includes(c.id)).map(c=>({characterId:c.id,bonus:bonus(c,type)+extra}))},f);};
 document.addEventListener('input',e=>{if(e.target.name==='v74SpellQuery'){set('spellQuery',e.target.value);A.refresh();}const f=e.target.closest('[data-v74-form="roll_request"]');if(f)rollPreview(f);});
 document.addEventListener('change',e=>{const key={v74Character:'character',v74SpellMode:'spellMode',v74SpellLevel:'spellLevel'}[e.target.name];if(key){set(key,e.target.value);A.refresh();}const f=e.target.closest('[data-v74-form="roll_request"]');if(f)rollPreview(f);});
 const guide=`<section class="v74 v74-card"><h2>Macera araçları · 3.5.0</h2><details><summary>Savaş ekranında büyü ve sınıf kaynakları</summary><p>Seçili cantripler, hazırlanan/öğrenilen büyüler ve otomatik domain büyüleri Savaş araçlarım’da listelenir. Katalog görünümü sınıfının erişebildiği diğer büyüleri inceletir. “Seç / kullan” ile slot ve hedefleri seç. Cantrip ücretsizdir; Warlock Pact Magic ve Mystic Arcanum ayrı kurallarla çalışır. DM slot tablosu aynı sayaçları gösterir.</p><p>İsabet, hasar/şifa, aksiyon ekonomisi ve değerli/tüketilen bileşenler DM tarafından çözülür. Kullanım kaydı HP’yi kendiliğinden değiştirmez. Sınıf kaynakları Harca ile düşer; pasif/serbest özelliklerde kullanım kaydı tutulur.</p></details><details><summary>Etkiler, süre ve konsantrasyon</summary><p>Süreli büyüler otomatik etki açar. Yeni konsantrasyon eski konsantrasyonu bitirir. Kaynağın sonraki sırası bir tur azaltır; kaynaksız etkiler yeni raundda azalır. Hasar kaydında CON kurtarması gelir, başarısız atış ilgili konsantrasyonu bitirir. Bilinç kaybı/0 HP konsantrasyonu sonlandırır. Savaş dışında veya özel koşullarda DM −1 tur / Bitir kullanır. Hasar ayrı vuruşlar hâlinde girilmeli; topluca girilen HP kaybı tek hasar kabul edilir.</p></details><details><summary>Atış istekleri ve gizlilik</summary><p>DM türü, karakterleri, avantajı, ek bonusu ve isteğe bağlı DC’yi seçer. Oyuncu bulunduğu sayfanın başından zarı atar. Atış sunucuda bir kez üretilir. “Sonucu yalnız DM görsün” oyuncuya yalnız gönderildi bilgisini gösterir.</p></details><details><summary>Belgeler, itibar ve faaliyetler</summary><p>DM bir belgeyi taslak tutabilir, tüm oyunculara veya seçilen kişilere yayınlayabilir. Topluluklarda −100…+100 itibar ve gerekçe geçmişi vardır; oyuncu yalnız grup ve kendi itibarını görür. Dinlenme faaliyeti DM onayı ve gün ilerlemesiyle tamamlanır. Bedel ve malzemeler tamamlanma anında birlikte harcanır, ödül envantere/keseye gider. İptalde tüketim olmaz. Kuşanılmış eşya malzeme olarak tüketilemez.</p></details></section>`;
 for(const registry of [dmPages,playerPages]){const old=registry.guide;registry.guide=()=>old()+guide;}
 if(current)render();
})();
