/* Build 75: character/NPC relationships and readable party dossiers. */
(()=>{
  'use strict';
  const R=window.v75Relations;
  const ABILITIES=['STR','DEX','CON','INT','WIS','CHA'];
  const SKILL_LABELS={Athletics:'Atletizm',Acrobatics:'Akrobasi','Sleight of Hand':'El Çabukluğu',Stealth:'Gizlilik',Arcana:'Gizem',History:'Tarih',Investigation:'Araştırma',Nature:'Doğa',Religion:'Din','Animal Handling':'Hayvan İdaresi',Insight:'Sezgi',Medicine:'Tıp',Perception:'Farkındalık',Survival:'Hayatta Kalma',Deception:'Aldatma',Intimidation:'Gözdağı',Performance:'Gösteri',Persuasion:'İkna'};
  let scope='',filters={query:'',kind:'all',type:'all',band:'all',sort:'recent',entity:''};
  const signed=value=>`${value>0?'+':''}${value}`;
  const date=value=>{try{return value?new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—'}catch{return'—'}};
  const id=()=>globalThis.crypto?.randomUUID?.()||`v75-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
  function ensure(){
    if(scope!==(current?.id||'')){scope=current?.id||'';filters={query:'',kind:'all',type:'all',band:'all',sort:'recent',entity:''}}
    if(!Array.isArray(state.relationshipsV75))state.relationshipsV75=[];
    state.relationshipsV75=state.relationshipsV75.filter(row=>row&&typeof row==='object').map(row=>{const out=R.normalize(row);out.id||=(row.id||id());return out});
  }
  function entities(){
    return[
      ...(state.characters||[]).map(row=>({type:'character',id:String(row.id),name:row.name||'İsimsiz karakter',subtitle:`${row.className||'Class yok'}${row.subclass?' / '+row.subclass:''} • Lv ${row.level||1}`,raw:row})),
      ...(state.npcs||[]).map(row=>({type:'npc',id:String(row.id),name:row.name||'İsimsiz NPC',subtitle:`${row.role||'Rol yok'} • ${row.faction||'Bağımsız'}`,raw:row}))
    ];
  }
  function resolve(ref){return entities().find(row=>row.type===ref?.type&&row.id===String(ref?.id))||null}
  function missing(ref){return{type:ref?.type==='npc'?'npc':'character',id:String(ref?.id||''),name:ref?.type==='npc'?'Silinmiş NPC':'Silinmiş karakter',subtitle:'Eski ilişki kaydı'}}
  function refKey(row){return`${row.type}:${row.id}`}
  function typeLabel(type){return R.TYPES.find(row=>row.id===type)?.label||'Nötr'}
  function kindLabel(kind){return kind==='characters'?'Karakter ↔ Karakter':kind==='npcs'?'NPC ↔ NPC':'Karakter ↔ NPC'}
  function relationCount(entity){const key=refKey(entity);return state.relationshipsV75.filter(row=>[refKey(row.source),refKey(row.target)].includes(key)).length}
  function currentRows(){
    ensure();const role=current?.role||'player';let rows=state.relationshipsV75.filter(row=>R.visibleTo(row,role)&&R.matches(row,filters,resolve));
    rows.sort((a,b)=>filters.sort==='strongest'?Math.abs(b.score)-Math.abs(a.score):filters.sort==='weakest'?Math.abs(a.score)-Math.abs(b.score):filters.sort==='name'?(resolve(a.source)||missing(a.source)).name.localeCompare((resolve(b.source)||missing(b.source)).name,'tr'):String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));
    return rows;
  }
  function scoreBar(row){const band=R.band(row.score),left=(row.score+100)/2;return`<div class="v75-score"><div><i class="${band.tone}" style="width:${left}%"></i><span style="left:${left}%"></span></div><b>${signed(row.score)} · ${band.label}</b></div>`}
  function relationCard(row){
    const source=resolve(row.source)||missing(row.source),target=resolve(row.target)||missing(row.target),dm=current.role==='dm';
    return`<article class="v75-relation-card ${R.band(row.score).tone}" data-entity-id="${esc(row.id)}"><header><span class="v75-kind">${kindLabel(R.entityKind(row))}</span>${dm&&!row.visible?'<span class="v75-hidden">OYUNCU EKRANINDA KAPALI</span>':''}<time>${date(row.updatedAt)}</time></header><div class="v75-pair"><button data-v75-focus="${esc(refKey(source))}"><b>${esc(source.name)}</b><small>${esc(source.subtitle)}</small></button><span title="${row.mutual?'Karşılıklı':'Tek yönlü'}">${row.mutual?'↔':'→'}</span><button data-v75-focus="${esc(refKey(target))}"><b>${esc(target.name)}</b><small>${esc(target.subtitle)}</small></button></div><div class="v75-relation-main"><span class="v75-type">${esc(typeLabel(row.type))}</span>${scoreBar(row)}</div><div class="v75-axes"><span><b>${row.trust}</b> Güven</span><span><b>${row.respect}</b> Saygı</span><span><b>${row.affection}</b> Yakınlık</span><span><b>${row.tension}</b> Gerilim</span></div>${row.note?`<p>${esc(row.note)}</p>`:''}${dm?`<footer><button class="ghost" data-v75-score="${esc(row.id)}">Puan işle</button><button class="ghost" data-v75-edit="${esc(row.id)}">Düzenle</button><button class="danger" data-v75-delete="${esc(row.id)}">Sil</button></footer>`:''}<details><summary>Değişim geçmişi (${row.history.length})</summary><div class="v75-history">${row.history.map(item=>`<div><b class="${(+item.delta||0)>=0?'up':'down'}">${signed(+item.delta||0)}</b><span>${esc(item.reason||'DM ayarı')}<small>${signed(+item.from||0)} → ${signed(+item.to||0)} • ${date(item.at)}</small></span></div>`).join('')||'<small>Henüz puan değişimi yok.</small>'}</div></details></article>`;
  }
  function directory(){
    const rows=entities();return`<section class="card v75-directory"><div class="v75-section-head"><div><span>KİŞİ DİZİNİ</span><h3>Karakterler ve NPC’ler</h3></div><b>${rows.length}</b></div><div class="v75-entity-grid">${rows.map(row=>`<article class="${filters.entity===refKey(row)?'selected':''}"><span>${row.type==='npc'?'NPC':'OYUNCU'}</span><b>${esc(row.name)}</b><small>${esc(row.subtitle)}</small><footer><i>${relationCount(row)} ilişki</i><button class="ghost" data-v75-focus="${esc(refKey(row))}">${filters.entity===refKey(row)?'Filtreyi kaldır':'İlişkileri göster'}</button>${current.role==='dm'?`<button class="ghost" data-v75-add-from="${esc(refKey(row))}">＋ Bağ ekle</button>`:''}</footer></article>`).join('')||'<div class="empty">Henüz karakter veya NPC yok.</div>'}</div></section>`;
  }
  function activeAc(c){return Number.isFinite(+c.ac)?+c.ac:(typeof prAutoAC==='function'?prAutoAC(c):10)}
  function skillBonus(c,name,key){if(typeof window.v53SkillCheckBonus==='function')return window.v53SkillCheckBonus(c,name,key);let stats=typeof prStats==='function'?prStats(c):(c.stats||{}),bonus=typeof prMod==='function'?prMod(stats[key]):Math.floor(((+stats[key]||10)-10)/2);return bonus}
  function partyDossier(c){
    const stats=typeof prStats==='function'?prStats(c):(c.stats||c.baseStats||{}),prof=typeof prProf==='function'?prProf(c.level):2,owner=members.find(row=>row.userId===c.userId)?.name||'Bağsız',dex=typeof prMod==='function'?prMod(stats.DEX):0,passive=10+skillBonus(c,'Perception','WIS'),speed=window.v53MovementSpeed?.(c)||c.speed||30,cfg=window.v74Rules?.casting(c),castMod=cfg&&typeof prMod==='function'?prMod(stats[cfg.ability]):0,spellDc=cfg?8+prof+castMod:null,spellAttack=cfg?prof+castMod:null,slots=window.v74Rules?.slots(c)||[],profs=typeof window.v30SkillProfs==='function'?window.v30SkillProfs(c):[],expert=c.expertise||[],equipped=typeof v25Equipped==='function'?v25Equipped(c):(c.inventory||[]).filter(item=>item.equipped),species=typeof prSpecies==='function'?prSpecies(c.species):{},res=[...new Set([...(species.resist||[]),...(c.resistances||[])])],weak=[...new Set([...(species.weak||[]),...(c.weaknesses||[])])];
    return`<details class="v75-dossier"><summary><div><span>${esc(owner)}</span><h3>${esc(c.name||'İsimsiz karakter')}</h3><p>${esc(c.species||'Species yok')}${c.subspecies?' / '+esc(c.subspecies):''} • ${esc(c.className||'Class yok')}${c.subclass?' / '+esc(c.subclass):''} • Lv ${c.level||1}</p></div><div class="v75-vital-mini"><b>${c.hp??c.maxHp??0}/${c.maxHp??0} HP</b><b>${activeAc(c)} AC</b><b>${speed} ft</b></div><i>＋</i></summary><div class="v75-dossier-body"><section class="v75-combat-grid"><span><small>Geçici HP</small><b>${c.tempHp||0}</b></span><span><small>İnisiyatif</small><b>${signed(dex)}</b></span><span><small>Pasif Farkındalık</small><b>${passive}</b></span><span><small>Proficiency</small><b>${signed(prof)}</b></span><span><small>Hit Die</small><b>d${typeof PR_HIT_DIE!=='undefined'?(PR_HIT_DIE[c.className]||8):8}</b></span>${cfg?`<span><small>Spell Save DC</small><b>${spellDc}</b></span><span><small>Spell Attack</small><b>${signed(spellAttack)}</b></span><span><small>Büyü Statı</small><b>${cfg.ability}</b></span>`:''}</section><section><h4>Statlar ve kurtarmalar</h4><div class="v75-stat-grid">${ABILITIES.map(key=>{const mod=typeof prMod==='function'?prMod(stats[key]):0,save=mod+((typeof prClass==='function'&&prClass(c.className).saves.includes(key))?prof:0);return`<span><b>${key} ${stats[key]??10}</b><small>${signed(mod)} mod · ${signed(save)} save</small></span>`}).join('')}</div></section>${slots.length?`<section><h4>Spell slotları</h4><div class="v75-tags">${slots.map((total,index)=>{const used=+c.spellSlotsUsed?.[index+1]||0;return total?`<span>${index+1}. seviye <b>${Math.max(0,total-used)}/${total}</b></span>`:''}).join('')}</div></section>`:''}<section><h4>Yetkinlikler</h4><div class="v75-tags">${profs.map(name=>`<span class="${expert.includes(name)?'expert':''}">${esc(SKILL_LABELS[name]||name)} <b>${signed(skillBonus(c,name,typeof V30_SKILLS!=='undefined'?V30_SKILLS[name]:'WIS'))}${expert.includes(name)?' ★':''}</b></span>`).join('')||'<small>Seçilmiş skill proficiency yok.</small>'}</div></section><section class="v75-detail-grid"><div><h4>Kuşanılanlar</h4><p>${equipped.map(item=>esc(item.name)).join(' • ')||'Kuşanılmış eşya yok.'}</p></div><div><h4>Aktif etkiler</h4><p>${(c.effects||[]).map(esc).join(' • ')||'Aktif efekt yok.'}</p></div><div><h4>Dirençler</h4><p>${res.map(esc).join(' • ')||'Yok'}</p></div><div><h4>Zayıflıklar</h4><p>${weak.map(esc).join(' • ')||'Yok'}</p></div></section></div></details>`;
  }
  function partyStats(){const chars=(state.characters||[]).filter(c=>c.approvalStatus!=='pending'&&c.approvalStatus!=='rejected');return`<section class="card v75-party"><div class="v75-section-head"><div><span>PARTİ BİLGİSİ</span><h3>Arkadaşlarının Detaylı Statları</h3><p>Savaşta karar vermek için HP, AC, hız, kurtarma, skill, slot ve kuşanılan eşyaları tek yerde gör.</p></div><b>${chars.length}</b></div><div class="v75-dossier-list">${chars.map(partyDossier).join('')||'<div class="empty">Onaylı parti karakteri yok.</div>'}</div></section>`}
  function filtersView(){return`<section class="card v75-tools"><label class="v75-search"><span>⌕</span><input id="v75Query" class="input" value="${esc(filters.query)}" placeholder="Kişi, ilişki türü veya not ara…"></label><select id="v75Kind"><option value="all">Tüm eşleşmeler</option><option value="characters" ${filters.kind==='characters'?'selected':''}>Karakter ↔ Karakter</option><option value="mixed" ${filters.kind==='mixed'?'selected':''}>Karakter ↔ NPC</option><option value="npcs" ${filters.kind==='npcs'?'selected':''}>NPC ↔ NPC</option></select><select id="v75Type"><option value="all">Tüm ilişki türleri</option>${R.TYPES.map(row=>`<option value="${row.id}" ${filters.type===row.id?'selected':''}>${row.label}</option>`).join('')}</select><select id="v75Band"><option value="all">Tüm puanlar</option>${[['hateful','Kinli'],['hostile','Düşmanca'],['cold','Soğuk'],['neutral','Nötr'],['positive','Olumlu'],['trusted','Güveniyor'],['unshakable','Sarsılmaz']].map(([id,label])=>`<option value="${id}" ${filters.band===id?'selected':''}>${label}</option>`).join('')}</select><select id="v75Sort"><option value="recent">Son düzenlenen</option><option value="name" ${filters.sort==='name'?'selected':''}>İsme göre</option><option value="strongest" ${filters.sort==='strongest'?'selected':''}>En güçlü bağ</option><option value="weakest" ${filters.sort==='weakest'?'selected':''}>En zayıf bağ</option></select>${filters.entity?'<button id="v75ClearEntity" class="ghost">Kişi filtresini kaldır</button>':''}</section>`}
  function pageView(){ensure();const rows=currentRows();return`<div class="v75-page"><section class="v75-hero"><div><span class="v26-kicker">SOSYAL HARİTA • BUILD 75</span><h2>İlişkiler</h2><p>Karakterler ve NPC’ler arasındaki bağı; tür, genel puan, güven, saygı, yakınlık ve gerilim eksenlerinde takip et.</p></div>${current.role==='dm'?'<button id="v75Add" class="primary">＋ Yeni ilişki</button>':'<span class="v75-player-mark">PARTİ GÖRÜNÜMÜ</span>'}</section>${filtersView()}<section class="v75-layout"><div><div class="v75-list-head"><h3>İlişki Listesi</h3><span>${rows.length} kayıt</span></div><div id="v75RelationList" class="v75-relation-list">${rows.map(relationCard).join('')||'<div class="card empty"><h3>Bu filtrede ilişki yok</h3><p>DM yeni bir ilişki ekleyebilir veya filtreleri temizleyebilirsin.</p></div>'}</div></div>${directory()}</section>${partyStats()}</div>`}
  function options(selected){return entities().map(row=>`<option value="${esc(refKey(row))}" ${selected===refKey(row)?'selected':''}>${row.type==='npc'?'NPC':'Karakter'} · ${esc(row.name)}</option>`).join('')}
  function editor(row,from=''){
    const value=row?R.normalize(row):R.normalize({id:id(),source:{type:'character',id:''},target:{type:'npc',id:''},type:'neutral',mutual:true,score:0,trust:50,respect:50,affection:0,tension:0,visible:true}),list=entities();if(!list.length)return alert('Önce en az bir karakter veya NPC oluştur.');
    if(from){const [type,...parts]=from.split(':');value.source={type,id:parts.join(':')}}
    let source=resolve(value.source)?refKey(value.source):(from||refKey(list[0])),target=resolve(value.target)?refKey(value.target):refKey(list.find(item=>refKey(item)!==source)||list[0]);
    modal(row?'İlişkiyi Düzenle':'Yeni İlişki',`<div class="v75-editor"><div class="v75-pair-fields"><label>Kim?<select id="v75Source">${options(source)}</select></label><label>Bağ yönü<select id="v75Mutual"><option value="true" ${value.mutual?'selected':''}>↔ Karşılıklı</option><option value="false" ${!value.mutual?'selected':''}>→ Tek yönlü</option></select></label><label>Kiminle?<select id="v75Target">${options(target)}</select></label></div><label>İlişki türü<select id="v75RelationType">${R.TYPES.map(type=>`<option value="${type.id}" ${value.type===type.id?'selected':''}>${type.label}</option>`).join('')}</select></label><div class="v75-range-grid">${[['Score','Genel puan',-100,100,value.score],['Trust','Güven',0,100,value.trust],['Respect','Saygı',0,100,value.respect],['Affection','Yakınlık',0,100,value.affection],['Tension','Gerilim',0,100,value.tension]].map(([key,label,min,max,n])=>`<label>${label}<span id="v75${key}Out">${signed(n)}</span><input id="v75${key}" type="range" min="${min}" max="${max}" value="${n}"></label>`).join('')}</div><label>DM / hikâye notu<textarea id="v75Note" rows="4" maxlength="2000" placeholder="Bağın sebebi, kırılma noktası veya ortak hatıra…">${esc(value.note)}</textarea></label><label class="v75-visible"><input id="v75Visible" type="checkbox" ${value.visible?'checked':''}> Oyuncu ekranında göster</label><button type="button" id="v75Save" class="primary" data-id="${esc(value.id)}">İlişkiyi Kaydet</button></div>`);
  }
  function scoreEditor(row){const a=resolve(row.source)||missing(row.source),b=resolve(row.target)||missing(row.target);modal('İlişki Puanı İşle',`<div class="v75-score-modal"><p><b>${esc(a.name)}</b> ${row.mutual?'↔':'→'} <b>${esc(b.name)}</b></p>${scoreBar(row)}<label>Puan değişimi<input id="v75Delta" class="input" type="number" min="-100" max="100" step="1" value="0" inputmode="numeric"></label><label>Neden<textarea id="v75Reason" rows="3" maxlength="300" placeholder="Örn: Tehlikede onu yalnız bırakmadı"></textarea></label><p id="v75ScorePreview">Yeni puan: ${signed(row.score)}</p><button type="button" id="v75ConfirmScore" class="primary" data-id="${esc(row.id)}">İşle</button></div>`)}
  async function commit(){save();await window.flushSave?.()}
  function installNav(nav){if(nav.some(row=>row[0]==='relationships'))return;const index=nav.findIndex(row=>row[0]===(nav===dmNav?'party':'partyview'));nav.splice(index>=0?index+1:1,0,['relationships','♥','İlişkiler'])}
  installNav(dmNav);installNav(playerNav);dmPages.relationships=pageView;playerPages.relationships=pageView;
  if(typeof V27_PAGE_HELP!=='undefined')V27_PAGE_HELP.relationships='Karakter ve NPC bağlarını filtrele; parti arkadaşlarının savaş statlarını ayrıntılı gör. İlişkileri yalnız DM düzenler.';
  window.kadimUiState?.registerPage?.('relationships',['characters','npcs','relationshipsV75','@members']);
  document.addEventListener('input',event=>{
    if(event.target.id==='v75Query'){filters.query=event.target.value;const list=$('#v75RelationList'),head=document.querySelector('.v75-list-head span'),rows=currentRows();if(list)list.innerHTML=rows.map(relationCard).join('')||'<div class="card empty">Bu aramada ilişki yok.</div>';if(head)head.textContent=`${rows.length} kayıt`;return}
    if(/^v75(Score|Trust|Respect|Affection|Tension)$/.test(event.target.id)){const out=$(`#${event.target.id}Out`);if(out)out.textContent=event.target.id==='v75Score'?signed(+event.target.value):event.target.value;return}
    if(event.target.id==='v75Delta'){const row=state.relationshipsV75.find(item=>item.id===$('#v75ConfirmScore')?.dataset.id),preview=$('#v75ScorePreview');if(row&&preview)preview.textContent=`Yeni puan: ${signed(R.clamp(row.score+(+event.target.value||0),-100,100))}`}
  });
  document.addEventListener('change',event=>{const map={v75Kind:'kind',v75Type:'type',v75Band:'band',v75Sort:'sort'},key=map[event.target.id];if(key){filters[key]=event.target.value;render()}});
  document.addEventListener('click',async event=>{
    const button=event.target.closest('button');if(!button)return;
    if(button.id==='v75Add'){editor(null);return}
    if(button.dataset.v75AddFrom){editor(null,button.dataset.v75AddFrom);return}
    if(button.dataset.v75Focus){filters.entity=filters.entity===button.dataset.v75Focus?'':button.dataset.v75Focus;render();return}
    if(button.id==='v75ClearEntity'){filters.entity='';render();return}
    if(button.dataset.v75Edit){const row=state.relationshipsV75.find(item=>item.id===button.dataset.v75Edit);if(row)editor(row);return}
    if(button.dataset.v75Score){const row=state.relationshipsV75.find(item=>item.id===button.dataset.v75Score);if(row)scoreEditor(row);return}
    if(button.dataset.v75Delete){const row=state.relationshipsV75.find(item=>item.id===button.dataset.v75Delete);if(!row||!confirm('Bu ilişki ve puan geçmişi silinsin mi?'))return;state.relationshipsV75=state.relationshipsV75.filter(item=>item.id!==row.id);await commit();render();return}
    if(button.id==='v75Save'){
      const parse=value=>{const [type,...parts]=String(value).split(':');return{type,id:parts.join(':')}},old=state.relationshipsV75.find(item=>item.id===button.dataset.id),source=parse($('#v75Source').value),target=parse($('#v75Target').value),mutual=$('#v75Mutual').value==='true';
      if(refKey(source)===refKey(target))return alert('Bir kişi kendisiyle ilişkilendirilemez.');
      const value=R.normalize({...(old||{}),id:button.dataset.id||id(),source,target,mutual,type:$('#v75RelationType').value,score:+$('#v75Score').value,trust:+$('#v75Trust').value,respect:+$('#v75Respect').value,affection:+$('#v75Affection').value,tension:+$('#v75Tension').value,note:$('#v75Note').value,visible:$('#v75Visible').checked,updatedAt:new Date().toISOString(),history:old?.history||[]});
      const duplicate=state.relationshipsV75.find(item=>item.id!==value.id&&R.pairKey(item)===R.pairKey(value));if(duplicate)return alert('Bu yönde bir ilişki zaten var; mevcut kaydı düzenle.');
      if(old&&old.score!==value.score)value.history.unshift({id:id(),delta:value.score-old.score,from:old.score,to:value.score,reason:'İlişki düzenleyicisinde değiştirildi',at:new Date().toISOString()});value.history=value.history.slice(0,100);
      const index=state.relationshipsV75.findIndex(item=>item.id===value.id);if(index>=0)state.relationshipsV75[index]=value;else state.relationshipsV75.unshift(value);await commit();$('#modal').close();render();return;
    }
    if(button.id==='v75ConfirmScore'){
      const row=state.relationshipsV75.find(item=>item.id===button.dataset.id),delta=Math.trunc(+$('#v75Delta').value||0),reason=$('#v75Reason').value.trim();if(!row)return;if(!delta)return alert('Sıfırdan farklı bir puan yaz.');if(!reason)return alert('Geçmişte anlaşılması için kısa bir neden yaz.');const from=row.score,to=R.clamp(from+delta,-100,100),actual=to-from;if(!actual)return alert('Puan zaten sınırda.');row.score=to;row.updatedAt=new Date().toISOString();row.history.unshift({id:id(),delta:actual,from,to,reason,at:row.updatedAt});row.history=row.history.slice(0,100);await commit();$('#modal').close();render();return;
    }
  },true);
})();
