const $=s=>document.querySelector(s),cfg=window.DM_CONFIG||{},db=window.supabase?.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY),uid=()=>globalThis.crypto?.randomUUID?.()||('id-'+Date.now().toString(36)+Math.random().toString(36).slice(2));
const EFFECTS=['Blessed','Blinded','Charmed','Deafened','Frightened','Grappled','Incapacitated','Invisible','Paralyzed','Petrified','Poisoned','Prone','Restrained','Stunned','Unconscious','Concentration','Exhaustion 1','Exhaustion 2','Exhaustion 3','Burning','Bleeding','Hasted','Slowed'];
const SPECIES=['Human','Elf','Dwarf','Halfling','Dragonborn','Gnome','Goliath','Orc','Tiefling','Aasimar'];
const ITEMS=['Healing Potion','Greater Healing Potion','Antitoxin','Rope 50 ft','Torch','Rations','Thieves’ Tools','Holy Water','Alchemist’s Fire','Climber’s Kit','Healer’s Kit','Longsword','Shortbow','Shield','Studded Leather','Chain Mail','Bag of Holding','Pearl of Power','Cloak of Protection','Sending Stones'];
const MONSTERS=[['Goblin',7,15,2,'Nimble Escape'],['Kobold',5,12,1,'Pack Tactics'],['Skeleton',13,13,2,'Undead'],['Zombie',22,8,2,'Undead Fortitude'],['Wolf',11,13,1,'Pack Tactics'],['Bandit',11,12,2,'Scimitar'],['Cultist',9,12,2,'Dark Devotion'],['Guard',11,16,2,'Spear'],['Orc',15,13,3,'Aggressive'],['Hobgoblin',11,18,3,'Martial Advantage'],['Bugbear',27,16,3,'Brute'],['Ghoul',22,12,2,'Paralyzing Claws'],['Giant Spider',26,14,3,'Web'],['Dire Wolf',37,14,3,'Pack Tactics'],['Ogre',59,11,4,'Greatclub'],['Mimic',58,12,3,'Adhesive'],['Wight',45,14,3,'Life Drain'],['Basilisk',52,15,2,'Petrifying Gaze'],['Troll',84,15,4,'Regeneration'],['Werewolf',58,11,3,'Immunity'],['Young Green Dragon',136,18,4,'Poison Breath'],['Young Red Dragon',178,18,4,'Fire Breath'],['Vampire Spawn',82,15,4,'Regeneration'],['Mind Flayer',71,15,4,'Mind Blast'],['Beholder',180,18,5,'Eye Rays'],['Stone Golem',178,17,4,'Immutable Form'],['Lich',135,17,5,'Spellcasting'],['Adult Black Dragon',195,19,5,'Acid Breath'],['Purple Worm',247,18,5,'Swallow'],['Tarrasque',676,25,6,'Legendary Resistance']].map((x,i)=>({id:'m'+i,name:x[0],hp:x[1],maxHp:x[1],ac:x[2],speed:x[3]*10,note:x[4]}));
const blank=()=>({session:1,notes:'',quests:[],characters:[],npcs:[],encounter:[],market:ITEMS.slice(0,8).map((name,i)=>({id:uid(),name,price:[50,150,50,1,1,5,25,25][i]+' gp',stock:3})),customEffects:[],customSpecies:[],log:[]});
let auth=JSON.parse(localStorage.getItem('kadim-auth')||'null'),campaigns=[],current=null,state=blank(),members=[],page='dashboard',guide='',registerMode=false,saveTimer;
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=(t,b,n=4)=>`<section class="card span${n}"><h3>${t}</h3>${b}</section>`;
const field=(id,l,type='text',v='')=>`<label>${l}<input class="input" id="${id}" type="${type}" value="${esc(v)}"></label>`;
function modal(t,b){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modal').showModal()}
function toast(s,bad=false){$('#saveState').textContent=(bad?'⚠ ':'● ')+s}
function normalized(s){return Object.assign(blank(),s||{})}
async function save(){if(!current||current.role!=='dm')return;clearTimeout(saveTimer);toast('Kaydediliyor');saveTimer=setTimeout(async()=>{let {data,error}=await db.rpc('campaign_save_v2',{p_user:auth.id,p_campaign:current.id,p_state:state});toast(error||!data?'Kayıt hatası':'Buluta kaydedildi',!!error)},450)}
async function refreshCampaigns(selectId){let {data,error}=await db.rpc('campaign_list_v2',{p_user:auth.id});if(error)return alert(error.message);campaigns=data||[];if(!campaigns.length){current=null;showLobby();return}await loadCampaign(selectId||current?.id||campaigns[0].id)}
async function loadCampaign(id){let {data,error}=await db.rpc('campaign_load_v2',{p_user:auth.id,p_campaign:id});if(error||!data?.length)return alert('Kampanya yüklenemedi');let r=data[0];current={id:r.id,code:r.code,name:r.name,role:r.role};state=normalized(r.state);members=r.members||[];document.body.classList.remove('landing-mode');page='dashboard';render()}
function showLobby(){document.body.classList.remove('landing-mode');current=null;$('#campaignSelect').innerHTML='<option>Kampanya yok</option>';$('#roomBadge').textContent=auth.name;$('#nav').innerHTML='';$('#pageTitle').textContent='Macera Salonu';$('#roleLabel').textContent='HOŞ GELDİN';$('#view').innerHTML=`<div class="grid">${card('Yeni bir hikâye başlat','<p>Odayı kuran hesap Dungeon Master olur.</p><button class="primary" id="lobbyCreate">Kampanya Kur</button>',6)}${card('Mevcut masaya katıl','<p>DM’den aldığın 6 haneli oda kodunu gir.</p><div class="row"><input class="input" id="lobbyCode" placeholder="ODA KODU"><button class="primary" id="lobbyJoin">Katıl</button></div>',6)}</div>`}
const dmNav=[['dashboard','⌂','Masa'],['party','♙','Karakterler'],['encounter','⚔','Savaş'],['npcs','♜','NPC Defteri'],['bestiary','☠','Yaratıklar'],['market','◇','Market'],['guide','⌕','Rehber'],['dice','⬡','Zarlar']];
const playerNav=[['dashboard','⌂','Karakterim'],['inventory','▣','Envanter'],['skills','✦','Yetenekler'],['market','◇','Market'],['guide','⌕','Rehber'],['dice','⬡','Zarlar']];
function myChar(){return state.characters.find(c=>c.userId===auth.id)}
function render(){if(!current)return showLobby();let nav=current.role==='dm'?dmNav:playerNav;$('#campaignSelect').innerHTML=campaigns.map(c=>`<option value="${c.id}" ${c.id===current.id?'selected':''}>${esc(c.name)} • ${c.role==='dm'?'DM':'Oyuncu'}</option>`).join('');$('#roomBadge').textContent=`ODA ${current.code} • ${current.role.toUpperCase()}`;$('#roleLabel').textContent=current.role==='dm'?'DUNGEON MASTER':'MACERACI';$('#newCampaign').style.display='';$('#nav').innerHTML=nav.map(n=>`<button data-page="${n[0]}" class="${page===n[0]?'active':''}">${n[1]}　${n[2]}</button>`).join('');let found=nav.find(n=>n[0]===page)||nav[0];page=found[0];$('#pageTitle').textContent=found[2];$('#view').innerHTML=(current.role==='dm'?dmPages:playerPages)[page]();bind()}
function hpbar(c){let pct=Math.max(0,Math.min(100,(c.hp/c.maxHp)*100));return `<div class="hpbar"><i style="width:${pct}%"></i></div><b>${c.hp}/${c.maxHp} HP</b>${c.tempHp?` <span class="pill">+${c.tempHp} geçici</span>`:''}`}
function dashboardDM(){return `<div class="grid">${card('Oturum',`<div class="stat">#${state.session}</div><button class="ghost" data-session="-1">−</button> <button class="ghost" data-session="1">+</button>`)}${card('Maceracılar',`<div class="stat">${state.characters.length}</div><p>${members.filter(x=>x.role==='player').length} hesap masada</p>`)}${card('Aktif savaş',`<div class="stat">${state.encounter.length}</div><button class="ghost" data-page="encounter">Savaşı aç</button>`)}${card('DM Notları',`<textarea id="notes">${esc(state.notes)}</textarea>`,8)}${card('Görevler',`<div class="stack">${state.quests.map((q,i)=>`<div class="row between"><span>${esc(q)}</span><button data-delquest="${i}" class="danger">×</button></div>`).join('')}<div class="row"><input id="quest" class="input"><button id="addQuest" class="primary">Ekle</button></div></div>`,4)}</div>`}
function party(){let pending=members.filter(m=>m.role==='player'&&!state.characters.some(c=>c.userId===m.userId));return `<div class="card"><div class="toolbar"><button id="addCharacter" class="primary">+ Karakter oluştur</button>${pending.map(m=>`<button class="ghost" data-makefor="${m.userId}">${esc(m.name)} için oluştur</button>`).join('')}</div><div class="chargrid">${state.characters.map(c=>`<article class="sheet"><div class="between row"><h3>${esc(c.name)}</h3><button class="danger" data-delchar="${c.id}">×</button></div><p>${esc(c.species)} • ${esc(c.className)} ${c.level} • AC ${c.ac}</p>${hpbar(c)}<div class="toolbar"><button class="ghost" data-damage="${c.id}">Hasar/İyileştir</button><button class="ghost" data-item="${c.id}">Eşya</button><button class="ghost" data-effect="${c.id}">Efekt</button><button class="ghost" data-editchar="${c.id}">Düzenle</button></div><p>${c.effects.map(x=>`<span class="effect">${esc(x)} <button data-rmeffect="${c.id}|${esc(x)}">×</button></span>`).join('')||'<small>Efekt yok</small>'}</p><details><summary>Envanter (${c.inventory.length})</summary>${c.inventory.map((x,i)=>`<div class="row between"><span>${esc(x.name)} ×${x.qty}</span><button class="danger" data-delitem="${c.id}|${i}">×</button></div>`).join('')}</details></article>`).join('')||'<div class="empty">Henüz karakter yok.</div>'}</div></div>`}
function encounter(){return `<div class="card"><div class="toolbar"><button id="addEncounter" class="primary">+ Savaşçı</button><button id="sortEncounter" class="ghost">Initiative sırala</button><button id="nextTurn" class="ghost">Sonraki tur</button><button id="clearEncounter" class="danger">Temizle</button></div>${state.encounter.map((x,i)=>`<div class="initiative-item ${x.turn?'active-turn':''}"><b>${x.init}</b><span>${esc(x.name)}</span><span>${x.hp} HP</span><span>AC ${x.ac}</span><button data-hitenc="${i}" class="ghost">HP</button><button data-delenc="${i}" class="danger">×</button></div>`).join('')||'<div class="empty">Savaş alanı boş.</div>'}</div>`}
function npcs(){return `<div class="card"><button id="addNpc" class="primary">+ NPC Oluştur</button><div class="chargrid">${state.npcs.map(n=>`<article class="sheet"><h3>${esc(n.name)}</h3><p>${esc(n.role)} • ${esc(n.faction||'Bağımsız')}</p>${hpbar(n)}<p>${esc(n.note)}</p><div class="toolbar"><button data-npchp="${n.id}" class="ghost">HP</button><button data-npcitem="${n.id}" class="ghost">Eşya</button><button data-delnpc="${n.id}" class="danger">Sil</button></div></article>`).join('')}</div></div>`}
function bestiary(){return `<div class="card"><div class="toolbar"><input id="monsterSearch" class="input" placeholder="Yaratık ara"><button id="customMonster" class="primary">+ Özel yaratık</button></div><div id="monsterList" class="catalog">${monsterCards(MONSTERS)}</div></div>`}
function monsterCards(list){return list.map(m=>`<article><b>${esc(m.name)}</b><small>HP ${m.hp} • AC ${m.ac} • Hız ${m.speed}</small><p>${esc(m.note)}</p><button class="ghost" data-spawn="${m.id}">Encounter'a ekle</button></article>`).join('')}
function market(){return `<div class="card"><div class="toolbar">${current.role==='dm'?'<button id="addMarket" class="primary">+ Ürün ekle</button>':''}</div><div class="catalog">${state.market.map((x,i)=>`<article><b>${esc(x.name)}</b><span class="pill">${esc(x.price)}</span><p>Stok: ${x.stock}</p>${current.role==='dm'?`<button data-marketgive="${i}" class="ghost">Oyuncuya ver</button> <button data-delmarket="${i}" class="danger">Sil</button>`:'<small>Satın almak için DM’e söyle.</small>'}</article>`).join('')}</div></div>`}
function guideView(){return `<div class="card"><div class="toolbar"><input id="guideSearch" class="input" placeholder="Grapple, concentration, DC..."><button id="searchGuide" class="primary">Ara</button></div><div id="guideResults" class="guide-results"><div class="empty">31 sayfalık Türkçe rehberde ara.</div></div></div>`}
function dice(){return `<div class="grid">${card('Zar Havuzu',`<div class="dice">${[4,6,8,10,12,20,100].map(x=>`<button data-die="${x}">d${x}</button>`).join('')}</div><div id="rollout" class="rollout">—</div><div class="row"><input id="diceCount" class="input" type="number" value="1"><input id="diceBonus" class="input" type="number" value="0"></div>`,8)}</div>`}
function playerDash(){let c=myChar();if(!c)return `<div class="card empty"><h2>Karakterin hazırlanıyor</h2><p>DM hesabını görüyor. Karakterini sana bağladığında burada belirecek.</p></div>`;return `<div class="grid">${card(esc(c.name),`<p>${esc(c.species)} • ${esc(c.className)} ${c.level}</p>${hpbar(c)}<div class="stats">${Object.entries(c.stats).map(([k,v])=>`<span><b>${v}</b><small>${k}</small></span>`).join('')}</div>`,8)}${card('Savunma',`<div class="stat">AC ${c.ac}</div><p>Hız ${c.speed} ft • PP ${c.pp}</p>`,4)}${card('Aktif Efektler',c.effects.map(x=>`<span class="effect">${esc(x)}</span>`).join('')||'<p>Efekt yok.</p>',6)}${card('Lonca / Bağ',`<p>${esc(c.guild||'Henüz yok')}</p>`,6)}</div>`}
function inventoryPlayer(){let c=myChar();return c?`<div class="card"><h3>${esc(c.name)} — Envanter</h3>${c.inventory.map(x=>`<div class="row between itemrow"><span><b>${esc(x.name)}</b><small>${esc(x.note||'')}</small></span><span>×${x.qty}</span></div>`).join('')||'<div class="empty">Çanta boş.</div>'}</div>`:playerDash()}
function skillsPlayer(){let c=myChar();return c?`<div class="grid">${card('Yetenekler',c.skills.map(x=>`<div class="itemrow"><b>${esc(x.name)}</b><p>${esc(x.note)}</p></div>`).join('')||'<p>Henüz yetenek eklenmedi.</p>',6)}${card('Tür Özellikleri',`<h3>${esc(c.species)}</h3><p>${esc(c.speciesNote||'DM özel özellik ekleyebilir.')}</p>`,6)}</div>`:playerDash()}
const dmPages={dashboard:dashboardDM,party,encounter,npcs,bestiary,market,guide:guideView,dice};const playerPages={dashboard:playerDash,inventory:inventoryPlayer,skills:skillsPlayer,market,guide:guideView,dice};
function charForm(c={},userId=''){return field('cName','Karakter adı','text',c.name)+`<label>Oyuncu hesabı<select id="cUser"><option value="">Bağsız</option>${members.filter(m=>m.role==='player').map(m=>`<option value="${m.userId}" ${m.userId===(c.userId||userId)?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label>`+`<label>Tür<select id="cSpecies">${[...SPECIES,...state.customSpecies].map(x=>`<option ${x===c.species?'selected':''}>${x}</option>`).join('')}</select></label>`+field('cClass','Sınıf','text',c.className||'Fighter')+field('cLevel','Seviye','number',c.level||1)+field('cHp','Maksimum HP','number',c.maxHp||10)+field('cAc','AC','number',c.ac||10)+field('cGuild','Lonca / bağ','text',c.guild||'')+`<button class="primary" id="saveCharacter" data-id="${c.id||''}">Kaydet</button>`}
function bind(){
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.body.classList.remove('menu');render()});$('#notes')?.addEventListener('input',e=>{state.notes=e.target.value;save()});document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{state.session=Math.max(1,state.session+(+b.dataset.session));save();render()});$('#addQuest')?.addEventListener('click',()=>{if($('#quest').value)state.quests.push($('#quest').value),save(),render()});document.querySelectorAll('[data-delquest]').forEach(b=>b.onclick=()=>{state.quests.splice(+b.dataset.delquest,1);save();render()});
 $('#addCharacter')?.addEventListener('click',()=>modal('Karakter oluştur',charForm()));document.querySelectorAll('[data-makefor]').forEach(b=>b.onclick=()=>modal('Oyuncu karakteri',charForm({},b.dataset.makefor)));document.querySelectorAll('[data-editchar]').forEach(b=>{let c=state.characters.find(x=>x.id===b.dataset.editchar);b.onclick=()=>modal('Karakteri düzenle',charForm(c))});document.querySelectorAll('[data-delchar]').forEach(b=>b.onclick=()=>{if(confirm('Karakter silinsin mi?'))state.characters=state.characters.filter(x=>x.id!==b.dataset.delchar),save(),render()});
 document.querySelectorAll('[data-damage]').forEach(b=>b.onclick=()=>modal('HP değiştir',field('hpAmount','Değer (+ iyileştirir, - hasar)','number')+`<button class="primary" id="applyHp" data-id="${b.dataset.damage}">Uygula</button>`));document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>modal('Eşya ekle',field('itemName','Eşya')+field('itemQty','Adet','number',1)+field('itemNote','Not')+`<button class="primary" id="giveItem" data-id="${b.dataset.item}">Ekle</button>`));document.querySelectorAll('[data-effect]').forEach(b=>b.onclick=()=>modal('Efekt uygula',`<label>Efekt<select id="effectName">${[...EFFECTS,...state.customEffects].map(x=>`<option>${x}</option>`).join('')}</select></label>`+field('customEffect','veya özel efekt')+`<button class="primary" id="giveEffect" data-id="${b.dataset.effect}">Uygula</button>`));
 document.querySelectorAll('[data-rmeffect]').forEach(b=>b.onclick=()=>{let [id,e]=b.dataset.rmeffect.split('|'),c=state.characters.find(x=>x.id===id);c.effects=c.effects.filter(x=>x!==e);save();render()});document.querySelectorAll('[data-delitem]').forEach(b=>b.onclick=()=>{let [id,i]=b.dataset.delitem.split('|'),c=state.characters.find(x=>x.id===id);c.inventory.splice(+i,1);save();render()});
 $('#addEncounter')?.addEventListener('click',()=>modal('Savaşçı ekle',field('eName','Ad')+field('eInit','Initiative','number')+field('eHp','HP','number')+field('eAc','AC','number')+'<button class="primary" id="saveEncounter">Ekle</button>'));$('#sortEncounter')?.addEventListener('click',()=>{state.encounter.sort((a,b)=>b.init-a.init);save();render()});$('#nextTurn')?.addEventListener('click',()=>{let i=state.encounter.findIndex(x=>x.turn);state.encounter.forEach(x=>x.turn=false);if(state.encounter.length)state.encounter[(i+1)%state.encounter.length].turn=true;save();render()});$('#clearEncounter')?.addEventListener('click',()=>{state.encounter=[];save();render()});document.querySelectorAll('[data-delenc]').forEach(b=>b.onclick=()=>{state.encounter.splice(+b.dataset.delenc,1);save();render()});document.querySelectorAll('[data-hitenc]').forEach(b=>b.onclick=()=>{let x=state.encounter[+b.dataset.hitenc],v=+prompt('HP değişimi (+ iyileştirir, - hasar)','-1');if(Number.isFinite(v))x.hp=Math.max(0,x.hp+v),save(),render()});
 $('#addNpc')?.addEventListener('click',()=>modal('NPC oluştur',field('nName','Ad')+field('nRole','Rol')+field('nFaction','Lonca / taraf')+field('nHp','HP','number',10)+field('nAc','AC','number',10)+field('nNote','Not')+'<button class="primary" id="saveNpc">Oluştur</button>'));document.querySelectorAll('[data-delnpc]').forEach(b=>b.onclick=()=>{state.npcs=state.npcs.filter(x=>x.id!==b.dataset.delnpc);save();render()});document.querySelectorAll('[data-npchp]').forEach(b=>b.onclick=()=>{let n=state.npcs.find(x=>x.id===b.dataset.npchp),v=+prompt('HP değişimi','-1');if(Number.isFinite(v))n.hp=Math.max(0,n.hp+v),save(),render()});
 document.querySelectorAll('[data-spawn]').forEach(b=>b.onclick=()=>{let m=MONSTERS.find(x=>x.id===b.dataset.spawn);state.encounter.push({...m,id:uid(),init:0,turn:!state.encounter.length});save();toast(m.name+' savaşa eklendi')});$('#monsterSearch')?.addEventListener('input',e=>{$('#monsterList').innerHTML=monsterCards(MONSTERS.filter(x=>x.name.toLocaleLowerCase('tr').includes(e.target.value.toLocaleLowerCase('tr'))))});
 $('#addMarket')?.addEventListener('click',()=>modal('Market ürünü',field('mkName','Ürün')+field('mkPrice','Fiyat')+field('mkStock','Stok','number',1)+'<button class="primary" id="saveMarket">Ekle</button>'));document.querySelectorAll('[data-delmarket]').forEach(b=>b.onclick=()=>{state.market.splice(+b.dataset.delmarket,1);save();render()});document.querySelectorAll('[data-marketgive]').forEach(b=>b.onclick=()=>{let idx=+b.dataset.marketgive;modal('Ürünü oyuncuya ver',`<label>Karakter<select id="giveMarketChar">${state.characters.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><button class="primary" id="confirmMarketGive" data-index="${idx}">Ver</button>`)});
 document.querySelectorAll('[data-die]').forEach(b=>b.onclick=()=>roll(+b.dataset.die));$('#searchGuide')?.addEventListener('click',searchGuide);$('#guideSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')searchGuide()});
}
document.addEventListener('click',e=>{
 if(e.target.id==='saveCharacter'){let old=state.characters.find(x=>x.id===e.target.dataset.id),c=old||{id:uid(),inventory:[],effects:[],skills:[],stats:{STR:10,DEX:10,CON:10,INT:10,WIS:10,CHA:10},tempHp:0,speed:30,pp:10};Object.assign(c,{name:$('#cName').value,userId:$('#cUser').value,species:$('#cSpecies').value,className:$('#cClass').value,level:+$('#cLevel').value,maxHp:+$('#cHp').value,hp:Math.min(c.hp??+$('#cHp').value,+$('#cHp').value),ac:+$('#cAc').value,guild:$('#cGuild').value});if(!old)state.characters.push(c);save();$('#modal').close();render()}
 if(e.target.id==='applyHp'){let c=state.characters.find(x=>x.id===e.target.dataset.id);c.hp=Math.max(0,Math.min(c.maxHp,c.hp+(+$('#hpAmount').value)));save();$('#modal').close();render()}
 if(e.target.id==='giveItem'){let c=state.characters.find(x=>x.id===e.target.dataset.id);c.inventory.push({name:$('#itemName').value,qty:+$('#itemQty').value||1,note:$('#itemNote').value});save();$('#modal').close();render()}
 if(e.target.id==='giveEffect'){let c=state.characters.find(x=>x.id===e.target.dataset.id),v=$('#customEffect').value||$('#effectName').value;if(v&&!c.effects.includes(v))c.effects.push(v);save();$('#modal').close();render()}
 if(e.target.id==='saveEncounter'){state.encounter.push({id:uid(),name:$('#eName').value,init:+$('#eInit').value,hp:+$('#eHp').value,ac:+$('#eAc').value,turn:!state.encounter.length});save();$('#modal').close();render()}
 if(e.target.id==='saveNpc'){let hp=+$('#nHp').value;state.npcs.push({id:uid(),name:$('#nName').value,role:$('#nRole').value,faction:$('#nFaction').value,hp,maxHp:hp,tempHp:0,ac:+$('#nAc').value,note:$('#nNote').value,inventory:[]});save();$('#modal').close();render()}
 if(e.target.id==='saveMarket'){state.market.push({id:uid(),name:$('#mkName').value,price:$('#mkPrice').value,stock:+$('#mkStock').value});save();$('#modal').close();render()}
 if(e.target.id==='confirmMarketGive'){let item=state.market[+e.target.dataset.index],c=state.characters.find(x=>x.id===$('#giveMarketChar').value);c.inventory.push({name:item.name,qty:1,note:'Market'});item.stock=Math.max(0,item.stock-1);save();$('#modal').close();render()}
});
function roll(sides){let count=+($('#diceCount')?.value||1),bonus=+($('#diceBonus')?.value||0),vals=Array.from({length:count},()=>1+Math.floor(Math.random()*sides)),total=vals.reduce((a,b)=>a+b,0)+bonus;let out=$('#rollout');if(out)out.innerHTML=`${total}<small>${vals.join(' + ')}${bonus?` ${bonus>0?'+':''}${bonus}`:''}</small>`;else alert('d'+sides+': '+total)}
async function searchGuide(){if(!guide)guide=await fetch('guide.txt').then(r=>r.text());let q=$('#guideSearch').value.trim(),low=guide.toLocaleLowerCase('tr'),needle=q.toLocaleLowerCase('tr'),hits=[],at=0;if(q.length<2)return;while((at=low.indexOf(needle,at))>=0&&hits.length<15){let s=Math.max(0,guide.lastIndexOf('\n',at-220)),en=guide.indexOf('\n',at+420);hits.push(guide.slice(s,en<0?at+420:en).trim());at+=needle.length}$('#guideResults').innerHTML=hits.map(h=>`<div class="guide-hit">${esc(h)}</div>`).join('')||'<div class="empty">Sonuç yok.</div>'}
$('#tabLogin').onclick=()=>{registerMode=false;$('#displayWrap').hidden=true;$('#tabLogin').classList.add('active');$('#tabRegister').classList.remove('active');$('#authSubmit').textContent='Kapıyı Aç'};$('#tabRegister').onclick=()=>{registerMode=true;$('#displayWrap').hidden=false;$('#tabRegister').classList.add('active');$('#tabLogin').classList.remove('active');$('#authSubmit').textContent='Hesap Oluştur'};
$('#authSubmit').onclick=async()=>{if(!db)return $('#authMsg').textContent='Supabase ayarı eksik';let fn=registerMode?'account_register':'account_login',args=registerMode?{p_username:$('#authUser').value,p_password:$('#authPass').value,p_display:$('#authDisplay').value}:{p_username:$('#authUser').value,p_password:$('#authPass').value};$('#authMsg').textContent='Bekle...';let {data,error}=await db.rpc(fn,args);if(error||!data?.length)return $('#authMsg').textContent=error?.message||'Kullanıcı adı veya şifre yanlış';auth={id:data[0].user_id,name:data[0].display_name};localStorage.setItem('kadim-auth',JSON.stringify(auth));await refreshCampaigns()};
$('#newCampaign').onclick=()=>modal('Macera Salonu',field('newCampName','Yeni kampanya adı')+'<button class="primary" id="createCampaign">DM olarak kur</button><hr>'+field('joinCampCode','Oda kodu')+'<button class="ghost" id="joinCampaign">Oyuncu olarak katıl</button>');document.addEventListener('click',async e=>{if(e.target.id==='lobbyCreate'||e.target.id==='createCampaign'){let name=$('#newCampName')?.value||prompt('Kampanya adı');if(!name)return;let {data,error}=await db.rpc('campaign_create_v2',{p_user:auth.id,p_name:name});if(error)return alert(error.message);$('#modal').close();await refreshCampaigns(data[0].campaign_id)}if(e.target.id==='lobbyJoin'||e.target.id==='joinCampaign'){let code=$('#lobbyCode')?.value||$('#joinCampCode')?.value;if(!code)return;let {data,error}=await db.rpc('campaign_join_v2',{p_user:auth.id,p_code:code});if(error||!data)return alert('Oda bulunamadı');$('#modal').close();await refreshCampaigns()}});
$('#campaignSelect').onchange=e=>loadCampaign(e.target.value);$('#nav').onclick=e=>{let b=e.target.closest('[data-page]');if(b){page=b.dataset.page;document.body.classList.remove('menu');render()}};$('#menu').onclick=()=>document.body.classList.toggle('menu');$('#quickRoll').onclick=()=>roll(20);$('#homeLink').onclick=e=>{e.preventDefault();showLobby()};$('#logoutBtn').onclick=()=>{localStorage.removeItem('kadim-auth');location.reload()};$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=(current?.name||'kampanya')+'-yedek.json';a.click()};
setInterval(async()=>{if(auth&&current){let id=current.id,old=page;let {data}=await db.rpc('campaign_load_v2',{p_user:auth.id,p_campaign:id});if(data?.[0]){state=normalized(data[0].state);members=data[0].members||members;page=old;render()}}},8000);
fetch('guide.txt').then(r=>r.text()).then(t=>guide=t);if(auth)refreshCampaigns();
