const KEY='ege-dm-guidebook-v1';
const fresh=()=>({active:0,campaigns:[{name:'İlk Kampanya',session:1,players:[],encounter:[],inventory:[],market:[{name:'Healing Potion',price:'50 gp',stock:3}],notes:'',quests:[],log:[]}]});
let data=JSON.parse(localStorage.getItem(KEY)||'null')||fresh(),page='dashboard',guide='',role='dm',room={code:'',password:'',cloud:false};
const cfg=window.DM_CONFIG||{},cloudReady=!!(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase),db=cloudReady?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=s=>document.querySelector(s), camp=()=>data.campaigns[data.active];
const navs=[['dashboard','⌂','Masa Özeti'],['session','✎','Oturum'],['encounter','⚔','Encounter'],['party','♙','Oyuncular'],['inventory','▣','Envanter'],['market','◇','DM Market'],['guide','⌕','Rehber Ara'],['dice','⬡','Zarlar']];
function save(){localStorage.setItem(KEY,JSON.stringify(data));$('#saveState').textContent=room.cloud?'● Buluta kaydediliyor':'● Cihaza kaydedildi';if(room.cloud&&role==='dm')db.rpc('room_save',{p_code:room.code,p_password:room.password,p_state:camp()}).then(({data:ok})=>{$('#saveState').textContent=ok?'● Buluta kaydedildi':'● Kayıt hatası'})}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderNav(){const allowed=role==='dm'?navs:navs.filter(n=>['dashboard','guide','dice'].includes(n[0]));$('#nav').innerHTML=allowed.map(n=>`<button data-page="${n[0]}" class="${page===n[0]?'active':''}">${n[1]}　${n[2]}</button>`).join('');$('#campaignSelect').innerHTML=data.campaigns.map((c,i)=>`<option value="${i}" ${i===data.active?'selected':''}>${esc(c.name)}</option>`).join('');$('#newCampaign').style.display=role==='dm'?'':'none';$('#roomBadge').textContent=room.code?`ODA: ${room.code} • ${room.cloud?'BULUT':'YEREL'}`:'YEREL KAYIT'}
function card(title,body,span=4){return `<section class="card span${span}"><h3>${title}</h3>${body}</section>`}
function dashboard(){const c=camp();return `<div class="grid">${card('Oturum',`<div class="stat">#${c.session}</div><p class="muted">${esc(c.name)}</p><button class="ghost" data-go="session">Hazırlığa git →</button>`)}${card('Parti',`<div class="stat">${c.players.length}</div><p class="muted">kayıtlı oyuncu</p><div class="progress"><i style="width:${Math.min(100,c.players.length*20)}%"></i></div>`)}${card('Aktif Encounter',`<div class="stat">${c.encounter.length}</div><p class="muted">sıradaki yaratık/oyuncu</p><button class="ghost" data-go="encounter">Takibi aç →</button>`)}${card('Hızlı Not',`<textarea id="notes" placeholder="NPC adı, ipucu, sonraki sahne...">${esc(c.notes)}</textarea>`,8)}${card('Açık Questler',`<div class="stack">${c.quests.map((q,i)=>`<div class="row between"><span>${esc(q)}</span><button class="danger" data-delquest="${i}">×</button></div>`).join('')||'<p class="muted">Henüz quest yok.</p>'}<div class="row"><input class="input" id="questName" placeholder="Yeni quest"><button class="ghost" id="addQuest">Ekle</button></div></div>`,4)}</div>`}
function session(){const c=camp();return `<div class="grid">${card('Oturum Kontrolü',`<div class="row"><button class="ghost" id="prevSession">−</button><div class="stat">#${c.session}</div><button class="ghost" id="nextSession">+</button></div><p class="notice">Hazırlık: güçlü açılış, 3 olası sahne, önemli NPC hedefi, ödül ve cliffhanger.</p>`,4)}${card('DM Not Defteri',`<textarea id="sessionNotes" style="min-height:360px" placeholder="Sahne akışı, gizli bilgiler, oyuncu kararları...">${esc(c.notes)}</textarea>`,8)}</div>`}
function encounter(){const c=camp();return `<div class="card"><div class="toolbar"><button class="primary" id="addCombatant">+ Savaşçı ekle</button><button class="ghost" id="sortInit">Initiative sırala</button><button class="ghost" id="nextTurn">Sonraki tur</button><button class="danger" id="clearEncounter">Temizle</button></div><div id="combatants">${c.encounter.map((x,i)=>`<div class="initiative-item ${x.turn?'active-turn':''}"><input class="input" data-e="init" data-i="${i}" value="${x.init}"><div><strong>${esc(x.name)}</strong><small class="muted"> ${esc(x.condition||'')}</small></div><input class="input hp" data-e="hp" data-i="${i}" value="${x.hp}"><span class="ac">AC ${x.ac}</span><button class="danger" data-delcombat="${i}">×</button></div>`).join('')||'<div class="empty">Encounter boş. Oyuncu veya yaratık ekle.</div>'}</div></div>`}
function party(){const c=camp();return `<div class="card"><div class="toolbar"><button class="primary" id="addPlayer">+ Oyuncu ekle</button></div><table><thead><tr><th>KARAKTER</th><th>SINIF</th><th>HP</th><th>AC</th><th>PP</th><th></th></tr></thead><tbody>${c.players.map((p,i)=>`<tr><td><strong>${esc(p.name)}</strong><br><small class="muted">${esc(p.player)}</small></td><td>${esc(p.class)}</td><td>${p.hp}</td><td>${p.ac}</td><td>${p.pp}</td><td><button class="danger" data-delplayer="${i}">×</button></td></tr>`).join('')}</tbody></table>${c.players.length?'':'<div class="empty">Partiyi ekleyerek başla.</div>'}</div>`}
function inventory(){const c=camp();return `<div class="card"><div class="toolbar"><input class="input" id="itemName" placeholder="Eşya / loot"><input class="input" id="itemOwner" placeholder="Sahibi"><input class="input" id="itemQty" type="number" value="1"><button class="primary" id="addItem">Ekle</button></div><table><thead><tr><th>EŞYA</th><th>SAHİP</th><th>ADET</th><th></th></tr></thead><tbody>${c.inventory.map((x,i)=>`<tr><td>${esc(x.name)}</td><td>${esc(x.owner)}</td><td>${x.qty}</td><td><button class="danger" data-delitem="${i}">×</button></td></tr>`).join('')}</tbody></table></div>`}
function market(){const c=camp();return `<div class="grid"><section class="card span8"><div class="toolbar"><button class="primary" id="addMarket">+ Ürün ekle</button></div><div class="stack">${c.market.map((x,i)=>`<div class="row between"><span><strong>${esc(x.name)}</strong><br><small class="muted">Stok: ${x.stock}</small></span><span class="pill">${esc(x.price)}</span><button class="danger" data-delmarket="${i}">×</button></div>`).join('')}</div></section>${card('Para Hızlı Referans','<p>10 cp = 1 sp<br>10 sp = 1 gp<br>10 gp = 1 pp</p><p class="muted">Fiyatları dünyana ve bölgeye göre ayarla.</p>',4)}</div>`}
function dice(){return `<div class="grid">${card('Zar Havuzu',`<div class="dice">${[4,6,8,10,12,20,100].map(d=>`<button data-die="${d}">d${d}</button>`).join('')}</div><div class="rollout" id="rollout">—</div><div class="row"><input class="input" id="diceCount" type="number" min="1" max="20" value="1"><input class="input" id="diceBonus" type="number" value="0"></div>`,8)}${card('DC Referansı','<p>5 — Çok kolay</p><p>10 — Kolay</p><p>15 — Orta</p><p>20 — Zor</p><p>25 — Çok zor</p><p>30 — Olağanüstü</p>',4)}</div>`}
function guideView(){return `<div class="card"><div class="toolbar"><input class="input" id="guideSearch" placeholder="Örn: grapple, concentration, DC, exhaustion..."><button class="primary" id="searchGuide">Ara</button></div><p class="muted">Gönderdiğin 31 sayfalık Türkçe D&D 5e (2024) DM rehberinde arar.</p><div id="guideResults" class="guide-results"><div class="empty">Bir kural veya kavram ara.</div></div></div>`}
const pages={dashboard,session,encounter,party,inventory,market,guide:guideView,dice};
function render(){renderNav();$('#pageTitle').textContent=navs.find(n=>n[0]===page)[2];$('#view').innerHTML=pages[page]();bind()}
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').showModal()}
function field(id,label,type='text'){return `<label>${label}<input class="input" id="${id}" type="${type}"></label>`}
function bind(){const c=camp();document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{page=x.dataset.go;render()});
 $('#notes')?.addEventListener('input',e=>{c.notes=e.target.value;save()});$('#sessionNotes')?.addEventListener('input',e=>{c.notes=e.target.value;save()});
 $('#addQuest')?.addEventListener('click',()=>{if($('#questName').value)c.quests.push($('#questName').value),save(),render()});document.querySelectorAll('[data-delquest]').forEach(x=>x.onclick=()=>{c.quests.splice(+x.dataset.delquest,1);save();render()});
 $('#prevSession')?.addEventListener('click',()=>{c.session=Math.max(1,c.session-1);save();render()});$('#nextSession')?.addEventListener('click',()=>{c.session++;save();render()});
 $('#addCombatant')?.addEventListener('click',()=>modal('Savaşçı ekle',field('mName','Ad')+field('mInit','Initiative','number')+field('mHp','HP','number')+field('mAc','AC','number')+'<button class="primary" id="confirmCombat">Ekle</button>'));$('#sortInit')?.addEventListener('click',()=>{c.encounter.sort((a,b)=>b.init-a.init);save();render()});$('#clearEncounter')?.addEventListener('click',()=>{c.encounter=[];save();render()});$('#nextTurn')?.addEventListener('click',()=>{if(!c.encounter.length)return;let i=c.encounter.findIndex(x=>x.turn);c.encounter.forEach(x=>x.turn=false);c.encounter[(i+1)%c.encounter.length].turn=true;save();render()});
 document.querySelectorAll('[data-delcombat]').forEach(x=>x.onclick=()=>{c.encounter.splice(+x.dataset.delcombat,1);save();render()});document.querySelectorAll('[data-e]').forEach(x=>x.onchange=()=>{c.encounter[+x.dataset.i][x.dataset.e]=+x.value;save()});
 $('#addPlayer')?.addEventListener('click',()=>modal('Oyuncu ekle',field('pName','Karakter')+field('pPlayer','Oyuncu')+field('pClass','Sınıf / Level')+field('pHp','HP','number')+field('pAc','AC','number')+field('pPp','Passive Perception','number')+'<button class="primary" id="confirmPlayer">Ekle</button>'));document.querySelectorAll('[data-delplayer]').forEach(x=>x.onclick=()=>{c.players.splice(+x.dataset.delplayer,1);save();render()});
 $('#addItem')?.addEventListener('click',()=>{if($('#itemName').value)c.inventory.push({name:$('#itemName').value,owner:$('#itemOwner').value,qty:+$('#itemQty').value}),save(),render()});document.querySelectorAll('[data-delitem]').forEach(x=>x.onclick=()=>{c.inventory.splice(+x.dataset.delitem,1);save();render()});
 $('#addMarket')?.addEventListener('click',()=>modal('Market ürünü',field('shopName','Ürün')+field('shopPrice','Fiyat')+field('shopStock','Stok','number')+'<button class="primary" id="confirmMarket">Ekle</button>'));document.querySelectorAll('[data-delmarket]').forEach(x=>x.onclick=()=>{c.market.splice(+x.dataset.delmarket,1);save();render()});
 document.querySelectorAll('[data-die]').forEach(x=>x.onclick=()=>roll(+x.dataset.die));$('#searchGuide')?.addEventListener('click',searchGuide);$('#guideSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')searchGuide()})}
function roll(sides,count=+($('#diceCount')?.value||1),bonus=+($('#diceBonus')?.value||0)){let vals=Array.from({length:count},()=>1+Math.floor(Math.random()*sides)),total=vals.reduce((a,b)=>a+b,0)+bonus;const out=$('#rollout');if(out)out.innerHTML=`${total}<small class="muted" style="display:block;font-size:12px">${vals.join(' + ')}${bonus?` ${bonus>0?'+':''}${bonus}`:''}</small>`;else alert(`d${sides}: ${total}`)}
async function searchGuide(){if(!guide)guide=await fetch('guide.txt').then(r=>r.text());let q=$('#guideSearch').value.trim();if(q.length<2)return;let low=guide.toLocaleLowerCase('tr'),needle=q.toLocaleLowerCase('tr'),hits=[],at=0;while((at=low.indexOf(needle,at))>=0&&hits.length<12){let start=Math.max(0,guide.lastIndexOf('\n',at-180)),end=Math.min(guide.length,guide.indexOf('\n',at+300));hits.push(guide.slice(start,end).trim());at+=needle.length}$('#guideResults').innerHTML=hits.length?hits.map(h=>`<div class="guide-hit">${esc(h).replace(new RegExp(esc(q),'gi'),m=>`<mark>${m}</mark>`)}</div>`).join(''):'<div class="empty">Sonuç bulunamadı.</div>'}
document.addEventListener('click',e=>{if(e.target.matches('#confirmCombat')){let c=camp();c.encounter.push({name:$('#mName').value,init:+$('#mInit').value,hp:+$('#mHp').value,ac:+$('#mAc').value,condition:'',turn:!c.encounter.length});save();$('#modal').close();render()}if(e.target.matches('#confirmPlayer')){camp().players.push({name:$('#pName').value,player:$('#pPlayer').value,class:$('#pClass').value,hp:+$('#pHp').value,ac:+$('#pAc').value,pp:+$('#pPp').value});save();$('#modal').close();render()}if(e.target.matches('#confirmMarket')){camp().market.push({name:$('#shopName').value,price:$('#shopPrice').value,stock:+$('#shopStock').value});save();$('#modal').close();render()}});
$('#nav').onclick=e=>{let b=e.target.closest('[data-page]');if(b){page=b.dataset.page;document.body.classList.remove('menu');render()}};$('#menu').onclick=()=>document.body.classList.toggle('menu');$('#quickRoll').onclick=()=>roll(20);$('#campaignSelect').onchange=e=>{data.active=+e.target.value;save();render()};$('#newCampaign').onclick=()=>{let n=prompt('Kampanya adı');if(n){data.campaigns.push({...fresh().campaigns[0],name:n});data.active=data.campaigns.length-1;save();render()}};
$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='dm-guidebook-yedek.json';a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=e=>{let r=new FileReader;r.onload=()=>{try{data=JSON.parse(r.result);save();render()}catch{alert('Geçersiz yedek dosyası')}};r.readAsText(e.target.files[0])};
function playerDashboard(){const c=camp();return `<div class="grid">${card('Macera',`<div class="stat">${esc(c.name)}</div><p class="muted">Oda kodu: ${esc(room.code)}</p><p class="notice">Masaya bağlandın. Zarlarını atabilir ve rehberde arama yapabilirsin.</p>`,8)}${card('Parti',`<div class="stat">${c.players?.length||0}</div><p class="muted">kayıtlı maceracı</p>`,4)}${card('Karakter Zarları','<button class="primary" data-go="dice">Zar havuzunu aç</button>',4)}${card('Kural Arama','<button class="ghost" data-go="guide">Rehberde ara</button>',4)}</div>`}
const dmDashboard=pages.dashboard;pages.dashboard=()=>role==='player'?playerDashboard():dmDashboard();
function enterApp(){document.body.classList.remove('landing-mode');page='dashboard';render()}
$('#homeLink').onclick=e=>{e.preventDefault();document.body.classList.add('landing-mode')};
$('#continueLocal').textContent='DM Paneline Gir →';$('#continueLocal').onclick=()=>modal('DM Girişi',field('dmCode','Oda kodu (yerel kayıt için boş bırak)')+field('dmPass','DM şifresi','password')+'<p class="muted">Varsayılan demo şifresi: 123123</p><button class="primary" id="localLogin">Panele gir</button>');
$('#createRoom').onclick=()=>modal('Yeni Kampanya',field('roomName','Kampanya adı')+`<label>DM şifresi<input class="input" id="roomPass" type="password" value="${esc(cfg.DEFAULT_DM_PASSWORD||'123123')}"></label><p class="muted">Bu şifreyi değiştir. 123123 yalnızca demo içindir.</p><button class="primary" id="confirmRoom">Odayı kur</button>`);
$('#joinRoom').onclick=()=>modal('Odaya Katıl',field('joinCode','6 haneli oda kodu')+field('joinName','Oyuncu / karakter adı')+'<button class="primary" id="confirmJoin">Masaya otur</button>');
document.addEventListener('click',async e=>{
 if(e.target.matches('#localLogin')){e.preventDefault();let code=$('#dmCode').value.trim().toUpperCase(),password=$('#dmPass').value;if(code&&cloudReady){let {data:ok}=await db.rpc('room_dm_login',{p_code:code,p_password:password});if(!ok)return alert('Kod veya DM şifresi yanlış');let {data:r}=await db.rpc('room_join',{p_code:code});data={active:0,campaigns:[r[0].state]};role='dm';room={code,password,cloud:true};localStorage.setItem('dm-room-meta',JSON.stringify(room))}else{if(password!==(cfg.DEFAULT_DM_PASSWORD||'123123'))return alert('Yanlış yerel DM şifresi');role='dm';room=JSON.parse(localStorage.getItem('dm-room-meta')||'{"code":"LOCAL","cloud":false}');room.password=password}$('#modal').close();enterApp()}
 if(e.target.matches('#confirmRoom')){e.preventDefault();let name=$('#roomName').value.trim(),password=$('#roomPass').value;if(!name||!password)return alert('Ad ve şifre gerekli');data=fresh();data.campaigns[0].name=name;role='dm';if(cloudReady){let {data:r,error}=await db.rpc('room_create',{p_name:name,p_password:password,p_state:data.campaigns[0]});if(error)return alert('Oda kurulamadı: '+error.message);room={code:r[0].code,password,cloud:true}}else room={code:'L'+Math.random().toString(36).slice(2,7).toUpperCase(),password,cloud:false};localStorage.setItem('dm-room-meta',JSON.stringify(room));save();$('#modal').close();enterApp();if(!cloudReady)alert('Yerel demo odası kuruldu. Farklı telefonlar için config.js dosyasına Supabase bilgilerini ekle.')}
 if(e.target.matches('#confirmJoin')){e.preventDefault();let code=$('#joinCode').value.trim().toUpperCase(),name=$('#joinName').value.trim();if(!code||!name)return alert('Kod ve ad gerekli');if(!cloudReady)return alert('Telefonlar arası oda için önce Supabase kurulumu gerekli. README dosyasındaki adımları uygula.');let {data:r,error}=await db.rpc('room_join',{p_code:code});if(error||!r?.length)return alert('Oda bulunamadı');await db.rpc('player_join',{p_code:code,p_name:name,p_data:{joined:true}});data={active:0,campaigns:[r[0].state]};role='player';room={code,password:'',cloud:true};$('#modal').close();enterApp()}
});
setInterval(async()=>{if(!room.cloud||!db)return;if(role==='player'){let {data:r}=await db.rpc('room_join',{p_code:room.code});if(r?.[0]){data.campaigns[0]=r[0].state;render()}}else{let {data:list}=await db.rpc('room_players',{p_code:room.code});if(list){let c=camp(),known=new Map((c.players||[]).map(p=>[p.player,p]));list.forEach(x=>{if(!known.has(x.name))c.players.push({name:x.name,player:x.name,class:'Maceracı',hp:1,ac:10,pp:10})});render()}}},5000);
fetch('guide.txt').then(r=>r.text()).then(t=>guide=t).catch(()=>{});render();
