function iaBonuses(x={}){let out=[];for(let [k,n] of [['magicBonus','Büyü'],['acBonus','AC'],['attackBonus','Saldırı'],['damageBonus','Hasar'],['saveBonus','Save']])if(Number(x[k]))out.push(`${n} ${Number(x[k])>0?'+':''}${x[k]}`);if(x.bonuses&&typeof x.bonuses==='object')for(let [k,v] of Object.entries(x.bonuses))out.push(`${k} ${Number(v)>0?'+':''}${v}`);if(x.strRequirement)out.push(`STR ${x.strRequirement} altındaysa hız -10 ft`);if(x.stealthDisadvantage)out.push('Stealth dezavantajı');return out}
function iaItem(x,i,actions=false){let bonuses=iaBonuses(x),detail=[x.note,x.effect,...bonuses].filter(Boolean).join(' • '),equip=window.v25CanEquip?.(x);return `<article class="ia-item"><button class="ia-summary" data-ia-expand="${i}" aria-expanded="false"><span><b>${esc(x.name||'İsimsiz eşya')}</b><small>${esc(detail||'Özel bilgi yok')}</small>${x.equipped?'<em>KUŞANILMIŞ</em>':''}</span><strong>×${Math.max(1,+x.qty||1)}　⌄</strong></button>${actions?`<div class="ia-actions" data-ia-panel="${i}" hidden>${equip?`<button class="primary" data-v25-equip="${i}">${x.equipped?'Çıkar':'Kuşan'}</button>`:''}<button class="ghost" data-ia-player="${i}">Arkadaşa Ver</button><button class="ghost" data-ia-guild="${i}">Loncaya Koy</button><button class="ghost" data-ia-drop="${i}">Yere At</button><button class="danger" data-v25-trash="${i}">Çöpe At</button></div>`:''}</article>`}
function iaGround(canTake=true){let list=state.groundLoot||[];return `<section class="card ia-ground"><div><small>ORTAK ALAN</small><h3>Yerdeki Eşyalar</h3></div>${list.map((x,i)=>`${iaItem(x,i,false)}${canTake?`<button class="ghost ia-take" data-ia-take="${i}">Yerden Al</button>`:''}`).join('')||'<div class="empty">Yerde eşya yok.</div>'}</section>`}
function iaInventory(){if(typeof sessionPending==='function'&&sessionPending())return sessionPendingPage();let c=myChar();return c?`<div class="ia-layout"><section class="card"><h3>${esc(c.name)} — Envanter</h3><p class="muted">Eşyanın bonusları, efektleri ve tüm özellikleri transfer sırasında aynen korunur.</p>${c.inventory.map((x,i)=>iaItem(x,i,true)).join('')||'<div class="empty">Çanta boş.</div>'}</section>${iaGround(true)}</div>`:playerDash()}
const iaBasePlayerGuild=playerPages.guild,iaBaseDmGuild=dmPages.guilddm;
playerPages.inventory=iaInventory;
playerPages.guild=()=>{if(typeof sessionPending==='function'&&sessionPending())return sessionPendingPage();return `${iaBasePlayerGuild()}${iaGround(true)}`};
dmPages.guilddm=()=>`${iaBaseDmGuild()}${iaGround(false)}`;
function iaMoveModal(index,destination){let item=myChar()?.inventory?.[index];if(!item)return;let players=members.filter(x=>x.role==='player'&&x.userId!==auth.id),itemId=window.v31ItemKey?.(item,'inventory')||item.id||'';modal(destination==='player'?'Eşyayı oyuncuya ver':destination==='guild'?'Lonca envanterine koy':'Eşyayı yere at',`<div class="ia-preview">${iaItem(item,index,false)}</div>${destination==='player'?`<label>Alıcı<select id="iaTarget">${players.map(x=>`<option value="${x.userId}">${esc(x.name)}</option>`).join('')}</select></label>`:''}<label>Adet<input id="iaQuantity" type="number" min="1" max="${Math.max(1,+item.qty||1)}" value="1"></label><button id="iaConfirmMove" class="${destination==='ground'?'danger':'primary'}" data-index="${index}" data-item-id="${esc(itemId)}" data-item-name="${esc(item.name||'')}" data-destination="${destination}" ${destination==='player'&&!players.length?'disabled':''}>${destination==='ground'?'Yere At':destination==='guild'?'Loncaya Koy':'Oyuncuya Ver'}</button>${destination==='player'&&!players.length?'<p class="pact-error">Eşyayı verebileceğin başka oyuncu yok.</p>':''}`)}
async function iaRefresh(message){$('#modal')?.close();await syncFromServer(false);if(realtimeChannel)realtimeChannel.send({type:'broadcast',event:'campaign-changed',payload:{campaignId:current.id,at:Date.now()}});render();toast(message)}
document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b||!current)return;
 if(current.role==='dm'&&b.dataset.item&&state.characters.some(c=>c.id===b.dataset.item)){e.preventDefault();e.stopImmediatePropagation();modal('Bonuslu eşya ekle',field('iaItemName','Eşya')+field('iaItemQty','Adet','number',1)+field('iaItemNote','Açıklama')+field('iaItemEffect','Etki / tür')+field('iaItemAc','AC bonusu','number',0)+field('iaItemAttack','Saldırı bonusu','number',0)+field('iaItemDamage','Hasar bonusu','number',0)+field('iaItemMagic','Büyü bonusu','number',0)+`<button class="primary" id="iaGiveRichItem" data-id="${b.dataset.item}">Eşyayı Ver</button>`);return}
 if(current.role==='dm'&&b.id==='iaGiveRichItem'){e.preventDefault();e.stopImmediatePropagation();let c=state.characters.find(x=>x.id===b.dataset.id);if(!c)return;c.inventory.push({id:uid(),name:$('#iaItemName').value,qty:Math.max(1,+$('#iaItemQty').value||1),note:$('#iaItemNote').value,effect:$('#iaItemEffect').value,acBonus:+$('#iaItemAc').value||0,attackBonus:+$('#iaItemAttack').value||0,damageBonus:+$('#iaItemDamage').value||0,magicBonus:+$('#iaItemMagic').value||0});save();$('#modal').close();render();toast('Eşya bütün bonuslarıyla verildi');return}
 if(current.role==='dm'&&b.id==='confirmMarketGive'){e.preventDefault();e.stopImmediatePropagation();let item=state.market[+b.dataset.index],c=state.characters.find(x=>x.id===$('#giveMarketChar').value);if(!item||!c)return;let gifted={...item,id:uid(),sourceItemId:item.id,qty:1};for(let k of ['stock','active','shop','priceCopper','tier','ready','custom'])delete gifted[k];c.inventory.push(gifted);item.stock=Math.max(0,(+item.stock||0)-1);save();$('#modal').close();render();toast('Market eşyası tüm özellikleriyle verildi');return}
 if(current.role!=='player')return;
 if(b.dataset.iaPlayer!=null)iaMoveModal(+b.dataset.iaPlayer,'player'); if(b.dataset.iaGuild!=null)iaMoveModal(+b.dataset.iaGuild,'guild'); if(b.dataset.iaDrop!=null)iaMoveModal(+b.dataset.iaDrop,'ground');
 if(b.id==='iaConfirmMove'){let quantity=Math.floor(+($('#iaQuantity')?.value||0)),destination=b.dataset.destination,target=destination==='player'?$('#iaTarget')?.value:null;if(quantity<1)return alert('Adet en az 1 olmalı.');b.disabled=true;let rpcName=destination==='guild'?'inventory_move_v32':'inventory_move_v31';let {error}=await db.rpc(rpcName,{p_user:auth.id,p_campaign:current.id,p_item_index:+b.dataset.index,p_expected_id:b.dataset.itemId||'',p_expected_name:b.dataset.itemName||'',p_quantity:quantity,p_destination:destination,p_target:target});if(error){b.disabled=false;return alert('Eşya taşınamadı: '+error.message+`\n\n${destination==='guild'?'v32-update.sql':'v31-update.sql'} dosyasını çalıştırdığından emin ol.`)}if(destination==='guild')window.v32InvalidateGuildActivity?.();await iaRefresh(destination==='ground'?'Eşya yere bırakıldı':destination==='guild'?'Eşya loncaya kondu':'Eşya oyuncuya verildi')}
 if(b.dataset.iaTake!=null){let item=(state.groundLoot||[])[+b.dataset.iaTake];if(!item)return;let max=Math.max(1,+item.qty||1),quantity=max===1?1:Math.floor(+(prompt(`Kaç adet ${item.name} alınsın?`,String(max))||0));if(quantity<1||quantity>max)return alert('Geçerli bir adet gir.');b.disabled=true;let {error}=await db.rpc('inventory_take_ground_v31',{p_user:auth.id,p_campaign:current.id,p_ground_index:+b.dataset.iaTake,p_expected_id:window.v31ItemKey?.(item,'ground')||item.groundId||item.id||'',p_expected_name:item.name||'',p_quantity:quantity});if(error){b.disabled=false;return alert('Eşya alınamadı: '+error.message+'\n\nv31-update.sql dosyasını çalıştırdığından emin ol.')}await iaRefresh('Eşya envantere alındı')}
},true);
if(auth&&current)render();
