-- Kadim Masa Defteri v19: oyuncu karakter oluşturma ve tek seferlik subclass seçimi.
-- Mevcut hesap, kampanya ve karakter kayıtlarını silmez.

create table if not exists public.dice_rolls (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  user_id uuid not null references public.accounts(id) on delete cascade,
  roller_name text not null,
  formula text not null,
  rolls integer[] not null default '{}',
  bonus integer not null default 0,
  total integer not null,
  created_at timestamptz not null default now()
);

create index if not exists dice_rolls_campaign_time_idx on public.dice_rolls(campaign_id,created_at desc);
alter table public.dice_rolls enable row level security;

create or replace function public.dice_roll_add(p_user uuid,p_campaign uuid,p_roller_name text,p_formula text,p_rolls integer[],p_bonus integer,p_total integer)
returns bigint language plpgsql security definer set search_path=public as $$
declare rid bigint;
begin
  if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user) then raise exception 'Bu kampanyaya üye değilsin'; end if;
  insert into dice_rolls(campaign_id,user_id,roller_name,formula,rolls,bonus,total)
  values(p_campaign,p_user,left(coalesce(nullif(trim(p_roller_name),''),'Bilinmeyen'),80),left(p_formula,40),p_rolls,p_bonus,p_total)
  returning id into rid;
  return rid;
end $$;

create or replace function public.dice_roll_list(p_user uuid,p_campaign uuid,p_limit integer default 50)
returns table(id bigint,user_id uuid,roller_name text,formula text,rolls integer[],bonus integer,total integer,created_at timestamptz)
language sql security definer set search_path=public as $$
 select d.id,d.user_id,d.roller_name,d.formula,d.rolls,d.bonus,d.total,d.created_at
 from dice_rolls d
 where d.campaign_id=p_campaign
   and exists(select 1 from campaign_members m where m.campaign_id=p_campaign and m.user_id=p_user)
 order by d.created_at desc limit greatest(1,least(coalesce(p_limit,50),200))
$$;

create or replace function public.dice_roll_clear(p_user uuid,p_campaign uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user and role='dm') then raise exception 'Yalnızca DM zar günlüğünü temizleyebilir'; end if;
 delete from dice_rolls where campaign_id=p_campaign;
 return true;
end $$;

create or replace function public.character_choices_set(p_user uuid,p_campaign uuid,p_subclass text,p_subspecies text,p_spells jsonb)
returns boolean language plpgsql security definer set search_path=public as $$
declare st jsonb; idx integer; ch jsonb; lvl integer;
begin
 if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user and role='player') then raise exception 'Bu kampanyada oyuncu değilsin'; end if;
 select state into st from campaigns where id=p_campaign for update;
 select (e.ordinality-1)::integer,e.value into idx,ch
 from jsonb_array_elements(coalesce(st->'characters','[]'::jsonb)) with ordinality e(value,ordinality)
 where e.value->>'userId'=p_user::text limit 1;
 if idx is null then raise exception 'Hesabına bağlı karakter yok'; end if;
 lvl:=coalesce((ch->>'level')::integer,1);
 if lvl<3 and coalesce(trim(p_subclass),'')<>'' then raise exception 'Subclass 3. seviyede açılır'; end if;
 if coalesce(ch->>'subclass','')<>'' and trim(coalesce(p_subclass,''))<>ch->>'subclass' then raise exception 'Subclass seçimi kilitli; yalnızca DM değiştirebilir'; end if;
 if coalesce(ch->>'subclass','')='' and lvl>=3 and coalesce(trim(p_subclass),'')<>'' then
   st:=jsonb_set(st,array['characters',idx::text,'subclass'],to_jsonb(trim(p_subclass)),true);
 end if;
 st:=jsonb_set(st,array['characters',idx::text,'preparedSpells'],coalesce(p_spells,'[]'::jsonb),true);
 update campaigns set state=st,updated_at=now() where id=p_campaign;
 return true;
end $$;

create or replace function public.character_create_player(
 p_user uuid,p_campaign uuid,p_name text,p_species text,p_subspecies text,p_class_name text,
 p_base_stats jsonb,p_max_hp integer,p_ac integer
) returns boolean language plpgsql security definer set search_path=public,extensions as $$
declare st jsonb; new_character jsonb;
begin
 if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user and role='player') then raise exception 'Bu kampanyada oyuncu değilsin'; end if;
 if length(trim(coalesce(p_name,'')))<2 then raise exception 'Karakter adı en az 2 karakter olmalı'; end if;
 select state into st from campaigns where id=p_campaign for update;
 if exists(select 1 from jsonb_array_elements(coalesce(st->'characters','[]'::jsonb)) c where c->>'userId'=p_user::text) then raise exception 'Bu kampanyada zaten bir karakterin var'; end if;
 new_character:=jsonb_build_object(
  'id',gen_random_uuid()::text,'userId',p_user::text,'name',left(trim(p_name),60),
  'species',left(trim(coalesce(p_species,'Human')),80),'subspecies',left(trim(coalesce(p_subspecies,'')),100),
  'className',left(trim(coalesce(p_class_name,'Fighter')),80),'subclass','','level',1,
  'baseStats',coalesce(p_base_stats,'{}'::jsonb),'stats',coalesce(p_base_stats,'{}'::jsonb),'statOverrides','{}'::jsonb,
  'maxHp',greatest(1,least(coalesce(p_max_hp,10),100)),'hp',greatest(1,least(coalesce(p_max_hp,10),100)),
  'ac',greatest(0,least(coalesce(p_ac,10),30)),'autoVitals',true,'tempHp',0,'speed',30,'pp',10,
  'guild','','inventory','[]'::jsonb,'effects','[]'::jsonb,'skills','[]'::jsonb,'preparedSpells','[]'::jsonb,
  'resistances','[]'::jsonb,'weaknesses','[]'::jsonb
 );
 st:=jsonb_set(st,'{characters}',coalesce(st->'characters','[]'::jsonb)||jsonb_build_array(new_character),true);
 update campaigns set state=st,updated_at=now() where id=p_campaign;
 return true;
end $$;

revoke all on function public.dice_roll_add(uuid,uuid,text,text,integer[],integer,integer),public.dice_roll_list(uuid,uuid,integer),public.dice_roll_clear(uuid,uuid),public.character_choices_set(uuid,uuid,text,text,jsonb),public.character_create_player(uuid,uuid,text,text,text,text,jsonb,integer,integer) from public;
grant execute on function public.dice_roll_add(uuid,uuid,text,text,integer[],integer,integer),public.dice_roll_list(uuid,uuid,integer),public.dice_roll_clear(uuid,uuid),public.character_choices_set(uuid,uuid,text,text,jsonb),public.character_create_player(uuid,uuid,text,text,text,text,jsonb,integer,integer) to anon,authenticated;
