-- Kadim Masa Defteri v17: oyuncuların kalıcı ve ortak zar günlüğü.
-- Mevcut hesap, kampanya ve karakter kayıtlarını silmez.

create table if not exists public.dice_rolls (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  user_id uuid not null references public.accounts(id) on delete cascade,
  roller_name text not null,
  formula text not null,
  rolls integer[] not null default '{}',
  bonus integer not null default 0,
  total integer not null,
  created_at timestamptz not null default now()
);

create index if not exists dice_rolls_campaign_time_idx on public.dice_rolls(campaign_id,created_at desc);
alter table public.dice_rolls enable row level security;

create or replace function public.dice_roll_add(p_user uuid,p_campaign uuid,p_roller_name text,p_formula text,p_rolls integer[],p_bonus integer,p_total integer)
returns bigint language plpgsql security definer set search_path=public as $$
declare rid bigint;
begin
  if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user) then raise exception 'Bu kampanyaya üye değilsin'; end if;
  insert into dice_rolls(campaign_id,user_id,roller_name,formula,rolls,bonus,total)
  values(p_campaign,p_user,left(coalesce(nullif(trim(p_roller_name),''),'Bilinmeyen'),80),left(p_formula,40),p_rolls,p_bonus,p_total)
  returning id into rid;
  return rid;
end $$;

create or replace function public.dice_roll_list(p_user uuid,p_campaign uuid,p_limit integer default 50)
returns table(id bigint,user_id uuid,roller_name text,formula text,rolls integer[],bonus integer,total integer,created_at timestamptz)
language sql security definer set search_path=public as $$
 select d.id,d.user_id,d.roller_name,d.formula,d.rolls,d.bonus,d.total,d.created_at
 from dice_rolls d
 where d.campaign_id=p_campaign
   and exists(select 1 from campaign_members m where m.campaign_id=p_campaign and m.user_id=p_user)
 order by d.created_at desc limit greatest(1,least(coalesce(p_limit,50),200))
$$;

create or replace function public.dice_roll_clear(p_user uuid,p_campaign uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from campaign_members where campaign_id=p_campaign and user_id=p_user and role='dm') then raise exception 'Yalnızca DM zar günlüğünü temizleyebilir'; end if;
 delete from dice_rolls where campaign_id=p_campaign;
 return true;
end $$;

revoke all on function public.dice_roll_add(uuid,uuid,text,text,integer[],integer,integer),public.dice_roll_list(uuid,uuid,integer),public.dice_roll_clear(uuid,uuid) from public;
grant execute on function public.dice_roll_add(uuid,uuid,text,text,integer[],integer,integer),public.dice_roll_list(uuid,uuid,integer),public.dice_roll_clear(uuid,uuid) to anon,authenticated;
