const V25_SKILLS={
 'Serbest d20':null,'Athletics (Atletizm)':'STR','Acrobatics (Akrobasi)':'DEX','Sleight of Hand (El Çabukluğu)':'DEX','Stealth (Gizlilik)':'DEX','Arcana (Gizem)':'INT','History (Tarih)':'INT','Investigation (Araştırma)':'INT','Nature (Doğa)':'INT','Religion (Din)':'INT','Animal Handling (Hayvan İdaresi)':'WIS','Insight (Sezgi)':'WIS','Medicine (Tıp)':'WIS','Perception (Farkındalık)':'WIS','Survival (Hayatta Kalma)':'WIS','Deception (Aldatma)':'CHA','Intimidation (Gözdağı)':'CHA','Performance (Gösteri)':'CHA','Persuasion (İkna)':'CHA','Initiative (İnisiyatif)':'DEX','STR Saving Throw':'STR','DEX Saving Throw':'DEX','CON Saving Throw':'CON','INT Saving Throw':'INT','WIS Saving Throw':'WIS','CHA Saving Throw':'CHA','Yakın saldırı (STR)':'STR','Menzilli/Finesse saldırı (DEX)':'DEX','Büyü saldırısı':'CAST'
};
const V25_CLASS_SKILLS={Barbarian:['Athletics (Atletizm)','Survival (Hayatta Kalma)'],Bard:['Persuasion (İkna)','Performance (Gösteri)','Insight (Sezgi)'],Cleric:['Religion (Din)','Insight (Sezgi)','Medicine (Tıp)'],Druid:['Nature (Doğa)','Animal Handling (Hayvan İdaresi)','Perception (Farkındalık)'],Fighter:['Athletics (Atletizm)','Perception (Farkındalık)'],Monk:['Acrobatics (Akrobasi)','Insight (Sezgi)','Stealth (Gizlilik)'],Paladin:['Athletics (Atletizm)','Persuasion (İkna)','Intimidation (Gözdağı)'],Ranger:['Survival (Hayatta Kalma)','Perception (Farkındalık)','Stealth (Gizlilik)'],Rogue:['Stealth (Gizlilik)','Sleight of Hand (El Çabukluğu)','Investigation (Araştırma)'],Sorcerer:['Arcana (Gizem)','Persuasion (İkna)'],Warlock:['Arcana (Gizem)','Deception (Aldatma)','Intimidation (Gözdağı)'],Wizard:['Arcana (Gizem)','History (Tarih)','Investigation (Araştırma)'],Artificer:['Arcana (Gizem)','Investigation (Araştırma)'],Psion:['Arcana (Gizem)','Insight (Sezgi)']};
const V25_ARMOR={
 'ex-leather':{slot:'armor',armorType:'light',armorBase:11},'ex-studded':{slot:'armor',armorType:'light',armorBase:12},'ex-padded':{slot:'armor',armorType:'light',armorBase:11,stealthDisadvantage:true},'ex-hide':{slot:'armor',armorType:'medium',armorBase:12},'ex-chain-shirt':{slot:'armor',armorType:'medium',armorBase:13},'ex-scale-mail':{slot:'armor',armorType:'medium',armorBase:14,stealthDisadvantage:true},'ex-breastplate':{slot:'armor',armorType:'medium',armorBase:14},'ex-chain-mail':{slot:'armor',armorType:'heavy',armorBase:16,strRequirement:13,stealthDisadvantage:true},'ex-splint':{slot:'armor',armorType:'heavy',armorBase:17,strRequirement:15,stealthDisadvantage:true},'ex-plate':{slot:'armor',armorType:'heavy',armorBase:18,strRequirement:15,stealthDisadvantage:true},'ex-adamantine-plate':{slot:'armor',armorType:'heavy',armorBase:18,strRequirement:15},'ex-shield':{slot:'shield',acBonus:2},'ex-sentinel-shield':{slot:'shield',acBonus:2},'ex-spellguard-shield':{slot:'shield',acBonus:2},'ex-animated-shield':{slot:'shield',acBonus:2},'ex-tower-shield':{slot:'shield',acBonus:2}
};
function v25HydrateItem(x={}){let key=x.sourceItemId||x.id,meta=V25_ARMOR[key];if(meta)Object.assign(x,Object.fromEntries(Object.entries(meta).filter(([k])=>x[k]==null)));if(!x.id)x.id=uid();return x}
function v25CanEquip(x){v25HydrateItem(x);return !!(x.slot||x.armorBase!=null||x.acBonus||x.attackBonus||x.damageBonus||x.magicBonus||x.statBonuses||x.bonuses)}
window.v25CanEquip=v25CanEquip;
function v25Equipped(c){return (c?.inventory||[]).filter(x=>x.equipped).map(v25HydrateItem)}
const v25BasePrStats=prStats;
prStats=function(c){let s=v25BasePrStats(c);for(let item of v25Equipped(c)){let b=item.statBonuses||item.bonuses||{};for(let k of PR_ABILITIES)if(Number(b[k]))s[k]=Math.min(30,s[k]+Number(b[k]))}return s};
prAutoAC=function(c){let s=prStats(c),dex=prMod(s.DEX),con=prMod(s.CON),wis=prMod(s.WIS),items=v25Equipped(c),armor=items.find(x=>x.slot==='armor'||x.armorBase!=null),shield=items.filter(x=>x.slot==='shield').reduce((n,x)=>n+(Number(x.acBonus)||2),0),other=items.filter(x=>x!==armor&&x.slot!=='shield').reduce((n,x)=>n+(Number(x.acBonus)||0),0),base;if(armor){base=Number(armor.armorBase)||10;if(armor.armorType==='light')base+=dex;if(armor.armorType==='medium')base+=Math.min(2,dex)}else if(c.species==='Tortle')base=17;else{let mode=PR_AC_BASE[c.className]??10;if(mode==='unarmored-con')base=10+dex+con;else if(mode==='unarmored-wis')base=10+dex+wis;else if(mode===14)base=12+Math.min(2,dex);else if(mode===12)base=11+dex;else if(mode===10)base=10+dex;else base=+mode||10}return base+shield+other};
function v25SeedEquipment(){let before=JSON.stringify((state.market||[]).map(x=>[x.id,x.slot,x.armorBase,x.acBonus]));for(let x of state.market||[])v25HydrateItem(x);for(let c of state.characters||[])for(let x of c.inventory||[])v25HydrateItem(x);let after=JSON.stringify((state.market||[]).map(x=>[x.id,x.slot,x.armorBase,x.acBonus]));if(current?.role==='dm'&&before!==after&&!state.v25EquipmentSeed){state.v25EquipmentSeed=true;setTimeout(save,0)}}
const v25OldEnsure=prEnsure;prEnsure=function(){v25SeedEquipment();v25OldEnsure();for(let c of state.characters||[]){c.stats=prStats(c);if(c.autoVitals!==false)c.ac=prAutoAC(c)}};
const v25OldExItemCard=exItemCard;exItemCard=function(i){v25HydrateItem(i);let html=v25OldExItemCard(i);if(current.role==='dm')html=html.replace('<div class="shop-admin">','<div class="shop-admin"><button data-v25-market-give="'+i.id+'" class="primary">Oyuncuya Ver</button>');return html};
function v25SkillBonus(c,name){let ability=V25_SKILLS[name],stats=prStats(c),key=ability==='CAST'?(PR_CASTING_ABILITY[c.className]||'INT'):ability;if(!key)return 0;let n=prMod(stats[key]);if(name.includes('Saving Throw')&&prClass(c.className).saves.includes(key))n+=prProf(c.level);else if((V25_CLASS_SKILLS[c.className]||[]).includes(name))n+=prProf(c.level);return n}
const v25OldSessionDice=sessionDice;sessionDice=function(){let html=v25OldSessionDice(),c=myChar(),options=Object.keys(V25_SKILLS).map(n=>`<option>${esc(n)}</option>`).join('');return html.replace('<div class="dice-action-row">',`<div class="v25-dice-skill"><label>Kontrol / saldırı<select id="v25Skill">${options}</select></label><div class="v25-dice-help"><b id="v25SkillBonus">Bonus ${prSigned(c?v25SkillBonus(c,'Serbest d20'):0)}</b><small id="v25SkillWhy">Bir kontrol seç; ilgili stat ve proficiency otomatik hesaplanır.</small></div></div><div class="dice-action-row">`)};
dmPages.dice=sessionDice;playerPages.dice=sessionDice;
const v25BaseRecord=sessionRecordRoll;sessionRecordRoll=async function(formula,values,bonus,total){let skill=$('#v25Skill')?.value;if(skill&&skill!=='Serbest d20')formula=skill+' • '+formula;return v25BaseRecord(formula,values,bonus,total)};
function v25UpdateSkill(){let c=myChar(),name=$('#v25Skill')?.value,ability=V25_SKILLS[name],bonus=c?v25SkillBonus(c,name):0,box=$('#sessionDiceBonus');if(box)box.value=bonus;if($('#v25SkillBonus'))$('#v25SkillBonus').textContent='Bonus '+prSigned(bonus);let key=ability==='CAST'?(PR_CASTING_ABILITY[c?.className]||'INT'):ability;if($('#v25SkillWhy'))$('#v25SkillWhy').textContent=key?`${key} modifier${(V25_CLASS_SKILLS[c?.className]||[]).includes(name)||name?.includes('Saving Throw')&&prClass(c?.className||'').saves.includes(key)?' + proficiency':''}. d20 atışına otomatik eklenir.`:'Elle bonus girebilirsin.'}
const v25OldPlayerCreate=prPlayerCreate;prPlayerCreate=function(){let species=allSpecies(),classes=allClasses(),sp=species[0],cl=classes.find(x=>x.name==='Fighter')||classes[0];return `<section class="card pr-create-hero"><small>KARAKTER OLUŞTURMA</small><h2>Kahramanını Ayrıntılarıyla Kur</h2><p>Species ve subspecies seviye 1'de seçilir ve kaydedilir. Subclass ise class uzmanlığıdır; seviye 3'te açılır.</p><div class="v25-create-grid"><div><label>Karakter adı<input id="prNewName" class="input" maxlength="60" placeholder="Kahramanın adı"></label><label>Species<select id="prNewSpecies">${species.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select></label><label>Subspecies / alt miras<select id="prNewSubspecies" required>${(sp.subs||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Class<select id="prNewClass">${classes.map(x=>`<option ${x.name===cl.name?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><button id="prCreatePlayerCharacter" class="primary">Karakterimi Oluştur</button></div><div id="v25CreatePreview" class="v25-create-preview"></div></div></section>`};
function v25CreatePreview(){let sp=prSpecies($('#prNewSpecies')?.value),sub=$('#prNewSubspecies')?.value||'',cl=prClass($('#prNewClass')?.value),className=$('#prNewClass')?.value||'',draft={species:$('#prNewSpecies')?.value,subspecies:sub,className,level:1,baseStats:Object.fromEntries(PR_ABILITIES.map((k,i)=>[k,cl.stats[i]])),inventory:[]},el=$('#v25CreatePreview');if(!el)return;let theme=prTheme(sub);el.innerHTML=`<h3>${esc(draft.species)} / ${esc(sub)}</h3><p>${sp.traits.map(esc).join(' • ')}</p><div class="v25-preview-tags"><span>Direnç: ${esc(sp.resist.join(', ')||'Yok')}</span><span>Zayıflık: ${esc(sp.weak.join(', ')||'Yok')}</span><span>Miras: ${esc(theme[0])}</span></div><h3>${esc(className)}</h3><p>Ana statlar: ${cl.primary.join(', ')} • Save proficiency: ${cl.saves.join(', ')} • ${cl.caster?'Büyü kullanan sınıf':'Fiziksel sınıf'}</p><p>${esc(cl.features[0]?.[1]||'Sınıf özelliği')}: ${esc(cl.features[0]?.[2]||'')}</p><b>Başlangıç: HP ${prAutoHP(draft)} • AC ${prAutoAC(draft)} • Hit Die d${PR_HIT_DIE[className]||8}</b><small>Subclass seviye 3'te seçilecek.</small>`}
const v25OldProgress=prProgress;prProgress=function(c){let html=v25OldProgress(c);return html.replace(/<p>([^<]*)<\/p><\/details>/g,(m,n)=>`<p>${n}</p><div class="v25-spell-meta"><span>Tür: açıklamaya göre action / bonus action / reaction</span><span>Cantrip ise slot harcamaz</span><span>Hasar/heal zarı büyü açıklamasına göre</span></div></details>`)};
document.addEventListener('change',e=>{if(e.target.id==='v25Skill')v25UpdateSkill();if(e.target.id==='prNewSpecies'){let x=allSpecies().find(s=>s.name===e.target.value),el=$('#prNewSubspecies');if(el)el.innerHTML=(x?.subs||[]).map(v=>`<option>${esc(v)}</option>`).join('');v25CreatePreview()}if(e.target.id==='prNewSubspecies'||e.target.id==='prNewClass')v25CreatePreview()},true);
document.addEventListener('focusout',()=>{if(window.kadimSyncQueued){window.kadimSyncQueued=false;setTimeout(()=>syncFromServer(false),150)}},true);
document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b||!current)return;
 if(b.dataset.iaExpand!=null){let p=document.querySelector(`[data-ia-panel="${b.dataset.iaExpand}"]`),open=p?.hidden;if(p)p.hidden=!open;b.setAttribute('aria-expanded',String(open));b.closest('.ia-item')?.classList.toggle('open',open);return}
 if(b.dataset.v25MarketGive){let item=state.market.find(x=>x.id===b.dataset.v25MarketGive);if(!item)return;modal('Market eşyasını oyuncuya ver',`<p><b>${esc(item.name)}</b> — ID: ${esc(item.id)}</p><label>Karakter<select id="v25GiveChar">${state.characters.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Adet<input id="v25GiveQty" type="number" min="1" value="1"></label><button id="v25ConfirmGive" data-item="${item.id}" class="primary">Ücretsiz Ver</button>`);return}
 if(b.id==='v25ConfirmGive'){let item=state.market.find(x=>x.id===b.dataset.item),target=$('#v25GiveChar').value,qty=Math.max(1,Math.floor(+$('#v25GiveQty').value||1));b.disabled=true;let {error}=await db.rpc('inventory_give_market',{p_user:auth.id,p_campaign:current.id,p_target_character:target,p_item_id:item.id,p_quantity:qty});if(error){b.disabled=false;return alert(error.message)}$('#modal').close();await syncFromServer(true);return}
 if(b.dataset.v25Equip!=null){b.disabled=true;let {error}=await db.rpc('inventory_equip',{p_user:auth.id,p_campaign:current.id,p_item_index:+b.dataset.v25Equip});if(error){b.disabled=false;return alert(error.message)}await syncFromServer(true);return}
 if(b.dataset.v25Trash!=null){let item=myChar()?.inventory?.[+b.dataset.v25Trash];if(!item||!confirm(`${item.name} kalıcı olarak çöpe atılsın mı?`))return;b.disabled=true;let {error}=await db.rpc('inventory_delete',{p_user:auth.id,p_campaign:current.id,p_item_index:+b.dataset.v25Trash});if(error){b.disabled=false;return alert(error.message)}await syncFromServer(true);return}
},true);
queueMicrotask(()=>{v25SeedEquipment();if(current)render();if(page==='dice')v25UpdateSkill();if(!myChar())v25CreatePreview()});
