const V26_SUBCLASSES={
Barbarian:['Berserker','Totem Warrior','Ancestral Guardian','Storm Herald','Zealot','Beast','Wild Magic'],
Bard:['Lore','Valor','Glamour','Swords','Whispers','Creation','Eloquence','Spirits'],
Cleric:['Knowledge','Life','Light','Nature','Tempest','Trickery','War','Arcana','Forge','Grave','Order','Peace','Twilight'],
Druid:['Land','Moon','Dreams','Shepherd','Spores','Stars','Wildfire'],
Fighter:['Champion','Battle Master','Eldritch Knight','Arcane Archer','Cavalier','Samurai','Echo Knight','Psi Warrior','Rune Knight'],
Monk:['Open Hand','Shadow','Four Elements','Long Death','Sun Soul','Drunken Master','Kensei','Mercy','Astral Self'],
Paladin:['Devotion','Ancients','Vengeance','Crown','Conquest','Redemption','Glory','Watchers','Oathbreaker'],
Ranger:['Hunter','Beast Master','Gloom Stalker','Horizon Walker','Monster Slayer','Fey Wanderer','Swarmkeeper','Drakewarden'],
Rogue:['Thief','Assassin','Arcane Trickster','Inquisitive','Mastermind','Scout','Swashbuckler','Phantom','Soulknife'],
Sorcerer:['Draconic','Wild Magic','Divine Soul','Shadow','Storm','Aberrant Mind','Clockwork Soul','Lunar'],
Warlock:['Archfey','Fiend','Great Old One','Celestial','Hexblade','Fathomless','Genie','Undead'],
Wizard:['Abjuration','Conjuration','Divination','Enchantment','Evocation','Illusion','Necromancy','Transmutation','Bladesinging','War Magic','Chronurgy','Graviturgy','Scribes'],
Artificer:['Alchemist','Artillerist','Battle Smith','Armorer']};
const V26_FEATURES={
Barbarian:[[1,'Öfke','Bonus action ile Rage aç. 1 dakika sürer; STR yakın saldırı hasarına bonus ve fiziksel hasarlara direnç verir.'],[1,'Zırhsız Savunma','Zırhsız AC = 10 + DEX + CON; kalkan kullanılabilir.'],[2,'Gözü Kara Saldırı','İlk STR yakın saldırında avantaj alırsın; karşı saldırılar da sana avantajlı olur.'],[2,'Tehlike Sezgisi','Görebildiğin tehlikelerin DEX savunmalarında avantaj.'],[5,'Ekstra Saldırı','Attack actionında iki ayrı saldırı.']],
Bard:[[1,'İlahi Büyü','Bard büyülerinde CHA kullanılır; bu başlık uygulamada genel büyü kartını açar.'],[1,'Bard İlhamı','Bonus action ile 60 ft dostuna d6 ver; attack/check/save sonucuna ekleyebilir.'],[2,'Her İşten Biraz','Proficiency olmayan ability checklere proficiency bonusunun yarısını ekle.'],[2,'Dinlenme Ezgisi','Kısa dinlenmede Hit Die ile iyileşen dostlara ek iyileşme zarı.']],
Cleric:[[1,'İlahi Büyü','Cleric büyülerinde WIS kullanılır; cantrip slot harcamaz.'],[1,'Kutsal Alan','Domain özelliğin 1. seviyede açılır.'],[2,'Kanal: Kutsallık','Action ile Turn Undead veya domain seçeneği; kısa/uzun dinlenmede yenilenir.'],[5,'Ölüleri Uzaklaştır','Turn Undead başarısızlığında düşük CR undead yok olabilir.']],
Druid:[[1,'Doğa Büyüsü','Druid büyülerinde WIS kullanılır; hazırlanan büyü sayısı WIS + Druid seviyesi.'],[1,'Druid Dili','Druidic gizli dilini bilirsin.'],[2,'Vahşi Şekil','Action ile gördüğün uygun Beast stat bloğuna dönüş; normal Druid için Lv2 CR 1/4, yüzme/uçma yok.'],[2,'Druid Çemberi','Subclass/çember seçimin ve ilk özellikleri açılır.']],
Fighter:[[1,'Dövüş Stili','Defense, Dueling, Archery gibi tek bir stil seç; bonus yalnız o stile göre uygulanır.'],[1,'İkinci Nefes','Bonus action: 1d10 + Fighter seviyesi HP; kısa/uzun dinlenmede yenilenir.'],[2,'Aksiyon Patlaması','Kendi turunda bir ek action; kısa/uzun dinlenmede bir kez.'],[5,'Ekstra Saldırı','Attack actionında iki ayrı saldırı.'],[9,'Yılmaz','Başarısız saving throw’u yeniden at.']],
Monk:[[1,'Dövüş Sanatları','Zırh/kalkan yokken unarmed/monk weapon için DEX ve Martial Arts zarı kullan; Attack sonrası bonus action yumruk.'],[1,'Zırhsız Savunma','Zırhsız ve kalkansız AC = 10 + DEX + WIS.'],[2,'Odak Puanı','2014 adı Ki’dir. Flurry of Blows, Patient Defense ve Step of the Wind için harcanır.'],[2,'Zırhsız Hareket','Zırh/kalkan yokken hız +10 ft.'],[5,'Ekstra Saldırı','Attack actionında iki saldırı.'],[5,'Sersemletici Darbe','İsabetten sonra 1 Ki; hedef CON save, DC 8 + proficiency + WIS.']],
Paladin:[[1,'Divine Sense','Action ile celestials/fiends/undead algıla; uzun dinlenmede 1 + CHA kullanımı.'],[1,'Lay on Hands','Action; Paladin seviyesi ×5 HP havuzundan dokunarak iyileştir, zar yok.'],[2,'Dövüş Stili','Tek bir savaş stili seç ve yalnız onun bonusunu uygula.'],[2,'İlahi Büyü','Paladin büyülerinde CHA kullanılır; hazırlama sayısı CHA + Paladin seviyesinin yarısı.'],[2,'İlahi Smite','Yakın silah isabetinden sonra slot harca; 1. seviye slot +2d8 radiant.'],[5,'Ekstra Saldırı','Attack actionında iki saldırı.'],[6,'Koruma Aurası','10 ft içindeki dostların save’lerine CHA modifier ekle.']],
Ranger:[[1,'Favori Düşman','2014 PHB: seçilen düşmanı izleme/bilgi kontrollerinde avantaj; doğrudan hasar bonusu yok.'],[1,'Doğal Kaşif','Seçilen arazide yolculuk ve iz sürme avantajları.'],[2,'Dövüş Stili','Archery, Dueling veya seçilen stile göre bonus.'],[2,'Ranger Büyüsü','WIS kullanır; bilinen büyüler ve slotlar sınıf tablosuna göre.'],[5,'Ekstra Saldırı','Attack actionında iki saldırı.']],
Rogue:[[1,'Uzmanlık','Seçilen iki proficiencyde proficiency bonusunu iki kez ekle.'],[1,'Sneak Attack','Şartlar varsa finesse/ranged isabete turda bir kez ek d6’lar.'],[1,'Hırsız Argosu','Thieves’ Cant gizli iletişimi.'],[2,'Kurnaz Eylem','Bonus action ile Dash, Disengage veya Hide.'],[5,'Esrarengiz Kaçış','Reaction ile görülen tek saldırının hasarını yarıya indir.'],[7,'Sakınma','DEX save alan hasarını başarıda sıfır, başarısızlıkta yarım al.']],
Sorcerer:[[1,'Doğuştan Büyü','Sorcerer büyülerinde CHA; bilinen büyüler sınırlıdır, cantrip slot yemez.'],[2,'Büyü Puanları','Sorcery point ve spell slot dönüşümü.'],[3,'Metamagic','Büyüye seçilen Metamagic etkisini puan harcayarak uygula.']],
Warlock:[[1,'Pact Magic','CHA kullanır; az sayıdaki pact slot kısa dinlenmede yenilenir.'],[2,'Eldritch Invocation','Seçilen invocation’ın tam kuralı uygulanır; otomatik genel bonus yok.'],[3,'Pact Lütfu','Chain, Blade veya Tome pact boon seçimi.'],[11,'Mystic Arcanum','Yüksek seviye büyüyü slotsuz, uzun dinlenmede bir kez.']],
Wizard:[[1,'Büyü Kitabı','Wizard büyülerinde INT; kitap, hazırlama ve ritüel kuralları uygulanır.'],[1,'Arcane Recovery','Kısa dinlenmede, günde bir kez sınırlı spell slot geri al.'],[2,'Arcane Tradition','Wizard okul/subclass özellikleri açılır.'],[18,'Spell Mastery','Seçilen düşük seviye büyüleri slotsuz kullan.']],
Artificer:[[1,'Büyülü Tamircilik','Küçük nesneye ışık/ses/koku/işaret gibi küçük etki ver.'],[1,'Artificer Büyüsü','INT ile hazırlanmış büyüler; alet veya infused eşya odak olabilir.'],[2,'Infusion','Uzun dinlenmede sıradan eşyalara seçilen infusion özelliklerini uygula.'],[3,'Artificer Uzmanlığı','Subclass özelliğin açılır.']]};
const V26_WEAPONS={Barbarian:'Simple ve martial silahlar; genelde STR yakın silah.',Bard:'Simple silahlar, hand crossbow, longsword, rapier, shortsword.',Cleric:'Simple silahlar; War/Tempest gibi bazı domainler martial verebilir.',Druid:'Club, dagger, dart, javelin, mace, quarterstaff, scimitar, sickle, sling, spear; metal zırh kullanmama teması masaya bağlı.',Fighter:'Simple ve martial silahların tamamı.',Monk:'Simple silahlar ve shortsword; Martial Arts için heavy/two-handed olmayan monk silahı.',Paladin:'Simple ve martial silahların tamamı.',Ranger:'Simple ve martial silahların tamamı.',Rogue:'Simple silahlar, hand crossbow, longsword, rapier, shortsword.',Sorcerer:'Dagger, dart, sling, quarterstaff, light crossbow.',Warlock:'Simple silahlar; Hexblade ek proficiency verebilir.',Wizard:'Dagger, dart, sling, quarterstaff, light crossbow.',Artificer:'Simple silahlar; subclass ek silah verebilir.'};
Object.assign(V25_FEATURE_RULES,{
'Zırhsız Savunma':['Pasif','Sınırsız','Zırh şartı sağlandıkça','Monk: zırh ve kalkan yokken 10 + DEX + WIS. Barbarian: zırh yokken 10 + DEX + CON; kalkan kullanabilir.'],
'Kutsal Alan':['Pasif/özelliğe göre','Domain özelliğine göre','Sürekli veya özellik süresi','Cleric domain seçiminin 1. seviye özelliklerini uygular; exact bonus için domain adı açılmalıdır.'],
'Druid Dili':['Pasif','Sınırsız','Sürekli','Druidic konuşup gizli işaretleri okuyabilirsin; savaş bonusu vermez.'],
'Druid Çemberi':['Pasif/özelliğe göre','Seçilen Circle’a göre','Özelliğe göre','Seçilen Druid Circle’ın 2. seviye özellikleri açılır; Moon Wild Shape’i, Land büyü kullanımını değiştirir.'],
'Divine Sense':['Action','1 + CHA modifier / uzun dinlenme','Sonraki turunun sonuna kadar','60 ft içindeki total cover arkasında olmayan celestial, fiend, undead ve kutsanmış/kirletilmiş alanı algılarsın; kimlik öğrenmezsin.'],
'Doğal Kaşif':['Pasif','Seçilen arazi','Yolculuk boyunca','Favori arazide kaybolmama, iz sürme ve yolculuk avantajları verir; doğrudan saldırı/hasar bonusu değildir.'],
'Ranger Büyüsü':['Spell’e göre','Spell slotların kadar','Spell’e göre','WIS kullanır. Spell attack = d20 + proficiency + WIS; save DC = 8 + proficiency + WIS.'],
'Hırsız Argosu':['Pasif','Sınırsız','Sürekli','Thieves’ Cant ile gizli anlam ve işaretler aktarırsın; savaş bonusu vermez.'],
'Arcane Tradition':['Pasif/özelliğe göre','Wizard okuluna göre','Özelliğe göre','Seçilen Wizard okulunun 2. seviye özellikleri açılır.'],
'Artificer Büyüsü':['Spell’e göre','Spell slotların kadar','Spell’e göre','INT kullanır. Spell attack = d20 + proficiency + INT; save DC = 8 + proficiency + INT.'],
'Artificer Uzmanlığı':['Pasif/özelliğe göre','Subclass’a göre','Özelliğe göre','Seçilen Artificer subclassının 3. seviye özellikleri açılır.']});
v25CombatCard=function(c){let s=prStats(c),p=prProf(c.level),str=prMod(s.STR),dex=prMod(s.DEX),cast=PR_CASTING_ABILITY[c.className],cm=cast?prMod(s[cast]):0,main=c.className==='Monk'?dex:(['Rogue','Ranger'].includes(c.className)?dex:str),attack=main+p,damage=main;return `<section class="card v25-combat-card"><span class="v26-kicker">KARAKTERE ÖZEL HIZLI KART</span><h2>${esc(c.name)} ile Fight</h2><div class="v26-info-grid"><article class="v26-info"><b>1. Initiative</b>d20 ${prSigned(dex)} at. Sıran gelince hareket + action; özellik izin verirse bonus action.</article><article class="v26-info"><b>2. Silah/Yumruk saldırısı</b>d20 ${prSigned(attack)}. Sonuç hedef AC’ye eşit/yüksekse isabet. Hasar silah zarı ${prSigned(damage)}.${c.className==='Monk'?' Monk Martial Arts zarı erken seviyede d4; Attack sonrası bonus action yumruk ayrı d20 atar.':''}</article><article class="v26-info"><b>3. Kullanabildiğin silahlar</b>${esc(V26_WEAPONS[c.className]||'Karakter sheetindeki weapon proficiency alanını kullan.')}</article>${cast?`<article class="v26-info"><b>4. Büyü</b>Spell attack d20 ${prSigned(cm+p)} • Spell Save DC ${8+cm+p} • Casting stat ${cast}. Spell kartında attack mı save mi yazdığına bak.</article>`:''}<article class="v26-info"><b>Species / Subspecies</b>${esc(c.species)}${c.subspecies?' / '+esc(c.subspecies):''}. Bunlar class saldırı formülünün yerine geçmez; aşağıdaki trait kartında yazan direnç ve aktif özellikleri ekler.</article></div><div class="v25-preview-tags"><span>AC ${prAutoAC(c)}</span><span>Initiative ${prSigned(dex)}</span><span>Proficiency ${prSigned(p)}</span><span>STR ${prSigned(str)}</span><span>DEX ${prSigned(dex)}</span></div></section>`};
const v26BasePrClass=prClass;
prClass=function(name){let base=v26BasePrClass(name);return V26_FEATURES[name]?{...base,features:V26_FEATURES[name]}:base};
const v26BaseAllClasses=allClasses;
allClasses=function(){return v26BaseAllClasses().filter(x=>V26_SUBCLASSES[x.name]||!['Blood Hunter','Psion'].includes(x.name)||(state.characters||[]).some(c=>c.className===x.name)).map(x=>{if(!V26_SUBCLASSES[x.name])return x;let used=(state.characters||[]).filter(c=>c.className===x.name&&c.subclass).map(c=>c.subclass);return {...x,subs:[...new Set([...V26_SUBCLASSES[x.name],...used])]}})};

function v26Head(kicker,title,note,actions=''){return `<div class="v26-page-head"><div><span class="v26-kicker">${esc(kicker)}</span><h2>${esc(title)}</h2><p class="muted">${esc(note)}</p></div>${actions?`<div class="v26-actions">${actions}</div>`:''}</div>`}
function v26Guide(){let tabs=[['fight','Savaş Akışı'],['checks','Zarlar & Skill'],['magic','Büyüler'],['conditions','Condition'],['character','Karakter Okuma']];return `<section class="card v26-guide-home">${v26Head('2014 KURALLARI','Masa Rehberi','Oturum sırasında gereken kısa ve uygulanabilir kurallar. Uzun teori ve tekrarlar ayıklandı.')}<div class="v26-guide-tabs">${tabs.map((x,i)=>`<button class="${i?'ghost':'primary'}" data-v26-guide="${x[0]}">${x[1]}</button>`).join('')}</div><div class="toolbar"><input id="guideSearch" class="input" placeholder="Örn: grapple, stealth, concentration, AC"><button id="searchGuide" class="primary">Rehberde Ara</button><button id="readFullGuide" class="ghost">Tam Kaynak</button></div><div id="guideResults" class="v26-guide-body">${v26GuideSection('fight')}</div></section>`}
function v26GuideSection(key){let data={
fight:['Savaş başlarken|Herkes d20 + DEX ile initiative atar. Yüksekten düşüğe sırala. Surprise varsa yalnız gerçekten hazırlıksız hedeflere uygula.','Bir oyuncunun turu|Hareket + 1 action + varsa 1 bonus action. Reaction tur dışında tetiklenir ve kendi sonraki turunda yenilenir.','Saldırı|d20 + ilgili STR/DEX modifier + silaha proficiency. Sonuç AC’ye eşit/yüksekse isabet. Sonra silah zarı + aynı modifier hasar.','DM turu|Yaratığın stat bloğundaki saldırı bonusunu aynen d20’ye ekle. İsabette yazan hasar zarını at. Hedefi mantıklı davranışına göre seç; gizli DM hilesi yapma.','0 HP|Oyuncu death save atar: d20, 10+ başarı. 3 başarı stabilize, 3 başarısızlık ölüm. Yaratıklar çoğunlukla 0 HP’de düşer.'],
checks:['Ability check|d20 + ilgili ability modifier + proficiency varsa proficiency. DM yalnız belirsizlik ve anlamlı sonuç varsa zar ister.','Skill bağlantısı|Athletics STR; Acrobatics/Stealth DEX; Investigation INT; Perception/Insight/Survival WIS; Persuasion/Deception/Intimidation CHA.','Saving throw|d20 + ability modifier + class o save’de proficient ise proficiency. Saldırgan değil, etkilenen hedef atar.','Advantage|2d20 at, yükseği kullan. Disadvantage’da düşüğü. Birden fazla kaynak üst üste üçüncü zar vermez.','Passive Perception|10 + Perception bonusu. Gizlenenin Stealth sonucu ile karşılaştır.'],
magic:['Spell attack|d20 + proficiency + casting modifier. Bard/Sorcerer/Warlock/Paladin CHA; Cleric/Druid/Ranger WIS; Wizard/Artificer INT.','Spell save DC|8 + proficiency + casting modifier. Spell hangi save’i söylüyorsa hedef onu atar.','Cantrip|Spell slot harcamaz ama casting time neyse onu harcar; çoğu actiondır.','Concentration|Aynı anda tek concentration. Hasar alınca CON save: DC 10 veya hasarın yarısı, yüksek olan.','Bonus-action spell|2014 kuralında aynı turdaki diğer spell yalnız casting time’ı 1 action olan cantrip olabilir.'],
conditions:['Grappled|Hız 0. 2014’te kaçmak için action ile Athletics veya Acrobatics, grappler Athletics’ine karşı.','Restrained|Hız 0; saldırıların dezavantajlı, sana saldırılar avantajlı, DEX save dezavantajlı.','Prone|Ayağa kalkmak hızın yarısı. 5 ft içi saldırılar avantajlı, uzak saldırılar dezavantajlı.','Stunned|Hareket/action yok; STR/DEX save otomatik başarısız; saldırılar avantajlı.','Unconscious|Hareket/action yok, yere düşer; 5 ft içi isabet kritik olur.'],
character:['Species|Doğuştan gelen hız, görüş, direnç ve aktif özellikler. Subspecies bunlara ek miras özellikleri verir.','Class|HP zarı, save proficiency, silah/zırh proficiency ve ana yetenek döngüsünü belirler.','Subclass|Class uzmanlığıdır. Çoğu 2014 class’ta seviye 3; Cleric/Sorcerer/Warlock gibi bazıları daha erken seçer. Mevcut karakter seçimleri korunur.','Skill|Bir ability check türüdür. Skill’in yanında yazan modifier d20’ye eklenir.','Spell kartı|Casting time, menzil, süre, concentration, component, saldırı/save ve zar alanlarını sırayla oku.']};return (data[key]||data.fight).map((x,i)=>{let [a,b]=x.split('|');return `<div class="v26-step"><i>${i+1}</i><div><b>${esc(a)}</b><p>${esc(b)}</p></div></div>`}).join('')}

function v26GuildState(){state.guild??=null;return state.guild}
function v26GuildMember(){let g=v26GuildState();return current.role==='dm'||!!g?.members?.includes(auth.id)}
function v26GuildPage(dm=false){queueMicrotask(()=>exLoadWallets());let g=v26GuildState(),member=v26GuildMember(),mine=exWalletRows.find(x=>x.user_id===auth.id),inv=state.guildInventory||[],c=myChar();if(!g)return `<section class="card v26-guild-hero">${v26Head('LONCA SALONU','Henüz lonca kurulmadı','Kampanyada tek ortak lonca bulunur. Kurulduğunda üyeler ortak kasa ve envanteri kullanabilir.')}<div class="v26-actions"><button id="v26CreateGuild" class="primary">Lonca Kur</button><button id="v26JoinGuild" class="ghost">Kodla Katıl</button></div></section>`;return `${v26Head('LONCA SALONU',g.name,member?'Ortak kasa ve envanter erişimin var.':'Üye değilsin; katılım koduyla loncaya girebilirsin.',`<button class="ghost" data-copy-guild="${esc(g.code)}">Kod: ${esc(g.code)}</button>${member&&current.role!=='dm'?'<button id="v26LeaveGuild" class="danger">Loncadan Çık</button>':!member?'<button id="v26JoinGuild" class="primary">Loncaya Katıl</button>':''}`)}<div class="v26-guild-grid"><section class="card v26-guild-hero"><span class="v26-kicker">ORTAK KASA</span><div class="v26-guild-code">${exMoney(exCoinTotal(exGuildWallet||{}))}</div>${member&&current.role==='player'?`<div class="v26-transfer"><label>Para<select id="v26GuildCoin"><option value="platinum">PP</option><option value="gold" selected>GP</option><option value="silver">SP</option><option value="copper">CP</option></select></label><label>Miktar<input id="v26GuildAmount" type="number" min="1" value="1"></label><button id="v26GuildDeposit" class="primary">Kasaya Yatır</button><button id="v26GuildWithdraw" class="ghost">Kasadan Çek</button></div><p class="muted">Kişisel bakiye: ${exMoney(exCoinTotal(mine||{}))}</p>`:dm?'<p class="muted">DM kasa miktarlarını Kasa menüsünden ayrıca düzenleyebilir.</p>':'<p class="muted">Kasayı kullanmak için loncaya katıl.</p>'}</section><section class="card"><span class="v26-kicker">ORTAK ENVANTER</span><h3>Lonca Eşyaları</h3>${inv.map((x,i)=>`<div class="v26-item"><span><b>${esc(x.name)}</b><small>${esc(x.note||x.effect||'')}</small>×${Math.max(1,+x.qty||1)}</span>${member&&current.role==='player'?`<button class="ghost" data-v26-guild-take="${i}">Envantere Al</button>`:''}</div>`).join('')||'<div class="empty">Lonca envanteri boş.</div>'}${member&&c?.inventory?.length?`<hr><label>Kendi envanterinden yatır<select id="v26GuildItem">${c.inventory.map((x,i)=>`<option value="${i}">${esc(x.name)} ×${x.qty}</option>`).join('')}</select></label><div class="v26-transfer"><label>Adet<input id="v26GuildItemQty" type="number" min="1" value="1"></label><button id="v26GuildItemDeposit" class="primary">Lonca Envanterine Ekle</button></div>`:''}</section></div>`}

guideView=v26Guide;dmPages.guide=v26Guide;playerPages.guide=v26Guide;dmPages.guilddm=()=>v26GuildPage(true);playerPages.guild=()=>typeof sessionPending==='function'&&sessionPending()?sessionPendingPage():v26GuildPage(false);
const v26RenderBase=render;render=function(){let out=v26RenderBase();queueMicrotask(()=>{document.querySelectorAll('#nav button').forEach(b=>{let label=b.textContent.trim();b.title=label+' menüsünü aç'});if(page==='guide')document.body.classList.add('v26-guide-page');else document.body.classList.remove('v26-guide-page')});return out};

document.addEventListener('click',async e=>{let b=e.target.closest('button');
 if(b?.id==='closeMenu'){document.body.classList.remove('menu');return}
 if(document.body.classList.contains('menu')&&!e.target.closest('aside')&&!e.target.closest('#menu')){document.body.classList.remove('menu');return}
 if(!b||!current)return;
 if(b.dataset.v26Guide){document.querySelectorAll('[data-v26-guide]').forEach(x=>x.className=x===b?'primary':'ghost');$('#guideResults').innerHTML=v26GuideSection(b.dataset.v26Guide);return}
 if(b.dataset.copyGuild){navigator.clipboard?.writeText(b.dataset.copyGuild);toast('Lonca kodu kopyalandı');return}
 if(b.id==='v26CreateGuild'){modal('Lonca Kur',field('v26GuildName','Lonca adı')+'<button id="v26ConfirmCreateGuild" class="primary">Lonca Kur</button>');return}
 if(b.id==='v26JoinGuild'){modal('Loncaya Katıl',field('v26GuildCode','6 haneli lonca kodu')+'<button id="v26ConfirmJoinGuild" class="primary">Katıl</button>');return}
 if(b.id==='v26ConfirmCreateGuild'){let name=$('#v26GuildName').value.trim();if(name.length<2)return alert('Lonca adı en az 2 karakter olmalı.');b.disabled=true;let {error}=await db.rpc('guild_manage_v26',{p_user:auth.id,p_campaign:current.id,p_action:'create',p_value:name});if(error){b.disabled=false;return alert(error.message)}$('#modal').close();await syncFromServer(true);exWalletCampaign=null;await exLoadWallets(true);render();return}
 if(b.id==='v26ConfirmJoinGuild'){let code=$('#v26GuildCode').value.trim().toUpperCase();b.disabled=true;let {error}=await db.rpc('guild_manage_v26',{p_user:auth.id,p_campaign:current.id,p_action:'join',p_value:code});if(error){b.disabled=false;return alert(error.message)}$('#modal').close();await syncFromServer(true);render();return}
 if(b.id==='v26LeaveGuild'){if(!confirm('Loncadan çıkılsın mı? Kişisel eşya ve paran silinmez.'))return;let {error}=await db.rpc('guild_manage_v26',{p_user:auth.id,p_campaign:current.id,p_action:'leave',p_value:''});if(error)return alert(error.message);await syncFromServer(true);render();return}
 if(b.id==='v26GuildDeposit'||b.id==='v26GuildWithdraw'){let amount=Math.floor(+$('#v26GuildAmount').value||0),coin=$('#v26GuildCoin').value;if(amount<1)return alert('Miktar en az 1 olmalı.');b.disabled=true;let {error}=await db.rpc('guild_wallet_move_v26',{p_user:auth.id,p_campaign:current.id,p_coin:coin,p_amount:amount,p_direction:b.id==='v26GuildDeposit'?'deposit':'withdraw'});if(error){b.disabled=false;return alert(error.message)}exWalletCampaign=null;await exLoadWallets(true);render();toast(b.id==='v26GuildDeposit'?'Para lonca kasasına yatırıldı':'Para lonca kasasından çekildi');return}
 if(b.id==='v26GuildItemDeposit'){let index=+$('#v26GuildItem').value,qty=Math.floor(+$('#v26GuildItemQty').value||0);if(qty<1)return alert('Geçerli adet gir.');b.disabled=true;let {error}=await db.rpc('guild_inventory_move_v26',{p_user:auth.id,p_campaign:current.id,p_direction:'deposit',p_item_index:index,p_quantity:qty});if(error){b.disabled=false;return alert(error.message)}await syncFromServer(true);render();return}
 if(b.dataset.v26GuildTake!=null){let item=state.guildInventory[+b.dataset.v26GuildTake],max=Math.max(1,+item.qty||1),qty=max===1?1:Math.floor(+(prompt(`Kaç adet ${item.name} alınsın?`,String(max))||0));if(qty<1||qty>max)return;b.disabled=true;let {error}=await db.rpc('guild_inventory_move_v26',{p_user:auth.id,p_campaign:current.id,p_direction:'withdraw',p_item_index:+b.dataset.v26GuildTake,p_quantity:qty});if(error){b.disabled=false;return alert(error.message)}await syncFromServer(true);render();return}
},true);

if(current)render();
fetch('guide-v26.txt',{cache:'no-cache'}).then(r=>r.ok?r.text():Promise.reject()).then(t=>guide=t).catch(()=>{});
