let v27MonsterCategory='all',v27MonsterCr='all',v27MonsterQuery='';
const V27_MONSTER_DETAIL={
Goblin:{category:'Humanoid',cr:'1/4',stats:[8,14,10,10,8,8],attacks:'Scimitar: +4, 1d6+2 slashing. Shortbow: +4, 1d6+2 piercing.',traits:'Nimble Escape: bonus action ile Disengage veya Hide.',resist:'Yok',immune:'Yok',weak:'Düşük HP; alan hasarı ve yakın baskı.'},
Kobold:{category:'Humanoid',cr:'1/8',stats:[7,15,9,8,7,8],attacks:'Dagger: +4, 1d4+2 piercing. Sling: +4, 1d4+2 bludgeoning.',traits:'Pack Tactics: müttefiki hedefin yanındaysa saldırıda avantaj. Sunlight Sensitivity.',resist:'Yok',immune:'Yok',weak:'Güneş ışığında saldırı ve görsel Perception dezavantajı.'},
Skeleton:{category:'Undead',cr:'1/4',stats:[10,14,15,6,8,5],attacks:'Shortsword/shortbow: +4, 1d6+2.',traits:'Undead Nature.',resist:'Piercing',immune:'Poison; exhaustion ve poisoned',weak:'Bludgeoning hasarına karşı vulnerable.'},
Zombie:{category:'Undead',cr:'1/4',stats:[13,6,16,3,6,5],attacks:'Slam: +3, 1d6+1 bludgeoning.',traits:'Undead Fortitude: 0 HP’de CON save ile 1 HP’de kalabilir; radiant/kritik bunu engeller.',resist:'Yok',immune:'Poison; poisoned',weak:'Çok düşük DEX ve AC.'},
Wolf:{category:'Beast',cr:'1/4',stats:[12,15,12,3,12,6],attacks:'Bite: +4, 2d4+2 piercing; hedef STR save başarısızsa prone.',traits:'Pack Tactics; keskin koku/işitme Perception avantajı.',resist:'Yok',immune:'Yok',weak:'Düşük HP.'},
Bandit:{category:'Humanoid',cr:'1/8',stats:[11,12,12,10,10,10],attacks:'Scimitar +3, 1d6+1; light crossbow +3, 1d8+1.',traits:'Basit taktikler; siper ve kaçış kullanır.',resist:'Yok',immune:'Yok',weak:'Düşük AC/HP.'},
Cultist:{category:'Humanoid',cr:'1/8',stats:[11,12,10,10,11,10],attacks:'Scimitar +3, 1d6+1 slashing.',traits:'Dark Devotion: charmed veya frightened olmaya karşı save avantajı.',resist:'Yok',immune:'Yok',weak:'Düşük HP ve menzilli seçeneği yok.'},
Guard:{category:'Humanoid',cr:'1/8',stats:[13,12,12,10,11,10],attacks:'Spear +3, 1d6+1 piercing; iki elle 1d8+1.',traits:'Kalkanıyla AC 16; kapı ve dar geçit savunmasında etkilidir.',resist:'Yok',immune:'Yok',weak:'Düşük HP ve mental savunmalar.'},
Orc:{category:'Humanoid',cr:'1/2',stats:[16,12,16,7,11,10],attacks:'Greataxe +5, 1d12+3; javelin +5, 1d6+3.',traits:'Aggressive: bonus action ile görülen düşmana yaklaşır.',resist:'Yok',immune:'Yok',weak:'WIS/INT kontrolleri zayıf.'},
Hobgoblin:{category:'Humanoid',cr:'1/2',stats:[13,12,12,10,10,9],attacks:'Longsword +3, 1d8+1; longbow +3, 1d8+1.',traits:'Martial Advantage: müttefiki hedef yakınındaysa turda bir +2d6.',resist:'Yok',immune:'Yok',weak:'Yalnız kaldığında hasarı düşer.'},
Bugbear:{category:'Humanoid',cr:'1',stats:[15,14,13,8,11,9],attacks:'Morningstar +4, 2d8+2; javelin +4, 2d6+2.',traits:'Brute; Surprise Attack; uzun erişim.',resist:'Yok',immune:'Yok',weak:'Düşük mental savunmalar.'},
Ghoul:{category:'Undead',cr:'1',stats:[13,15,10,7,10,6],attacks:'Bite +2, 2d6+2; Claws +4, 2d4+2 ve CON save ile paralysis.',traits:'Undead Nature.',resist:'Yok',immune:'Poison; charmed, exhaustion, poisoned',weak:'Düşük CON/CHA.'},
'Giant Spider':{category:'Beast',cr:'1',stats:[14,16,12,2,11,4],attacks:'Bite +5, 1d8+3 piercing + poison; Web ranged ile restrained.',traits:'Spider Climb, Web Sense, Web Walker.',resist:'Yok',immune:'Yok',weak:'Düşük mental statlar.'},
'Dire Wolf':{category:'Beast',cr:'1',stats:[17,15,15,3,12,7],attacks:'Bite +5, 2d6+3; STR save başarısızsa prone.',traits:'Pack Tactics, keen hearing/smell.',resist:'Yok',immune:'Yok',weak:'Menzilli kontrol.'},
Ogre:{category:'Giant',cr:'2',stats:[19,8,16,5,7,7],attacks:'Greatclub +6, 2d8+4; javelin +6, 2d6+4.',traits:'Büyük HP ve hasar, fakat kaba taktik.',resist:'Yok',immune:'Yok',weak:'DEX, INT, WIS ve CHA düşük.'},
Mimic:{category:'Monstrosity',cr:'2',stats:[17,12,15,5,13,8],attacks:'Pseudopod +5, 1d8+3 ve grapple; Bite +5, 1d8+3 +1d8 acid.',traits:'Shapechanger, Adhesive, False Appearance, Grappler.',resist:'Acid',immune:'Prone',weak:'Yavaş; uzaktan saldırı.'},
Wight:{category:'Undead',cr:'3',stats:[15,14,16,10,13,15],attacks:'Longsword/longbow +4; Life Drain +4, 1d6+2 necrotic ve CON save ile HP maksimumunu düşürür.',traits:'Sunlight Sensitivity; Life Drain ile öldürdüğü humanoid zombie olabilir.',resist:'Necrotic; nonmagical/non-silver fiziksel',immune:'Poison; exhaustion ve poisoned',weak:'Güneş ışığında saldırı ve Perception dezavantajı.'},
Basilisk:{category:'Monstrosity',cr:'3',stats:[16,8,15,2,8,7],attacks:'Bite +5, 2d6+3 piercing + 2d6 poison.',traits:'Petrifying Gaze: 30 ft içinde göz göze gelen hedef CON save; iki aşamada petrified.',resist:'Yok',immune:'Yok',weak:'DEX, INT ve WIS çok düşük; bakıştan kaçınmak saldırıları zorlaştırır.'},
Werewolf:{category:'Shapechanger',cr:'3',stats:[15,13,14,10,11,10],attacks:'Multiattack; bite +4, 1d8+2 ve curse; claws/spear.',traits:'Shapechanger, keen hearing/smell.',resist:'Yok',immune:'Nonmagical/non-silver bludgeoning, piercing, slashing',weak:'Silvered veya magical silahlar.'},
Troll:{category:'Giant',cr:'5',stats:[18,13,20,7,9,7],attacks:'Multiattack: bite +7 1d6+4; iki claw +7 2d6+4.',traits:'Regeneration 10 HP tur başı.',resist:'Yok',immune:'Yok',weak:'Acid veya fire alınca regeneration o tur çalışmaz.'},
'Young Green Dragon':{category:'Dragon',cr:'8',stats:[19,12,17,16,13,15],attacks:'Multiattack; bite/claw. Poison Breath: CON save, 12d6 poison.',traits:'Amphibious; breath recharge 5–6.',resist:'Yok',immune:'Poison; poisoned',weak:'Düşük DEX save; poison immune hedeflere nefes etkisiz.'},
'Young Red Dragon':{category:'Dragon',cr:'10',stats:[23,10,21,14,11,19],attacks:'Multiattack; Fire Breath DEX save, 16d6 fire.',traits:'Breath recharge 5–6; güçlü uçuş.',resist:'Yok',immune:'Fire',weak:'Düşük DEX ve WIS save.'},
'Vampire Spawn':{category:'Undead',cr:'5',stats:[16,16,16,11,10,12],attacks:'Multiattack; claws +6 ile grapple veya 2d4+3; grappled hedefe bite +6, piercing + necrotic ve iyileşme.',traits:'Regeneration 10; Spider Climb; Vampire Weaknesses.',resist:'Necrotic; nonmagical fiziksel',immune:'Poison; poisoned',weak:'Running water, sunlight ve radiant hasar regenerationı durdurur.'},
'Mind Flayer':{category:'Aberration',cr:'7',stats:[11,12,12,19,17,17],attacks:'Tentacles +7 ve grapple/stun; Extract Brain; Mind Blast INT save.',traits:'Magic Resistance, innate psionics.',resist:'Magic Resistance',immune:'Yok',weak:'Düşük fiziksel HP; STR save zayıf.'},
Beholder:{category:'Aberration',cr:'13',stats:[10,14,18,17,15,17],attacks:'Bite; rastgele Eye Rays; Antimagic Cone.',traits:'Legendary actions; uçuş; göz ışınları farklı save ister.',resist:'Yok',immune:'Prone',weak:'Antimagic cone kendi ışınlarını da bastırır.'},
'Stone Golem':{category:'Construct',cr:'10',stats:[22,9,20,3,11,1],attacks:'Multiattack: iki Slam +10, her biri 3d8+6 bludgeoning.',traits:'Immutable Form, Magic Resistance, Magic Weapons; Slow (Recharge 5–6) WIS save.',resist:'Nonmagical/non-adamantine fiziksel',immune:'Poison, psychic; çok sayıda condition',weak:'Çok düşük mental statlar ve yavaş hareket.'},
'Adult Black Dragon':{category:'Dragon',cr:'14',stats:[23,14,21,14,13,17],attacks:'Multiattack: bite +11, iki claw +11; tail/wing legendary action. Acid Breath: DEX DC 18, 12d8 acid.',traits:'Amphibious, Frightful Presence, Legendary Resistance 3/day, lair/legendary actions.',resist:'Yok',immune:'Acid',weak:'Düşük INT/WIS save’leri; nefes çizgisinden dağılmak gerekir.'},
'Purple Worm':{category:'Monstrosity',cr:'15',stats:[28,7,22,1,8,4],attacks:'Multiattack: bite +14, 3d8+9 ve swallow; tail stinger +14, 3d6+9 + CON save 12d6 poison.',traits:'Tunneler; swallowed hedef restrained ve kördür, tur başı acid alır.',resist:'Yok',immune:'Yok',weak:'Çok düşük DEX ve mental statlar; dev gövdesi kontrol büyülerine açıktır.'},
Lich:{category:'Undead',cr:'21',stats:[11,16,16,20,14,16],attacks:'Paralyzing Touch; yüksek seviye spellcasting; legendary actions.',traits:'Legendary Resistance, Rejuvenation, Turn Resistance.',resist:'Cold, lightning, necrotic; nonmagical fiziksel',immune:'Poison; çok sayıda condition',weak:'Phylactery yok edilirse kalıcı yenilgi mümkün.'},
Tarrasque:{category:'Monstrosity',cr:'30',stats:[30,11,30,3,11,11],attacks:'Beş saldırılı multiattack; swallow; legendary actions.',traits:'Legendary Resistance 3/day, Magic Resistance, Reflective Carapace, Siege Monster.',resist:'Yok',immune:'Fire, poison; nonmagical fiziksel; birçok condition',weak:'Uçan/uzak ve özel plan gerektirir; normal encounter değildir.'}};
const V27_EXTRA_MONSTERS=[
['Rat',1,10,20,'Beast','0',[2,11,9,2,10,4],'Bite +0, 1 piercing.','Keen Smell.','Yok','Yok','Çok düşük HP.'],
['Giant Rat',7,12,30,'Beast','1/8',[7,15,11,2,10,4],'Bite +4, 1d4+2.','Pack Tactics, Keen Smell.','Yok','Yok','Alan hasarı.'],
['Poisonous Snake',2,13,30,'Beast','1/8',[2,16,11,1,10,3],'Bite +5, 1 piercing + CON save poison.','Küçük ve gizlenebilir.','Yok','Yok','Tek isabette düşebilir.'],
['Giant Poisonous Snake',11,14,30,'Beast','1/4',[10,18,13,2,10,3],'Bite +6, 1d4+4 + 3d6 poison, CON save yarım.','Blindsight 10 ft.','Yok','Yok','Düşük HP.'],
['Black Bear',19,11,40,'Beast','1/2',[15,10,14,2,12,7],'Multiattack: bite +3 1d6+2, claws +3 2d4+2.','Keen Smell.','Yok','Yok','Düşük AC.'],
['Brown Bear',34,11,40,'Beast','1',[19,10,16,2,13,7],'Multiattack: bite +5 1d8+4, claws +5 2d6+4.','Keen Smell.','Yok','Yok','Düşük AC/WIS save.'],
['Giant Eagle',26,13,80,'Beast','1',[16,17,13,8,14,10],'Multiattack: beak +5 1d6+3, talons +5 2d6+3.','Keen Sight; uçuş 80 ft.','Yok','Yok','Kapalı alan.'],
['Swarm of Rats',24,10,30,'Swarm','1/4',[9,11,9,2,10,3],'Bites +2; HP’ye göre 2d6 veya 1d6.','Swarm, yarım alandan geçer.','Fiziksel direnç','Charmed, grappled, prone vb.','Alan hasarı.'],
['Bandit Captain',65,15,30,'Humanoid','2',[15,16,14,14,11,14],'Multiattack; scimitar +5, dagger +5. Parry reaction AC +2.','Lider ve taktikçi.','Yok','Yok','Mental kontrol.'],
['Cult Fanatic',33,13,30,'Humanoid','2',[11,14,12,10,13,14],'Multiattack dagger; 4. seviye Cleric spellcasting.','Dark Devotion.','Yok','Yok','Concentration kırma.'],
['Animated Armor',33,18,25,'Construct','1',[14,11,13,1,3,1],'Multiattack: iki slam +4, 1d6+2.','Antimagic Susceptibility, False Appearance.','Yok','Poison, psychic; birçok condition','Antimagic/Dispel etkileri.'],
['Gelatinous Cube',84,6,15,'Ooze','2',[14,3,20,1,6,1],'Pseudopod +4, 3d6 acid; Engulf DEX save.','Ooze Cube, Transparent.','Yok','Birçok condition','Çok düşük AC/DEX; uzaktan vur.'],
['Ochre Jelly',45,8,10,'Ooze','2',[15,6,14,2,6,1],'Pseudopod +4, 2d6+2 bludgeoning +1d6 acid.','Split: lightning/slashing ile bölünebilir.','Acid','Lightning, slashing; birçok condition','Yavaş ve düşük AC.'],
['Harpy',38,11,20,'Monstrosity','1',[12,13,12,7,10,13],'Multiattack club/claws; Luring Song WIS save.','Uçuş ve charm şarkısı.','Yok','Yok','Şarkıyı duymamak/menzil.'],
['Griffon',59,12,80,'Monstrosity','2',[18,15,16,2,13,8],'Multiattack: beak +6 1d8+4, claws +6 2d6+4.','Keen Sight; uçuş 80 ft.','Yok','Yok','Düşük AC.'],
['Ankheg',39,14,30,'Monstrosity','2',[17,11,13,1,13,6],'Bite +5, 2d6+3 + acid ve grapple; Acid Spray recharge 6.','Burrow 10 ft.','Yok','Yok','DEX/mental save.'],
['Worg',26,13,50,'Monstrosity','1/2',[16,13,13,7,11,8],'Bite +5, 2d6+3; STR save prone.','Keen hearing/smell.','Yok','Yok','Menzilli saldırı.'],
['Specter',22,12,50,'Undead','1',[1,14,11,10,10,11],'Life Drain +4, 3d6 necrotic; CON save HP max düşüşü.','Incorporeal Movement, Sunlight Sensitivity.','Acid, cold, fire, lightning, thunder; nonmagical fiziksel','Necrotic, poison; birçok condition','Radiant ve güneş ışığı.'],
['Shadow',16,12,40,'Undead','1/2',[6,14,13,6,10,8],'Strength Drain +4, 2d6+2 necrotic ve STR düşürür.','Shadow Stealth, Amorphous.','Birçok hasar; nonmagical fiziksel','Necrotic, poison; conditionlar','Radiant; parlak ışık.'],
['Wraith',67,13,60,'Undead','5',[6,16,16,12,14,15],'Life Drain +6, 4d8+3 necrotic; Create Specter.','Incorporeal Movement, Sunlight Sensitivity.','Acid, cold, fire, lightning, thunder; nonmagical fiziksel','Necrotic, poison; conditionlar','Radiant ve güneş.'],
['Hill Giant',105,13,40,'Giant','5',[21,8,19,5,9,6],'Multiattack greatclub +8, 3d8+5; rock +8, 3d10+5.','Basit, doğrudan taktik.','Yok','Yok','DEX/INT/CHA save.'],
['Stone Giant',126,17,40,'Giant','7',[23,15,20,10,12,9],'Multiattack greatclub +9, 3d8+6; rock +9, 4d10+6.','Rock Catching reaction.','Yok','Yok','CHA save ve kontrol.'],
['Young White Dragon',133,17,80,'Dragon','6',[18,10,18,6,11,12],'Multiattack; Cold Breath CON save, 10d8 cold.','Ice Walk; breath recharge 5–6.','Yok','Cold','Düşük INT/CHA.'],
['Young Blue Dragon',152,18,80,'Dragon','9',[21,10,19,14,13,17],'Multiattack; Lightning Breath DEX save, 12d10.','Burrow ve uçuş; breath recharge.','Yok','Lightning','Düşük DEX save.']
].map((x,i)=>({id:'v27-'+i,name:x[0],hp:x[1],maxHp:x[1],ac:x[2],speed:x[3],category:x[4],cr:x[5],stats:x[6],attacks:x[7],traits:x[8],resist:x[9],immune:x[10],weak:x[11],note:x[8]}));
const v27BaseAllMonsters=allMonsters;
allMonsters=function(){let base=v27BaseAllMonsters().map(m=>{let d=V27_MONSTER_DETAIL[m.name]||{},category=d.category||(/Dragon/.test(m.name)?'Dragon':/Wolf|Spider|Basilisk/.test(m.name)?'Beast':/Golem/.test(m.name)?'Construct':/Vampire|Wight|Lich/.test(m.name)?'Undead':'Other');return {...m,category,cr:d.cr||m.cr||'?',stats:d.stats||m.stats||[10,10,10,10,10,10],attacks:d.attacks||m.attacks||m.note||'Stat bloğu DM tarafından tamamlanmalı.',traits:d.traits||m.traits||m.note||'Özel özellik yok.',resist:d.resist||m.resist||'Yok',immune:d.immune||m.immune||'Yok',weak:d.weak||m.weak||'Belirgin zayıflık yok.'}});return [...base,...V27_EXTRA_MONSTERS.filter(x=>!base.some(b=>b.name===x.name))]};
function v27Mod(n){let x=Math.floor((Number(n)-10)/2);return x>=0?'+'+x:String(x)}
monsterCards=function(list){return list.map(m=>`<details class="v27-monster"><summary><div class="v27-monster-top"><div><span class="v26-kicker">${esc(m.category)} • CR ${esc(m.cr)}</span><h3>${esc(m.name)}</h3></div><span class="v27-badge">Ayrıntıyı Aç</span></div><div class="v27-monster-vitals"><span><b>${m.hp}</b><br>HP</span><span><b>${m.ac}</b><br>AC</span><span><b>${m.speed}</b><br>Hız</span><span><b>CR ${esc(m.cr)}</b><br>Tehdit</span></div></summary><div class="v27-monster-body"><div class="v27-monster-stats">${['STR','DEX','CON','INT','WIS','CHA'].map((k,i)=>`<span><b>${k}</b><br>${m.stats[i]} (${v27Mod(m.stats[i])})</span>`).join('')}</div><div class="v27-monster-section"><b>Saldırılar</b><p>${esc(m.attacks)}</p></div><div class="v27-monster-section"><b>Yetenek / Buff</b><p>${esc(m.traits)}</p></div><div class="v27-monster-section"><b>Direnç</b><p>${esc(m.resist)}</p><b>Bağışıklık</b><p>${esc(m.immune)}</p><b>Zayıflık / Karşı oyun</b><p>${esc(m.weak)}</p></div><div class="v27-monster-actions"><button class="primary" data-spawn="${m.id}">Savaşa Ekle</button><button class="ghost" data-clonemonster="${m.id}">${m.custom?'Düzenle':'Kopyala / Değiştir'}</button>${m.custom?`<button class="danger" data-delmonster="${m.id}">Sil</button>`:''}</div></div></details>`).join('')};
function v27FilteredMonsters(){let q=v27MonsterQuery.toLocaleLowerCase('tr');return allMonsters().filter(m=>(v27MonsterCategory==='all'||m.category===v27MonsterCategory)&&(v27MonsterCr==='all'||String(m.cr)===v27MonsterCr)&&(!q||[m.name,m.category,m.traits,m.attacks].some(x=>String(x).toLocaleLowerCase('tr').includes(q))))}
function v27CrNumber(x){let s=String(x);if(s.includes('/')){let [a,b]=s.split('/').map(Number);return b?a/b:999}return Number(s)||999}
function v27Bestiary(){let all=allMonsters(),cats=[...new Set(all.map(x=>x.category))].sort(),crs=[...new Set(all.map(x=>String(x.cr)))].sort((a,b)=>v27CrNumber(a)-v27CrNumber(b));return `<section class="card">${v26Head('DM ARAÇLARI','Yaratık Ansiklopedisi',`${all.length} hazır yaratık. Kategori veya CR seç; karta basınca bütün savaş bilgileri açılır.`)}<div class="v27-monster-tools"><input id="monsterSearch" class="input" placeholder="Ad, saldırı veya özellik ara" value="${esc(v27MonsterQuery)}"><select id="v27MonsterCategory"><option value="all">Tüm kategoriler</option>${cats.map(x=>`<option ${x===v27MonsterCategory?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="v27MonsterCr"><option value="all">Tüm CR</option>${crs.map(x=>`<option ${x===v27MonsterCr?'selected':''}>${esc(x)}</option>`).join('')}</select><button id="customMonster" class="primary">+ Özel Yaratık</button></div><div id="monsterList" class="v27-monster-grid">${monsterCards(v27FilteredMonsters())}</div></section>`}

const v27BaseFeatureRule=v25FeatureRule;v25FeatureRule=function(row,c){return v27BaseFeatureRule(row,c).replace('<details open>','<details>')};
const v27BaseTrait=prTraitCard;prTraitCard=function(c){return `<details class="v27-fold"><summary>Species / Subspecies Özellikleri</summary><div class="v27-fold-body">${v27BaseTrait(c)}</div></details>`};
function v27CharActions(c){return `${c.approvalStatus==='pending'?`<button class="primary" data-approve-char="${c.id}">Onayla</button><button class="danger" data-reject-char="${c.id}">Reddet</button>`:''}<button class="ghost" data-damage="${c.id}">HP</button><button class="ghost" data-effect="${c.id}">Efekt</button><button class="ghost" data-pr-level="${c.id}">Seviye</button><button class="ghost" data-editchar="${c.id}">Düzenle</button>`}
function v27PartyDM(){prEnsure();return `${v26Head('KAMPANYA YÖNETİMİ','Karakterler',`${state.characters.length} karakter. Özetler açık, uzun ayrıntılar kapalıdır.`,`<button id="addCharacter" class="primary">+ Karakter</button>${members.filter(m=>m.role==='player'&&!state.characters.some(c=>c.userId===m.userId)).map(m=>`<button class="ghost" data-makefor="${m.userId}">${esc(m.name)} için oluştur</button>`).join('')}`)}<div class="v27-char-list">${state.characters.map(c=>`<article class="card v27-char ${c.approvalStatus==='pending'?'approval-pending':''}"><div class="v27-char-core"><div><div class="v27-compact-head"><h2>${esc(c.name)}</h2>${c.approvalStatus==='pending'?'<span class="pill">ONAY BEKLİYOR</span>':''}</div><div class="v27-badges"><span class="v27-badge">Lv ${c.level}</span><span class="v27-badge">${esc(c.species)}${c.subspecies?' / '+esc(c.subspecies):''}</span><span class="v27-badge">${esc(c.className)}${c.subclass?' / '+esc(c.subclass):''}</span><span class="v27-badge">AC ${c.ac}</span></div></div><div>${hpbar(c)}<small>${(c.effects||[]).length?`Efekt: ${(c.effects||[]).map(x=>esc(typeof x==='string'?x:x.name)).join(', ')}`:'Aktif efekt yok'}</small></div><div class="v27-card-actions">${v27CharActions(c)}</div></div><details class="v27-fold"><summary>Statlar ve Saving Throwlar</summary><div class="v27-fold-body">${prStatGrid(c,true)}</div></details>${prTraitCard(c)}<details class="v27-fold"><summary>Class, Subclass, Skill ve Spell Açıklamaları</summary><div class="v27-fold-body">${prProgress(c)}</div></details><details class="v27-fold"><summary>Envanter (${c.inventory.length}) ve Özel Yetenekler (${c.skills.length})</summary><div class="v27-fold-body">${c.inventory.map((x,i)=>`<div class="v26-item"><span><b>${esc(x.name)}</b><small>${esc(x.effect||x.note||'')}</small>×${x.qty}</span><button class="danger" data-delitem="${c.id}|${i}">Sil</button></div>`).join('')||'<p class="muted">Envanter boş.</p>'}${c.skills.map(x=>`<details class="v27-fold"><summary>${esc(x.name)}</summary><div class="v27-fold-body">${esc(x.note)}</div></details>`).join('')}<div class="v27-card-actions"><button class="ghost" data-item="${c.id}">Eşya Ver</button><button class="ghost" data-skill="${c.id}">Özel Yetenek</button><button class="ghost" data-pr-defense="${c.id}">Direnç/Zayıflık</button><button class="danger" data-delchar="${c.id}">Karakteri Sil</button></div></div></details></article>`).join('')||'<div class="card empty">Henüz karakter yok.</div>'}</div>`}
const v27SkillsBase=prSkillsPlayer;prSkillsPlayer=function(){let c=myChar();if(!c)return v27SkillsBase();prEnsure();return `${v25CombatCard(c)}${prChoicePanel(c)}<section class="card pr-sheet">${v26Head('KARAKTER DEFTERİ',`${c.name} — Yetenekler`,'Başlığa basarak yalnız ihtiyacın olan bölümü aç.')}<details class="v27-fold"><summary>Statlar ve Saving Throwlar</summary><div class="v27-fold-body">${prStatGrid(c)}</div></details>${prTraitCard(c)}<details class="v27-fold"><summary>Class / Subclass Özellikleri ve Spell’ler</summary><div class="v27-fold-body">${prProgress(c)}</div></details>${c.skills.length?`<details class="v27-fold"><summary>DM Tarafından Verilen Özel Yetenekler (${c.skills.length})</summary><div class="v27-fold-body">${c.skills.map(x=>`<details class="v27-fold"><summary>${esc(x.name)}</summary><div class="v27-fold-body">${esc(x.note)}</div></details>`).join('')}</div></details>`:''}</section>`};

exWalletCard=function(title,w,target,scope='player'){return `<details class="card v27-wallet" ${current.role==='player'&&scope==='player'?'open':''}><summary><div class="between row"><div><span class="v26-kicker">${scope==='guild'?'ORTAK KASA':'KİŞİSEL KASA'}</span><h3>${esc(title)}</h3></div><div class="v27-coin-strip">${exMoney(exCoinTotal(w))}</div></div></summary><div class="v27-wallet-body">${current.role==='dm'?`<p class="muted">Düzenlemek istediğin para türünde miktarı yaz.</p><div class="coin-actions">${[['platinum','PP'],['gold','GP'],['silver','SP'],['copper','CP']].map(c=>`<div class="coin-editor"><b>${c[1]}</b><span>Mevcut ${w?.[c[0]]||0}</span><label><small>Miktar</small><input class="coin-amount" type="number" min="1" value="1"></label><button data-coin-adjust="${scope}|${target||''}|${c[0]}|1" class="coin-add">Ekle</button><button data-coin-adjust="${scope}|${target||''}|${c[0]}|-1" class="coin-remove">Çıkar</button></div>`).join('')}</div>`:'<p class="muted">Bu bakiye yalnızca sana ve DM’e görünür.</p>'}</div></details>`};
exTreasury=function(){queueMicrotask(()=>exLoadWallets());let mine=exWalletRows.find(x=>x.user_id===auth.id);return `${v26Head('EKONOMİ','Kasa ve Keseler','1 PP = 10 GP = 100 SP = 1000 CP. Kasa ayrıntıları varsayılan olarak kapalıdır.')} ${exWalletCampaign!==current.id?'<div class="card empty">Kasalar sayılıyor…</div>':!exGuildWallet?'<div class="card pact-error">economy-update.sql eksik.</div>':`<div class="v27-wallet-list">${exWalletCard('Lonca Kasası',exGuildWallet,'','guild')}${current.role==='dm'?exWalletRows.map(w=>exWalletCard(w.player_name,w,w.user_id)).join(''):exWalletCard('Kişisel Kesem',mine||{},auth.id)}</div>${current.role==='player'?exTransferCard():''}`}`};
exItemCard=function(i){v25HydrateItem(i);let price=exPrice(i),canBuy=current.role==='player'&&state.shopSettings.buyingEnabled&&i.stock>0;return `<details class="shop-item ${i.active===false?'disabled':''}"><summary><div class="v27-compact-head"><b>${esc(i.name)}</b><span class="tier">T${i.tier}</span></div><small>${esc(EX_SHOPS[i.shop]||i.shop)} • ${esc(i.effect||'Eşya')}</small><div class="between row"><div>${exMoney(price)}</div><b>Stok ${i.stock}</b></div></summary><div class="v27-shop-body"><p>${esc(i.note||'Açıklama yok.')}</p>${current.role==='dm'?`<div class="shop-admin"><button data-v25-market-give="${i.id}" class="primary">Oyuncuya Ver</button><button data-item-toggle="${i.id}" class="ghost">${i.active===false?'Göster':'Gizle'}</button><button data-item-price="${i.id}" class="ghost">Fiyat</button><button data-item-stock="${i.id}" class="ghost">Stok</button>${i.custom?`<button data-item-delete="${i.id}" class="danger">Sil</button>`:''}</div>`:`<button data-buy-item="${i.id}" class="primary buy-button" ${canBuy?'':'disabled'}>${i.stock>0?'Satın Al':'Tükendi'}</button>`}</div></details>`};
exMarket=function(){exEnsureState();queueMicrotask(()=>exLoadWallets());let shops=current.role==='dm'?Object.keys(EX_SHOPS):Object.keys(EX_SHOPS).filter(k=>state.shopSettings.shops[k].enabled),content=`<div><div class="shop-tabs"><button data-shop-filter="all" class="${exShopFilter==='all'?'active':''}">Tümü</button>${shops.map(k=>`<button data-shop-filter="${k}" class="${exShopFilter===k?'active':''}">${EX_SHOPS[k]}</button>`).join('')}</div><div class="shop-grid">${exVisibleItems().map(exItemCard).join('')||'<div class="card empty">Bu dükkân kapalı veya rafları boş.</div>'}</div></div>`;return `${v26Head('ALIŞVERİŞ','Market ve Dükkânlar','Ürün özeti görünür; açıklama ve yönetim araçları karta basınca açılır.')}<div class="v27-market-layout">${current.role==='dm'?exShopControls():`<div class="shop-player-head card"><div><small>KİŞİSEL BAKİYE</small>${exMoney(exCoinTotal(exWalletRows.find(x=>x.user_id===auth.id)||{}))}</div><p>${state.shopSettings.buyingEnabled?'Dükkânlar açık.':'DM satın almayı kapattı.'}</p></div>`}${content}</div>`};
function v27Npcs(){return `<section class="card">${v26Head('DÜNYA','NPC Defteri',`${state.npcs.length} NPC. Ayrıntılar karta basınca açılır.`,`<button id="addNpc" class="primary">+ NPC Oluştur</button>`)}<div class="v27-npc-list">${state.npcs.map(n=>`<details class="v27-npc card"><summary><div class="v27-compact-head"><div><h3>${esc(n.name)}</h3><small>${esc(n.role)} • ${esc(n.faction||'Bağımsız')}</small></div><span class="v27-badge">HP ${n.hp}/${n.maxHp} • AC ${n.ac}</span></div></summary><div class="v27-npc-body">${hpbar(n)}<p>${esc(n.note)}</p><div class="v27-card-actions"><button data-npchp="${n.id}" class="ghost">HP</button><button data-npcitem="${n.id}" class="ghost">Eşya</button><button data-delnpc="${n.id}" class="danger">Sil</button></div></div></details>`).join('')||'<div class="empty">NPC yok.</div>'}</div></section>`}

dmPages.party=v27PartyDM;playerPages.skills=prSkillsPlayer;dmPages.bestiary=v27Bestiary;dmPages.treasury=exTreasury;playerPages.treasury=exTreasury;dmPages.market=exMarket;playerPages.market=exMarket;dmPages.npcs=v27Npcs;
const V27_PAGE_HELP={dashboard:'Oturum özeti, notlar ve aktif görevler.',party:'Karakterleri özet gör; yalnız gerektiğinde ayrıntıyı aç.',partyview:'Partinin HP ve aktif efekt özeti.',inventory:'Eşyaya basarak kuşanma ve transfer araçlarını aç.',guild:'Ortak kasa, üyelik ve lonca envanteri.',guilddm:'Lonca, ortak kasa ve envanter yönetimi.',world:'Tarih, görev, özel içerik ve dünya ayarları.',encounter:'Initiative, tur, HP ve encounter yönetimi.',encounterview:'Oyuncu için salt okunur aktif savaş görünümü.',npcs:'NPC kartları özet başlar; karta basarak ayrıntıyı aç.',bestiary:'Kategori ve CR filtreli yaratık ansiklopedisi.',market:'Dükkân ve ürün özetleri; ayrıntı karta basınca açılır.',treasury:'Kasa özetleri; para düzenleme alanı karta basınca açılır.',skills:'Class, species, skill ve spell açıklamaları kapalı bölümlerdedir.',pacts:'Gizli oyuncu–DM anlaşmaları.',chat:'Genel ve özel masa yazışmaları.',notifications:'Kalıcı kampanya bildirimleri.',guide:'Sade 2014 masa rehberi.',dice:'Skill bonuslu ortak zar masası.'};
const v271OpenDetails=new Map(),v271ScrollState=new Map();
let v271RenderedPage=page;
function v271DetailEntries(root,pageName){
  const counts=new Map();
  return [...root.querySelectorAll('details')].map(el=>{
    const summary=(el.querySelector(':scope > summary')?.textContent||'Ayrıntı').trim().replace(/\s+/g,' ');
    const owner=el.closest('.v27-char')?.querySelector('h2')?.textContent?.trim()
      ||el.closest('.v27-monster')?.querySelector('h3')?.textContent?.trim()
      ||el.closest('.shop-item')?.querySelector('summary b')?.textContent?.trim()
      ||el.closest('.v27-wallet')?.querySelector('h3')?.textContent?.trim()
      ||el.closest('.v27-npc')?.querySelector('h3')?.textContent?.trim()||'';
    const base=`${pageName}|${owner}|${summary}`,occurrence=counts.get(base)||0;
    counts.set(base,occurrence+1);
    return {el,key:`${base}|${occurrence}`};
  });
}
function v271RememberView(view,pageName){
  v271OpenDetails.set(pageName,new Set(v271DetailEntries(view,pageName).filter(x=>x.el.open).map(x=>x.key)));
  v271ScrollState.set(pageName,{windowY:window.scrollY,asideY:document.querySelector('aside')?.scrollTop||0});
}
const v27RenderBase=render;render=function(){
  const oldView=$('#view'),domPage=v271RenderedPage,targetPage=page;
  if(oldView&&current)v271RememberView(oldView,domPage);
  let out=v27RenderBase();
  queueMicrotask(()=>{
    const view=$('#view');if(!view)return;
    view.className=`v27-view v27-page-${targetPage}`;
    if(!view.querySelector('.v26-page-head')&&V27_PAGE_HELP[targetPage])view.insertAdjacentHTML('afterbegin',`<p class="v27-page-note">${esc(V27_PAGE_HELP[targetPage])}</p>`);
    const openKeys=v271OpenDetails.get(targetPage)||new Set();
    v271DetailEntries(view,targetPage).forEach(({el,key})=>{el.dataset.v271Key=key;if(openKeys.has(key))el.open=true});
    v271RenderedPage=targetPage;
    if(domPage===targetPage){
      const pos=v271ScrollState.get(targetPage);
      if(pos)requestAnimationFrame(()=>{window.scrollTo(0,pos.windowY);const aside=document.querySelector('aside');if(aside)aside.scrollTop=pos.asideY});
    }
  });
  return out
};
document.addEventListener('input',e=>{if(e.target.id==='monsterSearch'){e.stopImmediatePropagation();v27MonsterQuery=e.target.value;$('#monsterList').innerHTML=monsterCards(v27FilteredMonsters());if(window.v31BindMonsterCards)v31BindMonsterCards();else bind()}},true);
document.addEventListener('change',e=>{if(e.target.id==='v27MonsterCategory'){v27MonsterCategory=e.target.value;$('#monsterList').innerHTML=monsterCards(v27FilteredMonsters());if(window.v31BindMonsterCards)v31BindMonsterCards();else bind()}if(e.target.id==='v27MonsterCr'){v27MonsterCr=e.target.value;$('#monsterList').innerHTML=monsterCards(v27FilteredMonsters());if(window.v31BindMonsterCards)v31BindMonsterCards();else bind()}},true);
if(current)render();
