/* v28: DM inventory transfer, dice history control and readable 2014 encyclopedia. */
const V28_LEVELS={
Barbarian:['Rage, Unarmored Defense','Reckless Attack, Danger Sense','Primal Path','ASI','Extra Attack, Fast Movement','Path feature','Feral Instinct','ASI','Brutal Critical +1','Path feature','Relentless Rage','ASI','Brutal Critical +2','Path feature','Persistent Rage','ASI','Brutal Critical +3','Indomitable Might','ASI','Primal Champion'],
Bard:['Spellcasting, Bardic Inspiration d6','Jack of All Trades, Song of Rest d6','Bard College, Expertise','ASI','Bardic Inspiration d8, Font of Inspiration','Countercharm, College feature','—','ASI','Song of Rest d8','Bardic Inspiration d10, Expertise, Magical Secrets','—','ASI','Song of Rest d10','Magical Secrets','Bardic Inspiration d12, College feature','ASI','Song of Rest d12','Magical Secrets','ASI','Superior Inspiration'],
Cleric:['Spellcasting, Divine Domain','Channel Divinity 1/rest, Domain feature','2nd-level spells','ASI','Destroy Undead CR 1/2, 3rd-level spells','Channel Divinity 2/rest, Domain feature','4th-level spells','ASI, Destroy Undead CR 1','5th-level spells','Divine Intervention','Destroy Undead CR 2','ASI','7th-level spells','Destroy Undead CR 3','8th-level spells, Domain feature','ASI','Destroy Undead CR 4','Channel Divinity 3/rest','ASI','Divine Intervention succeeds'],
Druid:['Druidic, Spellcasting','Wild Shape, Druid Circle','2nd-level spells','Wild Shape improvement, ASI','3rd-level spells','Circle feature','4th-level spells','Wild Shape improvement, ASI','5th-level spells','Circle feature','6th-level spells','ASI','7th-level spells','Circle feature','8th-level spells','ASI','9th-level spells','Timeless Body, Beast Spells','ASI','Archdruid'],
Fighter:['Fighting Style, Second Wind','Action Surge 1/rest','Martial Archetype','ASI','Extra Attack (2)','ASI','Archetype feature','ASI','Indomitable 1/rest','Archetype feature','Extra Attack (3)','ASI','Indomitable 2/rest','ASI','Archetype feature','ASI','Action Surge 2/rest, Indomitable 3/rest','Archetype feature','ASI','Extra Attack (4)'],
Monk:['Unarmored Defense, Martial Arts d4','Ki, Unarmored Movement +10','Monastic Tradition, Deflect Missiles','ASI, Slow Fall','Extra Attack, Stunning Strike, d6','Ki-Empowered Strikes, Tradition feature','Evasion, Stillness of Mind','ASI','Movement +15','Purity of Body','Tradition feature, d8','ASI','Tongue of Sun and Moon','Diamond Soul, Movement +25','Timeless Body','ASI','Tradition feature, d10','Empty Body','ASI','Perfect Self'],
Paladin:['Divine Sense, Lay on Hands','Fighting Style, Spellcasting, Divine Smite','Sacred Oath, Divine Health','ASI','Extra Attack, 2nd-level spells','Aura of Protection','Oath feature','ASI','3rd-level spells','Aura of Courage','Improved Divine Smite','ASI','4th-level spells','Cleansing Touch','Oath feature','ASI','5th-level spells','Aura range 30 ft','ASI','Oath capstone'],
Ranger:['Favored Enemy, Natural Explorer','Fighting Style, Spellcasting','Ranger Archetype, Primeval Awareness','ASI','Extra Attack, 2nd-level spells','Favored Enemy/Natural Explorer improvement','Archetype feature','ASI, Land’s Stride','3rd-level spells','Hide in Plain Sight','Archetype feature','ASI','4th-level spells','Favored Enemy improvement, Vanish','Archetype feature','ASI','5th-level spells','Feral Senses','ASI','Foe Slayer'],
Rogue:['Expertise, Sneak Attack 1d6, Thieves’ Cant','Cunning Action, Sneak 1d6','Roguish Archetype, Sneak 2d6','ASI','Uncanny Dodge, Sneak 3d6','Expertise','Evasion, Sneak 4d6','ASI','Archetype feature, Sneak 5d6','ASI','Reliable Talent, Sneak 6d6','ASI','Archetype feature, Sneak 7d6','Blindsense','Slippery Mind, Sneak 8d6','ASI','Archetype feature, Sneak 9d6','Elusive','ASI, Sneak 10d6','Stroke of Luck'],
Sorcerer:['Spellcasting, Sorcerous Origin','Font of Magic','Metamagic','ASI','3rd-level spells','Origin feature','4th-level spells','ASI','5th-level spells','Metamagic','6th-level spells','ASI','7th-level spells','Origin feature','8th-level spells','ASI','9th-level spells','Origin feature','ASI','Sorcerous Restoration'],
Warlock:['Otherworldly Patron, Pact Magic','Eldritch Invocations','Pact Boon, 2nd-level slots','ASI','3rd-level slots','Patron feature','4th-level slots','ASI','5th-level slots','Patron feature','Mystic Arcanum 6th','ASI','Mystic Arcanum 7th','Patron feature','Mystic Arcanum 8th','ASI','Mystic Arcanum 9th','—','ASI','Eldritch Master'],
Wizard:['Spellcasting, Arcane Recovery','Arcane Tradition','2nd-level spells','ASI','3rd-level spells','Tradition feature','4th-level spells','ASI','5th-level spells','Tradition feature','6th-level spells','ASI','7th-level spells','Tradition feature','8th-level spells','ASI','9th-level spells','Spell Mastery','ASI','Signature Spells'],
Artificer:['Magical Tinkering, Spellcasting','Infuse Item','Artificer Specialist, Right Tool','ASI','Specialist feature','Tool Expertise','Flash of Genius','ASI','Specialist feature','Magic Item Adept','Spell-Storing Item','ASI','—','Magic Item Savant','Specialist feature','ASI','Magic Item Master','—','ASI','Soul of Artifice']};
const V28_ACTION_HELP={Rage:'Bonus action; 1 dakika; ağır zırhta çalışmaz. STR yakın saldırı hasarı ve fiziksel direnç verir.',Sneak:'Turda bir kez, finesse/ranged isabetinde şartları sağlıyorsan ek hasar. Ayrı action değildir.',ASI:'Ability Score Improvement: iki puanı bölüştür veya bir feat seç; normal sınır 20.','Action Surge':'Kendi turunda ek action; bonus action vermez. Kısa/uzun dinlenmede yenilenir.',Metamagic:'Büyüyü atarken Sorcery Point harcayıp seçilen Metamagic kuralını uygula.','Divine Smite':'Yakın silah isabetinden sonra slot harca; saldırı zarı tekrar atılmaz.',Spellcasting:'Büyünün kartındaki action/bonus action/reaction süresini, menzili, component ve concentration bilgisini uygula.','Wild Shape':'Action; uygun Beast stat bloğuna dönüş. HP ve fiziksel statlar formdan gelir; mental statların sende kalır.','Extra Attack':'Attack action aldığında belirtilen sayıda saldırı yaparsın; her saldırı için ayrı d20 atılır.'};
function v28Explain(text){let hits=Object.entries(V28_ACTION_HELP).filter(([k])=>text.includes(k));return hits.map(([k,v])=>`<p><b>${esc(k)}:</b> ${esc(v)}</p>`).join('')}
function v28SpeciesCards(){return allSpecies().map(s=>{let d=prSpecies(s.name),bonus=Object.entries(d.bonus||{}).map(([k,v])=>`${k} +${v}`).join(', ')||'Sabit ability bonusu yok';return `<details class="v28-entry"><summary><b>${esc(s.name)}</b><span>${s.subs.length} alt tür</span></summary><div class="v28-entry-body"><p><b>Ability:</b> ${esc(bonus)}</p><p><b>Tür özellikleri:</b> ${esc((d.traits||[]).join(' • ')||'Kampanyaya özel')}</p><p><b>Direnç/bağışıklık:</b> ${esc((d.resist||[]).join(', ')||'Yok')}　 <b>Zayıflık/sınır:</b> ${esc((d.weak||[]).join(', ')||'Yok')}</p><div class="v28-subgrid">${s.subs.map(x=>`<span><b>${esc(x)}</b><small>${esc(prTheme(x)[1])}</small></span>`).join('')||'<span>Alt tür yok</span>'}</div></div></details>`}).join('')}
function v28FeatureCards(className){let rows=V26_FEATURES[className]||prClass(className).features||[];return rows.map(row=>{let rule=V25_FEATURE_RULES[row[1]],meta=rule?`<small>${esc(rule[0])} • Kullanım: ${esc(rule[1])} • Süre: ${esc(rule[2])}</small>`:'';return `<details class="v28-feature"><summary><b>Lv ${row[0]} — ${esc(row[1])}</b></summary><div><p>${esc(row[2])}</p>${meta}${rule?.[3]?`<p><b>Masada uygulama:</b> ${esc(rule[3])}</p>`:''}</div></details>`}).join('')||'<p class="muted">Kampanyaya özel class; kuralları DM tanımlar.</p>'}
function v28ClassCards(){return allClasses().map(c=>{let d=prClass(c.name),levels=V28_LEVELS[c.name]||Array.from({length:20},(_,i)=>d.features.filter(x=>x[0]===i+1).map(x=>x[1]).join(', ')||'Yeni çekirdek özellik yok; kaynak/subclass ilerleyişini uygula.');return `<details class="v28-entry"><summary><b>${esc(c.name)}</b><span>d${PR_HIT_DIE[c.name]||8} • ${d.caster?'Büyü kullanır':'Fiziksel/özellik odaklı'}</span></summary><div class="v28-entry-body"><p><b>Ana stat:</b> ${esc((d.primary||[]).join(', '))}　 <b>Save proficiency:</b> ${esc((d.saves||[]).join(', '))}</p><p><b>Silahlar:</b> ${esc(V26_WEAPONS[c.name]||'Subclass ve kaynak kitabındaki proficiency listesini kullan.')}</p><details class="v28-inner"><summary>Temel skill ve özellikler — nasıl kullanılır?</summary><div class="v28-feature-list">${v28FeatureCards(c.name)}</div></details><details class="v28-inner"><summary>Subclasslar (${c.subs.length})</summary><div class="v28-subgrid">${c.subs.map(x=>`<span><b>${esc(x)}</b><small>${esc(prTheme(x)[1])} Özellikleri class tablosundaki subclass seviyelerinde açılır.</small></span>`).join('')}</div></details><div class="v28-levels">${levels.map((x,i)=>`<details><summary><b>Lv ${i+1}</b><span>${esc(x)}</span></summary><div>${v28Explain(x)||'<p>Pasif ilerleme, spell seviyesi veya subclass özelliği. Zar/action gerektiriyorsa yukarıdaki özellik kartının açıklaması geçerlidir.</p>'}</div></details>`).join('')}</div></div></details>`}).join('')}
function v28Encyclopedia(){return `<section class="v28-ency"><div class="v28-ency-head"><div><span class="v26-kicker">2014 KARAKTER KAYNAĞI</span><h2>Species, Subspecies, Class ve Seviye Ansiklopedisi</h2><p>Sitede seçilebilen içeriklerin tamamı. Başlığa bas; yalnız ihtiyacın olan bilgi açılsın.</p></div><input id="v28EncySearch" class="input" placeholder="Örn: Plasmoid, Astral Self, Smite, seviye 5"></div><div class="v28-ency-tabs"><button data-v28-ency-tab="species" class="primary">Türler ve Alt Türler</button><button data-v28-ency-tab="classes" class="ghost">Classlar: Seviye 1–20</button></div><div id="v28EncyBody">${v28SpeciesCards()}</div></section>`}
const v28GuideBase=v26Guide;v26Guide=function(){return v28GuideBase().replace('<div class="v26-guide-tabs">','<div class="v26-guide-tabs"><button class="ghost" data-v28-encyclopedia="1">Karakter Ansiklopedisi</button>')};guideView=v26Guide;dmPages.guide=v26Guide;playerPages.guide=v26Guide;
const v28PartyBase=v27PartyDM;v27PartyDM=function(){return v28PartyBase().replace(/<button class="danger" data-delitem="([^"]+)">Sil<\/button>/g,'<button class="ghost" data-v28-item-transfer="$1">Aktar</button><button class="danger" data-delitem="$1">Sil</button>')};dmPages.party=v27PartyDM;
const v28DiceBase=sessionDice;sessionDice=function(){let html=v28DiceBase();return current?.role==='dm'?html.replace('<h2>Zar Günlüğü</h2>','<h2>Zar Günlüğü</h2><button id="prClearDice" class="danger v28-clear-dice">Geçmişi Temizle</button>'):html};dmPages.dice=sessionDice;playerPages.dice=sessionDice;
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!current)return;
 if(b.dataset.v28Encyclopedia){$('#guideResults').innerHTML=v28Encyclopedia();return}
 if(b.dataset.v28EncyTab){document.querySelectorAll('[data-v28-ency-tab]').forEach(x=>x.className=x===b?'primary':'ghost');$('#v28EncyBody').innerHTML=b.dataset.v28EncyTab==='species'?v28SpeciesCards():v28ClassCards();return}
 if(current.role==='dm'&&b.dataset.v28ItemTransfer){let [sourceId,itemIndex]=b.dataset.v28ItemTransfer.split('|'),source=state.characters.find(x=>x.id===sourceId),item=source?.inventory?.[+itemIndex],targets=state.characters.filter(x=>x.id!==sourceId);if(!item)return;if(!targets.length)return alert('Eşyayı aktarabileceğin başka karakter yok.');modal('Eşyayı karakterler arasında aktar',`<p><b>${esc(source.name)}</b> → ${esc(item.name)} ×${Math.max(1,+item.qty||1)}</p><label>Alıcı<select id="v28TransferTarget">${targets.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><label>Adet<input id="v28TransferQty" type="number" min="1" max="${Math.max(1,+item.qty||1)}" value="1"></label><button id="v28ConfirmTransfer" data-source="${sourceId}" data-index="${itemIndex}" class="primary">Eşyayı Aktar</button>`);return}
 if(current.role==='dm'&&b.id==='v28ConfirmTransfer'){let source=state.characters.find(x=>x.id===b.dataset.source),target=state.characters.find(x=>x.id===$('#v28TransferTarget').value),index=+b.dataset.index,item=source?.inventory?.[index],qty=Math.floor(+$('#v28TransferQty').value||0),available=Math.max(1,+item?.qty||1);if(!item||!target||qty<1||qty>available)return alert('Eşya, hedef veya adet geçersiz.');let moved={...item,id:uid(),qty,equipped:false};target.inventory.push(moved);if(qty===available)source.inventory.splice(index,1);else item.qty=available-qty;save();$('#modal').close();render();toast(`${item.name} → ${target.name}`);return}
},true);
document.addEventListener('input',e=>{if(e.target.id!=='v28EncySearch')return;let q=fold(e.target.value.trim());document.querySelectorAll('#v28EncyBody > .v28-entry').forEach(x=>x.hidden=!!q&&!fold(x.textContent).includes(q))},true);
if(current)render();
