/* v34 data: expanded economy, lore-based castle services and DM quest inspiration. */
EX_SHOPS.alchemist='Simyacı';
EX_SHOPS.stable='Ahır ve Binekler';
EX_SHOPS.temple='Tapınak';

const V34_MARKET_CATALOG=[
  // SİMYACI — malzeme, bomba, zehir ve iksirler.
  ['acid-vial','Asit Şişesi','alchemist',1,2500,8,'20 ft menzilli saldırı; isabette 2d6 asit. Action ile kullanılır.','Simya Silahı'],
  ['alchemist-fire','Simyacı Ateşi','alchemist',1,5000,6,'20 ft menzilli saldırı; hedef söndürülene kadar tur başlarında 1d4 ateş hasarı alır.','Simya Silahı'],
  ['basic-poison','Temel Zehir','alchemist',1,10000,4,'Bir kesici/delici silahı veya 3 mühimmatı kaplar; hedef DC 10 CON save, başarısızsa 1d4 poison.','Zehir'],
  ['lamp-oil','Yağ Şişesi','alchemist',1,10,30,'Fener yakıtı veya zeminde kontrollü ateş hazırlığı için 1 pint yağ.','Simya Malzemesi'],
  ['smoke-pellet','Duman Küresi','alchemist',1,1500,10,'Kırıldığı küçük alanı 1 tur yoğun dumanla kaplar; kesin alanı DM belirler.','Simya Aracı'],
  ['flash-powder','Parlama Tozu','alchemist',1,2000,8,'Yakındaki hedefi kısa süre şaşırtmak için kullanılır; DM uygun CON save ister.','Simya Aracı'],
  ['antiplague-tonic','Salgın Toniği','alchemist',1,1000,8,'8 saat boyunca sıradan hastalıklara karşı yapılan ilk save’e +1 verir; birikmez.','Tüketilebilir'],
  ['cold-pack','Soğuk Jel Paketi','alchemist',1,500,10,'Yanık veya şişliği tedavi eder; kısa dinlenmedeki Medicine kontrolüne +1 sağlayabilir.','Tıbbi Malzeme'],
  ['glow-chalk','Işıldayan Tebeşir','alchemist',1,200,20,'Karanlıkta 8 saat loş görünen rota işaretleri bırakır.','Keşif Aracı'],
  ['quick-resin','Hızlı Reçine','alchemist',1,300,12,'Küçük kırıkları geçici yapıştırır; kalıcı tamir yerine geçmez.','Simya Malzemesi'],
  ['monster-repellent','Yaratık Kovucu Öz','alchemist',1,2500,5,'Seçilen yaygın Beast türüne karşı 1 saat kokuyla caydırıcılık sağlar; saldıran yaratığı durdurmaz.','Keşif Tüketimi'],
  ['ink-solvent','Mürekkep Çözücü','alchemist',1,50,15,'Taze sıradan mürekkebi kâğıda büyük zarar vermeden çıkarabilir.','Simya Malzemesi'],
  ['potion-climbing','Tırmanma İksiri','alchemist',2,7500,4,'1 saat tırmanma hızı yürüyüş hızına eşit olur ve tırmanış kontrollerinde avantaj sağlar.','İksir'],
  ['potion-animal-friendship','Hayvan Dostluğu İksiri','alchemist',2,10000,4,'1 saat içinde Animal Friendship büyüsünü bir kez kullanmayı sağlar.','İksir'],
  ['potion-water-breathing','Su Altında Nefes İksiri','alchemist',2,15000,4,'1 saat su altında nefes almayı sağlar.','İksir'],
  ['potion-fire-breath','Ateş Nefesi İksiri','alchemist',2,15000,3,'Bonus action ile içilir; 1 saat içinde üç kez bonus action ile 4d6 ateş püskürtür, DC 13 DEX yarıya indirir.','İksir'],
  ['potion-resistance','Direnç İksiri','alchemist',2,25000,5,'DM’in belirlediği bir hasar türüne 1 saat direnç verir.','İksir'],
  ['potion-growth','Büyüme İksiri','alchemist',2,30000,3,'1d4 saat Enlarge etkisinin büyüme kısmını verir; concentration istemez.','İksir'],
  ['potion-diminution','Küçülme İksiri','alchemist',2,30000,3,'1d4 saat Reduce etkisinin küçülme kısmını verir; concentration istemez.','İksir'],
  ['potion-invisibility','Görünmezlik İksiri','alchemist',2,50000,2,'1 saat görünmezlik; saldırı yapmak veya büyü atmak etkiyi bitirir.','İksir'],
  ['truth-serum','Hakikat Serumu','alchemist',2,12500,3,'İçen hedef DC 11 CON save atar; başarısızsa 1 saat bilerek yalan söylemekte zorlanır. DM yorumu gerekir.','Zehir'],
  ['keoghtom-ointment','Keoghtom Merhemi','alchemist',2,50000,2,'Bir doz 2d8+2 HP yeniler; poison ve disease temizleyebilir. 1d4+1 dozluk kavanoz.','Nadir Merhem'],
  ['potion-flying','Uçuş İksiri','alchemist',3,150000,2,'1 saat yürüyüş hızına eşit uçuş hızı verir.','Çok Nadir İksir'],
  ['potion-speed','Hız İksiri','alchemist',3,200000,2,'1 dakika Haste etkisi verir; bitince bir tur uyuşukluk uygulanır.','Çok Nadir İksir'],
  ['potion-heroism','Kahramanlık İksiri','alchemist',3,120000,2,'1 saat Bless etkisi ve 10 geçici HP verir.','Nadir İksir'],
  ['potion-vitality','Canlılık İksiri','alchemist',3,250000,1,'Exhaustion temizler; 24 saat harcanan Hit Die başına maksimum iyileşme sağlar.','Çok Nadir İksir'],
  ['potion-stone-strength','Taş Devi Gücü İksiri','alchemist',3,150000,2,'1 saat Strength değerini 23 yapar.','Nadir İksir'],
  ['potion-frost-strength','Ayaz Devi Gücü İksiri','alchemist',3,250000,1,'1 saat Strength değerini 23 yapar.','Çok Nadir İksir'],
  ['oil-etherealness','Eter Yağı','alchemist',3,400000,1,'Sürülmesi 10 dakika; 1 saat Etherealness etkisi sağlar.','Nadir Yağ'],
  ['sovereign-glue','Hükümdar Tutkalı','alchemist',3,350000,1,'Birbirine sürdüğü iki yüzeyi olağanüstü güçlü ve kalıcı biçimde yapıştırır.','Efsanevi Simya'],
  ['universal-solvent','Evrensel Çözücü','alchemist',3,250000,1,'Hükümdar Tutkalı dahil güçlü yapıştırıcıları çözer.','Efsanevi Simya'],
  ['oil-sharpness','Keskinlik Yağı','alchemist',3,300000,1,'Bir silaha veya 5 mühimmata 1 saat saldırı ve hasar +3 verir.','Çok Nadir Yağ'],

  // AHIR — resmi 2014 binek/fiyatları + açıkça işaretlenmiş fantastik seçenekler.
  ['feed-day','Bir Günlük Binek Yemi','stable',1,5,50,'Bir Medium veya Large bineğin bir günlük yemi.','Binek Erzağı'],
  ['stabling-night','Bir Gecelik Ahır','stable',1,50,30,'Yem, su, kaba temizlik ve bir gecelik güvenli barınma.','Ahır Hizmeti',{service:true}],
  ['bit-bridle','Gem ve Dizgin','stable',1,200,15,'Çoğu sıradan binek için temel kontrol takımı.','Binek Ekipmanı'],
  ['pack-saddle','Yük Semeri','stable',1,500,10,'Yük taşımaya uygun semer.','Binek Ekipmanı'],
  ['riding-saddle','Binek Eyeri','stable',1,1000,10,'Normal yolculuk için standart eyer.','Binek Ekipmanı'],
  ['saddlebags','Heybe','stable',1,400,12,'Bineğin iki yanına dengeli eşya taşır.','Binek Ekipmanı'],
  ['donkey-mule','Eşek veya Katır','stable',1,800,8,'Sure-footed yük hayvanı; oyun için Mule stat bloğunu kullan.','Binek',{mount:true}],
  ['pony','Midilli','stable',1,3000,5,'Small sürücüler veya hafif yük için Pony stat bloğu.','Binek',{mount:true}],
  ['draft-horse','Koşum Atı','stable',1,5000,5,'Araba ve ağır yük çekmeye uygun Draft Horse.','Binek',{mount:true}],
  ['riding-horse','Binek Atı','stable',1,7500,5,'Hızlı yolculuk için Riding Horse stat bloğu.','Binek',{mount:true}],
  ['camel','Deve','stable',1,5000,5,'Kurak bölgelerde uzun yolculuğa uygun Camel stat bloğu.','Binek',{mount:true}],
  ['mastiff','Mastiff','stable',1,2500,6,'Bekçi, iz sürme veya Small karakter bineği; Mastiff stat bloğu.','Eğitimli Hayvan',{mount:true}],
  ['pack-goat','Yük Keçisi','stable',1,100,10,'Dağ patikalarında küçük yükleri taşır; savaş bineği değildir.','Yük Hayvanı',{mount:true}],
  ['cart','El/At Arabası','stable',1,1500,5,'Tek binekçe çekilebilen iki tekerli taşıt.','Taşıt'],
  ['wagon','Yük Vagonu','stable',1,3500,4,'Uzun yol ve ağır kargo için dört tekerli taşıt.','Taşıt'],
  ['riding-lesson','Temel Binek Dersi','stable',1,500,20,'Bir saatlik eğitim; DM uygun görürse sonraki Animal Handling kontrolüne +1 verir.','Eğitim Hizmeti',{service:true}],
  ['warhorse','Savaş Atı','stable',2,40000,3,'Savaşa alışkın Warhorse stat bloğu; binici kontrolü yine gerekebilir.','Savaş Bineği',{mount:true}],
  ['elephant','Fil','stable',2,20000,2,'Geniş yol ve yüksek bakım ister; Elephant stat bloğu.','Egzotik Binek',{mount:true}],
  ['giant-lizard-mount','Dev Kertenkele','stable',2,15000,3,'Mağara veya sıcak bölge bineği; Giant Lizard stat bloğu, DM onayı.','Egzotik Binek',{mount:true}],
  ['giant-goat-mount','Dev Keçi','stable',2,12500,3,'Dağlık arazide güvenli; Giant Goat stat bloğu, DM onayı.','Egzotik Binek',{mount:true}],
  ['axe-beak-mount','Balta Gagalı Binek','stable',2,8000,3,'Hızlı fakat ürkek; Axe Beak stat bloğu, DM onayı.','Egzotik Binek',{mount:true}],
  ['giant-boar-mount','Dev Yaban Domuzu','stable',2,35000,2,'Agresif ve dayanıklı; Giant Boar stat bloğu, özel eğitim ister.','Savaş Bineği',{mount:true}],
  ['war-dog-pair','Eğitimli Savaş Köpeği Çifti','stable',2,15000,2,'İki Mastiff; sahibinin komutlarını bilir fakat bağımsız NPC gibi yönetilir.','Eğitimli Hayvan',{mount:true}],
  ['carriage','Fayton','stable',2,10000,3,'Şehirler arası konforlu dört tekerli taşıt.','Taşıt'],
  ['chariot','Savaş Arabası','stable',2,25000,2,'İki binek ister; savaş kullanımı için DM taşıt kuralı belirler.','Savaş Taşıtı'],
  ['chain-barding','Zincir Binek Zırhı','stable',2,30000,2,'Uygun bineğe Chain Mail eşdeğeri koruma; barding fiyatı normal zırhın dört katıdır.','Binek Zırhı'],
  ['courier-relay','Kervan Yolu Kurye Ağı','stable',2,2500,10,'Aynı bölgedeki bilinen yerleşime mektup veya küçük paket ulaştırır.','Ulaşım Hizmeti',{service:true}],
  ['combat-training-mount','Binek Savaş Eğitimi','stable',2,15000,4,'Sıradan uygun bir bineği birkaç haftada savaş gürültüsüne alıştırır; süreyi DM ilerletir.','Eğitim Hizmeti',{service:true}],
  ['armored-warhorse','Plaka Zırhlı Savaş Atı','stable',3,640000,1,'Warhorse ve Plate Barding paketi; çok pahalı, ağır ve dikkat çekicidir.','Seçkin Savaş Bineği',{mount:true}],
  ['hippogriff-mount','Eğitimli Hippogriff','stable',3,250000,1,'Uçan binek; sadakat, bakım ve geniş barınak ister. Hippogriff stat bloğu.','Nadir Uçan Binek',{mount:true}],
  ['griffon-lease','Griffon Sefer Sözleşmesi','stable',3,500000,1,'Bir görev süresince griffon ve bakıcı desteği; kayıp/zarar bedeli sözleşmeye eklenir.','Nadir Binek Hizmeti',{service:true,mount:true}],
  ['giant-eagle-contract','Dev Kartal İttifakı','stable',3,300000,1,'Satın alma değil; zeki bir Giant Eagle ile görevlik taşıma anlaşması.','Nadir Ulaşım Hizmeti',{service:true,mount:true}],
  ['pegasus-bond','Pegasus Güven Sınaması','stable',3,800000,1,'Pegasus satılmaz; iyi niyetli karakterin bağ kurma görevi ve bakım bağışıdır.','Efsanevi Binek Hizmeti',{service:true,mount:true}],
  ['dire-wolf-mount','Eğitimli Ulu Kurt','stable',3,150000,1,'Yalnız uygun boy ve kültürdeki sürücü için Dire Wolf stat bloğu; DM onayı gerekir.','Nadir Savaş Bineği',{mount:true}],
  ['giant-elk-mount','Dev Geyik','stable',3,180000,1,'Orman koruyucularının verdiği eğitimli Giant Elk; açık arazide çok hızlıdır.','Nadir Binek',{mount:true}],
  ['wyvern-lease','Wyvern Binici Sözleşmesi','stable',3,1000000,1,'Satış değil; uzman binici ve zehir güvenliğiyle tek seferlik uçuş görevi.','Çok Nadir Ulaşım',{service:true,mount:true}],

  // TAPINAK — nesnelerden çok ayin, tedavi ve koruma hizmetleri.
  ['common-prayer','Yolcu Duası','temple',1,10,99,'Rahip güvenli yolculuk için dua eder; mekanik bonus vermez, rol yapma hizmetidir.','Tapınak Hizmeti',{service:true}],
  ['road-blessing','Yol Koruması','temple',1,100,30,'Grubun sonraki yolculuk complication kontrolüne DM onayıyla +1; birikmez.','Kutsama Hizmeti',{service:true}],
  ['bless-service','Bless Ayini','temple',1,500,12,'En fazla üç hedefe 1 dakikalık Bless; concentration rahipte kalır ve tapınak çevresinde kullanılmalıdır.','Büyü Hizmeti',{service:true}],
  ['healing-prayer','Şifa Duası','temple',1,1000,20,'Tapınakta tek hedefe 2d8+3 HP iyileştirme; savaş ortasında teslim edilmez.','Şifa Hizmeti',{service:true}],
  ['holy-water','Kutsal Su Şişesi','temple',1,2500,10,'Undead veya fiend hedefe 20 ft menzilli saldırıyla 2d6 radiant hasar.','Kutsal Tüketim'],
  ['holy-symbol','Kutsal Sembol','temple',1,500,12,'Amblem, kolye veya kutsal emanet kutusu; divine spell focus olabilir.','Kutsal Eşya'],
  ['funeral-rite','Defin ve Son Ayin','temple',1,200,20,'Ölü için dini tören ve kayıt; undead dönüşünü otomatik engellemez.','Ayin Hizmeti',{service:true}],
  ['sanctuary-lodging','Hacı Yatağı','temple',1,50,30,'Ortak salonda mütevazı bir gecelik konaklama.','Konaklama Hizmeti',{service:true}],
  ['ceremony-service','Ceremony Ayini','temple',1,2500,8,'2014 5e ek kitabındaki Ceremony seçeneklerinden biri; 25 GP gümüş tozu dahildir.','Ayin Hizmeti',{service:true}],
  ['gentle-repose-service','Gentle Repose Ayini','temple',1,1500,8,'Cesedi 10 gün bozulmaktan ve undead olmaktan korur; diriltme süresi sayacını durdurur.','Büyü Hizmeti',{service:true}],
  ['detect-evil-ritual','Kötülük ve İyilik Sezme','temple',1,500,10,'Tapınak içinde 10 dakikalık inceleme; yakın aberration/celestial/elemental/fey/fiend/undead varlığı araştırılır.','İnceleme Hizmeti',{service:true}],
  ['charity-meal','Yoksul Sofrası Bağışı','temple',1,1,99,'Bir bakır bağışla sade yemek; mekanik güç sağlamaz.','Hayır Hizmeti',{service:true}],
  ['aid-service','Aid Kutsaması','temple',2,2500,10,'Üç hedefin maksimum ve mevcut HP’sini 8 saat boyunca 5 artırır.','Büyü Hizmeti',{service:true}],
  ['protection-evil-service','Kötülükten ve İyilikten Koruma','temple',2,5000,8,'Gönüllü hedefe 10 dakika Protection from Evil and Good; concentration rahipte kalır.','Koruma Hizmeti',{service:true}],
  ['lesser-restoration-service','Lesser Restoration Hizmeti','temple',2,5000,8,'Bir disease veya blinded, deafened, paralyzed, poisoned durumlarından birini bitirir.','Arındırma Hizmeti',{service:true}],
  ['remove-curse-service','Remove Curse Hizmeti','temple',2,12000,5,'Bir yaratık veya nesne üzerindeki curse bağını kırar; lanetli eşya lanetsiz hale gelmeyebilir.','Arındırma Hizmeti',{service:true}],
  ['zone-truth-service','Zone of Truth Oturumu','temple',2,7500,5,'10 dakikalık görüşmede alan içindekiler CHA save atar; başarılı hedef susabilir.','Sorgu Hizmeti',{service:true}],
  ['speak-dead-service','Speak with Dead Ayini','temple',2,15000,4,'Cesede en fazla beş soru; hedef yalnız bildiğini söyler ve düşmanca olabilir.','Ayin Hizmeti',{service:true}],
  ['continual-flame-service','Continual Flame Kutsaması','temple',2,10000,5,'Nesnede ısı vermeyen kalıcı alev; 50 GP ruby dust fiyatın içindedir.','Büyü Hizmeti',{service:true}],
  ['augury-service','Augury Kehaneti','temple',2,5000,6,'Önümüzdeki 30 dakikadaki belirli plan için weal/woe sonucu; tekrar kullanım belirsizliği artırır.','Kehanet Hizmeti',{service:true}],
  ['divination-service','Divination Kehaneti','temple',2,25000,3,'Yedi gün içindeki amaç hakkında doğru fakat kapalı cevap; 25 GP sunu dahildir.','Kehanet Hizmeti',{service:true}],
  ['magic-circle-service','Magic Circle Ayini','temple',2,20000,4,'Seçilen creature türüne karşı 1 saatlik 10 ft yarıçaplı koruma; glif tapınakta hazırlanır.','Koruma Hizmeti',{service:true}],
  ['death-ward-service','Death Ward Kutsaması','temple',2,35000,4,'Hedef 8 saat içinde ilk kez 0 HP’ye düşecekken 1 HP’de kalır veya ani ölüm etkisini bozar.','Koruma Hizmeti',{service:true}],
  ['freedom-movement-service','Freedom of Movement Kutsaması','temple',3,45000,3,'Hedef 1 saat difficult terrain ve büyülü hareket kısıtlarına karşı korunur.','Üst Düzey Hizmet',{service:true}],
  ['greater-restoration-service','Greater Restoration Hizmeti','temple',3,65000,3,'Exhaustion azaltır veya güçlü bir zihin/özellik/HP azaltma etkisini bitirir; 100 GP diamond dust dahildir.','Üst Düzey Hizmet',{service:true}],
  ['reincarnate-service','Reincarnate Ayini','temple',3,125000,2,'10 gün içinde öleni yeni yetişkin bedende döndürür; 1000 GP oils/unguents dahildir, yeni tür rastgele belirlenir.','Diriltme Hizmeti',{service:true}],
  ['revivify-service','Revivify Ayini','temple',3,45000,3,'Son 1 dakika içinde öleni 1 HP ile döndürür; 300 GP diamonds dahildir. Ceset tapınağa zamanında ulaşmalıdır.','Diriltme Hizmeti',{service:true}],
  ['raise-dead-service','Raise Dead Ayini','temple',3,75000,2,'10 gün içinde öleni 1 HP ile döndürür; 500 GP diamond dahildir ve iyileşme cezaları uygulanır.','Diriltme Hizmeti',{service:true}],
  ['hallow-service','Hallow Ayini','temple',3,150000,1,'24 saatlik ayinle alanı kutsar; 1000 GP herbs/incense dahildir. DM hedef alanı ve erişimi onaylar.','Büyük Ayin',{service:true}],
  ['resurrection-service','Resurrection Ayini','temple',3,250000,1,'100 yıl içinde öleni döndürebilir; 1000 GP diamond dahildir, ruh istekli olmalıdır.','Diriltme Hizmeti',{service:true}],
  ['heroes-feast-service','Heroes’ Feast Ayini','temple',3,200000,1,'12 kişiye 24 saat fear/poison bağışıklığı, WIS save avantajı ve 2d10 maksimum HP sağlar.','Büyük Kutsama',{service:true}],
  ['true-resurrection-service','True Resurrection Ayini','temple',3,3000000,1,'200 yıl sınırı ve 25.000 GP diamonds içeren son derece nadir ayin; DM bunu görev ödülüne bağlayabilir.','Efsanevi Diriltme',{service:true}],

  // MEVCUT DÜKKÂNLARA YENİ GÜNLÜK, UZMAN VE NADİR SEÇENEKLER.
  ['bandage-roll','Sargı Bezi Rulosu','healer',1,50,25,'Medicine kontrolünde temiz malzeme sağlar; tek başına HP yenilemez.','Tıbbi Malzeme'],
  ['wooden-splint','Kırık Ateli','healer',1,100,15,'Kırık uzvu sabitlemek veya taşıma sırasında hasarı azaltmak için.','Tıbbi Malzeme'],
  ['field-medic-visit','Saha Hekimi Ziyareti','healer',2,7500,6,'Hekim kamp yerine gelir; gruptaki yaraları değerlendirir ve bir kısa dinlenmeye gözetim sağlar.','Şifa Hizmeti',{service:true}],
  ['regeneration-draught','Yenilenme Özütü','healer',3,300000,1,'1 dakika tur başına 1d6 HP; kopan küçük uzuv konusunda DM kararı gerekir.','Çok Nadir Tüketim'],
  ['javelin','Cirit','blacksmith',1,50,12,'1d6 delici; fırlatma 30/120.','Silah'],
  ['handaxe','El Baltası','blacksmith',1,500,8,'1d6 kesici; hafif, fırlatma 20/60.','Silah'],
  ['flail','Gürzlü Zincir','blacksmith',2,1000,5,'1d8 ezici.','Silah'],
  ['lance','Süvari Mızrağı','blacksmith',2,1000,4,'1d12 delici; reach, 5 ft hedefe dezavantaj; bineksizken iki elli.','Silah'],
  ['weapon-repair','Silah Tamiri ve Bileme','blacksmith',1,200,20,'Sıradan hasarlı silahı onarır; saldırı bonusu vermez.','Usta Hizmeti',{service:true}],
  ['ring-mail','Halkalı Zırh','armorer',1,3000,4,'AC 14; ağır zırh, stealth dezavantajı.','Ağır Zırh'],
  ['half-plate','Yarım Plaka','armorer',2,75000,2,'AC 15 + DEX (en fazla +2); stealth dezavantajı.','Orta Zırh'],
  ['armor-refit','Zırh Bedene Uydurma','armorer',1,500,15,'Bulunan sıradan zırhı yeni kullanıcıya göre ayarlar; büyülü zırh için uzman gerekir.','Usta Hizmeti',{service:true}],
  ['shield-plus1','Kalkan +1','armorer',3,600000,1,'Normal kalkanın AC +2 bonusuna ek büyülü AC +1 sağlar.','Nadir Kalkan'],
  ['glamoured-studded','Göz Alıcı Çivili Deri','armorer',3,1200000,1,'AC 12 + DEX ve büyülü AC +1; görünüşü bonus action ile değişir.','Nadir Zırh'],
  ['blowgun','Üfleme Borusu','fletcher',1,1000,5,'1 delici; menzil 25/100, loading.','Silah'],
  ['net','Ağ','fletcher',1,100,8,'Özel menzilli saldırı; isabette Large veya küçük hedef restrained olabilir.','Silah'],
  ['blowgun-needles','50 Üfleme İğnesi','fletcher',1,100,15,'Üfleme borusu için 50 mühimmat.','Mühimmat'],
  ['fire-arrows','10 Ateş Oku','fletcher',2,6000,3,'Hazırlanmış hedefleri tutuşturabilir; ek hasar ve söndürme DC’sini DM belirler.','Özel Mühimmat'],
  ['longbow-plus1','Uzun Yay +1','fletcher',3,500000,1,'Saldırı ve hasar zarlarına +1; büyülü silah sayılır.','Nadir Silah'],
  ['chalk','10 Parça Tebeşir','general',1,10,20,'Yol, kapı ve dungeon işaretlemek için.','Ekipman'],
  ['pitons10','10 Piton','general',1,50,20,'Halat sabitleme ve tırmanış güvenliği için.','Ekipman'],
  ['hammer','Çekiç','general',1,100,12,'Piton çakma ve sıradan kamp işleri için.','Alet'],
  ['hunting-trap','Av Tuzağı','general',1,500,8,'Action ile kurulur; basan hedef DEX save başarısızsa 1d4 hasar ve hareket kısıtı alır.','Ekipman'],
  ['waterskin','Su Tulumu','general',1,20,20,'4 pint sıvı taşır.','Ekipman'],
  ['map-case','Harita ve Parşömen Kutusu','general',1,100,10,'Kâğıtları yağmur ve ezilmeden korur.','Ekipman'],
  ['fishing-tackle','Balıkçı Takımı','general',1,100,8,'Olta, misina, kanca ve yem.','Alet'],
  ['potion-bandolier','İksir Askısı','general',2,2000,6,'Altı küçük şişeyi erişilebilir taşır; action ekonomisini değiştirmez.','Ekipman'],
  ['bath-laundry','Banyo ve Çamaşır','tavern',1,20,30,'Yol kirini temizler; mekanik bonus vermez ama sosyal sahneyi kurtarabilir.','Han Hizmeti',{service:true}],
  ['local-messenger','Yerel Haberci','tavern',1,100,15,'Kale içinde kısa mesajı aynı gün ulaştırır.','Haberci Hizmeti',{service:true}],
  ['hire-local-guide','Yerel Rehber Kiralama','tavern',2,1000,6,'Bir günlük bölge rehberi; Survival kontrolünü otomatik geçirmez fakat kaybolma riskini düşürür.','Rehber Hizmeti',{service:true}],
  ['guarded-escort','Silahlı Şehir Eskortu','tavern',3,15000,3,'Şehir veya yakın yol boyunca dört muhafızlık tek günlük refakat.','Koruma Hizmeti',{service:true}],
  ['poor-meal','Sade Günlük Öğün','restaurant',1,6,40,'Ekmek, peynir ve sıcak çorba; bir kişinin günlük mütevazı yemeği.','Yemek'],
  ['ration-crate','7 Günlük Erzak Sandığı','restaurant',1,350,12,'Bir kişi için yedi günlük dayanıklı erzak.','Erzak'],
  ['noble-catering','Soylu Davet Menüsü','restaurant',2,5000,3,'On kişilik kaliteli servis; sosyal itibar sağlar, otomatik skill bonusu vermez.','Ziyafet Hizmeti',{service:true}],
  ['antidote-tea','Arındırıcı Bitki Çayı','restaurant',2,1200,8,'İçildikten sonraki bir saat içinde yapılan ilk sıradan poison save’ine +1; birikmez.','Özel İçecek'],
  ['driftglobe','Süzülen Işık Küresi','mystic',1,20000,2,'Light ve günde bir Daylight etkisi; komutla yakında süzülebilir.','Yaygın Büyülü Eşya'],
  ['hat-disguise','Kılık Değiştirme Şapkası','mystic',2,45000,2,'Attunement: Disguise Self büyüsünü istediğin kadar kullanır.','Nadir Büyülü Eşya'],
  ['broom-flying','Uçan Süpürge','mystic',2,90000,1,'Komutla uçan binek; taşıdığı ağırlık hızını etkiler.','Nadir Büyülü Eşya'],
  ['stone-good-luck','Şans Taşı','mystic',3,800000,1,'Attunement: ability check ve saving throwlara +1.','Nadir Büyülü Eşya'],
  ['crystal-ball','Kristal Küre','mystic',3,5000000,1,'Attunement: Scrying büyüsünü kullanır; çok nadir ve dikkat çekicidir.','Çok Nadir Büyülü Eşya'],
  ['black-vigil-candle','Kara Nöbet Mumu','cursed',1,700,2,'Yakıldığında görünmez izleri belirginleştirebilir; söndüğünde kullanıcı bir gece kâbus görür.','Lanetli Tüketim'],
  ['quill-debt','Borç Yazan Tüy','cursed',1,1500,2,'İmzalanan sözü büyülü biçimde kaydeder; bozan kişinin adı sahibinin teninde belirebilir.','Lanetli Eşya'],
  ['locket-weeping','Ağlayan Madalyon','cursed',2,18000,1,'Günde bir kez ölü yakının sesini taklit eder; her kullanım sahibinin bir anısını çarpıtır.','Lanetli Eşya'],
  ['chain-oath','Yemin Zinciri','cursed',2,30000,1,'İki gönüllünün verdiği yemini güçlendirir; biri bozarsa ikisi de 3d6 psychic hasar alabilir.','Lanetli Eşya'],
  ['crown-ashen-command','Kül Buyruğu Tacı','cursed',3,120000,1,'Command büyüsünü günde bir kullanır; her kullanım kullanıcının sesini bir gün zayıflatır.','Lanetli Nadir Eşya']
].map(row=>({
  id:'ex-v34-'+row[0],name:row[1],shop:row[2],tier:row[3],priceCopper:row[4],stock:row[5],
  note:row[6],effect:row[7],active:true,ready:true,...(row[8]||{})
}));

EX_ALL_CATALOG.push(...V34_MARKET_CATALOG);

const V34_PRICE_PATCHES={
  'ex-healing-potion':[500,5000],
  'ex-antitoxin':[500,5000],
  'ex-torch':[10,1],
  'ex-flame-tongue':[85000,500000],
  'ex-frost-brand':[140000,2500000],
  'ex-dragon-slayer':[95000,400000],
  'ex-sun-blade':[110000,600000],
  'ex-executioner-plus2':[175000,800000],
  'ex-armor-resistance':[190000,2000000],
  'ex-spellguard-shield':[155000,2500000],
  'ex-animated-shield':[125000,1800000],
  'ex-oathbow':[150000,2500000],
  'ex-lightning-bow':[120000,750000],
  'ex-portable-hole':[145000,900000],
  'ex-boots-speed':[130000,800000],
  'ex-carpet-flying':[240000,2500000],
  'ex-ring-spell-storing':[145000,800000],
  'ex-staff-power':[260000,5000000],
  'ex-robe-stars':[210000,3000000],
  'ex-tome-intellect':[300000,7500000]
};

const V34_CASTLE_TIERS={
  'map-castle-01':{healer:1,alchemist:0,blacksmith:1,armorer:1,fletcher:1,general:1,tavern:1,restaurant:0,mystic:0,cursed:0,stable:1,temple:0},
  'map-castle-02':{healer:0,alchemist:1,blacksmith:3,armorer:3,fletcher:1,general:1,tavern:2,restaurant:1,mystic:0,cursed:0,stable:0,temple:1},
  'map-castle-03':{healer:3,alchemist:3,blacksmith:3,armorer:3,fletcher:0,general:2,tavern:1,restaurant:0,mystic:0,cursed:0,stable:0,temple:3},
  'map-castle-04':{healer:1,alchemist:2,blacksmith:1,armorer:1,fletcher:3,general:2,tavern:1,restaurant:0,mystic:0,cursed:0,stable:1,temple:0},
  'map-castle-05':{healer:2,alchemist:2,blacksmith:2,armorer:2,fletcher:1,general:2,tavern:2,restaurant:2,mystic:0,cursed:0,stable:2,temple:2},
  'map-castle-06':{healer:1,alchemist:1,blacksmith:2,armorer:1,fletcher:1,general:3,tavern:2,restaurant:2,mystic:0,cursed:0,stable:3,temple:1},
  'map-castle-07':{healer:2,alchemist:2,blacksmith:0,armorer:1,fletcher:0,general:2,tavern:2,restaurant:3,mystic:0,cursed:0,stable:0,temple:2},
  'map-castle-08':{healer:1,alchemist:2,blacksmith:2,armorer:2,fletcher:1,general:3,tavern:3,restaurant:2,mystic:0,cursed:0,stable:0,temple:1},
  'map-castle-09':{healer:0,alchemist:3,blacksmith:2,armorer:2,fletcher:1,general:2,tavern:1,restaurant:1,mystic:0,cursed:0,stable:3,temple:1},
  'map-castle-10':{healer:1,alchemist:1,blacksmith:1,armorer:0,fletcher:0,general:2,tavern:2,restaurant:3,mystic:0,cursed:0,stable:0,temple:1},
  'map-castle-11':{healer:3,alchemist:2,blacksmith:1,armorer:0,fletcher:0,general:1,tavern:1,restaurant:2,mystic:0,cursed:0,stable:0,temple:3},
  'map-castle-12':{healer:2,alchemist:3,blacksmith:0,armorer:0,fletcher:1,general:1,tavern:0,restaurant:0,mystic:0,cursed:0,stable:0,temple:0}
};

const V34_QUESTS=[
  ['1–2','Sur Çevresi Devriyesi','Devriye','Muhafızlar gece vardiyasına iki maceracı ekip ister; sur dibindeki izleri ve kırık işaret taşlarını kontrol edin.','İzler saldırganlara değil, sur altında gizli geçit açan korkmuş çocuklara aittir.','5–10 GP, muhafızlarla itibar ve bir sonraki kale girişinde kolaylık.'],
  ['1–2','Yaşlılara Erzak ve Odun Yardımı','Sosyal / Teslimat','Kış gelmeden dış mahalledeki yaşlılara erzak, ilaç ve odun dağıtın.','Bir ev boş görünür; sahibi bodrumdaki ses yüzünden üst kata çıkamıyordur.','Küçük para, mahalle desteği ve güvenilir bir söylenti ağı.'],
  ['1–2','Kervan Denetimi','İnceleme','Kale kapısında gelen kervanın yük listesini, hayvanlarını ve mühürlerini kontrol edin.','Kaçak eşya yoktur; fakat sandıklardan birinde farkında olmadan taşınan uyuyan bir ooze vardır.','Gümrük ücreti payı, tüccar indirimi veya ücretsiz erzak.'],
  ['1–2','Kayıp Keçiler','Arama / Doğa','Bir çobanın altı keçisi orman sınırında kayboldu; izleri hava kararmadan bulun.','Keçiler bir goblin tarafından çalınmadı; goblin onları kurttan korumuştur.','3–8 GP, süt/erzak ve goblinle dostluk ihtimali.'],
  ['1–2','Sarnıçtaki Metalik Ses','Dungeon Başlangıcı','Taçova’nın eski sarnıcından geceleri metal sürtünmesi geliyor.','Ses bir yaratık değil, kaçakçıların açmaya çalıştığı paslı su kapısıdır; arkada küçük ooze yuvası vardır.','10–20 GP ve Eski Su Kemerleri için giriş ipucu.'],
  ['1–2','Kuzey Kapısının Çanı','Gizem','Kapalı kapının alarm çanı rüzgâr yokken çalıyor; geceyi kapıda geçirin.','Çanı Leydi Meral’in ruhu değil, höyükten kaçmış yaralı bir iğne yaratığı tetikler.','Karaçam ormancılarıyla itibar ve şifalı bitkiler.'],
  ['1–2','Çalınan Şifa Çantası','Takip','Revirin ilaç çantası pazar yerinde çalındı; hastalar bekliyor.','Hırsız para için değil hasta kardeşi için çalmıştır; gerçek fırsatçı çeteyi o görmüştür.','Şifacı hizmetinde indirim ve suç ağına dair isim.'],
  ['1–2','Köprü Altı Haraççıları','Sosyal / Çatışma','Üçköprü’de küçük tüccarlardan zorla bakır toplayan grubu durdurun.','Çetenin lideri yoz vergi memurunun borç kayıtlarını ele geçirmiştir.','10 GP, köprü geçiş belgesi ve siyasi kanıt.'],
  ['1–2','Mezarlık Fenerleri','Undead','Mezarlıkta üç gece üst üste mavi ışıklar görüldü; mezarları koruyun.','Işıklar undead değil, ailesinin mezarını arayan kayıp bir will-o’-wisp yavrusu gibi davranan ruh kırıntısıdır.','Kutsal su, tapınak itibarı veya bir hayalet rehber.'],
  ['1–2','Çırak Kuryenin Son Rotası','Kurtarma','Bir kurye kaleden bir saat uzaktaki çiftliğe giderken dönmedi.','Kurye saldırıya uğramadı; kırık köprü yüzünden yaralı bir yabancıyı saklamaktadır.','8 GP ve kurye ağını bir kez ücretsiz kullanma.'],
  ['1–2','Fare Değil, Mimic Yavrusu','Yaratık','Han mahzenindeki erzaklar kayboluyor; işletmeci dev fare sanıyor.','Sandıklardan biri küçük ve korkmuş bir mimic; onu öldürmek, eğitmek veya uzaklaştırmak mümkün.','Ücretsiz konaklama ve mimic tarafından yutulmuş küçük eşya.'],
  ['1–2','Şifalı Mantar Toplama','Keşif','Simyacı, bataklık kenarındaki beyaz mantarlardan on sağlam örnek istiyor.','Mantarlar zehirli değildir fakat onları koruyan bullywug ailesi ilaç karşılığında pazarlık ister.','10 GP, iki antitoksin ve bataklıkta güvenli rota.'],

  ['3–4','Kervanı Gölgeleyen İzler','Koruma','İki günlük yolda erzak kervanına eşlik edin; aynı ayak izleri her kampta beliriyor.','Takipçiler haydut değil, kervandaki lanetli sandığı geri isteyen tapınak görevlileridir.','40–70 GP ve ticaret loncası itibarı.'],
  ['3–4','Kayıp Maden Vardiyası','Kurtarma / Dungeon','Buzdiş’te on iki madenci asansörden dönmedi; vardiya zilini aşağıdan hâlâ çalıyorlar.','Madenciler duergarlarla savaşmıyor, yaklaşan sıcak yaratık yüzünden geçici ateşkes yapmıştır.','75 GP, maden cevheri ve demirci indirimi.'],
  ['3–4','Batık Vergi Kasası','Su Altı','Üçköprü’nün eski vergi kasası sel tünellerinde bulundu; belgeleri sudan önce çıkarın.','Kasada para değil, bugün güçlü olan ailelerin sahte soy kayıtları vardır.','50 GP veya siyasi koz.'],
  ['3–4','Fener Kulesinden Yanlış Sinyal','Gizem','Sisardı’nın yıkık kulelerinden biri mavi savaş sinyali veriyor.','Sinyal istilayı değil peri elçisinin yardım çağrısını anlatır; yanlış çeviri askerleri savaşa sürükleyebilir.','Peri lütfu, özel oklar veya güvenli orman geçişi.'],
  ['3–4','Goblinlerle Ateşkes Masası','Diplomasi','Orman yolunu tutan goblinler geçiş parası istiyor; kale saldırı hazırlığında.','Goblinler aslında höyükten çıkan örümcekleri içeride tutmak için yolu kapatmıştır.','Çatışmasız XP, goblin rehber ve höyük haritası.'],
  ['3–4','Sahte Canavar Ödülü','İnceleme','Bir avcı, köylere saldıran “dev kurt” için ödülü yükseltiyor.','Kurt yoktur; avcı kendi saldırılarını gizleyip nadir kürk fiyatını artırmaktadır.','40 GP, el konulan av malzemeleri ve halk desteği.'],
  ['3–4','Karantina Örneği','Teslimat / Risk','Sazlık Nöbeti’nden alınan mühürlü örneği Taçova simyacısına bozmadan götürün.','Örnek bilinçlidir ve gece çantadan çıkmak için taşıyıcının sesini taklit eder.','60 GP, hastalık direnci toniği ve simyacı bağlantısı.'],
  ['3–4','Kaçak Avcı Halkası','Takip','Karaçam’daki kutsal hayvanlar kayboluyor; tuzak hattını geriye doğru izleyin.','Avcılar aç köylülerdir, asıl alıcı ise kalede saygın bir koleksiyoncudur.','50 GP, ormancı rozeti ve koleksiyoncunun defteri.'],
  ['3–4','Yankı Kulesinin Nöbetçisi','Korku','Terk edilmiş kuleye gönderilen muhafızlar aynı cümleyi tekrarlayarak dönüyor.','Kulede hayalet değil, ses ve hafızayla beslenen bir yankı taklitçisi vardır.','75 GP ve bir kez kullanılabilen sessizlik tılsımı.'],
  ['3–4','Kayıp Tapınak Emaneti','Hırsızlık / Takip','Kutsal sembol festival sabahı kayboldu; tören başlamadan bulun.','Hırsız emaneti satmak değil, içindeki laneti açığa çıkarmak isteyen eski rahiptir.','Tapınak hizmeti, kutsal su ve saklı arşiv erişimi.'],
  ['3–4','Hasat Şenliği Güvenliği','Sosyal / Savunma','Taçova hasat şenliğinde yarışmaları, kasayı ve kalabalığı koruyun.','Sabotajcı yarışmacı değil; eski su kemerinden çıkan yaratıklar tatlı kokusuna gelir.','30–60 GP, yerel ün ve ücretsiz festival alışverişi.'],
  ['3–4','Gelgitte Açılan Hücre','Dungeon','Tuzhisar’da alçak gelgit yalnız iki saat sürecek; eski hücredeki defteri alın.','Defterde korsan isimleri yerine kale reisinin ailesine ait bir mahkûm kaydı vardır.','70 GP, kaçakçı rotası ve siyasi sır.'],

  ['5–7','Aykuyu Katakombunun Kapısı','Dungeon','Gümüşgöl’de dolunay yansıması mahzen kapısını açıyor; kayıp rahibi bulun.','Rahip kaçırılmadı, danışmanın kurban düzenini belgelemek için içeride saklanıyor.','200 GP, ay tılsımı ve şato desteği.'],
  ['5–7','Remorhaz Yumurtası','Tehlikeli Teslimat','Buzdiş madenindeki sıcak yumurtayı kale erimeden güvenli bölgeye taşıyın.','Cüce lordu yumurtayı yok etmek değil savaş bineği yetiştirmek istiyor.','250 GP, usta demirci işi veya etik seçim sonucu müttefik.'],
  ['5–7','Boğuk Nöbetin Mahkûmları','Undead / Su','Tuzhisar hücrelerindeki boğulmuş ruhlar her gelgitte isimlerini bağırıyor.','Ruhların katili korsan değil, mahkûm kayıtlarını satan eski gardiyan soyudur.','180 GP, su altında nefes iksirleri ve aile sırrı.'],
  ['5–7','Komutanın İkizi','İnceleme','Sazlık komutanı aynı saatte iki farklı yerde görülüyor; kimse açıkça konuşamıyor.','Doppelganger paniği büyütüyor fakat gerçek komutan da yasadışı deneyleri saklıyor.','200 GP, karantina yetkisi ve simya örnekleri.'],
  ['5–7','Kült Konvoyu','Pusu / Karar','Kültaç’a giden mühürlü konvoyun ateş kültüne silah taşıdığı söyleniyor.','Sandıklarda silah değil, kaleyi ayakta tutan ateş devine ilaç vardır.','250 GP, volkan geçiş belgesi veya kültle düşmanlık.'],
  ['5–7','Göl Cadısının Bedeli','Pazarlık','Balıkçılar kaybolan çocuklar için göl cadısını suçluyor; izler onun adasına gidiyor.','Cadı çocukları yaklaşan su undeadlerinden korumaktadır ama karşılığında anı istemektedir.','Nadir iksir, güvenli su yolu veya tehlikeli anlaşma.'],
  ['5–7','Sahuagin Gece Baskını','Savunma','Üçköprü’de nehir çekildiğinde saldırı bekleniyor; savunmayı hazırlayın ve köprüleri tutun.','Sahuaginler kasayı değil nehir ruhundan çalınan kurucu taşı geri almaya gelir.','200 GP, köprü mülkiyeti payı veya nehir lütfu.'],
  ['5–7','Wyvern Yuvasındaki Mektup','Keşif / Kurtarma','Dağ kuryesinin çantası wyvern yuvasında görüldü; diplomatik mektup savaş çıkmadan alınmalı.','Kurye hayattadır ve yavru wyvernı avcılardan koruduğu için dönmeyi reddeder.','220 GP, binek eğitmeni bağlantısı ve diplomatik itibar.'],
  ['5–7','Fenerdeki Boş Zırh','Gizem / Undead','Fırtınaburnu feneri geceleri kayıp gemilere yanlış rota gösteriyor.','Sinyali korsanlar değil, boş amiral zırhına bağlanmış pişman ruh veriyor.','250 GP, liman desteği ve deniz haritası.'],
  ['5–7','Lanetli Şövalyenin Son Nöbeti','Sosyal / Savaş','Yolda aynı şövalye her gece düelloya çağırıyor; yenilse de geri geliyor.','Laneti onu öldürmek değil, koruyamadığı kervanın son eşyasını sahibine ulaştırmak bitirir.','Büyülü silah ipucu, şövalye arması ve huzura kavuşan ruhun yardımı.'],

  ['8–10','Kor Zindanının Üç Mührü','Büyük Dungeon','Kültaç’ın altındaki üç mühür çatlıyor; her kırık katın sıcaklığını artırıyor.','İçeride iblis değil kaleyi taşıyan yaralı ateş devi vardır; öldürmek kaleyi çökertebilir.','800 GP, ateş işçiliği ve kalenin kaderini belirleme.'],
  ['8–10','Duergar İsyanının Gerçek Hedefi','Savaş / Diplomasi','Buzdiş madeninde duergarlar üst galerileri ele geçirdi; kale tam saldırı istiyor.','Duergarlar cevheri değil, uyanan yaratığa karşı eski savunma makinesini arıyor.','700 GP, adamantin cevheri veya yeraltı ittifakı.'],
  ['8–10','Cam Mezarların Güneşi','Dungeon / Çevre','Kızılkapı kuyusu kuruyor; cam mezarlardaki ışık düzeneğini kapatın.','Düzenek suyu çekmiyor, kalenin simyacısının gizli laboratuvarını besleyen boruyu görünür kılıyor.','650 GP, nadir simya formülü ve kuyu üzerindeki hak.'],
  ['8–10','Ejderhaya Ödenen Vergi','Diplomasi / Ejderha','Üç kale yıllık hazineyi genç ejderhaya gönderiyor; bu yıl ödeme kayıp.','Ejderha vergiyi hiç istememiştir; bir soylu korkuyu kullanarak servet toplamıştır.','1000 GP veya ejderha bağlantısı; doğrudan savaş daha tehlikeli.'],
  ['8–10','Naibe Suikast Gecesi','Koruma / İnceleme','Taçova Naibi üç farklı suikast ihbarı aldı; ziyafet boyunca koruyun.','Üç ihbar da sahte, amaç muhafızları boşaltıp kırık taç anıtını çalmaktır.','800 GP, saray yetkisi ve siyasi nüfuz.'],
  ['8–10','Gelecekten Sızan Gölgeler','Planar','Ayhalka taş çemberinden gelecek harabelerin gölgeleri çıkıyor.','Gölgeler düşman değil, yaklaşan felaketi engellemek isteyen gelecekteki ada halkıdır.','900 GP, kehanet ve bir zaman anahtarı.'],
  ['8–10','Korsan Amiralin Son Filosu','Deniz Savaşı','Fırtınaburnu açıklarında batık gemiler geceleri yelken açıyor.','Filoyu boş zırh yönetiyor; gerçek amiral ruhu gemilerden birinde esir.','1000 GP, gemi, liman üssü veya amiral emaneti.'],
  ['8–10','Kumdan Yükselen Ordu','Savunma / Undead','Kızılbozkır’da cam muhafızlar kaleye doğru yürüyor; tahkimat için bir gece var.','Ordu saldırmıyor, eski sancak taşını gerçek sahibine götürmeye çalışıyor.','900 GP, sınır komutası itibarı ve kadim sancak.'],

  ['11–14','Dağın Kalbini Uyandırmak','Felaket Önleme','Kor Dağı’nın lav damarları durdu; kısa süre sonra basınç bütün bölgeyi patlatacak.','Dağı uyandırmak için ateş devini iyileştirmek gerekir; kült onu zincirli tutmak istiyor.','3000 GP, ateş direnci lütfu ve bölgesel ittifak.'],
  ['11–14','Kadim Ejderhayla Barış Masası','Diplomasi','İnsan kaleleri kadim ejderhanın yumurtasını buldu; ordular savaşa hazırlanıyor.','Yumurta ejderhaya ait değildir, mühürlenmiş planar bir yaratığın kabuğudur.','Krallık unvanı, ejderha lütfu veya güçlü büyülü eşya.'],
  ['11–14','Aynadaki İkinci Şehir','Planar Dungeon','Gümüşgöl yansımasında yaşayan şehir gerçek şehrin yerini almaya başlıyor.','Yansıma halkı kötü değildir; kendi dünyaları yok olduğu için kaçmaktadır.','2500 GP ve iki şehir arasında kalıcı geçit kararı.'],
  ['11–14','Leviathanın Zincirleri','Deniz / Boss','Kırıkadalar altındaki zincirler kopuyor; gelgit bütün kıyıları yutacak.','Leviathan dünyayı yok etmek istemiyor, zincirler onun yavrusunu zehirliyor.','3500 GP, deniz ulaşımı lütfu ve krallık filosu desteği.'],
  ['11–14','Üç Tahtın İç Savaşı','Siyasi Kampanya','Ova Yemini bozuldu; üç hanedan Taçova üzerinde hak iddia ediyor.','Savaşı başlatan varislerden hiçbiri gerçek değildir; aynı şekil değiştirici ağı tarafından hazırlanmıştır.','Toprak, unvan, kalıcı müttefikler ve kampanya yönünü değiştiren sonuç.'],

  ['15–20','Dünya Ağacındaki Çürüme','Dünya Tehdidi','Karaçam’ın kökleri kıtalar boyunca kararıyor; her kale farklı bir belirti gösteriyor.','Çürüme dışarıdan gelmemiştir; dünya ağacı yaklaşan kozmik varlıktan saklanmak için kendini öldürüyor.','Efsanevi lütuf ve dünyanın coğrafyasını değiştiren seçim.'],
  ['15–20','Tanrının Sessiz Avatarı','İlahi / Ahlaki','Tapınak mucizeleri bir gecede kesilir ve ölümlü bir yabancı kaleye sığınır.','Yabancı gücünü kaybetmiş tanrıdır; onu eski yerine döndürmek başka bir tanrıyı düşürecektir.','Artifact, divine boon veya yeni dini düzen.'],
  ['15–20','On İki Kalenin Son Kuşatması','Final Kampanyası','Haritadaki on iki kale aynı anda gökten inen ordu tarafından kuşatılır; hangi kalelerin yaşayacağına parti karar verir.','Düşman komutanı gelecekte başarısız olmuş parti üyelerinden biridir ve felaketi önlemek için geçmişi zorla değiştirir.','Kampanya finali: dünya düzeni, kalelerin kaderi ve karakterlerin mirası.']
].map((row,index)=>({id:`v34-quest-${String(index+1).padStart(2,'0')}`,levels:row[0],title:row[1],type:row[2],hook:row[3],twist:row[4],reward:row[5]}));
