using System.Net.Http.Headers;using System.Net.Http.Json;using System.Text.Json;using Npgsql;
namespace TaskPanel.Api;
public record CurrentUser(Guid Id,string Email,string FullName,string Role);
public record LoginRequest(string Email,string Password);
public record CreateUserRequest(string FullName,string Email,string Password,string Role="employee");
public record CreateTaskRequest(string Title,string Description,Guid AssigneeId,string Priority="normal",DateOnly? DueDate=null);
public record StatusRequest(string Status);
public class Db(IConfiguration c){public async Task<NpgsqlConnection> Open(){var x=new NpgsqlConnection(c.GetConnectionString("Supabase"));await x.OpenAsync();return x;}}
public class AuthService(IHttpClientFactory f,IConfiguration c){
  public async Task<JsonElement?> Login(LoginRequest r){var h=f.CreateClient();h.DefaultRequestHeaders.Add("apikey",c["Supabase:PublishableKey"]);var x=await h.PostAsJsonAsync($"{c["Supabase:Url"]}/auth/v1/token?grant_type=password",new{email=r.Email,password=r.Password});return x.IsSuccessStatusCode?await x.Content.ReadFromJsonAsync<JsonElement>():null;}
  public async Task<CurrentUser?> Validate(string token){var h=f.CreateClient();h.DefaultRequestHeaders.Add("apikey",c["Supabase:PublishableKey"]);h.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);var x=await h.GetAsync($"{c["Supabase:Url"]}/auth/v1/user");if(!x.IsSuccessStatusCode)return null;var j=await x.Content.ReadFromJsonAsync<JsonElement>();var m=j.GetProperty("user_metadata");var a=j.GetProperty("app_metadata");return new(j.GetProperty("id").GetGuid(),j.GetProperty("email").GetString()!,m.TryGetProperty("full_name",out var n)?n.GetString()!:j.GetProperty("email").GetString()!,a.TryGetProperty("app_role",out var role)?role.GetString()!:"employee");}}
public class AuthMiddleware(RequestDelegate next){public async Task InvokeAsync(HttpContext c,AuthService auth){if(c.Request.Path.StartsWithSegments("/api/auth/login")||c.Request.Path.StartsWithSegments("/swagger")){await next(c);return;}var h=c.Request.Headers.Authorization.ToString();if(!h.StartsWith("Bearer ")){c.Response.StatusCode=401;return;}var user=await auth.Validate(h[7..]);if(user is null){c.Response.StatusCode=401;return;}c.Items["User"]=user;await next(c);}}
public class TaskService(Db db){
  public async Task<List<object>> Get(CurrentUser u){await using var c=await db.Open();var sql=u.Role=="admin"?"select t.id,t.title,t.description,t.assignee_id,t.status::text,t.priority::text,t.due_date,p.full_name from tasks t join profiles p on p.id=t.assignee_id order by t.created_at desc":"select t.id,t.title,t.description,t.assignee_id,t.status::text,t.priority::text,t.due_date,p.full_name from tasks t join profiles p on p.id=t.assignee_id where t.assignee_id=@uid order by t.created_at desc";await using var q=new NpgsqlCommand(sql,c);q.Parameters.AddWithValue("uid",u.Id);await using var r=await q.ExecuteReaderAsync();var list=new List<object>();while(await r.ReadAsync())list.Add(new{id=r.GetInt64(0),title=r.GetString(1),description=r.GetString(2),assigneeId=r.GetGuid(3),status=r.GetString(4),priority=r.GetString(5),dueDate=r.IsDBNull(6)?null:r.GetDateTime(6).ToString("yyyy-MM-dd"),assigneeName=r.GetString(7)});return list;}
  public async Task<long> Create(CreateTaskRequest r,CurrentUser u){if(u.Role!="admin")throw new UnauthorizedAccessException();await using var c=await db.Open();await using var q=new NpgsqlCommand("insert into tasks(title,description,assignee_id,created_by,priority,due_date) values(@t,@d,@a,@c,@p::task_priority,@date) returning id",c);q.Parameters.AddWithValue("t",r.Title);q.Parameters.AddWithValue("d",r.Description);q.Parameters.AddWithValue("a",r.AssigneeId);q.Parameters.AddWithValue("c",u.Id);q.Parameters.AddWithValue("p",r.Priority);q.Parameters.AddWithValue("date",(object?)r.DueDate??DBNull.Value);return(long)(await q.ExecuteScalarAsync())!;}
  public async Task<bool> Status(long id,string status,CurrentUser u){await using var c=await db.Open();var sql=u.Role=="admin"?"update tasks set status=@s::task_status,updated_at=now() where id=@id":"update tasks set status=@s::task_status,updated_at=now() where id=@id and assignee_id=@uid";await using var q=new NpgsqlCommand(sql,c);q.Parameters.AddWithValue("s",status);q.Parameters.AddWithValue("id",id);q.Parameters.AddWithValue("uid",u.Id);return await q.ExecuteNonQueryAsync()>0;}}
public class UserService(Db db,IHttpClientFactory f,IConfiguration c){public async Task<List<object>> Get(){await using var x=await db.Open();await using var q=new NpgsqlCommand("select id,email,full_name,role::text from profiles order by full_name",x);await using var r=await q.ExecuteReaderAsync();var list=new List<object>();while(await r.ReadAsync())list.Add(new{id=r.GetGuid(0),email=r.GetString(1),fullName=r.GetString(2),role=r.GetString(3)});return list;}public async Task<bool>Create(CreateUserRequest r,CurrentUser u){if(u.Role!="admin")throw new UnauthorizedAccessException();var h=f.CreateClient();h.DefaultRequestHeaders.Add("apikey",c["Supabase:SecretKey"]);h.DefaultRequestHeaders.Authorization=new("Bearer",c["Supabase:SecretKey"]);var x=await h.PostAsJsonAsync($"{c["Supabase:Url"]}/auth/v1/admin/users",new{email=r.Email,password=r.Password,email_confirm=true,user_metadata=new{full_name=r.FullName},app_metadata=new{app_role=r.Role}});return x.IsSuccessStatusCode;}}
