const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const c={console};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','v76-core.js'),'utf8'),c,{filename:'v76-core.js'});const B=c.v76Backup,plain=x=>JSON.parse(JSON.stringify(x));
const state=()=>({session:4,notes:'Kale 5',quests:['Kurye'],characters:[{id:'c1',name:'Arven',inventory:[{id:'i1',name:'Kutsal Sembol'}]}],npcs:[{id:'n1',name:'Mira',inventory:[]}],encounter:[],market:[],relationshipsV75:[{id:'r1'}]});
test('legacy raw state backups remain importable',()=>{const result=B.validate(state());assert.equal(result.wrapped,false);assert.equal(result.counts.characters,1);assert.equal(result.counts.items,1);assert.equal(result.counts.relations,1)});
test('wrapped backups expose metadata without mixing it into state',()=>{const result=B.validate({format:B.FORMAT,createdAt:'2026-09-09',campaign:{name:'Test'},state:state()});assert.equal(result.wrapped,true);assert.equal(result.createdAt,'2026-09-09');assert.equal(result.campaign.name,'Test');assert.equal(result.state.format,undefined)});
test('invalid roots and unrelated json files are rejected',()=>{assert.throws(()=>B.validate([]),/kökünde/);assert.throws(()=>B.validate({hello:'world'}),/benzemiyor/);assert.throws(()=>B.validate({format:'another-app',state:state()}),/Kadim Masa/)});
test('known list fields cannot silently change type',()=>{assert.throws(()=>B.validate({...state(),characters:{c1:{}}}),/characters alanı liste/);assert.throws(()=>B.validate({...state(),relationshipsV75:'all'}),/relationshipsV75 alanı liste/)});
test('prototype pollution keys are rejected at every depth',()=>{const raw=JSON.parse('{"session":1,"notes":"x","characters":[],"npcs":[],"nested":{"__proto__":{"polluted":true}}}');assert.throws(()=>B.validate(raw),/güvenli olmayan/);assert.equal({}.polluted,undefined)});
test('validation clones input so preview cannot mutate the selected file object',()=>{const raw=state(),result=B.validate(raw);result.state.characters[0].name='Changed';assert.equal(raw.characters[0].name,'Arven')});
test('summary includes character, npc and guild inventory',()=>{const raw=state();raw.npcs[0].inventory=[{id:'n-item'}];raw.guildInventory=[{id:'g-item'}];assert.deepEqual(plain(B.counts(raw)),{characters:1,npcs:1,relations:1,quests:1,encounter:0,market:0,items:3})});

test('Build 76 import controls remain present in the current cache chain',()=>{const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),config=fs.readFileSync(path.join(root,'config.js'),'utf8');assert.match(html,/id="importBtn"/);assert.match(html,/id="backupFile"/);assert.match(config,/v76-core\.js/);assert.match(config,/v76\.js/);assert.match(config,/v76\.css/);assert.match(config,/\?v=82/);assert.match(html,/config\.js\?v=82/)})
