const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function fixture(){
  const listeners={},c={console,Date,Intl,confirm:()=>true,alert:()=>{},crypto:{randomUUID:()=>`id-${Math.random()}`}};c.window=c;c.globalThis=c;c.document={addEventListener:(name,fn)=>listeners[name]=fn,querySelectorAll:()=>[]};c.$=()=>null;c.esc=(x='')=>String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');c.uid=()=>`u-${Math.random()}`;c.modal=()=>{};c.save=()=>{};c.render=()=>{};c.toast=()=>{};c.field=(id,label,type='text',value='')=>`<label>${label}<input class="input" id="${id}" type="${type}" value="${value}"></label>`;c.auth={id:'dm1',name:'Leydi DM'};c.current=null;c.state={characters:[{id:'c1',name:'Arven',level:5,xp:7000,hp:30,maxHp:40,ac:16,autoVitals:false,xpHistory:[]}]};c.prEnsure=()=>{};c.prProgress=()=>'<section>CLASS</section>';c.playerDash=()=>'<div class="v46-character-page"><section>FÖY</section></div>';c.myChar=()=>c.state.characters[0];c.v27CharActions=()=>'<button class="ghost" data-pr-level="c1">Seviye</button><button>HP</button>';c.charForm=character=>c.field('cLevel','Seviye','number',character.level||1);c.dmPages={party:()=>'<main>PARTİ</main>'};c.playerPages={};c.V27_PAGE_HELP={};c.prStats=character=>character.stats||{};c.prAutoHP=character=>10*character.level;c.prAutoAC=character=>character.ac;c.queueMicrotask=queueMicrotask;vm.createContext(c);for(const file of ['v78-core.js','v78.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),c,{filename:file});return c;
}
test('detailed XP panel shows total, next threshold and full table',()=>{const c=fixture(),html=c.v78XpUi.panel(c.state.characters[0]);for(const text of ['XP İLERLEMESİ','7.000','14.000 XP','7.000 XP','1–20 XP eşiklerini göster'])assert.ok(html.includes(text),text)});
test('DM character actions replace manual level with XP management',()=>{const c=fixture(),html=c.v27CharActions(c.state.characters[0]);assert.ok(html.includes('XP Yönet'));assert.ok(!html.includes('data-pr-level'))});
test('party page gains bulk XP control and edit form locks manual level',()=>{const c=fixture();assert.ok(c.dmPages.party().includes('Partiye XP Ver'));const form=c.charForm(c.state.characters[0]);assert.ok(form.includes('XP ile otomatik'));assert.ok(form.includes('disabled'))});
test('player dashboard receives a compact XP indicator',()=>{const c=fixture(),html=c.playerDash();assert.ok(html.includes('v78-xp-panel compact'));assert.ok(html.includes('Seviye 5'))});
test('XP application preserves character data and updates derived level',()=>{const c=fixture(),character=c.state.characters[0],result=c.v78XpUi.applyToCharacter(character,{mode:'add',amount:8000,reason:'Büyük görev',id:'x',at:'2026-09-09T00:00:00Z',actor:'DM'});assert.equal(result.changed,true);assert.equal(character.xp,15000);assert.equal(character.level,6);assert.equal(character.name,'Arven');assert.equal(character.xpHistory[0].reason,'Büyük görev')});
test('Build 78 assets load last with the current cache key',()=>{const root=path.join(__dirname,'..'),config=fs.readFileSync(path.join(root,'config.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(config,/v78\.css/);assert.match(config,/v77\.js','v78-core\.js','v78\.js/);assert.match(config,/\?v=78\.1/);assert.match(html,/config\.js\?v=78\.1/)});
